delta-io/delta

build.sbt
src/main/scala/io/delta/tables/DeltaMergeBuilder.scala
src/main/scala/io/delta/tables/DeltaTable.scala
src/test/scala/io/delta/tables/DeltaTableSuite.scala
src/test/scala/org/apache/spark/sql/delta/ActionSerializerSuite.scala
src/test/scala/org/apache/spark/sql/delta/DeleteSuiteBase.scala
src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala
src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala
src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala
src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala
src/test/scala/org/apache/spark/sql/delta/DescribeDeltaHistorySuite.scala
src/test/scala/org/apache/spark/sql/delta/EvolvabilitySuite.scala
src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala
src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
src/test/scala/org/apache/spark/sql/delta/UpdateSuiteBase.scala

This will allow us to prepare in advance to use new APIs like data source v2.
Most of the diff here is classes being moved around. There's only one significant change: the PartitionCount physical plan metadata was removed, so we have to rewrite a test to use the equivalent SQL metric instead.

Create a new branch for development against the Spark head snapshot.

---

src/main/scala/org/apache/spark/sql/delta/analysis/DeltaAnalysis.scala
src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceUtils.scala
src/test/scala/org/apache/spark/sql/delta/InsertIntoSuite.scala

This PR adds a bunch of tests for insert into through the DataFrameWriter + SQL APIs. Most of these tests were inlined over from OSS Spark and we add more tests around schema enforcement in INSERT INTO which is a new feature.
We also add support for the syntax delta.`/some/path` and use this in INSERT INTO so that users can do 
```sql
INSERT INTO delta.`/some/path` VALUES (1, "a")
```

Adds tests for InsertInto

---

.circleci/config.yml
python/run-tests.py

It's trying to install pyspark with python 3.5 instead of the system global 3.7.

Fix pipenv used in tests

---

build.sbt
project/MimaExcludes.scala
storage/src/main/java/io/delta/storage/CloseableIterator.java
storage/src/main/java/io/delta/storage/LogStore.java

Move over the `LogStore` and `CloseableIterator` interfaces from `delta-core`'s `io.delta.storage` package

Delta Storage: initial project setup

---

build.sbt
examples/python/dynamodb_logstore.py
run-integration-tests.py

In the last few commits of the core scala DynamoDBLogStore work, we a) refactored from contribs to storage-dynamodb artifact, and also renamed `DynamoDBLogStore.scala` to `DynamoDBLogStoreScala.scala`
This PR updates the integration tests to work with those latest changes.

Fix python integration tests

---

build.sbt
run-integration-tests.py
storage-dynamodb/integration_tests/dynamodb_logstore.py

- Refactor `examples/python/dynamodb_logstore.py` into `storage-dynamodb/integration_tests` 
- Move it to a separate test within `run-integration-tests.py`
- To run the test provide command line argument `--run-storage-dynamodb-integration-tests` (this runs only the DynamoDB logstore test and none of the other integration tests)
- TODO: need to merge #990 into this and adjust code

Refactor DynamoDB Logstore integration tests

---

core/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/deltaMerge.scala
core/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
core/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
core/src/main/scala/org/apache/spark/sql/delta/constraints/DeltaInvariantCheckerExec.scala
core/src/main/scala/org/apache/spark/sql/delta/schema/SchemaMergingUtils.scala
core/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/GeneratedColumnSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/MergeIntoSQLSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/MergeIntoScalaSuite.scala

Commit 59d5ea2 replaced the usage of `AnalysisException` with `DeltaAnalysisException`. This caused the Python API exception conversion to not work. Earlier the exception `AnalysisException` used to be convertd to PySpark's `AnalysisException` (code is [here](https://github.com/databricks/runtime/blob/master/python/pyspark/sql/utils.py#L156)). With 59d5ea2, exception `DeltaAnalysisException` is thrown directly as a Py4JError.
Revert the usage of `DeltaAnalysisException` to not break the Python API compatibility.
Summary of reverts.
* `DeltaAnalysisException` - Reverted in all production code. Only place this remains is in a disabled test in `DeltaErrorsSuite`
* `DeltaIllegalArgumentException` - This is used only in two helper methods (`copyIntoEncryptionSseCRequired` and …

Revert usages of Delta*Exception extending DeltaThrowable

---

core/src/main/resources/error/delta-error-classes.json
core/src/main/scala/io/delta/tables/DeltaTable.scala
core/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
core/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
core/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala
core/src/main/scala/org/apache/spark/sql/delta/commands/UpdateCommand.scala
core/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
core/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceOffset.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaCDCStreamSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaDetailSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/MergeIntoMetricsBase.scala
core/src/test/scala/org/apache/spark/sql/delta/MergeIntoSQLSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/UpdateSQLSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala
examples/python/utilities.py
examples/scala/src/main/scala/example/Utilities.scala
python/delta/tables.py
python/delta/tests/test_deltatable.py

Cherry-pick the following:
05c39329d902e0f4a49f9edb7312c18a2b20cb29 Enable batch CDF queries on column mapping enabled tables with fewer limitations
4ff810943d2f00143fba5a3795b753d0a76a90b5 Block interval types in Delta
f7cc05f50f3bc8feb262340f096410500077d82f  Change DeltaTable.details() to DeltaTable.detail() to be consistent with SQL
3ff10fa9bcf8f54a6cb2448fabc92a70d0e98972  Trigger available now
3ce34c9371fa5c75107c83043b3b20a16f8963b5  Fix merge command `numTargetFilesAdded` metric
8df1844d4cdd89ab9567b2f70aa0453bc004ff37 Make update command return the number of updated rows.
0058673322aea1f375f297405872be1176888041 Make MERGE operation return useful metrics
**Do not merge this PR, this is just for the purpose of review.**

[DO_NOT_MERGE][Delta 2.1 Release] Backport commits to branch-2.1

---

.github/workflows/test.yaml
Dockerfile
python/run-tests.py

(Cherry-pick of c3020e1 to branch-2.1)
This change is needed to fix the pyspark version to 3.3.0. Without this the test setup installs latest 3.3.x pyspark and there are [partitioning differences](https://issues.apache.org/jira/browse/SPARK-40407) between 3.3.0 and 3.3.1 which cause tests to return slightly different behavior in partitioning.

Update delta Dockerfile

---

core/src/main/scala/org/apache/spark/sql/delta/commands/DeleteWithDeletionVectorsHelper.scala

(Cherry-pick of e0f0e91c80b431ee47861c49bd21ff5ac0294cc3 to branch-2.4)
This issue fixes https://github.com/delta-io/delta/issues/1725.
The mechanism of this fix is to call the Spark internal method, which is used to generate metadata columns, to see if it will canonicalize spaces in a crafted path string. If the answer is yes, then we don't need to do anything on the Delta side; otherwise, we manually canonicalize the obtained metadata column.
Why don't use the Spark internal method on `FileToDvDescriptor`, so both sides of the join are either canonicalized or not-canonicalized? Because most Delta methods are expecting a canonicalized path, thus the returned DF must be canonicalized in all cases.
Existing tests didn't fail.

Probe whether the metadata path is canonicalized in Spark (#1725)

---

core/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeIntoMaterializeSource.scala
core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
core/src/test/scala/org/apache/spark/sql/delta/MergeIntoMaterializeSourceSuite.scala

(Cherry-pick of 4932956ae52f7a1211999f5364b6f9e1875d183a to branch-2.4)
Add config to run MERGE source materialization eagerly.
Add a new config that that controls whether the MERGE source is materialized eagerly or lazily.
New config is set to eager by default to avoid suspected determinism issues with lazy materialization.
Run most sensitive tests with both eager and lazy settings, the rest only with the default to not blow up the CI time unnecessarily.

Add config to run MERGE source materialization eagerly

---

build.sbt

(Cherry-pick of d9a5f9f9c64b5066467801917de158650ae091cb to branch-2.4)
Reenable iceberg build that was previously disabled in #1720
N/A
Yes, add delta-iceberg back to Delta 2.4

[2.4] Re-enable iceberg module

---

kernel/kernel-default/src/main/java/io/delta/kernel/parquet/MapConverter.java
kernel/kernel-default/src/main/java/io/delta/kernel/parquet/RowConverter.java

This PR replaces usages of `Arrays.stream` (slow, known performance issues) with simple `for` loops (faster) inside of the delta kernel hot path (parquet row conversion). This yielded a ~3x performance boost at replaying the delta log.
Created a table with 1M rows, 1M add files, and 1000 commits. Loaded the latest snapshot of this table (20 times, to be able to aggregate my results), and recorded the time spent performing `LogReplay::loadTableProtocolAndMetadata()`.
The results are
- master (98fe7797f681408036d08aefda8c6684d8b0e0a1): ~4100ms
- this PR: ~1400ms

[Kernel] Replace `Arrays.stream` with `for` loops to improve replay performance ~3x

---

kernel/dev/checkstyle.xml
kernel/dev/copyrightHeader
kernel/kernel-api/src/test/java/io/delta/kernel/internal/types/JsonHandlerTestImpl.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/vector/VectorUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/DecimalConverters.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/RowConverter.java

Adds header to the java checkstyle for Kernel. Fixes instances where missing.
Checkstyle passes

[Kernel] Enforce header in java files with checksytle

---

core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala

Cherry-pick of d36623f0819a3b9a7e9ff924bb1faa4e9caf6050 for branch-2.4
There was an edge case in streaming with deletion vectors in the source, where in `ignoreChanges`-mode it could happen that if the same file occurred with different DVs in the same batch (or both with a DV and without a DV), then we would read the file with the wrong DV, since we broadcast the DVs to the scans by data file path.
This PR fixes this issue, by reading files from different versions in different scans and then taking the union of the result to build the final `DataFrame` for the batch.
Added new tests for having 2 DML commands (DELETE->DELETE and DELETE->INSERT) in the same batch for all change modi.
No.

Fix stream output when the same file occurs with different DVs in the same batch

---

core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceCDCSupport.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaCDCStreamSuite.scala

Cherry-pick of 9f70ee5a65f90970432c80ba96d718f56997442c for branch-2.4.
- When the add and remove file entries for a commit that contains DVs gets split into different batches, we don't recognise that they belong together and we need to produce CDF by calculating the diff of the two DVS.
- This PR prevents splitting of these commits, just like we do for AddCDCFile actions to prevent splitting the update_{pre/post}_image information.
GitOrigin-RevId: 11438c01ecc69f7c55c3a8826fa540f6b984e4c4

[Cherry-pick] Do not split commits that contain DVs in CDF streaming

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/DecimalConverters.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetBatchReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetConverters.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/RepeatedValueConverter.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/RowConverter.java

Minor cleanups.
* Currently, the `Converter` implementations have a method called `boolean moveToNextRow()`, which returns whether the previous row is `null` after moving the converter state to consume the next row. The return value is unnecessary now after delta-io/delta#1974. This PR removes the return type.
* There is an extra method on `RowConverter` called `boolean moveToNextRow(int rowIndex)`. This method is called to pass the row index of the record that was read. Also, there is an `if..and..else` to call this method or other method depending upon the `Converter`. Remove this extra method and just add one method `boolean finalizeCurrentRow(long currentRowIndex)`. This method sets the row index of the current row depending on the converter type and also finalizes the state of the …

[Kernel] Clean up `ParquetBatchReader` move to next row logic

---

core/src/test/scala/org/apache/spark/sql/delta/DeltaSourceDeletionVectorsSuite.scala

(Cherrypick of 67c4b983088ae7e2d1d5cac6403792eb9ba35385 to branch-2.4)
- Remove flakiness from a previously flaky test case, by ensuring that the stream is stopped processing before running new DML commands on the source table.
Fixes #1982
Testing-only PR.
No.

[Spark][2.4] Fix flaky test suite DeltaSourceDeletionVectorsSuite

---

connectors/testStandaloneCosmetic/src/test/scala/io/delta/standalone/internal/ShadedJarSuite.scala

Minor refactor to use GoldenTableUtils in ShadedJarSuite.
Trivial.
No.

[Standalone] Use GoldenTableUtils in ShadedJarSuite (to test delta standalone jar)

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActionsIterator.java

Fix a bug in resource handling where we are always closing the resources which should be closed only when a failure occurs.
Currently, the code opens two resources, it maintains the opened resource list to close in case the function isn't successful in opening all the required resources. Resources in the maintained list should only be closed when an error occurs (it should be in the `catch` block not in `finally`)
Existing tests
No

[Kernel] Fix a bug around closing partially opened resources

---

kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java
kernel/kernel-api/src/main/java/io/delta/kernel/data/ColumnarBatch.java
kernel/kernel-api/src/main/java/io/delta/kernel/data/FilteredColumnarBatch.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActiveAddFilesIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/integration/BaseIntegration.java

This is a preparatory change for supporting partition pruning in Delta Kernel.
Currently `DataReadResult` is used in representing a `ColumnarBatch` with a selection vector. It is used when reading the data from the scan files. The `ColumnarBatch` is the data read from Parquet data files and the selection vector is populated based on the deletion vector associated with the scan file. Having selection vector avoids the cost of rewriting the `ColumnarBatch`. We want to use the similar `DataReadResult` in metadata. Currently `Scan.getScanFiles` returns an iterator of `ColumnarBatch`. Instead, the plan is to return `DataReadResult` (which contains the `ColumnarBatch` of scan files, and a selection vector that tells whether a scan file is pruned or not based on the partition filter.).
Renaming …

[Kernel] Rename `DataReadResult` to `FilteredColumnarBatch`

---

kernel/kernel-api/src/main/java/io/delta/kernel/Table.java
kernel/kernel-api/src/main/java/io/delta/kernel/TableNotFoundException.java
kernel/kernel-api/src/main/java/io/delta/kernel/client/FileSystemClient.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultFileSystemClient.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/client/TestDefaultFileSystemClient.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/integration/BaseIntegration.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/utils/DefaultKernelTestUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeletionVectorSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplaySuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

Currently, we expect the path given to `Table.forPath()` to be fully qualified. This enforces an unnecessary burden on the connector to add the necessary schema or authority etc. Instead, add a `FileSystemClient.resolvePath` API and use it to resolve the path to a fully qualified path from `Table.forPath()`.
Existing tests (deleted the `file:` prefix added to tests tables in the path) and a couple of new tests around missing table paths.

[Kernel] Resolve path given to `Table.forPath` using `TableClient` APIs

---

kernel/kernel-api/src/main/java/io/delta/kernel/client/ExpressionHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActiveAddFilesIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultExpressionHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/vector/AbstractColumnVector.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultExpressionHandlerSuite.scala

Part of delta-io/delta#2071 (Partition Pruning in Kernel).
Delta `kernel-api` module creates a selection vector (a `ColumnVector` boolean data type) that goes along with `ColumnarBatch` of scan files read from the Delta checkpoint or commit files. It uses the `selection vector` to select only a subset of rows from the scan file `ColumnarBatch`. Also at the same time `kernel-api` module shouldn't be creating `ColumnVector`s. Instead should rely on the `TableClient` APIs to create the vectors.
It adds the below API on `ExpressionHandler`
```
/**
* Create a selection vector, a boolean type {@link ColumnVector}, on top of the range of values
* given in <i>values</i> array.
*
* @param values Array of initial boolean values for the selection vector. The ownership of
*               this array …
```

[Kernel] Add selection vector create API on `ExpressionHandler`

---

kernel/kernel-api/src/main/java/io/delta/kernel/data/ColumnVector.java
kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Column.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/vector/DefaultStructVector.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala

Part of delta-io/delta#2071 (Partition Pruning in Kernel). We need a way to reference the `partitionValues` nested column in scan file `ColumnarBatch`.
Currently, the `Column` expression can only be used to refer to a top-level column. There is no way to refer to a nested column. This PR updates the `Column` expression to be a multi-part identifier. This is similar to the Spark's [`NamedReference`](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/NamedReference.java) DSv2 expression. 
Fixes delta-io/delta#2040 (also contains different approaches to refer to a nested column).
Added a UT

[Kernel] Add support for nested column reference expression

---

kernel/kernel-api/src/main/java/io/delta/kernel/client/ExpressionHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/expressions/PredicateEvaluator.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultExpressionHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultPredicateEvaluator.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultPredicateEvaluatorSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/ExpressionSuiteBase.scala

Part of delta-io/delta#2071 (Partition Pruning in Kernel). We need a way to evaluate the predicate on a `ColumnarBatch` using an existing optional selection vector.
Adds `PredicateEvaluator` interface.
```
public interface PredicateEvaluator {
/**
* Evaluate the predicate on given inputData. Combine the existing selection vector with the
* output of the predicate result and return a new selection vector.
*
* @param inputData               {@link ColumnarBatch} of data to which the predicate
*                                expression refers to input.
* @param existingSelectionVector Optional existing selection vector. If not empty, it is
*                                combined with the predicate result. The caller is also
*                                releasing the ownership of …
```

[Kernel] Add `PredicateEvaluator` interface and default implementation

---

kernel/kernel-api/src/main/java/io/delta/kernel/expressions/PartitionValueExpression.java
kernel/kernel-api/src/main/java/io/delta/kernel/expressions/ScalarExpression.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/ElementAtEvaluator.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/ExpressionUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/ExpressionVisitor.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/PartitionValueEvaluator.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala

Part of delta-io/delta#2071 (Partition Pruning in Kernel). We need the following two expressions in order to evaluate predicate on scan file columnar batch data.
* `element_at(map_column, key_value)`: Take input a `map` type column and `key` value, return the `value` for the given `key`. This is similar to Apache Spark UDF for similar purposes. This expression will be used to retrieve the specific partition value from the `(partition column name -> string serialized partition)` map
* `partition_value(string_type_value, datatype)`: Decode the partition value given as a string into the given datatype format. The interpretation of the string value is according to the Delta protocol.
Added UTs

[Kernel] Add `partition_value` and `element_at` expressions

---

kernel/kernel-api/src/main/java/io/delta/kernel/expressions/And.java
kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Or.java
kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Predicate.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/InternalScanFileUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/PartitionUtilsSuite.scala

Part of delta-io/delta#2071 (Partition Pruning in Kernel). This PR adds the following utility methods:
* Dividing `Predicate` given to the `ScanBuilder.withFilter` into data column and partition column predicates
* Rewrite the partition column `Predicate` to refer to the columns in the scan file columnar batch with the appropriate partition value deserialization expressions applied.  
Added UTs

[Kernel] Add partition pruning related utility methods

---

kernel/kernel-api/src/main/java/io/delta/kernel/client/FileReadRequest.java
kernel/kernel-api/src/main/java/io/delta/kernel/client/FileSystemClient.java
kernel/kernel-api/src/main/java/io/delta/kernel/fs/FileReadRequest.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/deletionvectors/DeletionVectorStoredBitmap.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultFileSystemClient.java

Adds interface `FileReadRequest` which exposes the necessary information for reading a deletion vector.

[Kernel] Add a FileReadRequest interface for reading deletion vectors

---

icebergShaded/generate_iceberg_jars.py

Building UniForm depends on cloning and then building iceberg at a particular commit, in order to apply patch files. It starts this by cloning iceberg `master` branch. This has been renamed to `main`, and so we need to update our script to use `main` accordingly, else it fails to build and tests fail.
Local build.
No

[Delta-Iceberg] Fix delta iceberg clone script

---

examples/scala/build.sbt
run-integration-tests.py

- Fix to scala version check in examples
- Fix to allow iceberg integration tests to use staged sonatype repo
Locally ran integration tests
```
python3 run-integration-tests.py --run-iceberg-integration-tests --version 3.0.0rc2 --maven-repo https://oss.sonatype.org/content/repositories/iodelta-1120
```

[branch-3.0] Minor fixes to examples and integration test script

---

project/Mima.scala

Previously, the command `build/sbt spark/mimaPreviousClassfiles` was failing with:
```
[info] Resolved  dependencies
[error] sbt.librarymanagement.ResolveException: Error downloading io.delta:delta-spark_2.12:2.4.0
[error]   Not found
[error]   not found: /Users/scott.sandre/.ivy2/localio.delta/delta-spark_2.12/2.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/2.4.0/delta-spark_2.12-2.4.0.pom
```
due to our previous logic in `Mima.scala`:
- `getPrevSparkVersion(3.0.1-SNAPSHOT)` --> correctly returned `2.4.0`
- `getPrevSparkName(3.0.1-SNAPSHOT)` --> incorrectly returned `delta-spark` (instead of `delta-core`)
We need to better couple our logic of "prev version" and "prev spark name" so that there is no mismatch here. This PR does just that. …

[branch-3.0] Fix mima logic for delta-spark

---

kernel/kernel-api/src/main/java/io/delta/kernel/data/ColumnVector.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/DeletionVectorDescriptor.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Format.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Metadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Protocol.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/ChildVectorBasedRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/ColumnarBatchRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/StructRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActiveAddFilesIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/types/TableSchemaSerDe.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/InternalUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/Utils.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/VectorUtils.java
kernel/kernel-api/src/test/java/io/delta/kernel/internal/types/JsonHandlerTestImpl.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/vector/AbstractColumnVector.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/vector/DefaultGenericVector.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/vector/DefaultStructVector.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/vector/DefaultSubFieldVector.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/vector/DefaultViewVector.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/client/TestDefaultJsonHandler.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/internal/parquet/TestParquetBatchReader.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/utils/DefaultKernelTestUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestRow.scala

Removes the `getStruct` API from `ColumnVector`. We will use a wrapper to convert to rows only for the ColumnarBatch/FilteredColumnarBatch row-based processing APIs.
Existing tests should suffice.

[Kernel] Remove the ColumnVector::getStruct API

---

kernel/examples/run-kernel-examples.py
kernel/examples/table-reader/src/main/java/io/delta/kernel/examples/BaseTableReader.java
kernel/examples/table-reader/src/main/java/io/delta/kernel/examples/MultiThreadedTableReader.java
kernel/examples/table-reader/src/main/java/io/delta/kernel/examples/SingleThreadedTableReader.java
kernel/examples/table-reader/src/main/java/io/delta/kernel/integration/IntegrationTestSuite.java

Add the following integration tests to verify the sanity of staged maven artifacts for Kernel release signoff.
* Reading a simple table w/o partitions
* Reading a simple table with partitions
* Reading only a subset of columns from a table
* Reading a table with deletion vectors
* Reading a table with deletion vectors and column mapping.
* Reading a table with partition pruning (simple filter)
* Reading a table with partition pruning (filter - combined with partition col filter and data col filter)
Here are the examples to run these tests
```
<repo-root>/kernel/examples/run-kernel-examples.py --use-local
<repo-root>/kernel/examples/run-kernel-examples.py --maven-repo=https://oss.sonatype.org/content/repositories/iodelta-1120 --version=3.0.0rc2
```

[Kernel] Add integration tests for staged/released maven artifact verification

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/package-info.java

Add missing `package-info` for `io.delta.kernel.defaults.client` package.

[Kernel] Add `package-info` for `io.delta.kernel.defaults.client` package

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/SnapshotManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala

Adds mocked unit tests for the log segment construction code.
Items to address
1) [P0] For some of the _valid file listings_ the error messages are confusing / misleading. We should fix these.
2) [P2] Behavior for _corrupt file listings_ is sporadic and inconsistent and error messages are confusing. We should consider fixing these at some point.
3) [P2] The log segment building code is really confusing. I think completely re-doing this has been discussed (?) at some point but is low priority. I'm planning to revisit this PR and see what low-effort improvements I can make for readability (max 15-20 minutes.)
Test PR.

[Kernel] Add mocked unit tests for log segment construction

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/RowConverter.java

We are using `==` to compare strings. It worked because we used the same static variable everywhere.

[Kernel] Fix comparison bug in default Parquet reader

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/DefaultKernelUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetBatchReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetSchemaUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/RowConverter.java

Just a refactoring. Currently, the Parquet related utility methods are in the generic utility file. Move them to a separate file as the utility methods are going to increase (with #2374).

[Kernel] Move Parquet utility methods into a separate utils file

---

kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java
kernel/kernel-api/src/main/java/io/delta/kernel/client/ParquetHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetSchemaUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/RowConverter.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/integration/TestDeltaTableReads.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetSchemaUtilsSuite.scala

Adds support for column mapping id mode. The Parquet handler API contract is updated to look for the field id in `StructField`s of given read schema. When field IDs are present attempt is made to look up the column in the Parquet file by ID. If not found, an attempt is made to find the column in the Parquet file by column name.
Added integration tests and granular unittests (converting missing field ids etc.) for the Delta schema to Parquet schema conversion utilities.

[Kernel] Add support for column mapping `id` mode

---

kernel/kernel-api/src/main/java/io/delta/kernel/expressions/And.java
kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Or.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultPredicateEvaluatorSuite.scala

Updates the `DefaultExpressionEvaluator` to follow SQL null semantics for the logical operators `AND` and `OR`.
Also updates the docs for those expressions.
Existing unit tests are updated.

[Kernel][Expressions] Update `AND` and `OR` expressions to follow SQL null semantics

---

kernel/kernel-api/src/main/java/io/delta/kernel/client/JsonHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultJsonHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/DefaultJsonRow.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/vector/DefaultSubFieldVector.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/client/TestDefaultJsonHandler.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultJsonHandlerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/ExpressionSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/VectorTestUtils.scala

Part of #2229
1. Updates the JsonHandler::parseJson method to take an optional selection vector based on the design of #2229 
2. Updates DefaultJsonHandler to support remaining data types needed for data skipping using JSON statistics. Semantics of this are based on Design Decision 3 in the design of #2229.
3. Minor fix for `DefaultSubFieldVector` when top-level structs are null (test included in `DefaultJsonHandlerSuite`)

[Kernel][Data skipping] Add selection vector for JsonHandler::parseJson and support remaining types in DefaultJsonHandler

---

kernel/kernel-api/src/main/java/io/delta/kernel/expressions/ScalarExpression.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/ExpressionUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/ExpressionVisitor.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala

This PR introduces the `COALESCE` expression to the kernel-api expression framework. It also adds support for resolving _only boolean type_ `COALESCE` expressions to the `DefaultExpressionHandler`. This is needed for data skipping #2229. Further support for `COALESCE` in the `DefaultExpressionHandler` can come in follow-up PRs.
Adds unit tests for boolean type expressions.

[Kernel][Expressions] Support COALESCE expression for boolean type arguments

---

connectors/golden-tables/src/main/resources/golden/deltalog-getChanges/_delta_log/00000000000000000000.json
connectors/golden-tables/src/main/resources/golden/deltalog-getChanges/_delta_log/00000000000000000001.json
connectors/golden-tables/src/main/resources/golden/deltalog-getChanges/_delta_log/00000000000000000002.json
connectors/golden-tables/src/test/scala/io/delta/golden/GoldenTables.scala
kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/SetTransaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplaySuite.scala

This PR adds an internal API on `SnapshotImpl` to fetch the latest version of the transaction identifier for a given app id. For now, this API is internal to unblock the Flink upgrade to use Kernel.
Unittest

[Kernel] Add an internal API to fetch the latest txn identifier

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/PartitionUtilsSuite.scala

Currently filters are incorrectly identified as partition vs metadata filters only by checking the first child when it is not a column and we don't progress through the for loop / rest of the children. Fix this.
Adds a unit test.

[Kernel] Fix splitting of partition & data predicates 

---

.github/workflows/kernel_test.yaml
kernel/examples/run-kernel-examples.py
kernel/examples/table-reader/src/main/java/io/delta/kernel/examples/SingleThreadedTableReader.java

We have been changing the Kernel APIs which may cause the examples to fail. Currently, examples/integration can only be run manually. This PR runs the integration as part of the PR CI job so that we can cause any failure during the PR time.
Also fixes an issue with the integration test run script when using the local version of Kernel code.
CI job

[Kernel] Run Kernel integration tests as part of the CI job

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/DataSkippingUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/StatsSchemaHelper.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ScanSuite.scala

Generate skipping filters for IS_NOT_NULL and NOT(IS_NOT_NULL). Note NOT(IS_NOT_NULL) won't skip until IS_NULL is supported.
Adds tests.

[Kernel][Data skipping] Generate data skipping filters when possible for IS_NOT_NULL

---

kernel/examples/table-reader/src/main/java/io/delta/kernel/integration/IntegrationTestSuite.java

Recent data-skipping feature support that went into the master requires few changes in the expected results of integration tests.
Ran locally. Will follow up with a PR to enable this as part of the CI.
`delta/kernel/examples/run-kernel-examples.py --use-local`

[Kernel] Fix the integration test failures due to recent changes

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/DataSkippingPredicate.java

Due to a merge conflict, this error didn't occur in the CI of PR that made the change.
https://github.com/delta-io/delta/actions/runs/7507859889/job/20442273564?pr=2497
```
[error] /home/runner/work/delta/delta/kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/DataSkippingPredicate.java:25:1:  error: type arguments not allowed here
[error]  * A {@link Predicate} with a set of {@link Set<Column>} of columns referenced by the expression.
[error]  
```
It looks like we can't have a reference to generics class with a particular type in javadoc due to [type erasure with generics](https://stackoverflow.com/questions/9482309/javadoc-bug-link-cant-handle-generics)
build succeeds locally

[Kernel] Fix javadoc generate error

---

build.sbt
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java

Downgrades SLF4J version to 1.x. Version 2.x includes additional APIs that are unsupported in lower versions. This avoids using those APIs.
Ran some unit tests and checked the output logs locally.

[3.1][Kernel] Downgrade SLF4J version to 1.x to avoid compatibility issues with connectors

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/PartitionUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/PartitionPruningSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ScanSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

Currently, column name in the logical schema is used for lookup. For column mapping mode enabled tables, partition values are stored with physical name.
Added tests for pruning with `id` and `name` modes

[Kernel] Fix issue with column mapping and partition pruning

---

docs/source/delta-batch.md
docs/source/delta-default-columns.md
docs/source/index.md

This PR adds documentation for default column values for Delta lake added in https://github.com/delta-io/delta/pull/2210. 
Docs-only changes.
No.

Add docs for default column values

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingFileIndex.scala
sharing/src/main/scala/io/delta/sharing/spark/PrepareDeltaSharingScan.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/TestClientForDeltaFormatSharing.scala
spark/src/main/scala/io/delta/sql/DeltaSparkSessionExtension.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/PrepareDeltaScan.scala

(Cherry-pick of https://github.com/delta-io/delta/pull/2480 to branch-3.1)
Fifth PR of https://github.com/delta-io/delta/issues/2291: Adds deletion vector support for "delta format sharing"
- Extends PrepareDeltaScan to PrepareDeltaSharingScan, to convert DeltaSharingFileIndex to TahoeLogFileIndex.
- Update DeltaSparkSessionExtension to add the rule of PrepareDeltaSharingScan
- Added unit test in DeltaSharingDataSourceDeltaSuite
Unit Tests
No

[Spark][Sharing][3.1] Add deletion vector support in delta format sharing

---

build.sbt

The new artifact `sharing` is missing the release settings.

[Build][Sharing] Add release settings to new `sharing` artifact

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java

Not all connectors will support SLF4J 2.x so we should avoid using these newer APIs.
Ran unit tests and checked the output logs locally.

[Kernel][Logging] Don't use the fluent logging API in SLF4J

---

spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala

This PR allows UniForm to work together with Liquid table by enabling column mapping before Liquid table read the column names.
This is a cherry-pick of #2521 
Unit tests
No

[UniForm] [3.1] Enable Column mapping in metadata before Cluster table fetch column names

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoDVsSuite.scala

Avoid redudant jobs in buildRowIndexSetsForFilesMatchingCondition.
In buildRowIndexSetsForFilesMatchingCondition we join the results DataFrame with the candidate file list to fetch the Deletion Vector Descriptors. Currently, there is a sanity check there to verify we do not eliminate any rows due to path encoding issues. The sanity check compares before and after counts. The counts produce 2 extra jobs which can cause a significant performance overhead. For example, in the case of merge each job could be a full shuffle join between the source and the target. This PR eliminates the extra jobs while maintaining the sanity check.
This is a cherry pick of https://github.com/delta-io/delta/pull/2516.
Added a new test in MergeIntoDVsSuite.
No.

[#2515][3.1][Spark] Avoid redudant jobs in buildRowIndexSetsForFilesMatchingCondition 

---

connectors/examples/flink-example/pom.xml
connectors/flink/src/main/scala/io/delta/flink/internal/KernelDeltaLogDelegator.scala
connectors/flink/src/main/scala/io/delta/flink/internal/KernelSnapshotDelegator.scala
connectors/flink/src/test/java/io/delta/flink/internal/KernelDeltaLogDelegatorTest.java
connectors/standalone/src/main/scala/io/delta/standalone/internal/SnapshotImpl.scala

Previously the logging call in `SnapshotImpl` could cause an infinite loop as it called `deltaLog.tableId` which tries to get a snapshot, which would loop back an construct a new snapshot which would try and log, and so on.
Since we're in the snapshot, we just get the snapshot's metadata and get the table id out of that.
Additionally, since the call to `metadataScala` now happens in the constructor of `SnapshotImpl` we need to ensure that `kernelSnapshotWrapper` is already existent in `KernelSnapshotDelegator` _before_ the `extends` call, as `metadataScala` accesses that. So we move `kernelSnapshotWrapper` to be an argument to the constructor.
- unit test (difficult to confirm this way generally due to SO being dependent on logging behavior)
- Running locally
No

[Flink] Fix stack overflow when table doesn't exist and using delta-kernel in flink

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaFormatSharingSource.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaFormatSharingSourceSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaTestUtils.scala

Cherrypick of #2547
Log more info in DeltaFormatSharingSource and throw error when server returns bad version.
Unit Test
No

[3.1][Spark][Sharing] Log more info in DeltaFormatSharingSource

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala

(Cherry-pick of #2557 to branch-3.1)
This PR adds Write PROTOCOL check to the Vacuum Command since it makes changes to delta directory.
UTs
No

[Spark] Add Writer Protocol check in Vacuum Command

---

docs/source/delta-default-columns.md
docs/source/index.md

Fix index to contain correct reference to `delta-default-columns` instead of `delta-column-defaults` and include default replacements.
N/A
No

[Docs] Fix documentation for default columns

---

build.sbt
sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala
sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingFileIndex.scala
sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingUtils.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingFileIndexSuite.scala

Cherrypick #2574 to branch-3.1
Fix Delta Sharing DataFrame not updated for Snapshot Query:
When provider updated the table(insert or delete row), in delta-sharing-spark session, the dataframe on the same query for the same table is not updated, though a new rpc is made, the local delta log is updated, but it’s still at version 0.
Unit Test, Integration Test
```
scala> val df = spark.read.format("deltaSharing").load(dvcmtable2)
df: org.apache.spark.sql.DataFrame = [id2: int, name: string]
scala> df.show()
+---+----+                                                                      
|id2|name|
+---+----+
|  2| one|
|  3| one|
+---+----+
// Insert on provider table
scala> val df = spark.read.format("deltaSharing").load(dvcmtable2)
df: org.apache.spark.sql.DataFrame = [id2: int, name: …
```

[Spark][Sharing] Fix Delta Sharing DataFrame not updated for Snapshot Query

---

protocol_rfcs/README.md
protocol_rfcs/in-commit-timestamps.md

Adds the proposal for spec change In-Commit Timestamps (see https://github.com/delta-io/delta/issues/2532) to the RFC folder.
Spec-only change.
No

[Protocol Change] Add the In-Commit Timestamps spec change proposal

---

protocol_rfcs/README.md
protocol_rfcs/type-widening.md

This protocol change is part of the proposed Type Widening table feature, see feature request: https://github.com/delta-io/delta/issues/2622
Protocol RFC issue: https://github.com/delta-io/delta/issues/2623
The type widening table feature covers changing the type of existing columns or nested fields in a Delta table without having to rewrite the data.
The Delta Lake Community encourages protocol innovations. Would you or another member of your organization be willing to contribute this feature to the Delta Lake code base?

[Protocol Change Request] Type Widening table feature

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultParquetHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ArrayColumnReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/DecimalColumnReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/MapColumnReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetColumnReaders.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFileReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/RepeatedValueConverter.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/RowColumnReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/TimestampConverters.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetSuiteBase.scala

Rename Parquet readers to maintain consistency with Parquet writers.
Resolves https://github.com/delta-io/delta/issues/2636
No

[Kernel] Rename Parquet readers to maintain consistency with Parquet writers

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitStore.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitStoreSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitStoreSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

With this change, we require CommitStores to maintain and return the latestTableVersion in the getCommits API. The motivation here is for readers to get more context from CommitStore when all commits are backfilled and the Commit Response is empty.
Clients can use latestTableVersion to determine the version the table is when all commits are backfilled and the commits list is empty in the getCommits response.
Unit tests
No

[Spark] Add LatestTableVersion to CommitStore GetCommits API response

---

.github/workflows/spark_test.yaml

Use Python packages compatible to both Python 3.8 and 3.9
https://setuptools.pypa.io/en/stable/history.html#v41-1-0
https://pypi.org/project/pandas/1.1.3/

[Spark] CI - Use Python packages compatible to Python 3.9 + Run CI when workflow files change

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeIntoMaterializeSource.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoMaterializeSourceSuite.scala

Be more defensive about calling `Option.get` on `materializedSourceRDD` and check first that it's actually `Some`. In fact only invoke the entire branch where we log only when we actually did materialize the source (and not, say, ran out of disk space before).
This PR adds a new test for the scenario where we throw an out of disk space error without having materialized the source.
No

[Spark] In materialize merge source: Only log storage error if we actually materialized

---

run-tests.py

This removes compiling unidoc from the spark CI tests since we've seen a flaky failure on #2727.
We will follow up and create a separate job just for unidoc (which makes more sense anyways as it should run for changes in any of the projects.)
CI runs.

[CI] Disable running unidoc from the spark CI tests for now

---

PROTOCOL.md

The protocol spec accidentally described the version field for the DV file format as being `0 - 1`, i.e. a 2-byte range, but in truth it's only a single byte. This was likely a left-over from when the spec describe the ranges with exclusive bounds, rather than inclusive. This PR corrects this to clarify that only byte 0 contains the version number.
n/a
No.

[Protocol] Correct Delta Spec DV version field byte range

---

spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaEncoders.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala

The ICT is now retrieved during the Protocol & Metadata query. The only time this query will not retrieve the ICT will be when the latest version has a checkpoint. In that case, we fall back to reading the ICT from latest commit directly.
Added multiple tests in InCommitTImestampSuite
No

[Spark] Read In-Commit Timestamp during the P&M query

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/DeletionVectorDescriptor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeletionVectorsTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/deletionvectors/DeletionVectorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaSQLTestUtils.scala

This PR follows https://github.com/delta-io/delta/pull/2696 and https://github.com/delta-io/delta/pull/2719 to finally enable testing special characters in all DV tests.
One test is currently failing due to a potential bug in the `OPTIMIZE` code path, which is pending investigation.
Test-only.
No.

[Spark] Test special characters for temp folders used by DV tests

---

build.sbt

This dependency is needed for https://github.com/delta-io/delta/pull/2701/files.

[Kernel][Build] Add `jmh` dependency in kernel-defaults module

---

build.sbt
connectors/golden-tables/src/test/scala/io/delta/golden/GoldenTables.scala
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActionsIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/BasePrimitiveType.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultTableClient.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/benchmarks/BenchmarkParallelCheckpointReading.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplayMetricsSuite.scala

Currently, the `kernel-api` reads one file (either checkpoint or commit file) at a time. Once the file is fully read, then the next file is read request is issued. This makes reading large checkpoints split over multiple files slower. Instead `kernel-api` could issue read requests for all checkpoint files at once (in case of multi-part checkpoints) using the `ParquetHandler.readParquetFiles` and let the implementations of the `ParquetHandler` prefetch or using multiple threads to read the checkpoint parts concurrently.
This PR makes the change to `kernel-api` to issue one read request for all checkpoint files that need to be read for state reconstructions.
Resolves #2668
Resolves #1965
Existing tests and a benchmark with a test only parallel parquet reader. Here are the sample benchmark …

[Kernel][LogReplay] Make a single read request for all checkpoint files

---

spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala

Renames LogSegment.lastCommitTimestamp to lastCommitFileModificationTimestamp so as to distinguish this file timestamp from in-commit-timestamp.
Related to https://github.com/delta-io/delta/issues/2532 . 
Name-only change.
No

[Spark] Rename lastCommitTimestamp to lastCommitFileModificationTimestamp

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/columnmapping/RemoveColumnMappingCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingSuiteUtils.scala

Implement basic rewrite command to rewrite a table with column mapping enabled.
New unit tests

[Spark]Column mapping removal basic rewrite operation

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableFeatureSuite.scala

Add a new VacuumProtocolCheck ReaderWriter Table Feature so that Vacuum command on older DBR client and OSS clients fail.
This is in follow-up to https://github.com/delta-io/delta/pull/2557 where protocol-check was added during the vacuum-write flow.
UTs
No

[Spark]Add VacuumProtocolCheck ReaderWriter Table Feature

---

connectors/golden-tables/src/test/scala/io/delta/golden/GoldenTables.scala
kernel/kernel-api/src/main/java/io/delta/kernel/client/ExpressionHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultExpressionHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/ElementAtEvaluator.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultExpressionHandlerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/ExpressionTestUtils.scala

Having the API to tell if an expression is supported on a given input schema and expected data type, can make the Kernel make better decisions in splitting the given query predicate to a guaranteed predicate and a best-effort predicate. The proposed API is:
```
/**
* Is the given expression evaluation supported on the data with given schema?
*
* @param inputSchema Schema of input data on which the expression is evaluated.
* @param expression Expression to evaluate.
* @param outputType Expected result data type.
* @return true if supported and false otherwise.
*/
boolean isSupported(StructType inputSchema, Expression expression, DataType outputType);
```
Unittests

[Kernel] Add `ExpressionHandler.isSupported` to check for expression support

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaAlterTableTests.scala

Users are currently allowed to change the data type of their columns from char/varchar to string. Even though the command succeeds, the column metadata that indicates that the column is char/varchar is not removed during the process. As a result, Delta enforces the old char/varchar constraints on future inserts.
This PR fixes that by removing this metadata from any updated char/varchar column when the column is updated.
Added a new test which was failing without the code fix.
Yes, `ALTER COLUMN X TYPE STRING;` will now work correctly when X is char/varchar.

[Spark] Fix char/varchar to string column conversions

---

spark/src/main/scala/io/delta/tables/DeltaMergeBuilder.scala
spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/deltaMerge.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableMerge.scala
spark/src/main/scala/org/apache/spark/sql/delta/ResolveDeltaMergeInto.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/MergeCDCSuite.scala

This PR teaches the `MERGE INTO` command to turn on schema evolution when there exists `WITH SCHEMA EVOLUTION` keywords in the commands.
Changes in this PR are:
1. Modify case classes `MergeIntoCommand` and `DeltaMergeInto` to store schema evolution enablement information.
2. For `DeltaMergeInto`, we reuse the existing migrateSchema fields instead of adding a new one.
3. Scala user-facing `DeltaMergeBuilder` API.
Changed to be done but not in this PR:
1. Python user-facing DeltaMergeBuilder API.
2. Extend schema evolution tests to test `WITH SCHEMA EVOLUTION` keywords.
Improving the existing tests.
This PR allows user to turn on automatic scheme evolution for a specific MERGE command by issuing `MERGE WITH SCHEMA EVOLUTION INTO ...` SQL commands.

[Spark] MERGE INTO: turn on schema evolution when WITH SCHEMA EVOLUTION is given in SQL command

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/StatisticsCollection.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/StatsCollectionSuite.scala

This PR fixes a bug that happens when collecting the column attributes specified inside Delta statistic column table property.
The Delta statistic column table property translates all columns' name into lower case while table schema keep the case of each column created by customer. As a result, if there are upper case columns inside table definition, the delta statistic collection would miss these columns.
This PR fixes this issue by translating the column name to lower case while searching statistic columns.
Modify existing test case to cover more column character cases.

[Spark] Fix case sensitive of delta statistic column

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingSuiteUtils.scala

Add additional tests for tables with deletion vectors, generated columns and column constraints for column mapping removal.
New unit tests
No

[Spark] Column mapping removal: support tables with deletion vectors, column constraints and generated columns.

---

spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoTestUtils.scala

This PR follows https://github.com/delta-io/delta/pull/2737 (https://github.com/delta-io/delta/commit/bbbace1085e46d2ebaa6204bf2603d0a4e2f23ee) to add tests for turning on schema evolution via the `.withSchemaEvolution()` Scala API.
It also introduce a placeholder for the upcoming support for the SQL API.
This PR is test-only.
No.

[Spark] Add tests for MERGE with schema evolution Scala API

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala

Mark the flaky `"DeltaLog should throw exception when unable to create log directory with silent filesystem failure"` DeltaLogSuite test as ignored.
No

[Spark] Disable flaky DeltaLogSuite unit test that relies on filesystem behavior

---

spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdCloneSuite.scala

Add Row Tracking self-clone tests, making sure we have enough Row Tracking test coverage necessary to gear us towards [enabling Row Tracking outside of testing](https://github.com/delta-io/delta/pull/2059).
Existing + added UTs.
No.

[Spark][Test-Only] Add Row Tracking self-Clone tests

---

protocol_rfcs/managed-commits.md

This change puts added responsibility on CommitStore to return the latestTableVersion in the CommitStore.getCommits API along with the list of Commits. 
Protocol RFC issue: https://github.com/delta-io/delta/issues/2598
The Delta Lake Community encourages protocol innovations. Would you or another member of your organization be willing to contribute this feature to the Delta Lake code base?

[PROTOCOL Change Request] Return latestTableVersion in the CommitStore.getCommits API

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitStore.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckpointsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

This PR adds support for cold and hot snapshot update for managed-commits.
UTs
No

[SPARK] Managed Commit support for cold and hot snapshot update

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaDataFrameWriterV2Suite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSinkSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

Followup for this PR https://github.com/delta-io/delta/pull/2695, that classifies DeltaAnalysisException. This includes test change only to use checkError for exception verification.
existing tests changed
No

[Spark] Use checkError for testing DeltaAnalysisException

---

spark/src/main/scala/org/apache/spark/sql/delta/constraints/DeltaInvariantCheckerExec.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/CheckConstraintsSuite.scala

Heading towards the removal of codegenFallback from Date/Time expressions (https://github.com/apache/spark/pull/44261), delta constraints need to resolve current_datetime expressions during the analysis of the invariants. The proposed changes work for both Spark 3.5 and Spark master.
Existing tests. In particular, `CheckConstaintsSuite` covers constraints with `current_timestamp()` expressions. Added an extra test to cover `current_date()`.
No.

[Spark] Current Date/Time resolution in constraints

---

python/delta/tables.py
python/delta/tests/test_deltatable.py

This PR continues from https://github.com/delta-io/delta/pull/2737 to add a `withSchemaEvolution()` method for `DeltaMergeBuilder` in PySpark.
New unit tests.
Yes, this PR allows the user to turn on schema evolution for MERGE in PySpark by calling the `table.merge(...).withSchemaEvolution()` method.

[PySpark] Add schema evolution config to PySpark `DeltaMergeBuilder`

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableStrategy.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

Currently, when running OPTIMIZE on a clustered table without any clustering columns(after ALTER TABLE CLUSTER BY NONE), it would fail with a long stack trace:
```
[info]   org.apache.spark.SparkException: Exception thrown in awaitResult:
[info]   at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[info]   at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[info]   at org.apache.spark.util.ThreadUtils$.parmap(ThreadUtils.scala:383)
[info]   at org.apache.spark.sql.delta.commands.OptimizeExecutor.$anonfun$optimize$1(OptimizeTableCommand.scala:276)
...
[info]   Cause: java.util.concurrent.ExecutionException: Boxed Error
[info]   at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
...
[info]   Cause: java.lang.AssertionError: …
```

[Spark] OPTIMIZE on clustered table with no clustering columns should run compaction

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultFileSystemClient.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/DefaultTableClientErrors.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/logstore/LogStoreProvider.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/logstore/LogStoreProviderSuite.scala

`LogStore`s in `storage` module have file system operations (needed for reading/writing DeltaLogs) implemented for each storage (e.g. s3, GCS etc.) to take into account of the behavior of storage and also efficiently implement certain operations depending upon the storage system support (e.g. fast listing in S3).
This PR creates `LogStoreProvider` to get the specific implementation of the `LogStore` for given `scheme`. Also updates the `DefaultFileSystemClient.listFrom` to use the `LogStore.listFrom`.
The majority of the code here is copied from the `delta-spark` and `standalone` projects. 
Unittests for `LogStoreProvider` and existing integration tests for `DefaultFileSystemClient.listFrom` changes.

[Kernel] Use `LogStore`s in `listFrom` implementation in default `FileSystemClient`

---

spark/src/main/scala/org/apache/spark/sql/delta/BusyWait.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/AtomicBarrier.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/PhaseLockingTestMixin.scala
spark/src/test/scala/org/apache/spark/sql/delta/fuzzer/AtomicBarrierSuite.scala

Added the `AtomicBarrier` and `PhaseLockingTestMixin`, the initial building blocks of the Concurrency Testing framework, in order to make way to add a Suite that tests the interaction of the `ConflictChecker` with the `RowTracking` feature, ensuring Row Tracking is well-tested and getting ready for [enabling Row Tracking outside of testing in Delta](https://github.com/delta-io/delta/pull/2059).
Added UTs.
No.

Add Atomic Barrier and PhaseLockingTestMixin

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTypeWideningSchemaEvolutionSuite.scala

This change is part of the type widening table feature.
Type widening feature request: https://github.com/delta-io/delta/issues/2622
Type Widening protocol RFC: https://github.com/delta-io/delta/pull/2624
It adds automatic type widening as part of schema evolution in INSERT. During resolution, when schema evolution and type widening are enabled, type differences between the input query and the target table are handled as follows:
- If the type difference qualifies for automatic type evolution: the input type is left as is, the data will be inserted with the new type and the table schema will be updated in `ImplicitMetadataOperation` (already implemented as part of MERGE support)
- If the type difference doesn't qualify for automatic type evolution: the current behavior is preserved: a …

Automatic type widening in INSERT

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeFileIndex.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeRemoveFileIndex.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala

Adding the `base_row_id` field to the `_metadata` column for Delta tables. This field contains the value in the `baseRowId` field of the `AddFile` action for the file, allowing us to read the `base_row_id` from the file metadata after it is stored.
Added UTs.
No.

[Spark] Add read support for baseRowID

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/JsonMetadataDomain.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala

This refactors `RowTrackingMetadataDomain.isRowTrackingDomain` to `JsonMetadataDomain.isSameDomain` so that it can be useful for other domain metadata.

refactor isSameDomain for JsonMetadataDomain

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

We want Delta OSS to cross-compile against both Spark 3.5 and Spark Master (4.0).
Unfortunately, the constructor `new AnalysisException("msg")` became protected in Spark 4.0, meaning that all such occurances do not compile against Spark 3.5.
Thus, we decided to:
- replace `AnalysisException` with `DeltaAnalysisException`
- use errorClasses
- assign temporary error classes when needed to speed this along
This PR replaces the first 5 (of ~20) compilation errors.
New UTs in `DeltaErrorsSuite`.
Also, cherry-picked to the oss-cross-compile branch (https://github.com/delta-io/delta/pull/2780) and cross-compiled:
- (this branch) Spark 3.5: ✅ 
- (this branch) Spark 4.0: 11 compilation errors. (the oss-cross-compile branch has 16 compilation errors, this is expected)
No

[Spark] [Delta X-Compile] Refactor AnalysisException to DeltaAnalysisException (batch 1)

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DescribeDeltaDetailsCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaCommitFileProvider.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/FileNames.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

This PR introduces necessary adjustments in our approach to locating delta files, prompted by the adoption of managed-commits. Previously, certain code paths assumed the existence of delta files for a specific version at a predictable path `_delta_log/$x.json`. This assumption is no longer valid with managed-commits, where delta files may alternatively be located at `_delta_log/_commits/$x.$uuid.json`. We attempt to locate the correct delta files from the Snapshot's LogSegment now.
Add managed-commits to some of the existing UTs
No

[Spark]Update Delta File Resolution Logic with introduction of Managed Commits

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala

Delete a currently ignored test case.
N/A (only a test removal)
No

[Spark] Delete disabled flaky DeltaLogSuite test case

---

docs/source/delta-default-columns.md

The documentation incorrectly notes that "Enabling default column values for a table upgrades the Delta table version as a byproduct of enabling table features. This protocol upgrade is irreversible. Tables with default column values enabled can only be read in Delta Lake 3.1 and above."
Signed-off-by: Miles Cole [m.w.c.360@gmail.com](mailto:m.w.c.360@gmail.com)
Default columns is a writer table feature, not a reader feature.
I confirmed that a table with the defaultColumns table feature was readable by delta lake 3.0
No

[BUG] Default columns is a writer table feature, not a reader feature.

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala

Added support for Java8 time objects when Java8Api is enabled. 
The following query fails when Java8Api is enabled:
```
INSERT INTO $tableName REPLACE
where (DATE IN (DATE('2024-03-11'), DATE('2024-03-12')))
VALUES ('1', DATE('2024-03-13'))
```
Unit Test.
The potential public surface area for this change is limited to only external DateType, TimestampType. By default, Spark converts DateType values to java.sql.Date, TimestampType -> java.sql.Timestamp but with the SQL conf enabled, Spark uses java.time.LocalDate as the external type for DateType and java.time.Instant for TimestampType.
Necessity of fix: If users use Spark 3.0 and enable Java 8, they will be unable to parse and use dates in Delta tables correctly, leading to matching errors.

Support Java8 time objects

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala

We move the Table Feature from dev/test only to prod as part of this PR.
Existing UTs
No

[Spark] Move VacuumProtocolCheck Table Feature from Dev/Testing to Prod

---

icebergShaded/iceberg_src_patches/0005-iceberg-takes-updated-source-column-field-id.patch

context: Delta and Iceberg traverse schema and assigns field id in different way. Delta uniform currently use a extra Iceberg txn to overwrite the schema in iceberg table with wrong field ids reassigned by Iceberg.
However, if the source field id for partition columns is different in that schema overwrite txn, Iceberg always expect field id for partition columns to be the same and does not have logic to reconcile that, and then Iceberg will fail the overwrite txn. This PR adds the logic to adopt new source column field id to Iceberg PartitionField if changed, so the overwrite txn can go through and set the correct source column field id for PartitionFields.
parent PR https://github.com/delta-io/delta/pull/2676
manual test; unit test will come soon.

[Delta Uniform] overwrite source column field id for Iceberg PartitionField with field id assigned by Delta - 3.1

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSchemaEvolutionSuite.scala

We want Delta to cross-compile against both Spark 3.5 and Spark Master (4.0).
Unfortunately, the constructor `new AnalysisException("msg")` became protected in Spark 4.0, meaning that all such occurances do not compile against Spark 3.5.
Thus, we decided to:
- replace `AnalysisException` with `DeltaAnalysisException`
- use errorClasses
- assign temporary error classes when needed to speed this along
This PR fixes compilation errors [6, 11] of ~20.
New UTs in `DeltaErrorsSuite`.
Also, cherry-picked to the oss-cross-compile branch (https://github.com/delta-io/delta/pull/2780) and cross-compiled:
- (this branch) Spark 3.5: ✅ 
- (this branch) Spark 4.0: 10 compilation errors. (the oss-cross-compile branch has 16 compilation errors, this is expected)
No

[Spark] [Delta X-Compile] Refactor AnalysisException to DeltaAnalysisException (batch 2)

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/io/delta/exceptions/DeltaConcurrentExceptions.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

This PR bolsters the concurrent exceptions Delta throws by adding error codes to them and plugs them into the DeltaThrowable framework.
Added unit tests to verify the error codes get populated correctly for these exceptions.

[Spark] Add error codes to Delta concurrent exceptions

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/checkpoints/Checkpointer.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/checkpoints/CheckpointerSuite.scala

Currently, Kernel stops on first failure at loading the `_last_checkpoint` file (which contains info about the last checkpoint). We should have mechanisms to retry just like how Delta-Spark retries on retryable failures. More details are [here](https://docs.google.com/document/d/13Nock1I8-143Dwidj8rMpgt3wAicrOI2OvDJt3OufOQ/edit?usp=sharing).
Added mock unittests

[Kernel] Retry `_last_checkpoint` loading in case of failures

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala

Previously, `deltaLog.getHistory(start, endOpt)` served the `[start, endOpt]` range. However, this behavior was accidentally changed in #2799 to serve the `[start, endOpt)` range.
We revert it back to the original behavior and also update the function comment.
UTs
No

[Spark] Update deltaLog.getHistory to serve [start, end] version range

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/threads/DeltaThreadPool.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala

Improve performance of listDeltaCompactedDeltaAndCheckpointFilesWithCommitStore by making parallel calls to both the file-system and a commit-store (if available), reconciles the results to account for concurrent backfill operations and potentially makes another list call on the file-system to ensure a comprehensive list of file statuses.
UTs
No

[Spark]Parallelize deltaLog listFrom and commitStore getCommits call

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala

This PR updates the ensureLogDirectoryExist method to optimistically handle directory creation by attempting to create the directory before checking its existence. This is efficient because we're assuming it's more likely that the directory doesn't exist and it saves an filesystem existence check in that case.
Cloud Hadoop implementations are expected to throw org.apache.hadoop.fs.FileAlreadyExistsException if the file already exists. e.g. [S3AFileSystem.java](https://github.com/apache/hadoop/blob/fc166d3aec7c95110a8cd4ef6ce1fbf4955107e5/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java#L3763)
Unix-based File Systems are expected to throw java.nio.file.FileAlreadyExistsException if the file already exists.
To cover all bases, including unforeseen file …

[Spark]Optimize Directory Creation in ensureLogDirectoryExists method

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/io/delta/tables/DeltaColumnBuilder.scala
spark/src/main/scala/io/delta/tables/DeltaMergeBuilder.scala
spark/src/main/scala/io/delta/tables/DeltaTableBuilder.scala
spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DeltaUpdateTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/AnalysisHelper.scala
spark/src/test/scala/io/delta/tables/DeltaTableBuilderSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaDropColumnSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

We want Delta to cross-compile against both Spark 3.5 and Spark Master (4.0).
Unfortunately, the constructor `new AnalysisException("msg")` became protected in Spark 4.0, meaning that all such occurances do not compile against Spark 3.5.
Thus, we decided to:
- replace `AnalysisException` with `DeltaAnalysisException`
- use errorClasses
- assign temporary error classes when needed to speed this along
This PR fixes all remaining related compilation errors.
New UTs in `DeltaErrorsSuite`.
Also, cherry-picked to the oss-cross-compile branch (https://github.com/delta-io/delta/pull/2780) and cross-compiled:
- (this branch) Spark 3.5: ✅ 
- (this branch) Spark 4.0: no remaining compilation errors.

[Spark] [Delta X-Compile] Refactor AnalysisException to DeltaAnalysisException (batch 3) 

---

kernel/kernel-api/src/test/scala/io/delta/kernel/internal/DeltaHistoryManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/checkpoints/CheckpointerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockFileSystemClientUtils.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockTableClientUtils.scala

We have been duplicating the mocking `TableClient` across the test suites. Consolidate and make common utilities/classes that allow mocking `TableClient` with minimal code.
`MockTableClientUtils.scala` - is the base trait for mocking `TableClient`.
Just a refactor

[Kernel][Tests] Refactor `TableClient` mocking code duplication into a single file

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/InCommitTimestampUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala

Makes DeltaHistoryManager.getActiveCommitAtTime aware of `inCommitTimestamps`. DeltaHistoryManager.getActiveCommitAtTime will now bisect the history of commits into non-ICT and ICT commits based on the ICT enablement version and only search the range of commits relevant to the timestamp. If the relevant commit range is composed of ICT commits, `getActiveCommitAtTime` will perform a parallelized search (see `getActiveCommitAtTimeFromICTRange` for details).
New tests in InCommitTimestampSuite.
No

[Spark] InCommitTimestamps: Use parallel radix search for ICT commit history

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/checkpoints/CheckpointInstance.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checkpoints/Checkpointer.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/checkpoints/CheckpointerSuite.scala

Adds a utility method for iteratively searching backwards 1000 delta versions at a time from a given version to find the checkpoint. This utility method is used when loading a snapshot by version id. This is similar to how delta-spark does. More details are [here](https://docs.google.com/document/d/13Nock1I8-143Dwidj8rMpgt3wAicrOI2OvDJt3OufOQ/edit?usp=sharing).
Existing tests and mock unittests for granular tests.

[Kernel] Iteratively search (1000 versions at a time) for last checkpoint before a given version

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala

The existing Uniform convertion txn has a logic to launch a second txn to set schema, after the first CREATE TABLE or REPLACE TABLE txn, to set the correct field ids because Iceberg may reassign those. This behavior has following flaws:
Firstly iceberg core does NOT reassign field id for REPLACE txn if the table already exists (in Uniform case it always does). So set schema for REPLACE TABLE is not necessary.
Secondly, Uniform uses the replace transaction when number of snapshots to convert exceeds threshold. The replace txn will set last Delta converted version as -1, which can be confusing or erroneous.
This PR fixes above flaws by NOT set schema for REPLACE txn.
Manually tested. Unit test will come in separate PR.

only overwrite schema and field id for create table Iceberg conversion txn

---

spark/src/test/scala/org/apache/spark/sql/delta/CustomCatalogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

We want Delta to be able to cross-compile against Spark 3.5 and Spark Master (4.0).
Previously we have gotten Delta production code to compile (in a branch that enables shimming).
This PR gets the test code to compile, too, using changes that are forwards-compatible with spark master.

[SPARK] [Delta X-Compile] Get `delta-spark` tests cross-compiling against Spark 3.5.0 and Spark Master

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitStore.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuiteBase.scala

Handle CommitFailedException in OptimisticTransaction::commitLarge depending on the values of `retryable` and `conflict` in the exception.
UTs to cover the scenarios
No

[Spark]Handle CommitFailedException in OptimisticTransaction::commitLarge

---

spark/src/test/scala/org/apache/spark/sql/delta/DDLTestUtils.scala

In this PR, we add DDLTestUtils helper and ColumnSpec traits so that we have flexible interfaces for defining Delta tables. This will enable us to test both Scala and SQL interfaces easier. This PR introduces the helpers but this interface will not be used until later. 
We don't reuse the helper functions in GeneratedColumnSuite because they are less flexible. We can rewrite GeneratedColumnSuite to use DDLTestUtils later on.
Unused code. Introducing the interface only.
No.

[Spark][TEST-ONLY] Add DDLTestUtils helper

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaCommitFileProvider.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckpointsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogMinorCompactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitStoreSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

With managed-commit, commit files are not guaranteed to be present in the _delta_log directory at the time of checkpointing or minor compactions. While it is possible to compute a checkpoint file without backfilling, writing the checkpoint file in the log directory before backfilling the relevant commits will leave gaps in the directory structure. This can cause issues for readers that are not communicating with the CommitStore.
To address this problem, we now backfill commit files up to the committedVersion before performing a checkpoint or minor compaction operation
UTs
No

[Spark] Backfill commit files before checkpointing or minor compaction in managed-commits

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/TransactionExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/ExecutionPhaseLock.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/OptimisticTransactionPhases.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/PhaseLockingTransactionExecutionObserver.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionObserverSuite.scala

1. Add an observer field to `OptimisticTransaction` which can can be set via a thread-local to a custom instrumentation class. Instrumentation methods are invoked when creating a new transaction, for `prepareCommit`, for `doCommit`, and for completion of a transaction (failure or successful).
2. The default observer simply performs no-ops.
3. Added a testing `PhaseLocking` observer implementation that allows both observing, but also blocking the transaction's thread until unblocked by another thread. This allows fine control of how the transaction progresses, which is needed for some testing scenarios.
Added UTs.
No.

[Spark] Add TransactionExecutionObserver

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala

Return the ICT (In-Commit Timestamp) timestamp for ICT-enabled ranges in DeltaHistoryManager.getHistory when ICT is currently enabled.
New tests:
1. When all of history has ICT enabled.
2. When requested history is not an ICT range.
3. When requested range contains both ICT and non-ICT commits.
No visible differences for the user, the timestamp returned by `DESCRIBE HISTORY` will be different depending on whether ICT is currently enabled.

[Spark] Make DeltaHistoryManager.getHistory aware of ICT

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/checkpoints/Checkpointer.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java

Add log4j logging in the following cases:
1) Time taken to get the version for a given timestamp in time travel
2) When the `_last_checkpoint` metadata file is missing or corrupted.
3) Time to find the last completed checkpoint before a version.
4) Time to list the delta files after a given last checkpoint
5) Time to construct a `LogSegment`
6) Time to construct a snapshot with a `LogSegment` (includes loading P&M)
Manually verified.

[Kernel] Adding logging in few important places to help in debugging

---

spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdSuite.scala

Add read Delta format to tests that are not using it in `RowIdSuite`.
If we don't specify the format when reading from the path, the default would be Parquet. We would like to make sure all the relevant Row Tracking tests to use the Delta format to properly test Row Tracking.
Existing UTs.
No.

[Spark] Make sure the RowId Suite tests use the Delta Format when reading from path

---

spark/src/main/scala/org/apache/spark/sql/delta/ConcurrencyHelpers.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/PhaseLockingTestMixin.scala

We will soon add some common helper functions for the Concurrency Testing Framework, so we are renaming the object `BusyWait` to `ConcurrencyHelpers` in preparation for this.
Existing UTs, just some small name changes.
No.

[Spark] Rename BusyWait to ConcurrencyHelpers

---

spark/src/main/scala/org/apache/spark/sql/delta/ConcurrencyHelpers.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionTestMixin.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/ConflictCheckerRowIdSuite.scala

Add the `ConflictCheckerRowIdSuite`, to test the Row Tracking's Conflict Checker logic. We want to ensure that each row ID can only be assigned by one transaction. If we detect that a concurrent transaction also assigned row IDs, then we will assign different row IDs to the files added by the current transaction.
Add UTs.
No.

[Spark] Add ConflictCheckerRowIdSuite

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/WriteIntoDelta.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

Now that incremental clustering, ALTER TABLE CLUSTER BY and DESC DETAIL are merged, we can remove the preview guard for clustered table, to prepare for OSS 3.2 release.
Yes. User will no longer get the preview warning when they try out clustered table.

[Spark] Remove preview guard for clustered table

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeFileIndex.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/ActionSerializerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuite.scala

* Do not use the literal "testId" for every single tahoeId in testing. This can hide issues where we use the wrong id (for example as key in a map).
* Fix one of these issues with the partition stats for auto compaction, where we used a completely random tableId as the key, rather than than the tableId that commitLarge just wrote.
* Add a (temporary) flag to not include the tahoeId in the equals and hashCode methods of TahoeLogFileIndex. Having an unstable external field there is prone to race conditions (of the form this != this) and losing instances in hash sets/maps. So ideally we should make this the default.
Testing-only PR.
No.

[Spark] Don't use fixed tahoe id for testing

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/WriteIntoDelta.scala

In `WriteIntoDelta.scala`, there is a small mistake that we hardcode the default value of `SQLConf.READ_SIDE_CHAR_PADDING` to be `false`, instead of respecting the config definition.
existing test.
no

[Spark] do not hardcode the default conf value of READ_SIDE_CHAR_PADDING

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultParquetHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFileReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFilterUtils.java
kernel/kernel-defaults/src/main/java/org/apache/parquet/hadoop/ParquetRecordReaderWrapper.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/benchmarks/BenchmarkParallelCheckpointReading.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetFileReaderSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetReaderPredicatePushdownSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetSuiteBase.scala

Pushing down the predicate helps read fewer records especially when getting the scan files and reading multi-part checkpoint files.
The current library we use parquet-mr already has support for pruning the records based on the stats in rowgroups and individual records as each record is read. This PR converts the given Kernel `Predicate` into `parquet-mr` predicate and gives as input to the `parquet-mr` reader.
The support is only to prune the row groups using the pushed-down predicate. Individual record level filter is disabled due to the following reasons:
*  the `parquet-mr` materializes the entire record first before evaluating the predicate. This causes implementation challenges around the current `ColumnarBatch` construction out of the rows returned by the `parquet-mr`
* We have …

[Kernel] Support filter pushdown in default parquet reader

---

spark/src/main/scala/io/delta/sql/DeltaSparkSessionExtension.scala
spark/src/main/scala/org/apache/spark/sql/delta/ColumnWithDefaultExprUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/GenerateRowIDs.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TransactionalWrite.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/ImplicitMetadataOperation.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaParquetFileFormatSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/GenerateRowIDsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

1. Add the Analyzer Rule `GenerateRowIds` to generate default Row IDs.
2. Add the `row_id` field to the `_metadata` column for Delta tables, allowing us to read the `row_id` from the file metadata after it is stored.
Added UTs.
No.

[Spark] Add read support for RowId

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala

In the DROP FEATURE command we generate a checkpoint after cleaning reader+writer feature traces to allow metadata cleaning operations to truncate history before the cleanup. However, the checkpoint is not created if the cleanup operation does not do any work. This might cause an issue in some cases if the cleanup operation does not perform any work but there are historical traces that needed to be truncated. A scenario like this may occur if the user manually cleans the feature traces before invoking the DROP FEATURE command. This PR resolves this issue by relaxing the conditions the checkpoint is created. Note, this has as a side effect to create a checkpoint in both invocations of the DROP FEATURE command.
Added a new test in DeltaProtocolVersionSuite.
No.

[Spark] Always create checkpoint when dropping reader+writer features

---

build.sbt
project/Unidoc.scala
spark/src/main/scala-spark-3.5/shims/ColumnDefinitionShim.scala
spark/src/main/scala-spark-3.5/shims/IncrementalExecutionShim.scala
spark/src/main/scala-spark-3.5/shims/UnresolvedTableShim.scala
spark/src/main/scala-spark-master/shims/ColumnDefinitionShim.scala
spark/src/main/scala-spark-master/shims/IncrementalExecutionShim.scala
spark/src/main/scala-spark-master/shims/UnresolvedTableShim.scala
spark/src/main/scala/io/delta/sql/parser/DeltaSqlParser.scala
spark/src/main/scala/io/delta/tables/DeltaTableBuilder.scala
spark/src/main/scala/io/delta/tables/execution/VacuumTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/ColumnWithDefaultExprUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/test/scala/io/delta/sql/parser/DeltaSqlParserSuite.scala

- changes Delta's `build.sbt` to compile `delta-spark` against spark master. compilation succeeds. tests pass against spark 3.5. tests run but fail against spark master
- e.g. `build/sbt -DsparkVersion=master spark/test`
- the default spark version for Delta is still Spark 3.5
- testing requires building unidoc for (unfortunately) ALL projects in build.sbt. that breaks since spark master uses JDK 17 but delta-iceberg uses JDK 8. thus, we disable unidoc for delta-spark compiling against spark-master for now.
- Delta: creates `spark-3.5` and `spark-master` folders. Delta will be able to cross compile against both. These folders will contain `shims` (code that will be selectively pulled to compile against a single spark version) but also spark-version-only code
- this PR does not update any …

Make Delta able to cross-compile against Spark Latest Release (3.5) and Spark Master (4.0)

---

PROTOCOL.md

Currently, Delta protocol doesn't specify how a Delta data type is stored physically in Parquet files. This PR is attempting to document the Delta data type to Parquet physical/logical type mappings.
NA
No

Add Delta data type to Parquet physical type mappings in PROTOCOL.md

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala

Adds drop feature support for InCommitTimestamps. When the user runs DROP FEATURE, the following will happen if ICT is present in the PROTOCOL:
1. If any of the ICT-related properties are present, the first commit will:
- Set `IN_COMMIT_TIMESTAMPS_ENABLED` = true
- Remove `IN_COMMIT_TIMESTAMP_ENABLEMENT_VERSION` and `IN_COMMIT_TIMESTAMP_ENABLEMENT_TIMESTAMP`
2. A second commit will remove ICT from the protocol.
New tests in the DeltaProtocolVersionSuite for the following scenarios:
1. When ICT is enabled from commit 0 onwards.
2. When ICT is enabled in some commit after 0.
3.  Dropping when the feature is not there in protocol
4. Dropping when only one provenance property is present and even the enablement property is not present
5. Dropping when none of the table properties are present …

[Spark] Add drop support for InCommitTimestamp table feature

---

spark/src/main/scala-spark-3.5/shims/ColumnDefinitionShim.scala
spark/src/main/scala-spark-3.5/shims/IncrementalExecutionShim.scala
spark/src/main/scala-spark-3.5/shims/UnresolvedTableShim.scala
spark/src/main/scala-spark-master/shims/ColumnDefinitionShim.scala
spark/src/main/scala-spark-master/shims/IncrementalExecutionShim.scala
spark/src/main/scala-spark-master/shims/UnresolvedTableShim.scala
spark/src/main/scala/io/delta/sql/parser/DeltaSqlParser.scala
spark/src/main/scala/io/delta/tables/DeltaTableBuilder.scala
spark/src/main/scala/io/delta/tables/execution/VacuumTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/ColumnWithDefaultExprUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/test/scala/io/delta/sql/parser/DeltaSqlParserSuite.scala

Refactor shim package `org.apache.spark.sql.delta.shims`. When shimming `$package.$class`, use shim package `$package`
Trivial refactor only.
No

[Spark] Remove (and rename) package `org.apache.spark.sql.delta.shims`

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWidening.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWideningMetadata.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTypeWideningSuite.scala

Adds a guardrail for the type widening table feature to reject reads when an unsupported change was applied to the table.
This should never happen unless an implementation doesn't respect the type widening feature specification, which explicitly lists type changes that are allowed.
- Added a test manually committing an invalid type change.

Reject reads on table with unsupported type changes

---

build.sbt
spark/src/test/scala-spark-3.5/shims/DeltaInsertIntoTableSuiteShims.scala
spark/src/test/scala-spark-3.5/shims/DeltaVacuumSuiteShims.scala
spark/src/test/scala-spark-3.5/shims/DescribeDeltaHistorySuiteShims.scala
spark/src/test/scala-spark-3.5/shims/SnapshotManagementSuiteShims.scala
spark/src/test/scala-spark-3.5/shims/StatsCollectionSuiteShims.scala
spark/src/test/scala-spark-master/shims/DeltaInsertIntoTableSuiteShims.scala
spark/src/test/scala-spark-master/shims/DeltaVacuumSuiteShims.scala
spark/src/test/scala-spark-master/shims/DescribeDeltaHistorySuiteShims.scala
spark/src/test/scala-spark-master/shims/SnapshotManagementSuiteShims.scala
spark/src/test/scala-spark-master/shims/StatsCollectionSuiteShims.scala
spark/src/test/scala/io/delta/tables/DeltaTableSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoTableSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaHistorySuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/StatsCollectionSuite.scala

Fixes 25 tests in 6 suites for Delta OSS on Spark Master using shimming.
Existing UTs
No

[Spark] [Delta X-Compile] Fix tests for both Spark 3.5 and Spark Master (batch 1)

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/IcebergConverterHook.scala

sync iceberg conversion happens when enabled with session config, or uniform iceberg is turned on for the first time. This explicitly throws when sync iceberg conversion fails so user knows conversion status.
UT

Explicitly throw when sync iceberg conversion fails

---

spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoMaterializeSourceSuite.scala

This PR adds extra tests to consider determinism in subqueries for source merge materialization.
This patch is test only and adds new tests.
No.

[Spark][TEST-ONLY] Merge source materialization non-determinism determination in subqueries tests

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitStore.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitStoreSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

This PR revises the CommitStore equality check to use semantic comparison rather than direct object reference comparison.
UTs
No

[Spark] Enhance CommitStore Equality with Semantic Comparison

---

spark/src/main/scala/org/apache/spark/sql/delta/ColumnWithDefaultExprUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/GenerateRowIDs.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowCommitVersion.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/GenerateRowIDsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowtracking/RowTrackingReadWriteSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

1. Adding the `row_commit_version` field to the _metadata column for Delta tables, allowing us to read the `row_commit_version` from the file metadata after it is stored.
2. Adding Row Tracking preservation in Read/Write.
Added UTs.
No.

[Spark] Add Read support for RowCommitVersion and Row Tracking Preservation in Read/Write

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeleteSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/UpdateSuiteBase.scala

Before this PR, Delta computes a [SnapshotState](https://github.com/delta-io/delta/blob/v3.1.0/spark/src/main/scala/org/apache/spark/sql/delta/SnapshotState.scala#L46-L58) during every commit.  Computing a SnapshotState is fairly slow and expensive, because it involves reading the entirety of a checkpoint, sidecars, and log segment.
For many types of commit, it should be unnecessary to compute the SnapshotState.
After this PR, a transaction can avoid computing the SnapshotState of a newly created snapshot. Skipping the computation is enabled via a spark configuration option `spark.databricks.delta.commitStats.collect=false`
This change can have a big performance impact when writing into a Delta Table.  Especially when the table comprises a large number of underlying data files.
- Locally …

[Spark] Skip collecting commit stats to prevent computing Snapshot State

---

spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaSparkPlanUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoMaterializeSourceSuite.scala

Small fixes for determinism determination for Merge Materialize Source.
* since we consider joins as potentially non-deterministic, we should also consider correlated subqueries as such, because they essentially are also joins.
* non Delta source will not be found in subqueries in `findFirstNonDeltaScan`, but found in `findFirstNonDeterministicNode`. This will make merge source materialization give wrong reason for materialization.
Added tests with subqueries and nested subqueries in Project and Filters and correlated subqueries.
No.

[Spark] Merge should materialize source with correlated subqueries

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/TableCommitStore.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckpointsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogMinorCompactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/LogStoreSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitStoreSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitStoreSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

This PR adds a register API with managed commits.
1. Initial snapshot shouldn't have CommitStore.
2. Introduce concept of managedCommitTableConf. This info is unique to the table. e.g. tableId etc.
- with this change, now configuration has 2 table properties related to managed commits:
2.1 `managedCommitOwnerName` - name of the MC Owner
2.2 `managedCommitOwnerConf` - configuration related to owner
2.3 `managedCommitTableConf` - managed commit configuration related to table
`2.1` and `2.2` are used to initialize CommitStore.
`2.3` is passed as an argument to CommitStore{commit/getCommits/backfillUpto} APIs as it is needed to uniquely identify the table by the owner.
3. CommitStore pre-registration support. If a table is transitioning for FS -> MC, we register with commit-store and get the …

[Spark] Register API with managed-commits

---

spark/src/main/scala-spark-3.5/shims/DeltaInvariantCheckerExecShims.scala
spark/src/main/scala-spark-3.5/shims/DeltaTableValueFunctionsShims.scala
spark/src/main/scala-spark-master/shims/DeltaInvariantCheckerExecShims.scala
spark/src/main/scala-spark-master/shims/DeltaTableValueFunctionsShims.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTableValueFunctions.scala
spark/src/main/scala/org/apache/spark/sql/delta/constraints/DeltaInvariantCheckerExec.scala

This PR is batch 3. This PR fixes 2 tests in 2 suites for Delta on Spark Master using shimming.
Existing UTs
No

[Spark] [Delta X-Compile] Fix tests for both Spark 3.5 and Spark Master (batch 3)

---

kernel/kernel-api/src/main/java/io/delta/kernel/Table.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

Renames the snapshot time travel APIs on `Table` to be consistent with SQL syntax.
Just refactoring existing tests suffice.
Neither changed API has been released yet so no.

[Kernel] Rename snapshot time-travel APIs to be consistent with SQL syntax

---

spark/src/main/scala/org/apache/spark/sql/delta/IdentityColumn.scala

This PR is part of https://github.com/delta-io/delta/issues/1959
In this PR, we introduce IdentityColumn.scala, a common file which contains most of the helpers for Identity Columns, necessary for unblocking future PRs.
This PR commits dead code. Existing tests pass.
No.

[Spark] Add IdentityColumn.scala

---

spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala

The merge of these two PRs: 
1. https://github.com/delta-io/delta/pull/2902
2. https://github.com/delta-io/delta/pull/2883
broke master. This renames a variable in InCommitTimestampSuite to unbreak it.
Test-only fix.
No

[Spark] Fix InCommitTimestampSuite to make master compilable

---

spark/src/test/scala-spark-3.5/shims/ImplicitDMLCastingSuiteShims.scala
spark/src/test/scala-spark-master/shims/ImplicitDMLCastingSuiteShims.scala
spark/src/test/scala/org/apache/spark/sql/delta/ImplicitDMLCastingSuite.scala

This PR is batch 4. This PR fixes 20 tests in 1 suite for Delta on Spark Master using shimming.
Existing UTs
No

[Spark] [Delta X-Compile] Fix tests for both Spark 3.5 and Spark Maser (batch 4)

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala

This PR fixes a correctness bug when Column Mapping is enabled. The issue occurs when a column is renamed to the physical name of another column. If a query filters on this column then the Parquet scan incorrectly applies this filter to the other column. This PR fixes this problem by translating the column names in the filters from logical to physical in `DeltaParquetFileFormat` before passing them on to `ParquetFileFormat`. 
Added a unit test to `DeltaColumnMappingSuite`.
No

[Spark] Apply Column Mapping to filters pushed to Parquet scan

---

spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeleteCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingDeleteSuite.scala

Add Preserving Row Tracking in Delete by reading the metadata column and writing it out to the physical column.
Added UTs.
No.

[Spark] Add Preserving Row Tracking in Delete

---

spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/UpdateCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingUpdateSuite.scala

Preserve row IDs in UPDATE by reading the metadata column and writing it out to the physical column.
Added UTs.
No.

[Spark] Add Preserving Row Tracking in Update

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingCompactionSuite.scala

Preserve row IDs in Optimize/Reorg/Z-Order/Purge by reading the metadata column and writing it out to the physical column.
Added UTs.
No.

[Spark] Add Preserving Row Tracking in Optimize/Reorg/Z-Order/Purge

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/ClassicMergeExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeOutputGeneration.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingMergeSuite.scala

Preserve row IDs in Merge by reading the metadata column and writing it out to the physical column.
Existing UTs.
No.

[Spark] Add Preserving Row Tracking in Merge

---

docs/source/delta-utility.md

We have added [a new feature](https://github.com/delta-io/delta/commit/7d41fb7bbf63af33ad228007dd6ba3800b4efe81) for VACUUM command that allows users to provide a inventory table to specify the files to be considered by VACUUM. This PR updates the documentation to reflect this feature.
N/A. Doc updates only.
No

Add vacuum inventory table related description

---

spark/src/main/scala-spark-3.5/shims/DeltaThrowableHelperShims.scala
spark/src/main/scala-spark-master/shims/DeltaThrowableHelperShims.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaThrowableHelper.scala

In Apache Spark https://github.com/apache/spark/commit/c5b8e60e0d5956d9f648f77ae13a1558c99adf6b, `error-classes.json` was renamed to `error-conditions.json`.
Update Delta's DeltaThrowableHelper to use the right json file when cross compiling against Spark 3.5 and Spark Master.
Existing UTs.
No

Fix Delta on Spark Master tests broken by error-classes.json rename

---

kernel/kernel-api/src/main/java/io/delta/kernel/client/JsonHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/client/ParquetHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/Preconditions.java
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockTableClientUtils.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultJsonHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultParquetHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFileWriter.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultJsonHandlerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultParquetHandlerSuite.scala

(extracted out the `TableClient` related changes from #2941)
At a high level, the requirements for writing files (either JSON or Parquet) are as follows:
* Write given data into one or more Parquet files (for writing the data or v2 checkpoint sidecar files)
* `ParquetHandler.writeParquetFiles` is used in this case. 
* Write given data into exactly one atomically file (i.e either the file is created with full content or no file is created at all) (checkpoint classic, delta commit file, v2 cp manifest file)
* JSON: `JsonHandler.writeJsonFileAtomically` with `overwrite = false`
* Parquet: `ParquetHandler.writeParquetFileAtomically`
* Write given data atomically into a file (overwrite if it exists) (`_last_checkpoint`)
* JSON: `JsonHandler.writeJsonFileAtomically` with `overwrite = true` 
* …

[Kernel][Writes] `ParquetHandler` and `JsonHandler` API changes

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableWithDVs.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeFileIndex.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaParquetFileFormatSuite.scala

Back then, we relied on an [expensive Broadcast of DV files](https://github.com/delta-io/delta/pull/1542) to pass the DV files to the associated Parquet Files. With the introduction of [adding custom metadata to files](https://github.com/apache/spark/pull/40677) introduced in Spark 3.5, we can now pass the DV through the custom metadata field, this is expected to improve the performance of DV reads in Delta.
Adjusted the existing UTs that cover our changes.
No.

[Spark] DV Reads Performance Improvement in Delta by removing Broadcasting DV Information

---

spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdCreateReplaceTableSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdSuite.scala

Add additional read stable Row IDs assertions in some tests after read stable Row Tracking is introduced in the previous PRs.
Added UTs.
No.

[Spark] Add additional read stable Row IDs check

---

.github/workflows/spark_master_test.yaml

Create a new GitHub action workflow to run delta-spark tests against Spark Master
Ran CI tests.
No

Run Delta-Spark tests against Spark Master (new github workflow)

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableFeaturesSuite.scala

(Split from #2941)
Add a utility method to check if the table is of protocol/features that current insert APIs being planned support writing into. The current plan is to give a write support similar to that Standalone, which is at (minReaderVersion = 1 and minWriterVersion = 2 with `appendOnly` support).
Unittests

[Kernel][Writes] Add `TableFeatures.validateWriteSupportedTable` utility method

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/DateTimeConstants.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/IntervalParserUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/IntervalParserUtilsSuite.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/DefaultKernelUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala

Currently these configs are stored in SQL interval format. We could depend on external libraries, but to minimize the dependencies on `kernel-api`, the minimal relevant code is copied from Standalone (which was a copy of Apache Spark code). Also I couldn't find a minimal library that does just the interval parsing.

[Kernel][Writes] Add a utility to parse interval duration in Delta table configs

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala

Move the InCommitTimestamp feature to the list of supported features so that users can enable it outside of the test environment. Note that InCommitTimestamp is still an RFC and the feature name will still have the -dev suffix in it.
Yes, users can now use the `InCommitTimestamp-dev` feature in their environments if they want to try it before the RFC is  merged.

[Spark] Make ICT available outside of test environments

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/columnmapping/RemoveColumnMappingCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingRowTrackingSuite.scala

- Add Row Tracking Preservation for column mapping removal.
Added UTs.
No.

[Spark] Add preserving Row Tracking for Column Mapping Removal

---

.github/workflows/spark_master_test.yaml

Rename Spark Master github workflow name
CI test
No

Fix typo in Spark Master test workflow

---

kernel/kernel-api/src/main/java/io/delta/kernel/Table.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaHistoryManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultFileSystemClient.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultFileSystemClientSuite.scala

(Split from #2941)
Earlier it used to throw if the path is not valid. Now, it doesn't validate immediately. Instead the validation is done when we try to create a snapshot or other operations. We want to create tables from scratch and `Table. forPath` throwing error doesn't let us proceed.
Unittests

[Kernel][Writes] Update the behavior of `Table.forPath` to not throw error for empty tables

---

build.sbt

Allows kernel-defaults module to take advantage of kernel-api test utils (in preparation for refactor containing these changes).
N/A.
No.

[Kernel] Allow kernel-defaults to use kernel-api test utils

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala

Expose the type widening table feature outside of testing and set its preview user-facing name: typeWidening-preview (instead of typeWidening-dev used until now).
Feature description: https://github.com/delta-io/delta/issues/2622
The type changes that are supported for not are `byte` -> `short` -> `int`. Other types depend on Spark changes which are going to land in Spark 4.0 and will be available once Delta picks up that Spark version.
Extensive testing in `DeltaTypeWidening*Suite`.
User facing changes were already covered in PRs implementing this feature. In short, it allows:
- Adding the type widening table feature (using a table property)
```
ALTER TABLE t SET TBLPROPERTIES (‘delta.enableTypeWidening = true);
```
- Manual type changes:
```
ALTER TABLE t CHANGE COLUMN col TYPE INT;
``` …

[Spark] Type Widening preview

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/UpdateCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaUpdateCatalogSuite.scala

Currently, during schema sync to catalog, the whole schema gets truncated if any of the fields is longer than 4000 characters. This PR makes this threshold a configurable through the config `DeltaSQLConf. DELTA_UPDATE_CATALOG_LONG_FIELD_TRUNCATION_THRESHOLD`.
Created variations of existing test cases that validate that setting the config to a bigger value skips the truncation.
No

[Spark] Make update catalog schema truncation threshold configurable

---

kernel/kernel-api/src/main/java/io/delta/kernel/CheckpointAlreadyExistsException.java
kernel/kernel-api/src/main/java/io/delta/kernel/Table.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/RemoveFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/SingleAction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checkpoints/CheckpointMetaData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checkpoints/Checkpointer.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActiveAddFilesIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/CreateCheckpointIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplayUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/IntervalParserUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/replay/LogReplaySuite.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultParquetHandler.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CreateCheckpointSuite.scala

Implements `Table.checkpoint` API to checkpoint the table at given version
```
/**
* Checkpoint the table at given version. It writes a single checkpoint file.
*
* @param tableClient {@link TableClient} instance to use.
* @param version     Version to checkpoint.
* @throws TableNotFoundException if the table is not found
* @throws CheckpointAlreadyExistsException if a checkpoint already exists at the given version
* @throws IOException for any I/O error.
* @since 3.2.0
*/
void checkpoint(TableClient tableClient, long version)
throws TableNotFoundException, CheckpointAlreadyExistsException, IOException;
```
Unit and integration tests. TODO: one pending test for tombstones are removed correctly.

[Kernel][Writes] Implement `Table.checkpoint` API to write a classic single file checkpoint

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala

Follow up for https://github.com/delta-io/delta/pull/2946. Updates the configs and table feature name associated with InCommitTimestamp to indicate that it is in the preview phase --- the RFC has not been finalized but the feature is code complete.
 
No additional testing.
No

[Spark] Mark InCommitTimestamp as a preview feature

---

spark/src/test/scala-spark-3.5/shims/DeltaExcludedBySparkVersionTestMixinShims.scala
spark/src/test/scala-spark-master/shims/DeltaExcludedBySparkVersionTestMixinShims.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/GeneratedColumnSuite.scala

Disable 3 delta-spark tests from executing against Spark Master. They execute against Spark 3.5 only.
CI tests.
No

Disable 3 Delta Spark tests against Spark Master

---

protocol_rfcs/README.md
protocol_rfcs/variant-type.md

Adds the protocol changes for the Variant data type (see https://github.com/delta-io/delta/issues/2864) to the RFC folder.
N/A
N/A

[PROTOCOL RFC] Variant data type

---

python/delta/tests/test_deltatable.py

After https://github.com/apache/spark/commit/e01ac581f46aa595e66daf33fe92b56d1328bc78, `pyspark.sql.column._to_seq` has moved to `pyspark.sql.classic.column._to_seq`. This PR fixes the test to make the test compatible with old and new Spark versions.
<anually tested.
No, test-only

[Spark] Make test_deltatable compatible with the latest Spark dev branch

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/PartitionUtilsSuite.scala

(Split from larger PR #2944)
Adds a utility method to convert the partition value literal to Delta protocol-compliant string value.
UTs

[Kernel][Writes] Utility method to serialize partition literals as strings

---

spark/src/main/scala-spark-3.5/shims/VariantShims.scala
spark/src/main/scala-spark-master/shims/VariantShims.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/PartitionUtils.scala
spark/src/test/scala-spark-master/org/apache/spark/sql/delta/DeltaVariantSuite.scala

Adds the variant table feature to minimally implement the variant type as described in the RFC in #2867.
Also disables using variant columns as partition columns.
Added some UTs. More UTs will be merged in followup PRs
tested against both spark 3.5 and 4.0 snapshot with
```
build/sbt -DsparkVersion=latest spark/'testOnly org.apache.spark.sql.delta.DeltaVariantSuite'
build/sbt -DsparkVersion=master spark/'testOnly org.apache.spark.sql.delta.DeltaVariantSuite'
```
no

[SPARK][VARIANT] Add minimal support for variant type in delta-spark

---

spark/src/main/scala/org/apache/spark/sql/delta/GenerateIdentityValues.scala
spark/src/test/scala/org/apache/spark/sql/delta/GenerateIdentityValuesSuite.scala

This PR is part of https://github.com/delta-io/delta/issues/1959
In this PR, we introduce the `GenerateIdentityValues` UDF used for populating Identity Column values. The UDF is not used in Delta in this PR yet.
`GenerateIdentityValues` is a simple non-deterministic UDF which keeps a counter with the user specified `start` and `step`. It counts in increments of `numPartitions` so that it can be parallelized in different tasks.
New test suite and unit tests for the UDF.
No.

[Spark] Add GenerateIdentityValues UDF

---

spark/src/test/scala/io/delta/tables/DeltaTableBuilderSuite.scala

`DeltaTableBuilderSuite` was being aborted when testing against Delta on Spark Master (JDK 17) due to
```
[info] io.delta.tables.DeltaTableBuilderSuite *** ABORTED ***
[info]   java.lang.IllegalAccessError: Update to non-static final field io.delta.tables.DeltaTableBuilderSuite$SetPropertyThroughCreate$1$.preservedCaseConfig$1 attempted from a different method (io$delta$tables$DeltaTableBuilderSuite$CasePreservingTablePropertySetOperation$1$_setter_$preservedCaseConfig$1_$eq) than the initializer method <init>
[info]   at io.delta.tables.DeltaTableBuilderSuite$SetPropertyThroughCreate$1$.io$delta$tables$DeltaTableBuilderSuite$CasePreservingTablePropertySetOperation$1$_setter_$preservedCaseConfig$1_$eq(DeltaTableBuilderSuite.scala:400)
[info]   at …
```

Fix Delta Spark Master aborted DeltaTableBuilderSuite

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/CommitInfo.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Format.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Metadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Protocol.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/SetTransaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/SingleAction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/VectorUtils.java

(Split from larger PR #2944)
Add `toRow` for each of the action objects. Also add any missing actions such as `CommitInfo`.
Also
* Rename `READ_SCHEMA` to `FULL_SCHEMA` when all columns in an action are present. `READ_SCHEMA` is a term used to read just the subset of columns, but in some actions, it also represents the full schema.
* Utility method to create single action `Row` object from a specific actions. Eg. `createMetadataSingleAction(Metadata metadata)` returns a `Row` of single action schema with `metaData` column representing the given `metadata` object.

[Kernel[Writes] Add methods to encode Delta Log actions as `Row` objects

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/InternalScanFileUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ScanSuite.scala

Add a private API `ScanImpl.getScanFiles(TableClient tableClient, boolean includeStats)` to enable connectors to fetch the `stats` as part of the returned scan file rows. By default `stats` are not read unless there is a predicate on data columns.
The main reason why we are not making this a public API yet is that currently, the `ColumnarBatch` interface has no way to remove a nested column vector before returning it to the connector. It requires major work on the expression interfaces. Until we have that, this is a workaround for connectors that are interested in the `stats` field in scan files.
UTs

[Kernel] Expose the "stats" field in returned scan files in `ScanImpl` using a boolean parameter

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala

DROP Support for Vacuum Protocol Check table feature
UTs
No

[Spark] DROP Support for Vacuum Protocol Check table feature

---

spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwner.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitUtils.scala

This PR refactors several methods that were internal to commit owner (client) implementations (AbstractBatchBackfillingCommitOwnerClient and InMemoryCommitOwner) into ManagedCommitUtils. These methods are generic and should be easily accessible to any commit owner (client) implementations so we are making them static methods.
Refactor only so existing tests are sufficient.
No

[Spark] Refactor several managed commit-related methods into ManagedCommitUtils

---

spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSchemaEvolutionSuite.scala

Address following shortcomings of schema evolution tests in MERGE:
- Tests ignore the nullability of fields when validating the schema of the table after evolution, which prevents checking for nullability of specific fields.
- For struct evolution tests, a result schema can be passed but this schema is only used to parse the result data and not to validate the schema of the table after evolution.
Updated tests
No, test-only

[Spark] Better schema validation in MERGE schema evolution tests

---

spark/src/main/scala/org/apache/spark/sql/delta/TransactionExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/ExecutionPhaseLock.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/PhaseLockingExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/PhaseLockingTransactionExecutionObserver.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionObserverSuite.scala

Add the `nextObserver` and the `PhaseLockingExecutionObserver` for the Concurrency Testing Framework, as we will need it to write Row Tracking Backfill conflicts with other commands tests when we add Row Tracking Backfill.
Added UTs.
No.

[Spark] Add nextObserver and the PhaseLockingExecutionObserver for the Concurrency Testing Framework

---

docs/source/releases.md

Update `releases.md` to mention that Delta Spark 3.2 uses Spark 3.5
Trivial
No

[DOCS] Update `releases.md` to mention that Delta Spark 3.2 uses Spark 3.5

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitEnablementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

Enabling Managed Commits will automatically:
1. Add ICT and VacuumProtocolCheck features to the protocol.
2. Enable ICT
These two features are pre-requisites for managed commit.
New suite ManagedCommitEnablementSuite. Updated existing tests to work with ICT.
No

[Spark] Enable ICT and VacuumProtocolCheck automatically with Managed Commits

---

python/delta/tables.py

This PR proposes to move import from `from pyspark.sql.column import _to_seq ` to `from pyspark.sql.classic.column import _to_seq `
`pyspark.sql.column._to_seq` has moved to `pyspark.sql.classic.column._to_seq`, and `pyspark.sql.classic` does not exist in `pyspark-connect` package.
Manually tested.
Yes, this makes `delta.tables` compatible with pure Python library `pyspark-connect` (in Spark development branch).

[Spark] Move private import to method call to make it compatible with `pyspark-connect`

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala

Fix failing test `DeltaLog should throw exception if spark.sql.catalog.spark_catalog config is not found` in `DeltaExtensionAndCatalogSuite` by replacing `.getOption($key).isEmpty` with `.contains($key)`
- In Spark 3.5, `spark.conf.getOption("spark.sql.catalog.spark_catalog")` returned `None`
- In Spark Master (4.0), `spark.conf.getOption("spark.sql.catalog.spark_catalog")` returned `Some("undefined")`. I'm not sure why
Existing UTs.
No

[SPARK] Fix failing Spark Master test in DeltaExtensionAndCatalogSuite

---

kernel/kernel-api/src/main/java/io/delta/kernel/client/FileSystemClient.java
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockTableClientUtils.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultFileSystemClient.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultFileSystemClientSuite.scala

(Split from larger PR #2944)
This API allows the creation of an initial delta log directory when the table is created.

[Kernel][Writes] Add `FileSystemClient.mkdirs` API

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala

(Split from the larger PR #2944)
These are utility to make sure the given schema when creating the table is valid (has no duplicate column names or invalid chars). The code/logic is similar to Delta-Spark/Standalone.
Unittests

[Kernel][Writes] Add schema validation utils

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala

This PR changes how Column Mapping is applied to the filters that are pushed down in the Parquet reader. Before this change we would parse the identifiers before replacing the identifiers. This could cause some queries to fail, as the identifiers in the pushed down filters are not 100% guaranteed to be quoted. With this PR we avoid the parsing and instead match the unparsed identifier. If the identifier was not quoted as expected then we simply ignore the predicate. This matches how `ParquetFilters` (used by `ParquetFileFormat`) processes the identifiers in the pushed down predicates.
Existing tests
No

[Spark] Avoid parsing in translateFilterForColumnMapping

---

spark/src/main/scala-spark-3.5/shims/CreatableRelationProviderShims.scala
spark/src/main/scala-spark-master/shims/CreatableRelationProviderShims.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaDataSource.scala
spark/src/test/scala-spark-3.5/shims/DeltaExcludedBySparkVersionTestMixinShims.scala
spark/src/test/scala-spark-master/shims/DeltaExcludedBySparkVersionTestMixinShims.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeleteSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoTableSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/UpdateSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

Adds Variant as a delta source to enable writing with DF API and more tests
Writing variant using `df.write.format("delta").save(...)" works in tests.

[SPARK][VARIANT] Add Variant as a delta source to enable writing with DF API and more tests

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuite.scala

Prevent createDataFrame from dropping NullType columns with streaming sources.
New unit tests for streaming read/write and test for non-streaming createDataFrame code path verifying the current behavior is preserved.
No

Streaming Delta Source should not drop NullType columns

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwner.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/abstractActions.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClientSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

This PR is the first in a series of PRs that refactors the current CommitOwnerClient interface to become its own module. This is similar to `storage` module that currently exists and contains the LogStore interface and its implementations. In this PR, we remove any Delta Spark dependencies from the CommitOwnerClient in preparation for it to be moved outside of Delta Spark.
Added tests to check equivalence of newly introduced AbstractProtocol/AbstractMetadata with Protocol/Metadata.
No

[Spark] Makes CommitOwnerClient independent of Delta Spark dependencies

---

.github/workflows/spark_examples_test.yaml
examples/scala/build.sbt

Create new workflow `spark_examples_test.yaml` that compiles the `examples/scala/build.sbt` project.
Also fixes such compilation so that it uses the local jars (previously it was incorrectly hardcoded to Delta 3.0).
This requires running `publishM2` beforehand.
CI tests and specifically tested on a commit that uses a new `clusterBy` API in 3.2: https://github.com/delta-io/delta/pull/3012
No.

[INFRA] Fix and create new workflow to compile delta-spark examples

---

build.sbt

This is useful when we need to get the current version of Kernel. Approach is similar to how we do it for other modules in the delta.
Manually verified.

[Kernel] Add a meta file containing the Kernel version.

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableFeatureSuite.scala

When dropping a feature, DeltaLog now checks both backfilled and unbackfilled deltas for any traces of the feature before confirming it's safe to drop.
However, feature dropping currently does a checkpoint before detecting feature traces in the history, so there are no unbackfilled deltas at that point.
UTs
No

[Spark] Extend Delta feature drop safety check to unbackfilled deltas

---

build.sbt
connectors/flink/src/main/scala/io/delta/flink/internal/KernelSnapshotWrapper.java
project/plugins.sbt

https://github.com/delta-io/delta/pull/2828 upgrades the SBT version from 1.5.5 to 1.9.9 which causes `projectName/checkstyle` to fail with
```
sbt:delta> kernelApi/checkstyle
[error] stack trace is suppressed; run last kernelApi / checkstyle for the full output
[error] (kernelApi / checkstyle) org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[error] Total time: 0 s, completed May 1, 2024 2:59:48 PM
```
This failure was silent in our CI runs for some reason, if you search the logs before that commit you can see "checkstyle" in them but no instances after. This is a little concerning but don't really have time to figure out why this was silent.
For now, upgrades …

[Build] Fix Java checkstyle plugin to work with SBT upgrade

---

build.sbt

Merging https://github.com/delta-io/delta/pull/3019 broke the `kernelApi/checkstyle` which is failing CI jobs since it's original tests ran before https://github.com/delta-io/delta/commit/8cdf411d2c3e483a483595d117619c4aa6e15faa was committed.
Checked locally that `kernelApi/checkstyle` passes.

[Kernel][Infra] Fix the java checkstyle for Kernel's Meta file

---

spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTypeWideningSuite.scala

Fix an issue found while testing the Delta 3.2 RC2:
Dropping the type widening table feature may fail parsing the table identifier:
```
ALTER TABLE default.type_widening_int DROP FEATURE 'typeWidening-preview' TRUNCATE HISTORY;
[PARSE_SYNTAX_ERROR] Syntax error at or near '.'.(line 1, pos 21)
== SQL ==
spark_catalog.default.type_widening_int
```
Parsing the table identifier isn't needed as it's not used by the REORG operation that rewrite files when dropping the feature. This change skip parsing the table identifier and directly passes the table name to the REORG command
Added test covering the issue

[Spark] Fix dropping type widening feature with multipart identifiers

---

spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTypeWideningSuite.scala

Fix an issue found while testing the Delta 3.2 RC2:
Dropping the type widening table feature may fail parsing the table identifier:
```
ALTER TABLE default.type_widening_int DROP FEATURE 'typeWidening-preview' TRUNCATE HISTORY;
[PARSE_SYNTAX_ERROR] Syntax error at or near '.'.(line 1, pos 21)
== SQL ==
spark_catalog.default.type_widening_int
```
Parsing the table identifier isn't needed as it's not used by the REORG operation that rewrite files when dropping the feature. This change skip parsing the table identifier and directly passes the table name to the REORG command
Added test covering the issue

[Spark][3.2] Fix dropping type widening feature with multipart identifiers

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwner.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/TableCommitOwnerClient.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogMinorCompactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClientSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwnerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

- We use optional startVersion and optional endVersion for getCommits now.
- We use optional lastKnownBackfilledVersion and a required version for backfillToVersion now since the consumers of backfillToVersion must know the version.
Various existing UTs
No

[Spark] Refactor CommitStore getCommits and backfillToVersion API params

---

kernel/kernel-api/src/main/java/io/delta/kernel/client/ExpressionHandler.java
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockTableClientUtils.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/DefaultExpressionHandler.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultExpressionHandlerSuite.scala

Removes a currently unused API in `ExpressionHandler`.
See https://github.com/delta-io/delta/issues/3017 for details. **TLDR** we added this API before achieving consensus on what we want to implement and it is currently unused. Remove it for now and we can add it back later if needed.
N/A
No

[Kernel] Remove unused `ExpressionHandler.isSupported(...)` for now

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergFileManifest.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/ConvertIcebergToDeltaSuite.scala

Iceberg V2 spec introduce the row-level deletes, which is not supported yet for metadata conversion. We add the blocker here to throw exception if customer want to convert a iceberg table with row-level deletes.
Also MOR is not necessarily to be enabled for using row-level deletes, so we remove the check for MOR configurations here and only check if the deleteFiles is nonEmpty in `planFiles()`.
Exist tests.
No

[Spark]Block metadata conversion for Iceberg tables with row-level deletes

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/JsonHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/TransactionStateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/InternalUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/CloseableIterable.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/DataFileStatistics.java
kernel/kernel-api/src/test/scala/io/delta/kernel/test/VectorTestUtils.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultJsonHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultParquetHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/json/JsonUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CreateCheckpointSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/json/JsonUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

(Split from #2944)
Adds support for inserting data into the table.
Tests for inserting into partitioned and unpartitioned tables with various combinations of the types, partition values etc. Also tests the checkpoint is ready to create.

[Kernel][Writes] Add support of inserting data into tables

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/test/scala/org/apache/spark/sql/delta/ActionSerializerSuite.scala

Currently, if we deserialize a CommitInfo with a very small inCommitTimestamp and then try to access this inCommitTimestamp, this exception is thrown
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long
```
This PR fixes the CommitInfo so that the inCommitTimestamp field is deserialized correctly.
Added a new test case that was failing before the fix.
No

[Spark][3.2] Fix CommitInfo.inCommitTimestamp deserialization for very small timestamps

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/test/scala/org/apache/spark/sql/delta/ActionSerializerSuite.scala

Currently, if we deserialize a CommitInfo with a very small inCommitTimestamp and then try to access this inCommitTimestamp, this exception is thrown
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long
```
This PR fixes the CommitInfo so that the inCommitTimestamp field is deserialized correctly.
Added a new test case that was failing before the fix.
No

[Spark] Fix CommitInfo.inCommitTimestamp deserialization for very small timestamps

---

docs/source/delta-drop-feature.md
docs/source/delta-type-widening.md
docs/source/index.md
docs/source/versioning.md

Cherry-pick of https://github.com/delta-io/delta/pull/3036 to `master`
Add a documentation page for the type widening table feature, in preview in Delta. 3.2
N/A

[Doc] Type Widening documentation

---

kernel/kernel-api/src/main/java/io/delta/kernel/TransactionBuilder.java
kernel/kernel-api/src/main/java/io/delta/kernel/exceptions/ConcurrentTransactionException.java
kernel/kernel-api/src/main/java/io/delta/kernel/exceptions/ConcurrentWriteException.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala

(Split from #2944)
Adds an API on `TransactionBuilder` to take the transaction identifier for idempotent writes
```
/*
* Set the transaction identifier for idempotent writes. Incremental processing systems (e.g.,
* streaming systems) that track progress using their own application-specific versions need to
* record what progress has been made, in order to avoid duplicating data in the face of
* failures and retries during writes. By setting the transaction identifier, the Delta table
* can ensure that the data with same identifier is not written multiple times. For more
* information refer to the Delta protocol section <a
* href="https://github.com/delta-io/delta/blob/master/PROTOCOL.md#transaction-identifiers">
* Transaction Identifiers</a>.
*
* @param engine             {@link Engine} …
```

[Kernel][Writes] Support idempotent writes

---

kernel/kernel-api/src/main/java/io/delta/kernel/exceptions/MetadataChangedException.java
kernel/kernel-api/src/main/java/io/delta/kernel/exceptions/ProtocolChangedException.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/SingleAction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ConflictChecker.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala

Currently, Kernel throws an exception when there is a conflict (i.e., there already exists a committed file at a given version). We should retry the transaction as the current support is just for blind appends. Retry checks if there are no logical conflicts (`metadata`, `protocol` or `txn` (Set Tranaction)) conflicts that affect the blind append.
Tests for protocol, metadata and setTxn conflicts. Also tests to verify blind appends are retried and committed.

[Kernel][Writes] Allow transaction retries for blind append

---

kernel/README.md
kernel/USER_GUIDE.md

Rename the references of `TableClient` to `Engine`. Follow up to #3015.
Just docs change

[Kernel][Docs] Rename `TableClient` to `Engine`

---

kernel/USER_GUIDE.md

Capture the breaking API changes to enable connectors to migrate to the latest version of Kernel

[Kernel][Usage Guide] Migration docs for Kernel 3.2

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaLogGroupingIterator.scala
spark/src/test/scala/org/apache/spark/sql/delta/FindLastCompleteCheckpointSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/util/DeltaLogGroupingIteratorSuite.scala

This PR fixes an O(n^2) issue in `find last complete checkpoint before` method.
Today the `findLastCompleteCheckpointBefore` tries to find the last checkpoint before a given version. In order to do this, it do following:
findLastCompleteCheckpointBefore(10000):
1. List from 9000
2. List from 8000
3. List from 7000
...
Each of these listing today lists to the end as they completely ignore delta files and try to list with takeWhile with version clause:
```
listFrom(..)
.filter { file => isCheckpointFile(file) && file.getLen != 0 }
.map{ file => CheckpointInstance(file.getPath) }
.takeWhile(tv => (cur == 0 || tv.version <= cur) && tv < upperBoundCv)
```
This PR tries to fix this issue by terminating each listing early by checking if we have crossed a deltaFile for untilVersion.
In addition …

[Spark] Fix O(n^2) issue in find last complete checkpoint before

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwner.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClientSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwnerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

This is the second PR in a series of PRs to move the current CommitOwner interface to its own module. PR1 is [here](https://github.com/delta-io/delta/pull/3002).
This PR makes the fields of all CommitOwner-related classes private and forces callers to use getters to access the fields. This is needed in preparation for making the CommitOwner module a Java module (the same as the existing LogStore module) and to follow Java best practices to keep fields private and only allow access through getters.
Simple refactor so existing tests are sufficient.
No

[Spark] Makes fields in CommitOwner-related classes private and introduces getters

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/DataSkippingDeltaConstructDataFiltersSuite.scala

This fixes the hanging behavior for `constructDataFilters` with expressions like `EqualTo(Literal, Literal)`. This is due to infinite recursion caused by cases like `case EqualTo(v: Literal, a) => constructDataFilters(EqualTo(a, v))`.  This also fixes the same behavior for `EqualTo, Not(EqualTo), EqualNullSafe, LessThan, LessThanOrEqual, GreaterThan, GreaterThanOrEqual`
new UT `DataSkippingDeltaConstructDataFiltersSuite`
No

fix hanging behavior for constructDataFilters with expression like EqualTo(Literal, Literal) 

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/WriteIntoDelta.scala
spark/src/test/scala/io/delta/tables/DeltaTableSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaHistorySuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala

- Remove `createLogDirectory` and replace all usages with `ensureLogDirectoryExists` since the latter is optimized for creation rather than existence check now. Rename it `createLogDirectoriesIfNotExists`
- Ensure commit directory is created on existing tables from older releases when manged-commits is enabled.
UTs
No

[Spark] Ensure commit directory is created for old and new tables

---

spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingStreamingReadSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingSuiteUtils.scala

Add support for streaming reads on tables that undergo column mapping downgrade.
Basically most streams should fail when a downgrade is happening on the table.
New unit tests
We test all the different scenarios also with schema tracking enabled.

[Spark] Column mapping removal: support streaming tables

---

kernel/kernel-api/src/main/java/io/delta/kernel/utils/CloseableIterator.java

`CloseableIterator.map` creates new `CloseableIterator` which has wrong `forEachRemaining` impl (it calls itself). We should remove the impl and fall back on the default impl. This is a day 0 bug, not needed for 3.2 (given 3.2 is so close to release)

[Kernel] Fix the infinite loop in `CloseableIterator.map`

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/TransactionExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/OptimisticTransactionPhases.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/PhaseLockingTransactionExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitOwnerClient.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionObserverSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionTestMixin.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

This PR extends Fuzz test to test managed commit features. Specifically, it adds a new event phase inside commit operation, so that we can capture the backfill as a separate operation. By doing so, it is possible that multiple commits can go through before backfill and managed commit is expected to deal with various situation to return the correct output.
Existing fuzz tests should naturally use the extended backfill phases.
No

[Spark] Extend Fuzz test For Managed Commit

---

kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/BaseTableReader.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/BaseTableWriter.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/CreateTable.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/CreateTableAndInsertData.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/MultiThreadedTableReader.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/SingleThreadedTableReader.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/utils/Utils.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/integration/WriteIntegrationTestSuite.java
kernel/examples/run-kernel-examples.py

Sample connector programs using the Kernel write APIs to
* create unpartitioned table
* create partitioned table
* create unpartitioned table and insert data into it (CTAS)
* create partitioned table and insert data into it (CTAS)
* insert into an existing unpartitioned table
* idempotent inserts
* insert with optional checkpoint
Also run these examples as part of the integration tests for release verification
Manually ran 
```
$ kernel/examples/run-kernel-examples.py --use-local
$ kernel/examples/run-kernel-examples.py --version 3.2.0 --maven-repo https://oss.sonatype.org/content/repositories/iodelta-1138
```

[Kernel][Writes] Example connector programs using the Kernel Write APIs

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingFileIndex.scala

Fix on an edge case: Use lazy val for DeltaSharingFileIndex.queryCustomTablePath, to allow the table path to be resolved at execution time, to match the table path used in CachedTableManager.INSTANCE.register(: https://github.com/delta-io/delta-sharing/blob/main/client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala#L181, and allow the query to find the pre-signed urls for the delta sharing table. 
Unit Tests
No

Use lazy val for DeltaSharingFileIndex.queryCustomTablePath

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

Extends DeltaLogSuite to test ManagedCommit. DeltaLogSuite already has a good coverage for Delta, hence use this suite to test MangaedCommit enabled table as well.
This PR itself is a test.
No

[Spark] Extend DeltaLogSuite to have ManagedCommit coverage

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala

Adds table feature phaseout support for managed commits.
Fixes the ManagedCommit table feature --> correctly marks it as a WriterFeature instead of a ReaderWriterFeature.
New tests in DeltaProtocolVersionSuite.
Yes, the drop table command now works for managed commits.

[Spark] Add drop support for managed commits

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckpointsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogMinorCompactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaDetailSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

Extend various Delta suites to use Managed Commits.
Bug fix: During listing delta-files, Filter initial list to exclude files with versions beyond initialListingMaxDeltaVersionSeen to prevent duplicating non-delta files with higher versions in the combined list
UTs
No

[Spark] Extend various Delta Suites to Managed Commits

---

spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClientImplSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwnerSuite.scala

This PR refactors the existing InMemoryCommitOwnerClientSuite into a generic suite, CommitOwnerClientImplSuiteBase. This base suite can be extended by CommitOwnerClient implementations to run the basic set of tests provided by the base suite. This is to make it easier for CommitOwnerClient implementations to get test coverage in the future.
It also adds an implementation of the suite for the InMemoryCommitOwnerClient with two different backfilling batch sizes (1 and 5).
Ensured that the newly introduced suites pass.
No

[Spark] Refactors InMemoryCommitOwnerClient suite into a generic suite that can be implemented by other CommitOwnerClient implementations

---

spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala

Follow up for https://github.com/delta-io/delta/commit/2ef3a2ae887e4d79c1469c60c54b3ec993b97db0 . There is another site where we don't specify the right way to serialize inCommitTimestamp which will cause failures when deserializing very small timestamps.

[Spark] Fix inCommitTimestamp deserialization for very small timestamps

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetColumnWriters.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetSchemaUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetStatsReader.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetFileWriterSuite.scala

Write the `timestamp` as `INT64` physical format in Parquet. Currently, it is written as `INT96` which is a very old method of writing timestamp and deprecated a long time ago. Also, collect statistics, for `timestamp` type columns.
Update the existing tests.

[Kernel][Writes] Write `timestamp` as `INT64` type to Parquet data files

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/TableFeatureSupport.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableFeatureSuite.scala

This PR adds support for protocol versions downgrade when table features exist in the protocol. The downgraded protocol versions should be the minimum required to support all available table features. For example, `Protocol(3, 7, DeletionVectors, RowTracking)` can be downgraded to `Protocol(1, 7, RowTracking)` after removing the DV feature.
Added new UTs in DeltaProtocolVersionSuite. Furthermore, existing UTs cover a significant part of the functionality. These these are the following:
- Downgrade protocol version on table created with (3, 7).
- Downgrade protocol version on table created with (1, 7).
- Protocol version downgrade on a table with table features and added legacy feature.
- Protocol version is not downgraded when writer features exist.
- Protocol version is not downgraded …

[Spark] Protocol version downgrade in the presence of table features

---

spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClientImplSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwnerSuite.scala

This PR makes a small improvement to the recently introduced CommitOwnerClientImplSuiteBase (a base trait that can be extended by CommitOwnerClient implementation tests). The change improves how the result of a getCommits call is validated. Instead of passing in a list of versions to validateGetCommitsResult, it now accepts the entire GetCommitsResponse. This allows to do more filtering on the result and also compare the latestTableVersion that is returned as part of the response (which is now implemented in the InMemoryCommitOwnerSuite).
Ensure that InMemoryCommitOwnerSuite still passes
No

[Spark] Improve GetCommits validation in CommitOwnerClient tests

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala-spark-master/org/apache/spark/sql/delta/DeltaVariantSuite.scala

promotes variant type table feature to preview by removing `-dev` suffix and appending `-preview` suffix. We will support `-preview` forever.
existing tests

[SPARK] Promote Variant Type Table Feature to Preview

---

spark/src/main/scala/org/apache/spark/sql/delta/skipping/MultiDimClustering.scala
spark/src/test/scala/org/apache/spark/sql/delta/clustering/ClusteredTableClusteringSuite.scala

Fall back to zorder when clustering on a single column, because hilbert clustering doesn't support 1 column.
Resolves #3087 
New unit test.
No.

[Spark] Fall back to zordering when clustering on a single column

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala

We currently use NANOSECONDS.toMillis(System.nanoTime()) for generating the ICT when `commitLarge` is called. However, this usage of System.nanoTime() is not correct as it should only be used for measuring time difference, not to get an approximate wall clock time. This leads to scenarios where the ICT becomes very small (e.g. 1 Jan 1970) sometimes because some systems return a very small number when System.nanoTime() is called. This PR changes this so that clock.getCurrentTimeMillis() is used instead.
Added a test case to ensure that `clock.getCurrentTimeMillis()` is being used.
No

[Spark] InCommitTimestamp: Use clock.currentTimeMillis() instead of nanoTime() in commitLarge

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwner.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClientSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwnerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

Updates CommitOwnerBuilder.build so that it can take in a sparkSession object. This allows it to read CommitOwner-related dynamic confs from the sparkSession while building it.
No

[Spark] Pass sparkSession to commitOwnerBuilder

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/test/scala/org/apache/spark/sql/delta/FindLastCompleteCheckpointSuite.scala

Fixes an issue where `Checkpoints.findLastCompleteCheckpoint` goes into an almost infinite loop if it is passed a Checkpoint.MAX_VALUE.
UT
No

[Spark] Handle case when Checkpoints.findLastCompleteCheckpoint is passed MAX_VALUE

---

build.sbt
spark/src/main/java/io/delta/dynamodbcommitstore/DynamoDBCommitOwnerClient.java
spark/src/main/java/io/delta/dynamodbcommitstore/DynamoDBCommitOwnerClientBuilder.java
spark/src/main/java/io/delta/dynamodbcommitstore/DynamoDBTableEntryConstants.java
spark/src/main/java/io/delta/dynamodbcommitstore/ManagedCommitUtils.java
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClient.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClientImplSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/DynamoDBCommitOwnerClientSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwnerSuite.scala

Taking inspiration from https://github.com/delta-io/delta/pull/339, this PR adds a Commit Owner Client which uses DynamoDB as the backend. Each Delta table managed by a DynamoDB instance will have one corresponding entry in a DynamoDB table. The table schema is as follows:
* tableId: String --- The unique identifier for the entry. This is a UUID.
* path: String --- The fully qualified path of the table in the file system. e.g. s3://bucket/path.
* acceptingCommits: Boolean --- Whether the commit owner is accepting new commits. This will only
*  be set to false when the table is converted from managed commits to file system commits.
* tableVersion: Number --- The version of the latest commit.
* tableTimestamp: Number --- The inCommitTimestamp of the latest commit.
* schemaVersion: Number …

[Spark] Managed Commits: add a DynamoDB-based commit owner

---

spark/src/main/scala/org/apache/spark/sql/delta/skipping/MultiDimClustering.scala
spark/src/test/scala/org/apache/spark/sql/delta/clustering/ClusteredTableClusteringSuite.scala

Fall back to zorder when clustering on a single column, because hilbert clustering doesn't support 1 column.
Resolves #3087 
New unit test.
No

[Spark][3.2] Fall back to zordering when clustering on a single column

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingPredicateBuilder.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/StatsProvider.scala

This refactoring adds support for nested statistics columns. So far, all statistics are keys in the stats struct in AddFiles. This PR adds support for statistics that are part of nested structs. This is a prerequisite for file skipping on collated string columns ([Protocol RFC](https://github.com/delta-io/delta/pull/3068)). Statistics for collated string columns will be wrapped in a struct keyed by the versioned collation that was used to generate them.  For example:
```
"stats": { "statsWithCollation": { "icu.en_US.72": { "minValues": { ...} } } }
```
This PR replaces statType in StatsColumn with pathToStatType, which can be used to represent a path. This way we can re-use all of the existing data skipping code without changes.
It is not possible to test this change without altering …

[SPARK] Support predicates for stats that are not at the top level

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala

Enable column mapping removal feature flag to allow user to run 
```
ALTER TABLE table_name SET TBLPROPERTIES ('delta.columnMapping.mode' = 'none')
```
or
```
ALTER TABLE table_name UNSET TBLPROPERTIES ('delta.columnMapping.mode')
```
to remove column mapping property from their table and rewrite physical files to match the logical column names.
Also allows column mapping feature to be dropped with
```
ALTER TABLE <table_name> DROP FEATURE columnMapping
```
existing tests
Yes
Allows user to run 
```
ALTER TABLE table_name SET TBLPROPERTIES ('delta.columnMapping.mode' = 'none')
```
or
```
ALTER TABLE table_name UNSET TBLPROPERTIES ('delta.columnMapping.mode')
```
to remove column mapping from a Delta table.
Previously, this commands would not run successfully and would return an exception …

[Spark] Enable column mapping removal feature flag

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceCDCSupport.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCStreamSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceColumnMappingSuite.scala

Skip reading log entries beyond endOffset, if specified while getting file changes for CDC in streaming queries
Also verified using logs to ensure that additional Delta logs are not read
```
24/05/16 01:21:01 INFO StateStore: StateStore stopped
Run completed in 54 seconds, 237 milliseconds.
Total number of tests run: 1
Suites: completed 1, aborted 0
Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```
Before:
```
10457:24/05/16 01:38:37 INFO DeltaSource: [queryId = 199ce] [batchId = 0] Getting CDC dataFrame for delta_log_path=file:/tmp/spark-c3309e79-80cf-4819-8b03-2fc607cc2679/_delta_log with startVersion=0, startIndex=-100, isInitialSnapshot=false, endOffset={"sourceVersion":1,"reservoirId":"75194ee3-4ff6-431e-8e7c-32006684d5ad","reserv …
```

[Spark] Skip reading log entries beyond endOffset, if specified while getting file changes for CDC in streaming queries

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSuite.scala

This PR modifies `DeltaCDFRelation` to apply the filters that are pushed down into this. This enables both partition pruning and row group skipping to happen when reading the Change Data Feed.
Unit tests
No

[Spark] Apply filters pushed down into DeltaCDFRelation

---

spark/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuiteBase.scala

Unbackfilled deltas eligible for deletion:
- Version <= max(backfilled-delta-deleted-versions)
Unit tests
No

[Spark] Metadata Cleanup for Unbackfilled Delta Files

---

spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/DropColumnMappingFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingSuiteUtils.scala

Allow column mapping feature to be dropped.
```
ALTER TABLE <table_name> DROP FEATURE columnMapping
```
Feature is hidden behind a flag.
new unit tests
No

[Spark] Column Mapping DROP FEATURE

---

spark/src/main/java/io/delta/dynamodbcommitstore/DynamoDBCommitOwnerClient.java
spark/src/main/java/io/delta/dynamodbcommitstore/DynamoDBCommitOwnerClientBuilder.java
spark/src/main/java/io/delta/dynamodbcommitstore/DynamoDBTableEntryConstants.java
spark/src/main/java/io/delta/dynamodbcommitstore/ReflectionUtils.java
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClientImplSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/DynamoDBCommitOwnerClientSuite.scala

Updates DynamoDBCommitOwner:
- Added logging around table creation flow
- Get wcu, rcu, and awsCredentialsProvider from SparkSession
- Return -1 as the table version if registerTable has already been called but no actual commits have gone through the owner. This is done by tracking an extra flag in DynamoDB.
Existing tests
Yes, introduces new configs (see DeltaSQLConf changes) which can be used to configure the DynamoDBCommitOwner.

[Spark] DynamoDBCommitOwner: add logging, get dynamic confs from sparkSession

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala

This PR introduces AddFile.longTag which factors out the pattern `tag(...).map(_.toLong)` and also converts the insertion time tag lazy val to a method in order to save memory.
No

[Standalone] AddFile Long Tags Accessor + Memory Optimization

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/zorder/ZCubeInfo.scala

This PR introduces Introduce `FileAction.tagsOrEmpty` to factor out the common pattern `Option(tags).getOrElse(Map.empty)`.
No

[Standalone] Introduce FileAction.tagsOrEmpty

---

build.sbt
project/Checkstyle.scala

Resolves #3067.
On local machine, intentionally create checkstyle errors in module `kernelDefaults` (for experimental), then run the `build/sbt compile` and `build/sbt kernelDefaults/test`.
No.

[INFRA] Improve the java style checks log the errors to sbt console

---

spark/src/main/java/io/delta/dynamodbcommitstore/ManagedCommitUtils.java
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala

Renames the ManagedCommit feature and config names by replacing -dev with -preview to indicate that it is in preview phase.
No new tests.
No

[Spark] Make ManagedCommit a preview feature

---

spark/src/main/scala/io/delta/sql/DeltaSparkSessionExtension.scala
spark/src/test/scala/org/apache/spark/sql/delta/perf/OptimizeGeneratedColumnSuite.scala

The following change in Spark master broke tests in `OptimizeGeneratedColumnSuite`: https://github.com/apache/spark/commit/7974811218c9fb52ac9d07f8983475a885ada81b
It added an execution of the `ConstantFolding` rule after `PrepareDeltaScan`, causing constant expressions in filters on generated columns to be simplified, which `OptimizeGeneratedColumnSuite` heavily used.
This change:
- updates the expected results in `OptimizeGeneratedColumnSuite` to simplify constant expressions
- adds a pass of `ConstantFolding` after `PrepareDeltaScan` so that Delta on spark 3.5 behaves the same as Delta on spark master.
Updated tests
No

[Spark] Update OptimizeGeneratedSuite to apply constant folding

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaTypeWideningSuite.scala

Additional tests covering type widening and:
- Reading CDF
- Column mapping
- Time travel
- RESTORE
- CLONE
Test only

[Spark] Test type widening compatibility with other Delta features

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/CheckConstraintsSuite.scala

This PR fixes an internal error thrown from `AlterTableAddConstraintDeltaCommand`. This error is thrown when adding a CHECK constraint with a non-existent column in the expression. The error is thrown when we check if the expressions returns a boolean. This works correctly for most expressions, but will result in an exception if the data type of the unresolved column is checked.
This PR fixes this issue by making the analyzer responsible for checking whether the expression returns a boolean by wrapping the expression with a `Filter` node.
Added a test
Yes, `ALTER TABLE ... ADD CONSTRAINT ... CHECK` will now throw a `UNRESOLVED_COLUMN` error instead of a `INTERNAL_ERROR` in the case described above.

[Spark] Validate the expression in AlterTableAddConstraintDeltaCommand

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

Factors out the main logic from `listDeltaCompactedDeltaCheckpointFilesAndLatestChecksumFile` into a new function `listFromFileSystemInternal` which can potentially be reused by other callers. Also added a new test utility which runs tests with in-memory-tracking commit owner enabled.
Existing tests should cover this.
No

[Spark] Make listDeltaCompactedDeltaCheckpointFilesAndLatestChecksumFile reusable

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/schema/InvariantViolationException.scala
spark/src/test/scala-spark-master/org/apache/spark/sql/delta/DeltaVariantSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/CheckConstraintsSuite.scala

This PR modifies the error message for the `DELTA_EXCEED_CHAR_VARCHAR_LIMIT` error class to include the value that violated the constraint.
Modified a test in `DeltaErrorsSuite` and added a test to `DeltaConstraintsSuite`.
Yes, the error message for the `DELTA_EXCEED_CHAR_VARCHAR_LIMIT` error class is modified to include the value that violated the constraint.

[Spark] Include violating value in DELTA_EXCEED_CHAR_VARCHAR_LIMIT

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/test/scala/org/apache/spark/sql/delta/clustering/ClusteringTableFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

Support in-place migration from unpartitioned table to clustered table. If the table is an unpartitioned table and users run `ALTER TABLE CLUSTER BY` on it, it will now create a clustered table with ClusteringMetadataDomain.
Resolves #2460 
New UTs.
No

[Spark] Support in-place migration from unpartitioned table to clustered table

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/ImplicitMetadataOperation.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/ClusteredTableTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

Fix replacing clustered table with non-clustered table, by creating a domain metadata with empty clustering columns.
New UTs.
No

[Spark] Fix replacing clustered table with non-clustered table

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/types/DataTypeParser.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/types/DataTypeParserSuite.scala

Currently when parsing the `FieldMetadata` in `StructField` (as part of the schema parsing), we always assume the integral values are of `int` type, but it could be of value `long`.
Add couple of cases to existing test

[Kernel] Handle long values in `FieldMetadata` parsing

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

[MINOR] Fix typo

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala

This PR fixes a race condition in UniForm Iceberg Converter. 
Before our change, UniForm Iceberg Converter executes as follows:
1. Read `lastConvertedDeltaVersion` from Iceberg latest snapshot
2. Convert the delta commits starting from `lastConvertedDeltaVersion` to iceberg snapshots
3. Commit the iceberg snapshots.
When there are multiple iceberg conversion threads, a race condition may occur, causing one delta commit to be written into multiple Iceberg snapshots, and data corruption. 
As an example, considering we have a UniForm table with latest delta version and iceberg version both 1. Two threads A and B start writing to delta tables.
1. Thread A writes Delta version 2, reads `lastConvertedDeltaVersion` = 1, and converts delta version 2. 
2. Thread B writes Delta version 3, reads …

[Spark] Fix race condition in Uniform conversion

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/types/DataTypeParser.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala

Minor fix to throw `KernelException` when `VOID` type is encountered as it is an unsupported data type in Kernel.
Test

[Kernel] Throw `KernelException` when `VOID` type is encountered

---

build.sbt

Move unidoc settings from `crossSparkSettings()` to the spark project definition since they are duplicated. This simplifies sbt definition for delta-connect projects that need the `crossSparkSettings()` but don't have javadocs enabled.
Compilation fails when this is provided
```
scalacOptions ++= Seq(
"-P:genjavadoc:strictVisibility=true" // hide package private types and methods in javadoc
),
```
_and_ javadocs are not enabled.
Existing tests suffice it's a refactoring.

[INFRA] Move unidoc settings from `crossSparkSettings()` to the spark project definition since they are the same

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/ImplicitMetadataOperation.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/ClusteredTableTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

Fix replacing clustered table with non-clustered table, by creating a domain metadata with empty clustering columns.
Cherry-picked from 59f8c64c2a2bc49877e8e19913c9249f9f337028
New unit tests
No

[Spark][3.2] Fix replacing clustered table with non-clustered table

---

spark/src/main/scala/io/delta/sql/DeltaSparkSessionExtension.scala
spark/src/main/scala/org/apache/spark/sql/delta/GenerateRowIDs.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/ResolveDeltaPathTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowCommitVersion.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/AutoCompactUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceCDCSupport.scala

- Spark
Many of these changes are to make the code more Scala-idiomatic (and less "Pythonic") to ease code comprehension ❤️
A few typos got squashed along the way, too 😎
Local builds
No

[SPARK][MINOR] Code cleanup (reformatting and typo hunting)

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala

Shallow cloned tests have `AddFile`s with an absolute path to the source table location. Normally the path is relative to the table root. Add a test to verify that reading works in Kernel.

[Kernel][Test] Add test for reading a shallow cloned table

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActiveAddFilesIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplayMetrics.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ActiveAddFilesLogReplayMetricsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplayEngineMetricsSuite.scala

Currently, the log replay code used to find the active add files in a table snapshot is not observable. Add a few metrics to provide visibility into the log replay. These metrics are collected as the `CloseableIterator` of scan files is consumed and printed in slf4j logs when the iterator is closed. Following are the metrics collected:
* number of `AddFile` actions seen
* number of `AddFile` actions seen from delta files
* number of duplicate `AddFile` actions seen
* number of tombstones seen
* number of active `AddFile`s
Add unit tests with different scenarios
* deltas only
* checkpoint class/multi-parts,
* stats recompute - generates duplicate add files, 
* removes - generates tombstones)
No, but the info level logs will have a message with the log replay metrics.

[Kernel] Add Delta log replay metrics in active file list construction

---

spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWidening.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaReorgTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTypeWideningSuite.scala

The initial approach to identify files that contain a type that differs from the table schema and that must be rewritten before dropping the type widening table feature is convoluted and turns out to be more brittle than intended.
This change switches instead to directly reading the file schema from the Parquet footer and rewriting all files that have a mismatching type.
Files are identified using their default row commit version (a part of the row tracking feature) and matched against type changes previously applied to the table and recorded in the table metadata: any file written before the latest type change should use a different type and must be rewritten.
This requires multiple pieces of information to be accurately tracked:
- Default row commit versions must be correctly assigned …

[Spark] Drop Type widening feature: read Parquet footers to collect files to rewrite

---

spark/src/main/scala/org/apache/spark/sql/delta/util/FileNames.scala

- Clients are expected to use DeltaCommitFileProvider instead.
- FileNames.unsafeDeltaFile can be used in case the clients knows for sure the file has been backfilled.
Build
No

[Spark] Remove deprecated FileNames.deltaFile method

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableUtilsSuite.scala

This PR follows https://github.com/delta-io/delta/pull/3153 and introduces a Delta config to enable or disable the workaround of handling colons ':' in paths. The value of this config is `true` by default.
No, unless the user encountered any problem, which is very unlikely.

[Spark] Add a Delta config to enable/disable the workaround of handling colons ':' in paths

---

protocol_rfcs/managed-commits.md
spark/src/main/java/io/delta/dynamodbcommitstore/DynamoDBCommitOwnerClient.java
spark/src/main/java/io/delta/dynamodbcommitstore/DynamoDBCommitOwnerClientBuilder.java
spark/src/main/java/io/delta/dynamodbcommitstore/ManagedCommitUtils.java
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/DynamoDBCommitOwnerClientSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

1. Replaces instances of Managed Commits with Managed Commit (without the s) in functions, configurations, and docs.
2. Renames the feature name to managedCommit-preview
3. Renames the DynamoDBCommitOwner tableConfig key to dynamoDBTableName
Cherrypicked from https://github.com/delta-io/delta/pull/3224
Existing tests should cover this refactor.
The managed commit table feature name has been updated to managedCommit-preview

[Spark] Make naming of manage commit consistent

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampTestUtils.scala

Refactors DeltaHistoryManagerSuite so that a common method is used for updating timestamps.
No

[Delta] Simplify DeltaHistoryManagerSuite

---

spark/src/main/scala/org/apache/spark/sql/delta/DomainMetadataUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/RestoreTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/ClusteredTableTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

Support RESTORE for clustered tables by adding a new domain metadata to overwrite the existing one so that clustering columns are correctly restored.
New unit tests.
No

[Spark] Support RESTORE for clustered table

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala

Propose a fix to prevent delta table got duplicate ids assigned when schema have nested fields and ids assigned.
**Issue**: today when we are assigning column's ids we first compute the `maxId` of existing columns and assign ids for new fields from `maxId + 1`. However, the existing code doesn't consider nested ids when computing the `maxId`, so it's possible to have duplicate ids assigned to different columns - which causes failure of uniform iceberg conversion since iceberg requires that id is unique for each column.
**Proposed fix**: we are adding the logic to consider nested fields' ids when computing `maxId`. 
No

[Delta Uniform] Compute correct MAX_ID in column mapping on a schema with nested fields and already have IDs assigned

---

spark/src/main/scala/org/apache/spark/sql/delta/DomainMetadataUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/RestoreTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/ClusteredTableTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

Backported from https://github.com/delta-io/delta/commit/ef1def9e3c97d80518dcb9b5cd48f58e8e859bd8
Support RESTORE for clustered tables by adding a new domain metadata to overwrite the existing one so that clustering columns are correctly restored.
New unit tests.
No

[Spark][3.2] Support RESTORE for clustered table

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/temp/ClusterBySpec.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

Support creating a clustered table from an external location that already has a clustered table. We follow the same semantics as partitioned tables:
External location already has clustered/partitioned table:
| Create clustered/partitioned table | partitioned | clustered |
| ----------------------------------- | ------ | ----------- |
| schema not specified, cluster/partitioned by not specified | success | success |
| schema specified, cluster by/partitioned by not specified | throw `DELTA_CREATE_TABLE_WITH_DIFFERENT_PARTITIONING` | throw `DELTA_CREATE_TABLE_WITH_DIFFERENT_CLUSTERING` |
| schema specified, cluster by/partitioned by different column | throw `DELTA_CREATE_TABLE_WITH_DIFFERENT_PARTITIONING` | throw `DELTA_CREATE_TABLE_WITH_DIFFERENT_CLUSTERING` |
| schema specified, cluster …

[Spark] Support create external table for clustered table

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaFormatSharingSource.scala
sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingFileIndex.scala
sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingUtils.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingFileIndexSuite.scala

Fix the issue of not using the correct refreshToken, when refreshing on the 2nd time, or more.
Unit Tests
No

Fix the issue of not using the correct refreshToken

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/StatisticsCollection.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/StatsCollectionSuite.scala

This is to not append the tieBreaker character when no part of the string was truncated
UTs
No

[Spark] Append the tieBreaker unicode max character only if we actually truncated the string

---

PROTOCOL.md

This PR adds a remark in PROTOCOL.md about the behaviour of tightBounds when not present in the statistics.
Doc only change.
Yes. Adds a remark in PROTOCOL.md about the behaviour of tightBounds when not present in the statistics.

Improve documentation in PROTOCOL.md about TightBounds

---

spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala

This PR removes the asInstanceOf[Metadata] casts in AbstractBatchBackfillingCommitOwnerClient.
Ensured the existing test suites, along with the newly added unit test for the helper function, all pass after the removal.
No.

[DELTA] Removes asInstanceOf[Metadata] casts

---

spark/src/test/scala/org/apache/spark/sql/delta/schema/CheckConstraintsSuite.scala

[Spark] Clean up imports in CheckConstraintsSuite.scala

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultJsonHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/DefaultEngineErrors.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/logstore/LogStoreProvider.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/logstore/LogStoreProviderSuite.scala

Minor cleanups + additional logging.
* Pass the cause exception to `KernelException`, so that it is visible to the caller
* Add logging when the LogStore can't be created.
* Convert `RuntimeException` to `KernelException` when an invalid schema JSON string is received.
Existing tests

[Kernel][Defaults] Minor cleanups + additional logging

---

spark/src/test/scala/io/delta/tables/DeltaTableBuilderSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/ClusteredTableTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/IncrementalZCubeClusteringSuite.scala

Currently, clustering columns are validating by parsing a list of clustering columns. This is super brittle, and breaks when any clustering column has a comma in the name. Fix that by passing a list of clustering columns directly.
This fix resolves https://github.com/delta-io/delta/issues/3265
No.

[Spark] Fix validation of clustering columns

---

storage/src/main/java/io/delta/storage/commit/Commit.java
storage/src/main/java/io/delta/storage/commit/CommitCoordinatorClient.java
storage/src/main/java/io/delta/storage/commit/CommitFailedException.java
storage/src/main/java/io/delta/storage/commit/CommitResponse.java
storage/src/main/java/io/delta/storage/commit/GetCommitsResponse.java
storage/src/main/java/io/delta/storage/commit/UpdatedActions.java
storage/src/main/java/io/delta/storage/commit/actions/AbstractCommitInfo.java
storage/src/main/java/io/delta/storage/commit/actions/AbstractMetadata.java
storage/src/main/java/io/delta/storage/commit/actions/AbstractProtocol.java

This PR takes the existing definitions in CommitCoordinatorClient.scala and converts them to java classes/interfaces in the storage module. This is in preparation for replacing the CommitCoordinatorClient in Spark Delta with a generic java-based module that can be implemented in any Delta client.
This PR only copies existing definitions to java classes/interfaces in the storage module. These new classes/interfaces are not in use yet so no tests are required.
No

[Other] Adds coordinated commits-related interfaces and definitions to storage module

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

Currently, Spark interprets the timestamp partition columns in the local zone and Kernel in UTC. Delta protocol specifies no details on what timezone to use. This is a known issue and in Kernel we decided to always interpret as UTC to avoid timezone issues. Fix here is when getting the expected results using Spark, set the timezone to UTC to get the same values as Kernel.
Ran locally on Pacific timezone test env

[Kernel][Tests] Fix test failure when running in non-UTC tz env

---

spark/src/main/scala-spark-3.5/shims/ParserInterfaceShims.scala
spark/src/main/scala-spark-3.5/shims/SqlScriptingLogicalOperatorsShims.scala
spark/src/main/scala-spark-master/shims/ParserInterfaceShims.scala
spark/src/main/scala/io/delta/sql/parser/DeltaSqlParser.scala

https://github.com/apache/spark/pull/46665 introduced a new `parseScript` method in `ParserInterface`, which broke compilation against Spark master:
```
[error] /home/runner/work/delta/delta/spark/src/main/scala/io/delta/sql/parser/DeltaSqlParser.scala:75:7: class DeltaSqlParser needs to be abstract.
[error] Missing implementation for member of trait ParserInterface:
[error]   def parseScript(sqlScriptText: String): org.apache.spark.sql.catalyst.parser.CompoundBody = ???
[error] class DeltaSqlParser(val delegate: ParserInterface) extends ParserInterface {
[error]       ^
[warn] 100 warnings found
[error] one error found
[error] (spark / Compile / compileIncremental) Compilation failed
```
This PR fixes the issue by shimming the `ParserInterface` since `parseScript` is not available in …

[Spark] Fix compile error on Spark master due to ParserInterface changes

---

kernel/kernel-api/src/main/java/io/delta/kernel/exceptions/InvalidTableException.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala

During log reconstruction we throw a bunch of various errors when we encounter a table state that we consider invalid. This PR updates some of those errors to be `InvalidTableException`. This doesn't necessarily cover all possible exceptions due to an invalid table, just some of the known and clear cases during log reconstruction.
Updates existing tests.
Yes, instead of internal `RuntimeExceptions` or `IllegalStateExceptions`, etc a `InvalidTableException` will be thrown when certain invalid table states are encountered.

[Kernel] Throw InvalidTableException when we encounter a known invalid table state

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DataWriteContextImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/PartitionUtilsSuite.scala

The current code does not escape the control + special characters in partition values when constructing a path for writing the data related to the partition. Not escaping these characters could cause invalid path issues. 
The escaping logic is similar to what Spark and Hive do.
Unit tests.

[Kernel] Fix the partition path construction

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFilterUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetReaderPredicatePushdownSuite.scala

Allows pushing down predicates `IS NULL` and `IS NOT NULL` into the default Parquet reader. Helps prune the number of row groups read based on the predicates.
Unit tests

[Kernel][Defaults] Add support for pushing IS [NOT] NULL into Parquet reader

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/logstore/LogStoreProvider.java

Look for the `LogStore` class more broadly in the class loader than just the thread local's class loader. The thread context class loader requires the Thread local variables to have the `LogStore` in it, but this class loader may not have all the dependencies wired up.
Not tested yet.
Fixes https://github.com/delta-io/delta/issues/3299.

[Kernel] Change `Class.forName()` usage  in the `LogStoreProvider`.

---

PROTOCOL.md

Update the Delta PROTOCOL to allow `AddCDCFile` actions that do not add Change Data Files, but instead register Data Files that are also added by `AddFile` actions. In this case the `_change_type` column in the Data Files might not be `null`. Non-change data readers should disregard this column and only process columns defined within the table's schema.
N/A
Protocol clarification.

[PROTOCOL] Allow CDC actions to register data files

---

build.sbt
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingCDFUtilsSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingFileIndexSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/TestClientForDeltaFormatSharing.scala

Upgrade delta-sharing-client to v1.1.0
Existing test
No.

[Spark][Sharing] Update delta sharing client to version 1.1.0

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala

**_Issue_**: the current uniform iceberg table doesn't have a mechanism to cleanup old manifest/manifest list files, which adds great storage maintenance overhead
**_Proposed_**: when `OPTIMIZE` is running on uniform delta table, it will trigger the `expireSnapshot` operation on corresponding iceberg table to do cleanup on manifests. The `OPTIMIZE` is chosen as the trigger since it's recommended to run frequently on delta table and iceberg's `expireSnapshot` is also recommended to run frequently (once every day) 
Manually tested

[Delta Uniform] Support expireSnapshot in uniform iceberg table automatically when OPTIMIZE

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCreateTableLikeSuite.scala

When 2 or more CREATE TABLE IF NOT EXISTS table commands are run concurrently, they both think the table doesn't exist yet and the second command fails with TABLE_ALREADY_EXISTS error.
With this PR, we aim to make sure the second command end up in a no-op instead of a failure.
UTs
No

[Spark] Handle concurrent CREATE TABLE IF NOT EXISTS ... LIKE ... table commands

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConversionTransaction.scala
hudi/src/test/scala/org/apache/spark/sql/delta/hudi/ConvertToHudiSuite.scala

This PR fixes a bug in the Delta->Hudi metadata conversion logic. When the number of actions to convert is greater than the action batch size (can be changed by user), the previous code incorrectly only converted the last batch instead of converting all batches.
Unit test
No

[Hudi] setCommitFileUpdates bug fix

---

protocol_rfcs/type-widening.md

Finalize the protocol RFC for type widening:
- Add missing supported type changes: `byte`,`short`,`int` to `double` and integers to decimals.
- Remove `tableVersion` from the type change metadata fields.
- Remove requirements around populating default row commit versions.
The two last requirements were initially intended to allow matching each file against type changes that happened before or after it was written. This didn't prove useful in practice - it was temporarily used to collect files to rewrite when dropping the feature but this now relies on fetching parquet footer as a more robust and simpler approach.

[Protocol RFC] Finalize type widening protocol

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

We already log the failure scenario when additional file-system listing also can't reconcile the gap between concurrent file-system listing and commit-owner calls.
With this PR, we will throw an exception if the above condition is triggered while testing.
UTs
No

[Spark] Throw exception when additional listing also doesn't reconcile the listing gap in testing

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWidening.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningTableFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningTestMixin.scala

This is the first step in transitioning the type widening table feature from preview to stable.
Requirement: the protocol spec is finalized and the final version doesn't contain any backward-incompatible changes. See https://github.com/delta-io/delta/pull/3297
This change introduces a new table feature `typeWidening` for the final, stable phase of type widening. Both the preview and stable table features are supported simultaneously - the current implementation respects both the protocol spec used during the preview and the finalized protocol spec.
The stable feature isn't enabled automatically though as type widening is still in preview. The preview feature `typeWidening-preview` is the default feature enabled when the type widening table property is set. 
The second step of the …

[Spark] Introduce stable type widening table feature

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/CommitInfo.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/Clock.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ManualClock.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala

Add read support for inCommitTimestamp and ensure the increasing monotonicity of inCommitTimestamp assuming that there are no conflicts to prepare for the complete inCommitTimestamp support with conflict resolution in Kernel.
Add unit tests to verify that the read of inCommitTimestamp is correct and inCommitTimestamp is monotonic.
Yes, user can enable monotonic inCommitTimestamp assuming that there are no conflicts by enabling its property.

[Kernel] Add monotonic inCommitTimestamp and read support for inCommitTimestamp

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiSchemaUtils.scala
hudi/src/test/scala/org/apache/spark/sql/delta/hudi/ConvertToHudiSuite.scala

This PR fixes a bug in the Delta->Hudi schema conversion for structs. Previously, any table conversion that included at least one struct somewhere in the schema would fail. This is because the previous code was incorrectly naming the Avro RecordSchemas. There were two problems:
1.  There was no namespace added to each record, so for a struct column with the following schema:
` (myName STRUCT<myName: STRUCT<field1: INT>>)`
there would be an error due to the duplicate naming of the two structs. (**Avro does not allow recordSchemas with the same name under the same namespace**) It would incorrectly place the nested struct in the same namespace as the parent struct, and even though our schema should be valid the Avro schema creation would fail.
2. For some reason we were naming each record by …

[Hudi] Fix duplicate record naming in schema conversion

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiSchemaUtils.scala
hudi/src/test/scala/org/apache/spark/sql/delta/hudi/ConvertToHudiSuite.scala
spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala

This PR adds functionality to convert Delta tables with list or map type columns to be Hudi-readable. 
Added unit tests in ConvertToHudiSuite and tested manually with external Hudi Spark reader.
Yes. Previously users could not enable the Delta table property for Hudi conversion on tables containing list/map columns and would receive an unsupportedType error but now they can.

[Hudi] Support list/map data type conversion

---

spark/src/main/scala/org/apache/spark/sql/delta/hooks/HudiConverterHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

This PR adds a Delta SQL config to let us make the Hudi metadata conversion synchronously after each commit instead of asynchronously (default). This SQL config is used for testing and debugging purposes only.
Unit tests
No

[Hudi] Add SQL config for synchronous Delta -> Hudi metadata conversion

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala

Add missing operation metrics to SQL metrics emitted by Delta command Spark plans.
existing tests
no

Add Delta command operation metrics to SQL metrics

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala

add Delta logging to UniForm conversion mismatch

[Spark] add Delta logging to UniForm conversion mismatch

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/DeletionVectorDescriptor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/deletionvectors/StoredBitmap.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeFileIndex.scala

The Deletion Vector descriptor of each file is currently serialized in file's custom metadata as a JSON string. We can reduce the size of the descriptor by using a custom binary encoding. Note that the serialized DV descriptor is never persisted to disk so this change is safe.
Updated existing new tests.
No

[Spark] Use binary encoding for DV descriptor in file metadata

---

hudi/integration_tests/write_uniform_hudi.py
run-integration-tests.py

This PR adds integration tests for Hudi. Previously, the integration test was not able to actually read the table from a Hudi engine due to Spark incompatibility, but since the new Hudi 15.0.0 release supports Spark 3.5 we can now add verifications that actually read the tables from Hudi.
Added integration tests
No

[Hudi] Add integration tests for Hudi

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConversionTransaction.scala
hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConverter.scala
hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiSchemaUtils.scala
hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiTransactionUtils.scala
hudi/src/test/scala/org/apache/spark/sql/delta/hudi/ConvertToHudiSuite.scala
spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala

This PR adds unit tests and also removes support of some data types that are not supported by Hudi (e.g. TIMESTAMP_NTZ, SHORT, BYTE, etc)
Unit tests
No

[Hudi] Flesh out tests and update column type support

---

spark/src/main/scala/org/apache/spark/sql/delta/TypeWideningMetadata.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningMetadataSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningTableFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningTestMixin.scala

The protocol specification for type widening dropped the requirement to populate a `tableVersion` field as part of type change history to track in which version of the table a given change was applied.
See protocol update: https://github.com/delta-io/delta/pull/3297
This field was used at some point during the preview but isn't needed anymore.
It is now deprecated:
- The field is preserved in table metadata that already contains it.
- The field isn't set anymore when the stable table feature is active on the table.
- The field is still set when only the preview table feature is active on the table.
The last point is necessary to avoid breaking preview clients (Delta 3.2 & Delta 4.0 preview) that require the field to be set.
- Updated existing metadata tests to cover `tableVersion` not …

[Spark] Deprecate tableVersion field in type widening metadata

---

spark/src/main/scala/org/apache/spark/sql/delta/files/CdcAddFileIndex.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeChangeFileIndex.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeRemoveFileIndex.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSuite.scala

The CDC's `_commit_timestamp` is incorrect when we try to read/display it under a different Spark Session's timezone `spark.sql.session.timeZone` (e.g. `America/Chicago`, `Asia/Ho_Chi_Minh`, ...). 
In this PR, we address this issue by taking into account timezone to capture the precise point in time when we convert `CDCDataSpec`'s [Java Timestamp](https://github.com/delta-io/delta/blob/master/spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala#L173) field to [Spark's Timestamp](https://github.com/delta-io/delta/blob/master/spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala#L80) for the `_commit_timestamp` column for all CDC's file indexes (`CDCAddFileIndex`, `TahoeRemoveFileIndex`, `TahoeChangeFileIndex`).
This is needed in order for CDF …

[Spark] Fix CDC Commit Timestamp value under different Timezones

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaAlterTableTests.scala

Context: VARCHAR/CHAR to String column conversion was broken. https://github.com/delta-io/delta/pull/2731 was an attempted fix where we strip CHAR/VARCHAR metadata from columns in `alterDeltaTableCommands.scala` during column conversion if the target type is String.
However, this introduced a regression --- updating any metadata for a CHAR/VARCHAR column will convert it into a StringType. This is because the original fix did not account for the fact that the target data type of a VARCHAR column appears to be a String even during other types of column DDL updates that are not data type changes.
This PR:
1. Removes the changes from https://github.com/delta-io/delta/pull/2731
2. Makes it so that StringType is temporarily converted into CHAR/VARCHAR Type and the CHAR/VARCHAR metadata is …

[Spark] Fix VARCHAR/CHAR to string conversion

---

spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaCommitFileProvider.scala

Make sure that version and maxVersionInclusive are formatted correctly.
Build
No

[Spark] Fix error message formatting in DeltaCommitFileProvider

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConversionTransaction.scala
hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergFileManifest.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala

Migrate remaining logging code to use Spark structured logging. Structured logging will be introduced in Spark 4.0, as highlighted in the [preview release of Spark 4.0 | Apache Spark](https://spark.apache.org/news/spark-4.0.0-preview1.html). Note that the feature is turned off by default and the output log message will remain unchanged.
Resolves #3145 
No

[Spark] Migrate remaining logging code to use Spark Structured Logging

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/InMemoryCommitCoordinator.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

For CLONE, the priority order for Coordinated Commits related settings is:
1. Explicit overrides with the CLONE command
2. SparkSession defaults
Note, we never pick the Coordinated Commits related settings from the source metadata even if the above two are not set.
UTs
No

[Spark] Use Coordinated Commits Properties from SparkSession during CLONE

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaWithNewTransactionSuite.scala

This PR extends NewTransactionSuite with coordinated commits enabled.
This is a test.
No

[Spark] Extends NewTransactionSuite with CoordinatedCommits

---

spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaCommitFileProvider.scala

Add a list util to DeltaCommitFileProvider.
Build
No

[Spark] Add list utils to DeltaCommitFileProvider

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

- Add a new codepath (disabled by default except in testing) to `findDeltaTableRoot` (which is the implementation of `isDeltaTable`), that throws the first exception if the passed in path is not accessible, and no accessible parent is found to contain a `_delta_log` folder.
- This improves error reporting on permission errors, which current often get misreported as `t is not a DeltaTable`.
- This also reduces the risk for transient cloud storage errors causing us to silently resolve a DeltaTable as a non-Delta table, which can lead to inconsistencies in how we process it when we check multiple times.
- Note that this is still not ideal, we could still end up with a situation where we the first path is accessible but a child of the Delta Table, such as a partition, but then when we check …

[Spark] Expose uncertainty in isDeltaTable resolution via exceptions

---

spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionTestMixin.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/ConflictCheckerRowIdSuite.scala

Remove tracking usageRecords generated from the query runs in runFunctionsWithOrderingFromObserver because it is unnecessary for our testing purpose.
Existing UTs.
No.

[Spark] Remove tracking usageRecords in runFunctionsWithOrderingFromObserver

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/IcebergCompat.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala

Now users could directly enable Delta UniForm using `ALTER TABLE SET TBLPROPERTIES` command, this only converts the corresponding metadata from `delta` to `iceberg` without rewriting all the underlying parquet files.
Through manual tests and e2e tests.
Yes, this PR let users enable Delta UniForm directly via `ALTER TABLE SET TBLPROPERTIES` command.

[Spark] Enable UniForm Without Rewrite

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaParquetFileFormatSuite.scala

- Iceberg states in the spec that Timestamps should be written with INT64 physical types. There were already flags to enable this, but this PR makes this behavior the default.
- `INT96` is discouraged: https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L981
- Added new unit-tests to validate the correct behavior
Yes, it will default to INT64 if nothing has been set.

[Spark] Write INT64 by default for Timestamps

---

spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/InMemoryCommitCoordinator.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

`TrackingCommitCoordinatorClient` currently takes a `InMemoryCommitCoordinator` in the constructor. This makes it hard to test the coordinator with other coordinator types. This PR makes it take `CommitCoordinatorClient` instead and moves the `InMemoryCommitCoordinator`-specific APIs to `InMemoryCommitCoordinator`.
No new tests for this test-only change.
No

[Spark] Make TrackingCommitCoordinatorClient more generic

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/SingleAction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ConflictChecker.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/InCommitTimestampUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala

Update ConflictChecker to perform conflict resolution of inCommitTimestamp and complete the inCommitTimestamp support in Kernel.
Add unit tests to verify the conflict resolution of timestamps and enablement version.
Yes, user can enable monotonic inCommitTimestamp by enabling its property.

[Kernel] Update ConflictChecker to perform conflict resolution of ICT

---

spark/src/test/scala/org/apache/spark/sql/delta/DDLTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/GeneratedColumnTest.scala
spark/src/test/scala/org/apache/spark/sql/delta/RestoreTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowtracking/RowTrackingTestUtils.scala

Follow-up from https://github.com/delta-io/delta/pull/3365
Mix in `DeltaSQLTestUtils` in more test suites so that they use the Delta temp dir creation helpers.
Test-only

[Spark] Use DeltaSQLTestUtils in more test suites

---

spark/src/main/scala/org/apache/spark/sql/delta/util/PartitionUtils.scala

I was looking at this code path for another issue and noticed that when parsing partition values from paths (only used for the write path) without type inference we still attempt to due parsing for date/decima/timestamp types even though it's not required. We can avoid that work with a small refactoring.
This is a refactoring/minor optimization where existing unit tests will exercise this path
No

[Spark] Only attempt parsing partition path into different types if type inference is enabled

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeIntoMaterializeSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoMaterializeSourceSuite.scala

Source materialization for MERGE INTO currently uses 2-way replication on retries. This may not be enough when executors are aggressively killed, for example when using spot instances.
This change retains 2-way replication on the first retry, then increases it 3-way by default on the following retries.
Update merge source materialization test

[Spark] Increase replication level in MERGE source materiazliation after first retry

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaReorgTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableHelper.scala
spark/src/test/scala/org/apache/spark/sql/delta/optimize/DeltaReorgSuite.scala

According to #3228, we add the support to also find and remove dropped columns when running `REORG PURGE`.
Close #3228.
Through unit test in `DeltaReorgSuite.scala`.
No.

[Spark] Remove dropped columns when running REORG PURGE

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaParquetFileFormatSuite.scala

Move OutputTimestampType to `DeltaSQLConf`

---

kernel/kernel-api/src/main/java/io/delta/kernel/engine/CommitCoordinatorClientHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/Engine.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/coordinatedcommits/Commit.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/coordinatedcommits/CommitFailedException.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/coordinatedcommits/CommitResponse.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/coordinatedcommits/GetCommitsResponse.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/coordinatedcommits/UpdatedActions.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/coordinatedcommits/actions/AbstractCommitInfo.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/coordinatedcommits/actions/AbstractMetadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/coordinatedcommits/actions/AbstractProtocol.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockEngineUtils.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultEngine.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplayEngineMetricsSuite.scala

Add coordinated commits interfaces and related table properties in Kernel to prepare for Kernel read and write supported by coordinated commits.
Unit tests
Yes. User can define and register their own commit coordinator builder and get the corresponding commit coordinator client handler from engine.

[Kernel] Add coordinated commits interfaces and table properties

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolTransitionsSuite.scala

Minor refactor in `DeltaProtocolTransitionsSuite`.
Test only PR.
No.

[Spark] Minor refactor in Delta Protocol Transition Suite

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/ClassicMergeExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/InsertOnlyMergeExecutor.scala

Make `notMatchedClauses` a custom `def`
Unit tests
No

[Spark] Add custom not matched for insert clauses expr

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/ClassicMergeExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/InsertOnlyMergeExecutor.scala

This reverts commit 1d9ad36f53a73d9a5e207adaac41dd54626937b8.
Reverts adding custom expressions for not matched insert clauses.
Unit tests
No

Revert "[Spark] Add custom not matched for insert clauses expr (#3405)"

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala

Make the match loop exhaustive to avoid scala.MatchError
Existing Unit tests.
No

Match table exhaustively for ConvertToDelta to avoid scala.MatchError

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

- Change the default value of the isDeltaTable.throwOnError flag to `true`.
Existing tests (was already `true` in testing).
Resolving a Delta that is accessed by path (e.g. DeltaTable.forPath() or SELECT ... FROM delta.<path>) will now forward exceptions thrown while accessing , instead of always throwing a DELTA_MISSING_DELTA_TABLE exception.
This helps locating issues such as missing access permissions without having to through support.

[Spark] Flip isDeltaTable.throwOnError to true

---

iceberg/src/test/scala/org/apache/spark/sql/delta/uniform/UniFormE2ESuite.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaReorgTableCommand.scala

currently we utilize the helper function `shouldRewriteToBeIcebergCompatible` to filter the portion of parquet files that need to be rewritten when running `REORG UPGRADE UNIFORM` based on the tags in the `AddFile`.
however, the `DeltaUpgradeUniformOperation.icebergCompatVersion` is accidentally shadowed, which will make `shouldRewriteToBeIcebergCompatible` always return `false` if the `AddFile.tags` is not `null` - this is not the expected semantic of this function.
this PR introduces the fix for this problem and add unit tests to ensure the correctness.
through unit tests in `UniFormE2ESuite.scala`.
no.

[Spark] Fix the semantic of `shouldRewriteToBeIcebergCompatible` in REORG UPGRADE UNIFORM

---

spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaDetailSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaHistorySuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

Extends various existing Delta suite with coordinated commits. This helps to add more coverage with coordinated commit changes.
This is test PR.
No

[Spark] Extend coordinated commit changes to other suites

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala

Catch fatal error in error matching in commitLarge
Existing test cases pass.
No.

[DELTA] Catch fatal error in error matching in commitLarge

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingLogFileSystem.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaFormatSharingSourceSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala

Use bytes length for file size in DeltaSharingLogFileStatus, to match the actual size of the bytes in SeekableByteArrayInputStream, this is to avoid the length difference caused by non utf-8 characters.
Unit Test
No

 [Sharing]Use bytes length for file size in DeltaSharingLogFileStatus

---

storage-s3-dynamodb/src/main/java/io/delta/storage/BaseExternalLogStore.java
storage-s3-dynamodb/src/test/java/io/delta/storage/MemoryLogStore.java
storage-s3-dynamodb/src/test/scala/io/delta/storage/ExternalLogStoreSuite.scala
storage/src/main/java/io/delta/storage/LogStore.java

Resolves #3423.
This PR updates the logic in `BaseExternalLogStore::listFrom` so that it does not make a request to get the latest entry from the external store (which is used to perform recovery operations) in the event that a non `_delta_log` file is being listed.
This is useful for VACUUM operations which may do hundreds or thousands of list calls in the table directory and nested partition directories of parquet files. This is NOT the `_delta_log`. Thus, checking the external store during these list calls is (1) useless and unwanted as we are not listing the `_delta_log` so clearly now isn't the time to attempt to do a fixup, and (2) expensive.
This PR makes it so that future VACUUM operations do not perform unnecessary calls to the external store (e.g. DyanamoDB).
Unit tests and an …

[#3423] Fix unnecessary DynamoDB GET calls during LogStore::listFrom VACUUM calls

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingLogFileSystem.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaFormatSharingSourceSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala

(cherry-pick e1dd541ce99389a79e8c70dbcf9045fd5d4112a7 to branch-3.2)
Use bytes length for file size in DeltaSharingLogFileStatus, to match the actual size of the bytes in SeekableByteArrayInputStream, this is to avoid the length difference caused by non utf-8 characters.
Unit Test

[Sharing][3.2] Use bytes length for file size in DeltaSharingLogFileStatus

---

kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/ScanStateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetFileWriterSuite.scala

Resolve to `enum` as part of the `TableConfig` fetch methods. This avoids comparing strings and dealing with case sensitivity.

[Kernel][Clean up] Use enums for column mapping modes instead of strings

---

spark/src/test/scala/org/apache/spark/sql/delta/ConflictCheckerPredicateEliminationUnitSuite.scala

Update `ConflictCheckerPredicateEliminationUnitSuite` to work with Spark 4.0 where `rand()` returns an `UnresolvedFunction` instead of `Rand()` expression.
No

[Spark] Make ConflictCheckerPredicateEliminationUnitSuite work Spark 4.0

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/FieldMetadata.java
kernel/kernel-api/src/test/scala/io/delta/kernel/types/FieldMetadataSuite.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetSchemaUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetSuiteBase.scala

This adds a `get()` method to `FieldMetadata` for easier extraction of the value in the correct type and fixes https://github.com/delta-io/delta/issues/3419

[Kernel] Add get method to FieldMetadata for easier extraction of value in the correct type

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/StatisticsCollection.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/StatsCollectionUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/StatsCollectionSuite.scala

[Spark] Fix the inconsistencies in min/max Delta Log stats for special characters

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeStats.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoDVsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoMetricsBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala

Originally MERGE source materialization was lazy, and triggered when the source was used for the first time. Because of that, it couldn't be cleanly separated as a stage. Since it was changed to be eager, we can now annotate it, which should make it easier to find in Spark UI.
Merge materialize source stage is now annotated:
Unit tests validate that the new stage is present in MERGE commit metrics.
No

[Spark] Add annotation for merge materialize source stage of merge

---

spark/src/main/scala/io/delta/tables/DeltaMergeBuilder.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/SchemaValidationSuite.scala

Due to Spark unfortunate behavior of resolving plan nodes it doesn't know, the `DeltaMergeInto` plan created when using the MERGE scala API needs to be manually resolved to ensure spark doesn't interfere with its analysis.
This currently completely bypasses Spark's analysis as we then manually execute the MERGE command which has negatiev effects, e.g. the execution is not visible in QueryExecutionListener.
This change addresses this issue, by executing the plan using the Dataframe API after it's manually resolved so that the command goes through the regular code path.
Resolves https://github.com/delta-io/delta/issues/1521
Covered by existing tests.

[Spark] Execute MERGE using Dataframe API in Scala

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/FileMetadataMaterializationTracker.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/TransactionExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillBatch.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillBatchStats.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillCommandStats.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillBatch.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/PhaseLockingTransactionExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaUsageLogsOpsTypes.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingBackfillSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowtracking/RowTrackingConflictResolutionSuite.scala

Adding the [RowTrackingBackfillCommand](https://docs.google.com/document/d/1ji3zIWURSz_qugpRHjIV_2BUZPVKxYMiEFaDORt_ULA/edit#heading=h.8al9qhd83yov), the ability to assign row IDs to table rows after the table creation.
Added UTs.
No.

[Spark] Add RowTrackingBackfillCommand

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala

The existing conversion logic used toLocalIterator which will spawn many Spark jobs to collect AddFiles to the driver based on default spark partition size. Mostly the default size is not good and thus conversion and commit to Iceberg will be bottlenecked.
The PR used repartition to size the partition properly to avoid the bottleneck.
manually tested on a 5M files table. performance improved from tens of minutes to 5 minutes.

Use correct partition/batch size for Delta Uniform iceberg conversion

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowtracking/RowTrackingConflictResolutionSuite.scala

`RowTrackingBackfill` (or backfill for short) is a special operation that materializes and recommits all existing files in table using one or several commits to ensure that every AddFile has a base row ID and default Row Commit Version.
In this PR, we add a new rule to `ConflictChecker` that resolve concurrent conflicts involving Backfill. We check that RowTrackingBackfill is not resurrecting files that were removed concurrently and that an AddFile and its corresponding RemoveFile have the same base row ID and default RCV. We also add logic to skip certain concurrency checks if it involves Backfill.
This opens up a lot of interesting Conflict Resolutions cases to test, so we will add more UTs revolving conflict checking/resolutions between Backfill and other operations with different …

[Spark] Add Row Tracking Backfill Conflict Checker RemoveFile rule

---

spark/src/main/scala/org/apache/spark/sql/delta/IdentityColumn.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/RestoreTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnTestUtils.scala

This PR is part of https://github.com/delta-io/delta/issues/1959 .
It adds support for clone and restore tables with identity columns.
Clone and restore related test cases.
Users will be able to call clone and restore on tables with identity columns.

[Spark] Support clone and restore for Identity Columns

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSQLSuite.scala

populate clone override table properties to catalog, which is missed in the current impl
UT

[Spark] populate Delta clone override table properties to catalog

---

spark-connect/server/src/test/scala-spark-master/io/delta/connect/DeltaConnectPlannerSuite.scala

Fixes `DeltaConnectPlannerSuite` by replacing `SessionHolder.forTesting` with a copy of `createDummySessionHolder`, as this method got moved in the Spark master branch: https://github.com/apache/spark/commit/acb2fecb8c174fa4e2f23c843a904161151c8dfa
Fixes test.
No.

[Spark] Fix DeltaConnectPlannerSuite by copying the moved createDummySessionHolder

---

storage-s3-dynamodb/src/main/java/io/delta/storage/BaseExternalLogStore.java
storage-s3-dynamodb/src/test/java/io/delta/storage/MemoryLogStore.java
storage-s3-dynamodb/src/test/scala/io/delta/storage/ExternalLogStoreSuite.scala

Cherry-pick 03bdf8476c3e4f76d9a2d26592b7fd638736f57a to branch 3.0
Resolves #3423.
This PR updates the logic in `BaseExternalLogStore::listFrom` so that it does not make a request to get the latest entry from the external store (which is used to perform recovery operations) in the event that a non `_delta_log` file is being listed.
This is useful for VACUUM operations which may do hundreds or thousands of list calls in the table directory and nested partition directories of parquet files. This is NOT the `_delta_log`. Thus, checking the external store during these list calls is (1) useless and unwanted as we are not listing the `_delta_log` so clearly now isn't the time to attempt to do a fixup, and (2) expensive.
This PR makes it so that future VACUUM operations do not perform …

[3.0 Cherry Pick] [#3423] Fix unnecessary DynamoDB GET calls during LogStore::listFrom VACUUM calls

---

storage-s3-dynamodb/src/main/java/io/delta/storage/BaseExternalLogStore.java
storage-s3-dynamodb/src/test/java/io/delta/storage/MemoryLogStore.java
storage-s3-dynamodb/src/test/scala/io/delta/storage/ExternalLogStoreSuite.scala

Cherry-pick 03bdf8476c3e4f76d9a2d26592b7fd638736f57a to branch 3.1
Resolves #3423.
This PR updates the logic in `BaseExternalLogStore::listFrom` so that it does not make a request to get the latest entry from the external store (which is used to perform recovery operations) in the event that a non `_delta_log` file is being listed.
This is useful for VACUUM operations which may do hundreds or thousands of list calls in the table directory and nested partition directories of parquet files. This is NOT the `_delta_log`. Thus, checking the external store during these list calls is (1) useless and unwanted as we are not listing the `_delta_log` so clearly now isn't the time to attempt to do a fixup, and (2) expensive.
This PR makes it so that future VACUUM operations do not perform …

[3.1 Cherry Pick] [#3423] Fix unnecessary DynamoDB GET calls during LogStore::listFrom VACUUM calls

---

storage-s3-dynamodb/src/main/java/io/delta/storage/BaseExternalLogStore.java
storage-s3-dynamodb/src/test/java/io/delta/storage/MemoryLogStore.java
storage-s3-dynamodb/src/test/scala/io/delta/storage/ExternalLogStoreSuite.scala

Cherry-pick 03bdf8476c3e4f76d9a2d26592b7fd638736f57a to branch 3.2
Resolves #3423.
This PR updates the logic in `BaseExternalLogStore::listFrom` so that it does not make a request to get the latest entry from the external store (which is used to perform recovery operations) in the event that a non `_delta_log` file is being listed.
This is useful for VACUUM operations which may do hundreds or thousands of list calls in the table directory and nested partition directories of parquet files. This is NOT the `_delta_log`. Thus, checking the external store during these list calls is (1) useless and unwanted as we are not listing the `_delta_log` so clearly now isn't the time to attempt to do a fixup, and (2) expensive.
This PR makes it so that future VACUUM operations do not perform …

[3.2 Cherry Pick] [#3423] Fix unnecessary DynamoDB GET calls during LogStore::listFrom VACUUM calls

---

iceberg/src/test/scala/org/apache/spark/sql/delta/uniform/UniFormE2ESuite.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaReorgTableCommand.scala

currently we utilize the helper function
`shouldRewriteToBeIcebergCompatible` to filter the portion of parquet files that need to be rewritten when running `REORG UPGRADE UNIFORM` based on the tags in the `AddFile`.
however, the `DeltaUpgradeUniformOperation.icebergCompatVersion` is accidentally shadowed, which will make
`shouldRewriteToBeIcebergCompatible` always return `false` if the `AddFile.tags` is not `null` - this is not the expected semantic of this function.
this PR introduces the fix for this problem and add unit tests to ensure the correctness.
through unit tests in `UniFormE2ESuite.scala`.
no.

[Spark][Backport 3.2] Fix the semantic of `shouldRewriteToBeIcebergCompatible` in REORG UPGRADE UNIFORM

---

.github/workflows/spark_test.yaml

Cherry-pick #3302
... enforced by the `pip` from `24.1`
Recent `delta-spark` [CI
jobs](https://github.com/delta-io/delta/actions/runs/9628486756/job/26556785657) are failing with the following error.
```
ERROR: Invalid requirement: 'delta-spark==3.3.0-SNAPSHOT': Expected end or semicolon (after version specifier)
delta-spark==3.3.0-SNAPSHOT
~~~~~~~^
```
Earlier
[runs](https://github.com/delta-io/delta/actions/runs/9526169441/job/26261227425) had the following warning
```
DEPRECATION: delta-spark 3.3.0-SNAPSHOT has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of delta-spark or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at …
```

[Spark] Pin the `pip` version to `24.0` to get around the version format requirement 

---

spark/src/main/scala/org/apache/spark/sql/delta/NumRecordsStats.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeleteCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/UpdateCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/WriteIntoDelta.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeStats.scala

Extend `delta.dml.{merge, update, delete}.stats` metrics with the following fields:
- `commitVersion` The commit version of the DML version. This allows associating DML metrics with commit metrics and distinguishing DML operations that did not commit.
- `numLogicalRecordsAdded` and `numLogicalRecordsRemoved`: The number of logical records in AddFile and RemoveFile actions to be committed. These metrics can be compared to the row-level metrics emitted by the DML operations.
Finally, this commit adds the `isWriteCommand` field in DELETE metrics to distinguish DELETE operations that are performed in the context of WRITE commands that selectively overwrite data.
Log-only changes. Existing tests.
No

[Spark] Add commit version and logical records in Delta DML metrics

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CommitCoordinatorClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUsageLogs.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala

Snapshot construction will now be allowed even if the table has a configured coordinator but the coordinator implementation has not been registered. Writes will still be blocked in such cases.
The change has been gated behind a new flag.
Added a new test in CoordinatedCommitsSuite.
No

[Spark] Allow stale reads when commit coordinator has not been registered

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaCommitTag.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingBackfillSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowtracking/RowTrackingConflictResolutionSuite.scala

Introducing a new `DeltaCommitTag` which allows ALTER TABLE commands that do row tracking enablement only not to fail concurrent transactions if they do not do metadata update. This is a special case of metadata update conflict that we can safely resolve.
Added UTs.
No.

[Spark] Allowing Row Tracking enablement only txn to not fail concurrent no metadata update txns

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/lang/ListUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/TableCommitCoordinatorClientHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/CoordinatedCommitsUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/FileNames.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/coordinatedcommits/CoordinatedCommitsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/coordinatedcommits/CoordinatedCommitsTestUtils.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/coordinatedcommits/InMemoryCommitCoordinatorBuilder.scala
storage/src/test/scala/io/delta/storage/commit/InMemoryCommitCoordinator.scala

Update the Kernel read with coordinated commit support and prepare for kernel coordinated commit write support.
Unit tests
Yes. Users can enable coordinated commit read support by configuring its properties.

[Kernel] Update the Kernel read with coordinated commit support

---

spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/FileNames.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala

This PR updates the comparison (equals) method of LogSegments to consider coordinated commits. The reason for this change is as follows: The current comparison logic determines whether a LogSegment is equal to another LogSegment, if the deltas match and the modification time of the last delta is equal for both LogSegments. However, on a coordinated commits table, this may not be true anymore. This is because after a commit, we update the LogSegment by appending the last commit to it to create the post commit snapshot. In a coordinated commits table, this will be a UUID commit. However, by the next time DeltaLog.update is called, that UUID commit could have already been backfilled and so the LogSegment determined as part of the update call will contain the backfilled commit, which will …

[Spark] Makes LogSegment comparison aware of coordinated commits

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFileWriter.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetFileWriterSuite.scala

Currently, the default Parquet writer returnes `numRows` statistics only if one or more column statistics are requested. This changes to always return the `numRows` in `DataFileStatus`. It is easy to compute the number of rows written without reading the Parquet footer. Reading parquet footer is needed for finding the column stats for written file.
The `numRows` stat is needed for supporting writing into Uniform enabled tables.
Modify existing tests.

[Kernel][Default Parquet Writer] Always return the row count in returned file statistics

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaDataSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala

Column mapping metadata should be pruned during a streaming read, just like that of batch read.
New UT.
No

Do not leak column mapping metadata during streaming read 

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/TransactionStateRow.java
kernel/kernel-api/src/test/scala/io/delta/kernel/TransactionSuite.scala

When `icebergCompatV2` is enabled, include the partition columns in the physical data that are going to be written in the data files. `Transaction.transformLogicalData` takes care of converting the table logical data into physical data that should go into the Parquet files. One of the transformations done is removing the partition columns that are not required to be in data files for Delta. `icebergCompatV2` requires partition columns to be in data files. Update `Transaction.transformLogicalData` so that partition columns are not removed from physical data if the table has `icebergCompatV2` enabled.
Unit tests

[Kernel][IcebergCompatV2] Include partition columns in physical data written to files

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/IcebergCompatV2Utils.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/DataFileStatistics.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/DataFileStatus.java
kernel/kernel-api/src/test/scala/io/delta/kernel/TransactionSuite.scala

Delta [IcebergCompatV2](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#iceberg-compatibility-v2) requires each `add` action added to the Delta Log contain `numRecords` in statistics. This PR adds the change to enforce the check as part of `Transaction.generateAppendActions`. 
Unit tests.

[Kernel][IcebergCompatV2] Validate `add` actions have `numRecords` in statistics

---

.github/workflows/spark_master_test.yaml
.github/workflows/spark_test.yaml
build.sbt
project/TestParallelization.scala
run-tests.py

This change adds a matrix of 3 shards to github CI for the delta spark/spark master tests and plumbs those through to our parallelization strategy which will then select tests to run if they are assigned to that shard. This brings down CI times from ~4 hours to 2 hours.
3 shards seemsd to be the point of diminishing returns, and we should look at the actual tests and possibly higher instance types if we really want to get those down further.
No sharding: 4 hours
2 shards: 3 hours
3 shards:  ~2 hours
4 shards: ~2 hours
To undo this change without a full revert commit there are a few ways (in order of recommendation)
1. Remove/comment out *both* 
the shard row in the GH matrix https://github.com/delta-io/delta/pull/3517/files#diff-b77047dc65c62d814f7f67eec57c23c4cf9d9796e6a8a018558e0e935739d …

Infra: Shard spark and spark master tests across 3 actions

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/IdentityColumn.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnConflictSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionTestMixin.scala

This PR is part of https://github.com/delta-io/delta/issues/1959.
The PR relaxes metadata conflict for identity column SYNC high water mark operation. When winning transaction contains identity column metadata change and the current transaction does not contain metadata change, we mark the current transaction as no metadata conflict.
A new test suite.
No.

[SPARK] Relax metadata conflict for identity column

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActionsIterator.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CheckpointV2ReadSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/PartitionPruningSuite.scala

The sidecar actions in the checkpoint manifest of a CPV2 table should always be read regardless of the checkpoint predicate, as actions satisfying the predicate may be found in the sidecar file.
See added test.
No.

[Kernel] Always read the checkpoint manifest for CPV2 if sidecar files are present

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/test/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillConflictsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionTestMixin.scala

Add extensive testing that checks various scenario of conflict scenarios between Backfill and other concurrent transactions.
Note: We have not yet covered the case of conflicts between Row Tracking Backfill and Clone, and also the case of multiple Row Tracking Backfills, which will be added in follow-up PRs.
Added UTs.
No.

[Spark] Add RowTrackingBackfillConflictsSuite

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala

Fix time travel utility method for ICT.
DeltaHistoryManager modified the in-commit-timestamp to custom values for testing specific scenarios. This is done by getting the delta file from the snapshot's logsegment and modifying its content.
Sometimes the Snapshot might be pointing to UUID files - in such cases we should also modify the timestamp in backfilled commit.json file.
Existing UTs
No

[Spark] Fix time travel utility method for ICT

---

spark/src/test/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillBackfillConflictsSuite.scala

Add `RowTrackingBackfillBackfillConflictsSuite` with test cases for concurrent backfills.
Added UTs.
No.

[Spark] Add RowTrackingBackfillBackfillConflictsSuite

---

spark/src/test/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillCloneConflictsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionTestMixin.scala

Add some `RowTrackingBackfill` and Clone conflicts tests.
Added UTs.
No.

[Spark] Add RowTrackingBackfill and Clone conflicts tests

---

python/run-tests.py

Python tests are specific to Spark Delta, so there is no need to publish everything.
```
is_testing_spark_group = args.group is None or args.group == "spark"
is_testing_scala_212 = scala_version is None or scala_version.startswith("2.12")
if is_testing_spark_group and is_testing_scala_212:
run_python_tests(root_dir)
```
Unit Tests
No

[Spark] CI - Publish Spark Group only during Python tests

---

Dockerfile

Later versions of pip doesn't allow installing python packages with "-" in the name but we use version with "-SNAPSHOT" in it. Instead fix the pip version to 24.0.
Copied from our other CI.

[INFRA] Fix the pip version in the dockerfile as well to accomodate for versions with "-" in it 

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetSchemaUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetSchemaUtilsSuite.scala

(stacked on top of #3504, see the latest commit)
Add validation of field IDs in the given schema of data before writing to the Parquet files.
UTs

[Kernel][Defaults] Add field id validation when writing data to Parquet files

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsEnablementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

1. Moves the checks for Coordinated Commits configurations for CLONE early to `CreateDeltaTableCommand.scala`. This also affects CREATE and REPLACE code paths; the same checks are placed on all three commands.
2. Modified the precedence of Coordinated Commits configurations for CLONE. Now for existing tables, it blocks Coordinated Commits overrides completely, even if the existing table had no commit coordinator before. We want the users to upgrade a table with Coordinated Commits only with ALTER command, and not piggyback in other commands like CLONE.
4. Updated the error messages to better reflect the exceptions.
5. Added UTs and modified existing UTs for the new logic.
UTs.
No.

[Delta] Centralize checks for coordinated commits property via different code paths

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaUDF.scala

This Spark commit https://github.com/apache/spark/commit/67d2888c476b6c472722f9cfebfb2e99302aff1c breaks Spark master compilation (specifically [this diff](https://github.com/apache/spark/commit/67d2888c476b6c472722f9cfebfb2e99302aff1c#diff-7852549cf1376f95414d804c8a9382a236179582cb4f03f836c284b0c1a81191L93-R99)).

[Spark] Use `encoderFor` to copy encoders for DeltaUDF

---

spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CommitCoordinatorClient.scala

In commit coordinator registration, we use the same variable name from the method and case use case which are bad practice. This PR simply fixes it.
Simple variable renaming change + existing unit tests will cover them
No

[Spark] Do not use the same variable name in the coordinator registration code

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

Enable Row Tracking Backfill by default in Delta, after we extensively added the test coverage.
Existing UTs.
No.

[Spark] Enable Row Tracking Backfill by default in Delta

---

spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnTestUtils.scala

This PR is part of https://github.com/delta-io/delta/issues/1959 .
The change refactors `IdentityColumnTestUtils` to reuse `createTableWithIdColAndIntValueCol` to create tables and to unify the column names in identity column tests.
This is test only change.
No.

[SPARK] Refactor IdentityColumnTestUtils

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala

The current randomly assigned physical names do not match with anything in parquet file in source iceberg table, and caused it cannot convert type widened iceberg tables; 
manually tested the fix to convert a type widened iceberg table.

use logical column name as physical name for Iceberg clone source tables

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/ColumnWithDefaultExprUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/GeneratedColumn.scala
spark/src/main/scala/org/apache/spark/sql/delta/IdentityColumn.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeleteCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/UpdateCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/WriteIntoDelta.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/InsertOnlyMergeExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/GenerateSymlinkManifest.scala
spark/src/main/scala/org/apache/spark/sql/delta/optimizablePartitionExpressions.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/MultiDimClusteringFunctions.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/StatisticsCollection.scala
spark/src/test/scala/org/apache/spark/sql/delta/AutoCompactSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/ConflictCheckerPredicateEliminationUnitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/EvolvabilitySuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/GenerateIdentityValuesSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/metric/IncrementMetricSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/util/BitmapAggregatorE2ESuite.scala

Spark master compilation is currently broken due to this commit in Spark
https://github.com/apache/spark/commit/a767f5cb1704075ee249169e8faf2ab3610b9dbc#diff-81eca9f7af2e9b23b13904131c3d32b0af9e9e1dcc7ddb5efba13201b00066c4 which changes the `Column` constructor. 
To fix, change any instances of `new Column(...)` to `Column(...)` so that we can use the constructors in `object Column`.

[Spark][Master] Fix compilation issues on Spark master

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableConfigSuite.scala

Resolves #3455. 
Added editable property to TableConfig. Changed TableConfig#validateProperties to check if property is editable.
Test added to `TableConfigSuite.scala`.
No.

[Kernel] Add editable property to TableConfig

---

PROTOCOL.md
spark/src/main/scala/org/apache/spark/sql/delta/files/DelayedCommitProtocol.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/DeltaFileFormatWriter.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/PartitionUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/TimestampFormatter.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoTableSuite.scala

- [ X] Spark
Currently, in the Delta Protocol, timestamps are not stored with their time zone. This leads to unexpected behavior when querying across systems with different timezones configured (e.g. different spark sessions for instance). For instance in Spark, the timestamp value will be adjusted to spark session time zone and written to the delta log partition values without TZ. If someone were to query the same "timestamp" from a different session timezone,  the same time zone value it can fail to surface results due to partition pruning.
What this change proposes to the delta lake protocol is to allow timestamp partition values to be adjusted to UTC and explicitly stored in partition values with a UTC suffix. The original approach is still supported for compatibility but it is …

[Protocol, Spark] UTC normalize timestamp partition values

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingUtils.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaFormatSharingSourceSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/TestClientForDeltaFormatSharing.scala

Add timestamp_ntz to Delta Sharing reader feature header.
Unit test

[Sharing] Add timestamp_ntz to Delta Sharing reader feature header

---

spark/src/main/scala/io/delta/tables/DeltaMergeBuilder.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/SchemaValidationSuite.scala

(cherrypick of #3456)
Due to Spark unfortunate behavior of resolving plan nodes it doesn't know, the `DeltaMergeInto` plan created when using the MERGE scala API needs to be manually resolved to ensure spark doesn't interfere with its analysis.
This currently completely bypasses Spark's analysis as we then manually execute the MERGE command which has negatiev effects, e.g. the execution is not visible in QueryExecutionListener.
This change addresses this issue, by executing the plan using the Dataframe API after it's manually resolved so that the command goes through the regular code path.
Resolves https://github.com/delta-io/delta/issues/1521 Covered by existing tests.

[3.2][Spark] Execute MERGE using Dataframe API in Scala

---

python/delta/tests/test_deltatable.py
spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSuite.scala

`DeltaOptions` are equipped to accept case-insensitive values of boolean flags, but CDCReader was not, resulting in not-accepting 'True'. Make it case insensitive. 
A separate bug in Spark Connect was causing "True" to be passed from Python boolean True. That is being fixed by https://github.com/apache/spark/pull/47790
Tests added.
Datasource option to enable CDC should now accept "True" and other mixed-case variants and not only "true".

[Spark] CDC reader accept case insensitive Boolean option values

---

spark/src/test/scala/org/apache/spark/sql/delta/DeleteSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/UpdateSuiteBase.scala

The paths of partitioned tables contain the partition values in escaped form that follows the Hive-style partitioning. This PR introduces a basic test for DML operations on such tables.
Test-only PR.
No

[Spark] Add tests for DML commands on partitioned tables with special chars

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableUtils.scala
spark/src/test/scala-spark-master/org/apache/spark/sql/delta/DeltaVariantSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

Today when either the clustering column data type is unsupported for data skipping or clustering column is not in the first 32 columns, it shows the following message
[DELTA_CLUSTERING_COLUMN_MISSING_STATS] Liquid clustering requires clustering columns to have stats. Couldn't find clustering column(s) 'current_version' in stats schema:
This is confusing to users when the column data type is not supported for data skipping. To improve this scenario this PR introduces a new error class DELTA_CLUSTERING_COLUMNS_NOT_SUPPORTED_DATATYPE  when cluster by non data skipping data type such as cluster by Boolean column

[Spark] Improve missing stats column message for unsupported data skipping types

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

This PR is part of https://github.com/delta-io/delta/issues/1959 .
We have implemented identity column support and all the tests passed. We now can move identity column feature out of developer mode.
Existent tests.
No.

[SPARK] Move identity column feature out of dev mode

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala

Today, `DeltaCatalog` takes care of the Spark CREATE TABLE command and calls `CreateDeltaTableCommand#run` at the end. Within this command, `spark.sessionState.catalog.createTable` is called, which bypasses any custom catalog that overwrites `spark_catalog`. `DeltaCatalog` always creates tables in the Hive Metastore.
This PR fixes this issue by calling the Spark catalog plugin API to create the table, to respect custom catalog that overwrites `spark_catalog`, such as Unity Catalog.
Locally tested it with Spark + Unity Catalog.
no

[3.2] invoke Spark catalog plugin API to create tables

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
spark/src/test/scala/org/apache/spark/sql/delta/uniform/UniFormE2ESuite.scala

Now for newly disabling delta uniform iceberg tables, it would always convert all delta metadata into a newly created iceberg table. 
This is for newly enabling uniform table to start a new history line for iceberg metadata so that if a uniform table is corrupted, user can unset and re-enable to unblock.
Add UTs

[Delta Uniform] Enforce newly enabled iceberg converter to create a new iceberg table

---

build.sbt

Adds Jackson as a general purpose JSON parsing library into the Kernel-Api jar. The library is shaded to avoid version dependency conflicts downstream for connector developers. 
Ran existing tests.

[Kernel] Shade`jackson` into Kernel-Api for internal JSON operations 

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/test/scala/org/apache/spark/sql/delta/CustomCatalogSuite.scala

`DeltaTableV2` uses the options to create `DeltaLog`, assuming that the options should always be consistent with the one in `CatalogTable#storage#properties`. This may not be true as custom catalogs may add more table storage properties on the fly, like Unity Catalog.
Tested locally with UC. It's not an issue for HMS.
no

always include CatalogTable#storage#properties into data source options

---

build.sbt
connectors/flink/src/main/scala/io/delta/flink/internal/KernelSnapshotWrapper.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/MultiThreadedTableReader.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/utils/RowSerDe.java
kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java
kernel/kernel-api/src/main/java/io/delta/kernel/engine/JsonHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Metadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/ScanStateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/TransactionStateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/types/DataTypeJsonSerDe.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/ArrayType.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/BasePrimitiveType.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/DataType.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/DecimalType.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/FieldMetadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/MapType.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/StructField.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/StructType.java
kernel/kernel-api/src/test/scala/io/delta/kernel/TransactionSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/types/DataTypeJsonSerDeSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockEngineUtils.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultJsonHandler.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplaySuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala

Given now Kernel-API module contains Jackson libs:
1) Remove `JsonHandler.deserializeStructType` and its usages
2) Rename `DataTypeParser` to `DataTypeJSONSerDe` (similarly the test suite)
3) Add `StructType` serialization utilities to `DataTypeJSONSerDe`
Unit tests
For connectors that implement custom `JsonHandler`, don't need to implement `deserializeStructType` API.

[Kernel] Remove `JsonHandler.deserializeStructType` and add `DataType` JSON SerDe in API module

---

spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

Updates `TrackingInMemoryCommitCoordinatorBuilder` so that the class user can now override the name of the coordinator returned by this builder. This will be useful when the `defaultCommitCoordinatorClientOpt` is defined and is different from the "in-memory" coordinator.
Test-only change
No

[Spark][Test-Only] Allow override of the name of the tracked commit coordinator

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/test/scala/org/apache/spark/sql/delta/CustomCatalogSuite.scala

backport https://github.com/delta-io/delta/pull/3536 . It's a clean cherry-pick
`DeltaTableV2` uses the options to create `DeltaLog`, assuming that the options should always be consistent with the one in `CatalogTable#storage#properties`. This may not be true as custom catalogs may add more table storage properties on the fly, like Unity Catalog.
Tested locally with UC. It's not an issue for HMS.
no

[3.2] always include CatalogTable#storage#properties into data source options

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala

Changed string comparing from UTF16 to UTF8. This fixes comparison issues around the characters with surrogate pairs.
Tests added to `DefaultExpressionEvaluatorSuite.scala`

[Kernel] Change string comparing from UTF16 to UTF8

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala

Uniform iceberg conversion transaction should not convert commit with only AddFiles without datachange. Otherwise it will result in duplicate AddFile in Iceberg.
Manual tested with Spark; UT will be added in future PR.

Uniform iceberg conversion transaction should not convert commit with only AddFiles without datachange

---

.github/workflows/spark_python_test.yaml
run-tests.py

Separate out delta-spark python tests to their own GitHub CI
CI tests
No

[Infra] Separate out delta-spark python tests

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala

Guard the iceberg metadata for Vacuum only when uniform is enabled on table
UTs

[Delta Uniform] Delete Iceberg Metadata when Vacuum

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala

Uniform iceberg conversion transaction should not convert commit with only AddFiles without datachange. Otherwise it will result in duplicate AddFile in Iceberg.

Uniform iceberg conversion transaction should not convert commit with only AddFiles without datachange - 3.1

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala

Uniform iceberg conversion transaction should not convert commit with only AddFiles without datachange. Otherwise it will result in duplicate AddFile in Iceberg.

Uniform iceberg conversion transaction should not convert commit with only AddFiles without datachange  - 3.2

---

spark/src/main/resources/error/delta-error-classes.json

[Spark] Fix wordings and sqlState for DELTA_CLUSTERING_COLUMNS_DATATYPE_NOT_SUPPORTED

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/test/scala/org/apache/spark/sql/delta/TightBoundsSuite.scala

Check `DeletionVectorFilesHaveWideBoundsCheck` has been disabled for COMPUTE STATS because it reintroduces stats with tight bound to files with Deletion Vectors. However, there are other operations that can then copy over these AddFile actions with DVs and tight stats. These operations resulted in DELTA_ADDING_DELETION_VECTORS_WITH_TIGHT_BOUNDS_DISALLOWED error, which was a false positive.
In this PR we also attempt to introduce and discuss a "framework" for checks like that as a property of DeltaOperations, with DeltaOperations declaring as a member method whether a certain property and check should be performed. This is opposed to current practice, where many places in the code feature special cases like matching against a certain DeltaOperation and doing something special; this kind of …

[Spark] Fix stats with tightBounds check for AddFiles with deletionVectors

---

spark/src/test/scala/org/apache/spark/sql/delta/ConvertToDeltaSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/HiveConvertToDeltaSuite.scala

Enable injection of special chars in temporary directories in two tests in ConvertToDeltaSuite. The previous issues have been resolved in 90c1b2a26a86ce0c16e8218ec4188c81b9f7a21c.
No

[Spark] Update tests in ConvertToDeltaSuite
