delta-io/delta

spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala

This PR extends the vacuum suite to run with coordinated commits configs. This will help vacuum related code to have a better coverage with coordinated commits.
This is a test PR.
No

[Spark] Extends Vacuum Suite with Coordinated Commits

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsEnablementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtilsSuite.scala

1. Blocks ALTER TABLE command from setting Coordinated Commits properties if the table already had them. If the table did not have them, checks that the CC property overrides contains exactly Coordinator Name and Coordinator Conf, no Table Conf.
2. Blocks ALTER TABLE command from unsetting Coordinated Commits properties if the table already has them.
3. Added UTs for both cases. Moved the UT to a new suite `CoordinatedCommitsUtilsSuite.scala`.
4. Renamed some methods for clarity.
UTs.
No.

[Delta] Block alter command from overriding or unsetting coordinated commits properties

---

.github/workflows/connectors_test.yaml
.github/workflows/kernel_test.yaml
.github/workflows/spark_examples_test.yaml
.github/workflows/spark_master_test.yaml
.github/workflows/spark_python_test.yaml
.github/workflows/spark_test.yaml
.github/workflows/unidoc.yaml

I'd like to do some data science using the GitHub REST API on our PR runtimes.
Unfortunately, using the GitHub CHECKs API (https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#list-check-runs-for-a-git-reference), I only get the name of the individual job. Getting the name of the parent workflow requires an additional API call.
This is because our job names are the default job names right now for most of our GitHub workflows. This doesn't give us any info as to which workflow it is for. For example, today I'd get result `test (2.13.13, 0)` but I am unable to determine if this is for Delta Spark Latest or Delta Spark Master.
This PR updates the workflow job name to include the workflow name so now we can uniquely identify the jobs.
CI tests.
No

[Infra] Include GitHub workflow name in each task

---

connectors/standalone/src/main/scala/io/delta/standalone/internal/Checkpoints.scala
connectors/standalone/src/main/scala/io/delta/standalone/internal/SnapshotImpl.scala

This PR
- adds better logging throughout Delta Standalone (improves debuggability)
- fixes an issue in the Delta Standalone Checkpoint code path where we would incorrectly close an incomplete checkpoint upon error
Existing UTs + tested and verified locally
No

[Standalone] Safer checkpointing and better logging

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaLogActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddCDCFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/CommitInfo.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TableChangesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/coordinatedcommits/CoordinatedCommitsTestUtils.scala

https://github.com/delta-io/delta/pull/3531 added support for reading the add and remove file actions using the LogImpl::getChangesByVersion API. This PR adds support for additional actions metadata, protocol, commitInfo and cdc.

[KERNEL] Additional Delta action support (Metadata, Protocol, CommitInfo and AddCDCFile) for LogImpl::getChangesByVersion

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSink.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSinkImplicitCastSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningStreamingSinkSuite.scala

This change introduces automatic type widening during schema evolution in the Delta streaming sink.
Conditions for type widening to trigger:
- Type widening is enabled on the Delta table
- Schema evolution (`mergeSchema`) is enabled on the sink
- The data written to the sink uses a type that is strictly wider than the current type in the table schema, and moving from the narrower to the wider type is eligible for type widening - see `TypeWidening.isTypeChangeSupportedForSchemaEvolution`
When all conditions are satisfied, the table schema is updated to use the wider type before ingesting the data.
Added test suite `TypeWideningStreamingSinkSuite` covering type widening in the Delta streaming sink
This builds on the user-facing change introduced in …

[Spark] Automatic type widening in Delta streaming sink

---

spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/ClusteredTableTestUtils.scala

This PR extends the incremental clustering suite to run with coordinated commits configs. This will help clustering related code to have a better coverage with coordinated commits.
This is a test PR.
No

[Spark] Extends IncrementalClustering Suite with Coordinated Commits

---

sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingTestSparkUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaDDLUsingPathSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolTransitionsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/GeneratedColumnSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/RestoreTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/InvariantEnforcementSuite.scala

Currently enabling legacy features on legacy protocols with metadata properties results to enabling all preceding legacy features. For example, enabling enableChangeDataFeed results to protocol (1, 4). This is inconsistent with the rest protocol operations. In this PR, we fix this inconsistency by always enabling only the requested feature. This is a behavioral change.
Existing and new unit tests.
Yes. When enabling a feature using a table property, e.g. by setting `delta.enableChangeDataFeed` to `true`, then in the previous situation you would typically get protocol `(1, 4)`. Now you would get `(1, 7, changeDataFeed)`. The user can get `(1, 4)` by also asking for `delta.minWriterVersion = 4`. This change is OK now because (a) enabling fewer features is safer than enabling more features, …

[Spark] Only enable a single legacy feature with legacy metadata properties

---

spark/src/test/scala/org/apache/spark/sql/delta/GeneratedColumnSuite.scala

Small test fix, follow up from https://github.com/delta-io/delta/pull/3601
The test contains an overflow and fails when running with ANSI_MODE enabled.
Test-only

[Spark] Fix overflow in GeneratedColumnSuite

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaHistoryManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/DeltaHistoryManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableImplSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockFileSystemClientUtils.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala

Adds the functions `getVersionBeforeOrAtTimestamp` and `getVersionAtOrAfterTimestamp` to `TableImpl` for use with the `getChangesByVersion` API to enable querying changes between two timestamps. 

[Kernel] Support beforeOrAt and atOrAfter semantics for getting a commit version from a timestamp

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala

1. Exclude default CC properties during REPLACE command. Before, all default properties are merged at some later stage of REPLACE; now, we exclude the CC ones. If an existing commit coordinator is retained, the existing ICT properties are also retained; otherwise, default ICT properties are included.
2. Added UTs.
UTs.
No.

[Delta] Exclude default coordinated commits properties during replace

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/test/scala/org/apache/spark/sql/delta/CustomCatalogSuite.scala

Even if a table has the location field, it should still be a managed table if `PROP_IS_MANAGED_LOCATION` is present in the table properties.
Note: this case won't happen with Spark integration solely. It's only an issue for third-party catalogs that delegate requests to `DeltaCatalog`, such as Unity Catalog.
new test
no

DeltaCatalog.createTable should respect PROP_IS_MANAGED_LOCATION

---

spark/src/main/scala/org/apache/spark/sql/delta/storage/dv/DeletionVectorStore.scala

We identified a potential issue with the API used to write DV to files, where the `DataOutputStream.size()` method may not return the correct file size. Our investigation revealed that `DataOutputStream` maintains its own byte count, but its `write(data)` method does not increment this counter `DataOutputStream` has multiple subclasses, which might override the counter or the `write(data)` method to update the counter correctly. We want to find out which class is being used when the issue occurs, thus this PR.
To address this, we introduced our own mechanism to track the number of bytes written, which will be used solely for logging. If there is a discrepancy between the system's reported file size and our own record, a Delta event will be triggered.
Not needed.
No.

[Spark] Report writer offset mismatch in DVStore

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaWithNewTransactionSuite.scala

OptimisticTransaction.setActive() and OptimisticTransaction.withActive() methods will fail if the active transaction is already set, even if the caller tries to set the same transaction. This commit fixes this issue and allows setting the same transaction instance.
New and existing tests.
No

[Spark] Allow setting the same active Delta transaction

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableCreationTests.scala

Fix a number of tests in `DeltaTableCreationSuite` that were not correctly handling paths with special chars. Enable special char injection in `DeltaTableCreationIdColumnMappingSuite` and `DeltaTableCreationNameColumnMappingSuite` suites.
Test-only PR.
No.

[Spark] Fix path handling in DeltaTableCreationSuite

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/test/scala/org/apache/spark/sql/delta/CustomCatalogSuite.scala

Even if a table has the location field, it should still be a managed
table if `PROP_IS_MANAGED_LOCATION` is present in the table properties.
Note: this case won't happen with Spark integration solely. It's only an
issue for third-party catalogs that delegate requests to `DeltaCatalog`,
such as Unity Catalog.
new test
no

[3.2] DeltaCatalog.createTable should respect PROP_IS_MANAGED_LOCATION

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaLogActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TableChangesSuite.scala

To avoid reading invalid tables, Kernel should check that any read protocol actions are supported by Kernel. This PR makes the current API private, and adds a public API around it that does this check when the `Protocol` is included in the list of actions to be read from the file.
Also removes the "byVersion" part of the API name since we are adding separate timestamp APIs in https://github.com/delta-io/delta/pull/3650.

[Kernel] Adds protocol checks to the public getChanges API on TableImpl

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala

1. Blocks ALTER TABLE command unsetting or disabling ICT properties, which is a dependency for Coordinated Commits. Scenarios to block:
a) Table had CC enabled -- `ALTER TABLE t SET TBLPROPERTIES ('ict' = 'xx')` -- blocked.
b) Table had CC enabled -- `ALTER TABLE t UNSET TBLPROPERTIES ('ict' = 'xx')` -- blocked.
c) Table without CC -- `ALTER TABLE t SET TBLPROPERTIES ('coordinator' = 'yy', 'ict' = 'xx')` -- blocked, because the table is about to be upgraded with CC, so ICT modification along with it is blocked as well.
2. Added UTs.
UTs.
No.

[Delta] Block ALTER from unsetting ICT property dependencies for CC

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCColumnMappingSuite.scala

This PR fixes the push down of filters into CDF. Previously this would cause a parsing exception to be thrown if the filter referenced an attribute with at least one special character in the name. This is due to having to turn the `Filter`s back into `Expression`s. We avoid this by extending `CatalystScan` instead, which avoids the `Expression` to `Filter` to `Expression` roundtrip.
Added a new test
No

[Spark] Fix for pushing down filters referencing attributes with special characters in name into CDF

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/TableFeatureSupport.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/test/scala/org/apache/spark/sql/delta/ActionSerializerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaHistorySuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingBackfillSuite.scala

This PR fixes a bug where protocol (2, 7) is not considered to support reader features. This issue could manifest in several places. For example, it would result in hiding (2, x) features in the reader features list when it was the only reader feature present. For example, Protocol(2, 7, None, Set(ColumnMapping, RowTracking).
Added new test and adapted existing tests.
No.

[Spark] Table features protocols should handle legacy reader features as reader features

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingFileIndex.scala

Tiny bit of code hygiene: Remove some redundant code from `DeltaSharingFileIndex` by invoking the existing alternate constructor for `TahoeLogFileIndex` that does the same thing.
Existing tests cover this code.
No.

[SPARK] Use better TahoeLogFileIndex constructor

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaDDLSuite.scala

This PR fixes a bug that could occur, if a table is created at the same location but under a different name and had delta.minReader/WriterVersion set explicitly as part of the table creation. Because these properties are removed from the table metadata, they will not appear as part of the table property comparison during the second table creation. As it is required for the properties to match, the second creation will fail, even though the specified properties are identical to the first one. This PR removes these two special properties from the comparison to allow table creation to succeed.
Added a unit test to assert that repeat table creation succeeds, even if minReader/WriterVersion is specified.
No

[Spark] Correctly handles protocol properties during repeat table creation

---

kernel/kernel-api/src/main/java/io/delta/kernel/engine/FileSystemClient.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/lang/ListUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/MetadataCleanup.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/FileNames.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/snapshot/MetadataCleanupSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockEngineUtils.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockFileSystemClientUtils.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultFileSystemClient.java

Add support for metadata cleanup as part of the checkpointing. Metadata cleanup removes expired Delta table log files (delta + checkpoints) according to the table log retention configuration. Any removed delta log files must not cause the table state to be inconstructible.

[Kernel] Support clean expired log

---

kernel/kernel-api/src/main/java/io/delta/kernel/data/ColumnarBatch.java

Remove `ColumnarBatch.slice` API. This API was proposed during the prototype for handling DVs, but the final implementation took a different route (basically passing a selection vector to indicate the selected rows). This is not used anywhere.

[Kernel][Cleanup] Remove unused API

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala

During commit we validate that `AddFile` actions cannot contain Deletion Vectors when DVs are not enabled for a table (table property). This restriction is incorrect for actions that update metadata of existing files, e.g. `ComputeStatistics` or `RowTrackingBackfill`. The current code skips the check for `ComputeStatistics` operation but not for other operations that perform in-place-metadata updates. The new `isInPlaceFileMetadataUpdate` method is added to Delta operations so that we can easily distinguish such operations. 
The `getAssertDeletionVectorWellFormedFunc` function is slightly refactor to be more readable.
Existing tests provide coverage.
No

Exclude metadata only updates from DV check

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala

Post merge review followup: update and fix some comments.
N/A
No.

[Spark] Followup to #3633: update some comments to checkAddFileWithDeletionVectorStatsAreNotTightBounds

---

spark/src/main/scala/org/apache/spark/sql/delta/util/DatasetRefCache.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/StateCache.scala

`DatasetRefCache` instances are currently untracked, making it hard to discard or invalidate them when no longer needed. We start to address that issue by using `StateCache` to track them, so that `Snapshot.uncache()` can clean them up -- the same way `CachedDS` instances are already tracked and cleaned up.
Existing unit tests exercise `Snapshot.uncache` path.
No

[SPARK] Use StateCache to manage DatasetRefCache instances

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/ConvertToIcebergSuite.scala
icebergShaded/iceberg_src_patches/0002-iceberg-core-must-not-delete-any-delta-data-files.patch

Uniform
This reverts commit b51b5b45595e46748339e42dbb0792e8b485a234.
disabling the cleanExpiredFiles API technically prevents removal manifests/manifest lists and users may not be running orphan file removal, so for those users manifests/manifest list may never be cleaned up. For now we can revert this patch to preserve the original behavior of just preventing data file removal so storage can be reclaimed via manifest/manifest list cleanup during uniform commits.
This reverts to cleaning up unreachable manifests/manifest lists during background commits, not really a direct user facing change.

Revert "[UNIFORM] Disable cleanup of files in expire snapshots via API"

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaDDLSuite.scala

As of today, Delta extracts write options from table properties only for CTAS (in `StagedDeltaTableV2#commitStagedChanges`), but not for CREATE TABLE. In general, this makes sense because CREATE TABLE has no data-writing but CTAS has. However, the write options can be file system configs that we should respect because CREATE TABLE needs to access Delta logs.
This PR makes Delta CREATE TABLE to follow CTAS and also extract write options from table properties.
Locally tested with Unity Catalog. It's hard to write a test in Delta because the write options are not persisted but only used during table creation.
No

DeltaCatalog#createTable should respect write options

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala

Make CTAS with replace honor column mapping when writing first set of parquet files; Otherwise the uniform table will end up with parquet files without column mapping and thus have null in query results.
manual test with CTAS.

Make CTAS with replace honor column mapping when writing first set of parquet files

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaDDLSuite.scala

As of today, Delta extracts write options from table properties only for CTAS (in `StagedDeltaTableV2#commitStagedChanges`), but not for CREATE TABLE. In general, this makes sense because CREATE TABLE has no data-writing but CTAS has. However, the write options can be file system configs that we should respect because CREATE TABLE needs to access Delta logs.
This PR makes Delta CREATE TABLE to follow CTAS and also extract write options from table properties.
Locally tested with Unity Catalog. It's hard to write a test in Delta because the write options are not persisted but only used during table creation.
No

[3.2] DeltaCatalog#createTable should respect write options (#3674)

---

build.sbt
spark/src/test/resources/log4j2_spark_master.properties

https://github.com/delta-io/delta/pull/3146 added support for spark master structured logging, but broke the test logging for delta-spark against spark 3.5. This PR fixes that.
The broken logging looked like this (https://github.com/delta-io/delta/actions/runs/10856009436/job/30129811815):
```
ERROR StatusConsoleListener Unable to locate plugin type for JsonTemplateLayout
ERROR StatusConsoleListener Unable to locate plugin for JsonTemplateLayout
ERROR StatusConsoleListener Could not create plugin of type class org.apache.logging.log4j.core.appender.FileAppender for element File: java.lang.NullPointerException
java.lang.NullPointerException
at org.apache.logging.log4j.core.config.plugins.visitors.PluginElementVisitor.findNamedNode(PluginElementVisitor.java:104)
```
GitHub CI tests.
No.

[Spark] Fix delta-spark test log4j

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala

As part of the effort to make commit coordinator client aware of the table identifier, this PR handles the code path going from the checkpoint hook to the commit coordinator client.
Ran existing unit tests
No

[Spark] Passing TableIdentifier from CheckpointHook to commit coordinator client

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoImplicitCastSuite.scala

https://github.com/delta-io/delta/pull/3443 introduced implicit casting when writing to a Delta table using a streaming query.
We are disabling this change for now as it regresses behavior when a struct field is missing in the input data. This previously succeeded, filling the missing fields with `null` but would now fail with:
```
DELTA_UPDATE_SCHEMA_MISMATCH_EXPRESSION] Cannot cast struct<name:string> to struct<name:string,age:bigint>. All nested columns must match.
```
Note: batch INSERT fails in this scenario with:
```
[DELTA_INSERT_COLUMN_ARITY_MISMATCH] Cannot write to '<table>, not enough nested fields in <struct>; target table has 3 column(s) but the inserted data has 2 column(s)
```
but since streaming write allowed this, we have to preserve that behavior.
Tests added as part of …

[Spark] Disable implicit casting in Delta streaming sink

---

spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaFileOperations.scala

`DeltaFileOperations.recursiveListDirs` calls `parallelize` without specifying the parallelism. Hence, it always uses [the number of available cores on a cluster](https://github.com/apache/spark/blob/d2e8c1cb60e34a1c7e92374c07d682aa5ca79145/core/src/main/scala/org/apache/spark/SparkContext.scala#L1003). When a cluster has many cores but `subDirs` is small, it will launch many empty tasks.
This PR makes a small change to use `subDirs.length.min(spark.sparkContext.defaultParallelism)` as the parallelism so that when `subDirs` is smaller than the number of available cores, it will not launch empty tasks.
No

Set parallelism for the parallelize job in recursiveListDirs

---

storage/src/main/java/io/delta/storage/commit/CoordinatedCommitsUtils.java

This is a simple cleanup PR for improving documentation of getCoordinatorName
1. Return an Optional<String> to indicate the method may return null if no coordinator is set
2. Rename the method from getCoordinator -> getCoordinatorName
Build
No

[Storage] Add Javadoc for CoordinatedCommitsUtils::getCoordinatorName

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaMergingUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

Improving some schema utils to allow path index into non-struct root data structures.
New UT.
No.

Genericalize schema utils to support non-struct root level access

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceCDCSupport.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckCDCAnswer.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala

Context: Currently CDCReader.changesToDF relies on DeltaHistoryManager.getCommits for getting a list of commits and their timestamps. Since DeltaHistoryManager.getCommits is not aware of InCommitTimestamps and Coordinated Commits, it will either return the wrong timestamp or no timestamp at all for certain commits. 
This PR updates CDCReader.changesToDF so that it only relies on DeltaHistoryManager.getCommits for non-ICT commits. The rest of CDCReader.changesToDF relies on the output of deltaLog.getChanges which is already Coordinated Commit-aware. The function also already extracts the `CommitInfo` for all of these commits, which we reuse to get the In-Commit Timestamp for relevant commits. Since the actions were already being read in the function, this PR does not add any additional IO. …

[Spark][ICT] Make CDCReader.changesToDF aware of InCommitTimestamps

---

sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSink.scala

This PR fixes the compilation error against the latest Spark.
Manually compiled.
No

[Spark] Fix compilation error against latest Spark master

---

spark/src/main/scala/org/apache/spark/sql/delta/GeneratedColumn.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableUpdate.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeFileIndex.scala

This PR fixes the OOM caused by SparkSession.cloneSession and TemporaryView. It replaces the reference of `Snapshot`  in `TahoeLogFileIndex` using `SnapshotDescriptor`, thus remove the reference to `SparkSession` from `TahoeLogFileIndex`.
UT
No

Remove snapshotAnalysis from TahoeLogFileIndex

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/ClusteredTableTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

1. Adds coordinated commits coverage for ClusteredTableDDLSuite. 
2. Fix CC configurations' interaction with CREATE LIKE command. Before, all three CC configurations are copied along with all other table properties from the source table; now, we filter them out, since CREATE LIKE is similar to CLONE, and we do not copy the commit coordinator from the source table during CLONE.
3. Fix CC configuration's interaction with CREATE an external table in a location with an existing table. Before, the CC configurations from the existing table and the command are compared against each other, and exceptions are thrown when they don't match; now, omitting CC configurations in the command does not error out, and the existing commit coordinator is retained, along with the ICT configuration …

[Delta] Extend ClusteredTableDDLSuite with Coordinated Commits and Fix Issues

---

.github/workflows/spark_test.yaml
project/README.md
project/TestParallelization.scala

This PR reduces delta-spark CI test runtime by 33 mins. Previously the max shard duration was 1h 46 mins, and now it is 1h 13 mins.
This PR does so by the following
0. We add an extra shard
1. I used https://github.com/delta-io/delta/pull/3694 to collect some metrics about delta-spark test runtime execution.
2. I specifically identified (a) the 50 slowest test suites and (b) the average suite duration excluding those top 50 (it was 0.71 minutes)
3. I used this information to update `TestParallelization` to do smarter test suite assignment. The logic is as follows:
- For the top 50 slowest test suites, we assign them deterministically by, in sorted descending order, assigning the suites to the shard + group (group means thread) with the lowest duration so far.
- For the remaining tests …

[Infra] [Spark] Reduce delta-spark CI test runtime by 33 mins (1h46m to 1h13m)

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala

This is a small fix that changes the `sizeCollectorInputEncoders` in `DataSkippingReader` to a `lazy val`. We are already doing this for other encoders in the codebases (e.g. see [here](https://github.com/delta-io/delta/blob/master/spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala#L106)) in order to prevent initialization failures of those encoders during JVM startup.
Existing tests are sufficient as this does make any logical changes.
No

[Spark] Makes DataSkippingReader encoders lazy to prevent initialization failures

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/io/delta/tables/DeltaTable.scala
spark/src/main/scala/io/delta/tables/execution/DeltaTableOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/test/scala/io/delta/tables/DeltaTableSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableScalaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

- Add the `isShallow` argument to the Clone Scala APIs (`clone`, `cloneAtVersion`, and `cloneAtTimestamp`).
- This enables users to be able to decide the type of clone they would like from the API call.
Added UTs.
Yes, modified the Clone Scala APIs of `DeltaTable`

[Spark] Add isShallow argument to Clone Scala APIs

---

PROTOCOL.md

Right now, the Delta protocol for Row tracking references the DomainMetadata table feature, but does not explicitly state domainMetadata as one of its required table feature like e.g. Clusteredtable.  The code in `TableFeature.scala` accurately lists domainMetadata as one of the required table feature. 
This PR amends the Protocol to accurately reflect the state of the system and the remainder of the Row tracking proposition. Row Tracking cannot require writers to write DomainMetadata if it is not listing domainMetadata as one of its required feature. This is also to be consistent with how other table features handle listing their required table features.
N/A
'No'

[Protocol] Amend Row Tracking Protocol to explicitly require domainMetadata

---

storage/src/main/java/io/delta/storage/internal/LogStoreErrors.java

Simple PR that adds `isFatal` utility that can be used in `delta-storage`
Build
No

[Spark][Kernel] Add isFatal detection to LogStoreErors

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWidening.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWideningMetadata.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningFeatureCompatibilitySuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningMetadataSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningTableFeatureSuite.scala

Using type widening on a table that contains a char/varchar column causes the following reads to fail with `DELTA_UNSUPPORTED_TYPE_CHANGE_IN_SCHEMA`:
```
CREATE TABLE t (a VARCHAR(10), b INT);
ALTER TABLE t SET TBLPROPERTIES ('delta.enableTypeWidening' = 'true');
ALTER TABLE t ALTER COLUMN b TYPE LONG;
SELECT * FROM t;
[DELTA_UNSUPPORTED_TYPE_CHANGE_IN_SCHEMA] Unable to operate on this table because an unsupported type change was applied. Field cut was changed from VARCHAR(10) to STRING`
```
Type changes are recorded in the table metadata and a check on read ensures that all type changes are supported by the current implementation as attempting to read data after an unsupported type change could lead to incorrect results.
CHAR/VARCHAR columns are sometimes stripped down to STRING …

[Spark] Fix type widening with char/varchar columns

---

spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala

Add a new `Catalog` type to be used in Spark Structured Logging within delta-spark
Build
No

[Spark] Add Catalog Type to Spark Structured Logging MDC framework for Delta

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala

Change all relevant APIs of `DeltaLog` to take in a table identifier and pass this identifier all the way to the commit coordinator. Update `OptimisticTransaction` to use the new API. 
New unit tests
No

[Spark] Pass table identifier through DeltaLog API to commit coordinator

---

spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotState.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/StatsCollectionUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala

The PR refactors `StatsCollectionUtils.computeStats`:
- Replaces parameter `dataPath` with `deltaLog`
- Replaces parameter `columnMappingMode` and `dataSchema` with `snapshot`
The old fields can be accessed from the newly added fields, so it's better to not have parameters more than necessary.
In order to achieve this, the PR adds a new parameter `protocolOpt` in the constructor of `InitialSnapshot` to make the `statsSchema` derived from the snapshot consistent with the desired protocol rather than the default protocol computed from the metadata in the snapshot. 
We also changed the name `InitialSnapshot` to `DummySnapshot` to fit its semantics more.
It's a refactor change. Existing tests should cover this.
No.

[SPARK] Refactor StatsCollectionUtils.computeStats

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaEncoders.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala

This PR implements the logic of Lite Vacuum. Since the user surface is not defined yet, all of the code is behind a spark conf which is set to false by default.
Modified existing tests to run in both Lite and full mode. Additionally, added new tests cases specific to Lite vacuum.
NO

Implementation for Lite Vacuum without parser changes

---

spark/src/main/java/io/delta/dynamodbcommitcoordinator/DynamoDBCommitCoordinatorClient.java
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/AbstractBatchBackfillingCommitCoordinatorClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala
storage/src/main/java/io/delta/storage/commit/CoordinatedCommitsUtils.java
storage/src/test/scala/io/delta/storage/commit/InMemoryCommitCoordinator.scala

This PR fixes the coordinated commits utils to not write UUID-based commit files with put-if-absent semantics. This is not necessary because we assume that UUID-based commit files are globally unique so we will never have concurrent writers attempting to write the same commit file.
DynamoDBCommitCoordinator also now uses the utils for writing backfilled files.
Existing tests are sufficient as this only affects how a commit is
written in the underlying storage layer but does not change any logic in
Delta Spark.
No

[Spark] Writing of UUID commits should not use put-if-absent semantics

---

storage/src/main/java/io/delta/storage/commit/CoordinatedCommitsUtils.java

Add utils to find logPath from dataPath in CoordinatedCommitsUtils
Build
No

[Spark] Add utils to find logPath from dataPath in CoordinatedCommitsUtils

---

spark/src/main/scala/org/apache/spark/sql/delta/FileMetadataMaterializationTracker.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableForUpgradeUniformHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeIntoMaterializeSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala
spark/src/main/scala/org/apache/spark/sql/delta/storage/DelegatingLogStore.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaProgressReporter.scala

Rename a few log keys to make the intention more clear. Also remove unused log keys.
No

[Spark] Clean up log keys

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/redirect/TableRedirect.scala
spark/src/test/scala/org/apache/spark/sql/delta/TableRedirectSuite.scala

This PR introduces a new reader-writer table feature "redirection". This table feature would redirect the read and write query from the current storage location to a new storage location  described inside the value of table feature.
The redirection has several phases to ensure no anomaly. To label these phases, we introduces four states:
0. NO-REDIRECT: This state indicates that redirect is not enabled on the table.
1. ENABLE-REDIRECT-IN-PROGRESS: This state indicates that the redirect process is still going on. No DML or DDL transaction can be committed to the table when the table is in this state.
2. REDIRECT-READY: This state indicates that the redirect process is completed. All types of queries would be redirected to the table specified inside RedirectSpec object.
3. …

[Table Redirect] Introduce Redirect ReaderWriter Feature

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/ChecksumHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/ChecksumSuite.scala

This PR adds a `ChecksumHook` which is responsible for a writing a checksum (See https://github.com/delta-io/delta/pull/3777) of the current table state after every commit. This is guarded behind a flag which is `false` by default. Currently, every checksum write will trigger a full state reconstruction, which can be very expensive. An upcoming PR will try to make this checksum computation incremental so that we don't have to pay a performance penalty.
Added a new suite --- ChecksumSuite.
No

[Spark] Write a checksum after every commit

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ConflictChecker.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/InCommitTimestampUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/JsonUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableConfigSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/JsonUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala

Remove `engine` references from `TableConfig` APIs. We don't actually need it, and it muddles our APIs, making us pass `engine` references everywhere. Clean up code along the way.
Existing UTs.
No.

[Kernel] Remove `engine` from `TableConfig` APIs

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoColumnOrderSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoImplicitCastSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoMissingColumnSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoTest.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningInsertSchemaEvolutionSuite.scala

Follow on https://github.com/delta-io/delta/pull/3605
Adds more tests covering behavior for all ways of running insert with:
- an extra column or struct field in the input, in `DeltaInsertIntoSchemaEvolutionSuite`
- a missing column or struct field in the input, in `DeltaInsertIntoImplicitCastSuite`
- a different column or field ordering than the table schema, in `DeltaInsertIntoColumnOrderSuite`
Note: tests are spread across multiple suites as each test case covers 20 different ways to run inserts, quickly leading to large test suites.
This change includes improvements to `DeltaInsertIntoTest`:
- Group all types of inserts into categories that are easier to reference in tests:
- SQL vs. Dataframe inserts
- Position-based vs. name-based inserts
- Append vs. overwrite
- Provide a mechanism …

[Spark] Add INSERT tests with missing, extra, reordered columns/fields

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/redirect/TableRedirect.scala
spark/src/test/scala/org/apache/spark/sql/delta/TableRedirectSuite.scala

This PR introduces a new writer-only table feature "redirection". This table feature would redirect the read and write query from the current storage location to a new storage location described inside the value of table feature.
No.

[Spark] Introduce Redirect WriterOnly Feature

---

build.sbt
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingCDFUtilsSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingFileIndexSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/TestClientForDeltaFormatSharing.scala

Upgrade delta-sharing-client to 1.2.1 in DBR master, see the changes in https://github.com/delta-io/delta-sharing/releases/tag/v1.2.1, supporting EndStreamAction, and additional logging.
Unit Tests
No

Upgrade delta-sharing-client to 1.2.1

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaParquetFileFormatSuite.scala

Revert "Write Int64 by default for Timestamps"
UT

Revert "Write Int64 by default for Timestamps"

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala

A minor refactor for checkpoint function
* Change the signature from `checkpoint(snapshotToCheckpoint, tableIdentifierOpt: Option[TableIdentifier] = None)` to `checkpoint(snapshotToCheckpoint, catalogTable: Option[CatalogTable] = None)`
Existing UTs
No

[Delta] Extend signature for checkpoint function

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaFormatSharingLimitPushDown.scala
spark/src/main/scala-spark-3.5/shims/LogicalRelationShims.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/GenerateRowIDs.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableWithDVs.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableWithDVsStrategy.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSinkSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala

This PR proposes to replace the default pattern matching for `LogicalRelation` to newly introduced pattern object `LogicalRelationWithTable` which will be available in upcoming Spark 4.0.
This change helps the project to modify less pieces of code when Spark makes the change to the LogicalRelation; most pattern matchings with LogicalRelation only extract the relation and catalog table, hence they fit with LogicalRelationWithTable.
Existing tests would suffice.
No.

[Spark] Replace the default pattern matching for LogicalRelation to LogicalRelationWithTable

---

spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/ChecksumSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala

https://github.com/delta-io/delta/pull/3799 added the capability to write a Checksum file after every commit. However, writing a checksum currently requires a full state reconstruction --- which is expensive. This PR adds the capability to compute most of the fields incrementally (apply the current delta on top of the last checksum to get the checksum of the current version). This works as long as the the actual operation performed matches exactly with the specified operation type in the commit. Note that this feature is gated behind a flag that is `true` by default.
Added tests in ChecksumSuite.
No

[Spark][Version Checksum] Incrementally compute the checksum

---

kernel/kernel-api/src/main/java/io/delta/kernel/Table.java
kernel/kernel-api/src/main/java/io/delta/kernel/TableIdentifier.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/test/scala/io/delta/kernel/TableIdentifierSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala

- adds a new `TableIdentifier` class, that kernel will pass on to Commit Coordinator Client
- adds a new `Table::forPathWithTableId(engine, path, tableId)` interface
- the tableId is stored as an `Optional` in the `Table`, and this PR does **not** propagate that value into SnapshotManager, Snapshot, etc. Future PRs can take care of that.
TableIdentifier UTs
Yes. See the above.

[Kernel] [CC Refactor #1] Add `TableIdentifier` API

---

spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampTestUtils.scala

For code hygiene, we move some ICT test helper utils from the `ICTSuite` to the object `InCommitTimestampTestUtils`, which is dedicated to contain the ICT test utils.
Existing UTs.
No.

[Spark] Move some ICT test helper utils to InCommitTimestampTestUtils.scala

---

python/delta/tables.py
python/delta/tests/test_deltatable.py

This PR introduces a `DeltaTable.addFeatureSupport` API which was missing in PySpark. This API is used to add support of a table feature to a given Delta table.
A new test is added.
Yes. See the above `Description` section.

[Spark] Add `DeltaTable.addFeatureSupport` API to PySpark

---

spark/src/main/scala-spark-master/shims/LogicalRelationShims.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala

This PR proposes to reflect a new parameter in the constructor of LogicalRelation for Spark 4.0. This PR deals with it via creating a shim object like we have done with IncrementalExecution for parameters difference.
There are overloaded methods to create a LogicalRelation instance and Spark community tried to provide the new method to avoid this change, but Spark couldn't just add a new overloaded method to workaround as it was ambiguous with existing method with default param.
No.

[Spark] Reflect a new parameter in the constructor of LogicalRelation for Spark 4.0

---

spark/src/main/antlr4/io/delta/sql/parser/DeltaSqlBase.g4
spark/src/main/scala/io/delta/sql/parser/DeltaSqlParser.scala
spark/src/main/scala/io/delta/tables/execution/VacuumTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/test/scala/io/delta/sql/parser/DeltaSqlParserSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala

This PR implements parser related changes for Lite Vacuum. As part of this, Vacuum overall syntax has been changed to accept vacuum parameters in any order unlike a fixed order before. This was one of the recommendations from the SQL committee.
Additionally, PR contains some test related changes.
Added new tests
No

Implement parser changes for Lite Vacuum

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeletionVectorUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/deletionvectors/StoredBitmap.scala
spark/src/main/scala/org/apache/spark/sql/delta/storage/dv/DeletionVectorStore.scala

It wraps two `RoaringBitmapArray` APIs `readFrom` and `serializeAsByteArray` with two utils function `DeletionVectorUtils.serialize` and `DeletionVectorUtils.deserialize`, which will log a delta event when it fails during (de-)serialization to enable monitoring and debugging the error.
Log-only change.
No.

[SPARK] Add metric for DV-related errors

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/GeneratedColumn.scala
spark/src/test/scala/org/apache/spark/sql/delta/GeneratedColumnSuite.scala

- Changes the behaviour of generated columns over nested types to allow nullability mismatches like we do for top-level types by switching exact data type equal to using `equalsIgnoreNullability` instead.
- Additionally, improve the error message in the case where the SQL string is identical (which hopefully shouldn't happen anymore after this, but just in case this comes up again later).
- Added new tests for various type (mis-) matches.
Yes: Generated columns now allow the type of the column definition to differ by nullability from the type of the generating expression, even when the type is a nested type.

[Spark] Accept generated columns of nested types that differ in nullability

---

spark/src/main/scala/org/apache/spark/sql/delta/CheckpointProvider.scala
spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/ChecksumSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala

Follow up for https://github.com/delta-io/delta/pull/3828.
This PR adds checksum validation logic. On every checkpoint, we will take the computed state of the table as per the deltas and the previous checkpoint and compare it against the checksum that was written at that version. The same methods can potentially be used to validate more frequently (if needed).
Added a new test case in ChecksumSuite that tests that all logically corrupted fields are being caught by the validation logic.
No

[Spark] Validate computed state against checksum on checkpoint

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

add retry logic for delta uniform iceberg conversion

add retry logic for delta uniform iceberg conversion

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/TableFeatureSupport.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolTransitionsSuite.scala

This is base PR for Fast Drop feature. This is a new implementation of the DROP FEATURE command that requires no waiting time and no history truncation.
The main difficulty when dropping a feature is that after the operation is complete the history of the table still contains traces of the feature. This may cause the following problems:
1. Reconstructing the state of the latest version may require replaying log records prior to feature removal. Log replay is based on checkpoints, an auxiliary data structure, which is used by clients as a starting point for replaying history. Any actions before the checkpoint do not need to be replayed. However, checkpoints are not permanent and may be deleted any time.
2. Clients may create checkpoints in historical versions when do not support the …

[Spark] Fast Drop Feature Command

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaGenerateCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DescribeDeltaDetailsCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/RestoreTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala

This PR changes the API of the DeltaLog to take in an extra parameter for table catalog and switching some call sites (more to come) to use the new API version.
Delta log API changes
+ Added `forTable(SparkSession, CatalogTable, Map[String, String])`
+ Added `forTableWithSnapshot(SparkSession, CatalogTable, Map[String, String])`
+ Modified `withFreshSnapshot` to take in a catalog table.
Unit tests
No

[Spark] Pass catalog table to DeltaLog API call sites 

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala

An opaque URI is an absolute URI whose scheme-specific part does not begin with a slash character ('/'), and are not further parsed by `java.net.URI` library (see https://docs.oracle.com/javase/7/docs/api/java/net/URI.html):
```
val uri = new URI("http:example.com")
uri.isOpaque -> true
uri.isAbsolute -> true
uri.getPath -> null
```
This causes issues when we try to call path-related methods in the URIs, e.g.:
```
val filePath = new Path(uri)
filePath.toString -> "http:"
filePath.isAbsolute -> NullPointerException
```
This commit fixes this issue by detecting such URIs in Delta file actions and throwing a proper exception.
Add new UT.
No

[Spark] Detect opaque URIs and throw proper exception

---

spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSchemaEvolutionSuite.scala

Fix flaky test that very rarely fail with actual result being off by one day compared to the expected result.
Turns out it calls `current_date()` separately to compute the input data and the expected result.
~Run the test around midnight~  (as a thought experiment)

[Spark] Remove use of current_date in MERGE test

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaDataSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceMetadataEvolutionSupport.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableUtilsSuite.scala

When reading from a Delta streaming source with schema tracking enabled - by specifying `schemaTrackingLocation` - internal metadata in the table schema causes a schema change to be detected.
This is especially problematic for identity columns that track the current high-water mark for ids as metadata in the table schema and update it on every write, causing streams to repeatedly fail and requiring a restart.
This change addresses the issue by ignoring internal metadata fields when detecting schema changes.
A flag is added to revert to the old behavior if needed.
Added test case covering problematic use case with both fix enabled and disabled.

[Spark] Ignore internal metadata when detecting schema changes in Delta source

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaTestImplicits.scala

Previously, we passed the table identifier to the DeltaLog's constructor and methods to use. For future-proof purpose, we should pass the whole catalog table instead.
Unit test
No

[Spark] Pass table catalogs throughout DeltaLog

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/ClusteredTableTestUtils.scala

Add isFull operation peramemter in the commit history for command OPTIMIZE tb FULL.
No

[Spark]Add OPTIMIZE FULL history support

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableForUpgradeUniformHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ShowDeltaTableColumnsCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/AutoCompact.scala

Fix a number of code paths where we want to pass table identifier to the commit coordinator client via the update method of DeltaLog
unit tests
No

[Spark] Pass catalog table to DeltaLog API call sites, part 2

---

build.sbt

This PR proposes to upgrade the version of delta-sharing-client to 1.2.2, which is compatible with recent change in master branch for Apache Spark. The version can work for both Spark 4.0 and prior.
Existing tests with CI
No.

Upgrade the version of delta-sharing-client to 1.2.2

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaDataSource.scala

I found an unused method. Removed it, and also did a mini refactor in Checkpoints.scala
No

[Spark] Remove unused method and do a little refactor in Checkpoints.scala

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/ConvertToDeltaSQLSuite.scala

Add the metric "numConvertedFiles" to the ConvertToDelta command node
Added a new test validating the values
The metric become visible in the plan (i.e. Spark UI)

[SPARK] Add SQL metrics for ConvertToDelta

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingUtils.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceTypeWideningSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/TestClientForDeltaFormatSharing.scala

Adds type widening to the list of supported features for D2D delta sharing and adds client-side tests covering reading a table that had a type change applied using the type widening table feature.
Added tests.

[Delta Sharing] Enable D2D delta sharing with type widening

---

spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotState.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaIncrementalSetTransactionsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DomainMetadataSuite.scala

Follow up for https://github.com/delta-io/delta/pull/3828. Adds support for incrementally computing the set transactions and domain metadata actions based on the current commit and the last version checksum. Incremental computation for both these action types have thresholds so that we don't store them if they are too long (tests have been added for the same). 
Added new tests in DomainMetadataSuite and a new suite called `DeltaIncrementalSetTransactionsSuite`
No

[Spark][Version Checksum] Incrementally compute VersionChecksum setTransactions and domainMetadata

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/ChecksumSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaAllFilesInCrcSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala

Follow up for https://github.com/delta-io/delta/pull/3895. Adds incremental computation of the allFiles field in the VersionChecksum. There are only included until a threshold (defined using a SQL conf) is reached. This field is later used for validation.
Added DeltaAllFilesInCRCSuite
No

[Spark][Version Checksum] Incrementally compute allFiles in the checksum

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/PartitionLikeDataSkippingSuite.scala

Currently, we try to rewrite any arbitrary expression as partition-like. To avoid having to repeatedly remove known-bad expressions, start with a whitelist (to be expanded) of known-good expressions that can safely be rewritten. 
This change will fix an existing issue where partition-like filters are generated for a non-skipping eligible column. This partition-like filter will throw an analysis exception because these referenced columns aren't found in the stats. This issue was originally missed (and is a difference in behavior vs. partition filters) because partitioning isn't allowed on non-atomic types (or string types), so we missed adding this additional match.
See test changes.
No.

[Spark] Restrict partition-like data filters to whitelist of known-good expressions

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/constraints/Constraints.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/ImplicitMetadataOperation.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningConstraintsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningGeneratedColumnsSuite.scala

The current checker of dependent expressions doesn't validate changes for array and map types. For example, usage of type widening could lead to constraints breaks:
```
scala> sql("CREATE TABLE table (a array<byte>) USING DELTA")
scala> sql("INSERT INTO table VALUES (array(1, -2, 3))")
scala> sql("SELECT hash(a[1]) FROM table").show()
+-----------+
| hash(a[1])|
+-----------+
|-1160545675|
+-----------+
scala> sql("ALTER TABLE table ADD CONSTRAINT ch1 CHECK (hash(a[1]) = -1160545675)")
scala> sql("ALTER TABLE table SET TBLPROPERTIES('delta.enableTypeWidening' = true)")
scala> sql("ALTER TABLE table CHANGE COLUMN a.element TYPE BIGINT")
scala> sql("SELECT hash(a[1]) FROM table").show()
+----------+
|hash(a[1])|
+----------+
|-981642528|
+----------+
scala> sql("INSERT INTO table VALUES …
```

[Spark] Fix dependent constraints/generated columns checker for type widening

---

project/SparkMimaExcludes.scala
spark/src/main/scala/io/delta/sql/parser/DeltaSqlParser.scala
spark/src/main/scala/io/delta/tables/DeltaTable.scala
spark/src/main/scala/io/delta/tables/execution/DeltaTableOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaGenerateCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/GenerateSymlinkManifest.scala
spark/src/test/scala-spark-3.5/shims/DeltaGenerateSymlinkManifestSuiteShims.scala
spark/src/test/scala-spark-master/shims/DeltaGenerateSymlinkManifestSuiteShims.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaGenerateSymlinkManifestSuite.scala

This PR rewrites the GENERATE SYMLINK MANIFEST command (`DeltaGenerateCommand`) to use Spark's table resolution mechanism. It is replaced to be a `UnaryRunnableCommand` that takes in a child logical plan, which is initially an unresolved table. The table is then resolved by Spark's resolution mechanism, resulting in a `DeltaTableV2` object.
With this object, we also have a catalog table which is passed down into `generateFulllManifest` as part of the effort to pass the catalog table to DeltaLog API's call sites.
unit tests
No

[SPARK] Rewrite GENERATE SYMLINK MANIFEST command to use Spark table resolution

---

examples/scala/src/main/scala/example/EvolutionWithMap.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoTableSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningInsertSchemaEvolutionSuite.scala

This PR fixes an issue with schema evolution in Delta Lake where adding a new field to a struct within a map and renaming an existing top level field caused the operation to fail.
The fix includes logic to handle these transformations properly, ensuring that new fields are added without conflicts.
It also resolved a ToDo of casting map types in the [DeltaAnalysis.scala](https://github.com/Richard-code-gig/delta/blob/feature/schema-evolution-with-map-fix/spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala) module.
- Updated schema evolution logic to support complex map transformations.
- Enabled schema evolution for both map keys, simple and nested values
- Added additional case statements to handle MapTypes in addCastToColumn method in DeltaAnalysis.scala module.
- …

[Spark] Fix schema evolution issue with nested struct (within a map) and column renamed

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/deletionvectors/RoaringBitmapArray.java
kernel/kernel-api/src/test/scala/io/delta/kernel/deletionvectors/RoaringBitmapArraySuite.scala

Resolves #3881 
- The bitmaps array should be initialized in the `create` path.
- The `expandBitMaps` method should set new bitmaps from the old length up to the new length, instead of overwriting the old ones.
Also adds a `toArray` method mimicking the one provided by the scala version which the class is based on.
Added unit tests.
No

[Kernel] Fix RoaringBitmapArray create/add methods. Closes issue #3881

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoTableSuite.scala

Small test fix to get https://github.com/delta-io/delta/commit/ca118d189591a98082e7bfa5014bf9264918c0a2 to compile against spark master
The `errorClass` argument of `checkError` was renamed to `condition` in recent spark release. To work with both, the named argument is changed to be unnamed.
N/A, test-only
No

Update checkError calls in DeltaInsertIntoTableSuite to compile against spark master

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/TableFeatureSupport.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningTableFeatureSuite.scala

Adds support for dropping the `CheckpointProtection` table feature. To drop the feature, we need to truncate all history prior to the CheckpointProtection version. For this cleanup operation we use a shorter retention period of 24 hours. This is configured in `delta.dropFeatureTruncateHistory.retentionDuration` and is the same config we use in the drop feature with History Truncation implementation.
Added tests in `DeltaFastDropFeatureSuite`.
No.

[Spark] Add support for dropping the CheckpointProtection table feature

---

kernel/kernel-api/src/main/java/io/delta/kernel/Snapshot.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java

Add a new `Snapshot::getTimestamp` public API.
N/A. Trivial.
Yes. Adds a new `Snapshot::getTimestamp` public API.

[Kernel] Add `Snapshot::getTimestamp` public API

---

build.sbt
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/DomainMetadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metadatadomain/JsonMetadataDomain.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/RowTrackingMetadataDomain.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metadatadomain/JsonMetadataDomainSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metadatadomain/TestJsonMetadataDomain.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DomainMetadataSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestJsonMetadataDomain.java

This PR adds the following to Delta Kernel Java:
- `JsonMetadataDomain.java`: Introduces the base abstract class `JsonMetadataDomain` for metadata domains that use JSON as their configuration string. Concrete implementations, such as `RowTrackingMetadataDomain`, should extend this class to define their specific metadata domain. This class provides utility functions for
- serializing to/deserializing from a JSON configuration string
- creating a `DomainMetadata` action for committing
- creating a specific metadata domain instance from a `SnapshotImpl`
- `RowTrackingMetadataDomain.java`: Implements the metadata domain `delta.rowTracking`. It has a configuration field `long rowIdHighWaterMark`, which will be used in the future for assigning fresh row IDs.
Added unit tests and integration …

[Kernel] Add JsonMetadataDomain and RowTrackingMetadataDomain

---

spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckpointsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/ChecksumSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaAllFilesInCrcSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala

Stacked over https://github.com/delta-io/delta/pull/3907. 
This PR makes the Checksum (if available) the source of truth for Protocol, Metadata, ICT during snapshot construction. This helps us avoid a Spark query and improves performance.
Added some test cases to existing suites
No

[Spark][Version Checksum] Read Protocol, Metadata, and ICT directly from the Checksum during Snapshot construction

---

spark/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckpointProtectionTestUtilsMixin.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala

Base implementation of `CheckpointProtectionTableFeature`. Writers are only allowed to cleanup metadata as long as the can truncate history up to `requireCheckpointProtectionBeforeVersion` in one go.
As a second step, the feature can be improved by allowing metadata cleanup even when the invariant above does not hold. Metadata cleanup could be allowed if the client verifies it supports all writer features contained in the history it intends to truncate. This improvement is important to support for providing GDPR compliance.
Added tests in `DeltaRetentionSuite`.
No.

[Spark] CheckpointProtectionTableFeature base implementation

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

This PR is part of https://github.com/delta-io/delta/issues/1959
In this PR, we flip the SQLConf that guards the creation of Identity Column from false to true. Without this, we cannot create identity columns in Delta Spark!
Existing tests pass.
Yes, it enables the creation of Identity Columns.

[Spark] Enable Identity column SQLConf

---

spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnIngestionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnSyncSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnTestUtils.scala

In this PR, we expand the test coverage for identity columns. Specifically, we add more assertions for the high watermarks and cover more test scenarios with replacing tables.
Test-only PR. We expand test coverage.
No.

[Spark][TEST-ONLY] Identity Column high watermark and replace tests

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

This PR is part of https://github.com/delta-io/delta/issues/1959
In this PR, we flip the SQLConf that guards the creation of Identity Column from false to true. Without this, we cannot create identity columns in Delta Spark!
Existing tests pass.
Yes, it enables the creation of Identity Columns.
(cherry picked from commit 7224677acda11eb21103112c8b636963874e9071)

[3.3][Spark] Enable Identity column SQLConf (#3936)

---

build.sbt

Skips release for delta connect projects for 3.3 release. These artifacts are only compiled with Spark 4 / Spark master but currently our release process includes them (likely empty since compile is skipped?).
Tested release from this branch and checked the artifacts are not included.
No.

[3.3 Release] Update SBT to not publish delta connect artifacts

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/S3LikeLocalFileSystem.scala

This PR introduces a better way to check if the schema tracking location is under the checkpoint location that would work with arbitrary file systems and paths.
New UT.
No

Fix schema tracking location check condition against checkpoint location

---

spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableMerge.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableUpdate.scala
spark/src/main/scala/org/apache/spark/sql/delta/UpdateExpressionsSupport.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSink.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoColumnOrderSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoMissingColumnSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoSchemaEvolutionSuite.scala

Follow-up on https://github.com/delta-io/delta/pull/3443 that introduced implicit casting during streaming write to delta tables.
The feature was shipped disabled due to a regression found in testing where writing data with missing struct fields start being rejected. Streaming writes are one of the few inserts that allows missing struct fields.
This change allows configuring the casting behavior used in MERGE, UPDATE and streaming writes wrt to missing struct fields.
Extensive tests were added in https://github.com/delta-io/delta/pull/3762 in preparation for this changes, covering for all inserts (SQL, dataframe, append/overwrite, ..):
- Missing top-level columns and nested struct fields.
- Extra top-level columns and nested struct fields with schema evolution.
- Position vs. name based …

[Spark] Allow missing fields with implicit casting during streaming write

---

project/SparkMimaExcludes.scala
spark/src/main/scala/io/delta/sql/parser/DeltaSqlParser.scala
spark/src/main/scala/io/delta/tables/DeltaTable.scala
spark/src/main/scala/io/delta/tables/execution/DeltaTableOperations.scala
spark/src/main/scala/io/delta/tables/execution/VacuumTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DescribeDeltaDetailsCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaTestImplicits.scala

This PR cleans up a few things
+ In scala API, use the `VacuumTableCommand` instead of calling `VacuumCommand.gc` directly,
+ Pass `DeltaTableV2` to `VacuumCommand.gc` instead of `DeltaLog`.
+ Use `DeltaTableV2` in tests instead of `DeltaLog`.
Unit tests
No

[SPARK] Clean up vacuum-related code

---

spark/src/main/scala/io/delta/tables/DeltaTable.scala
spark/src/main/scala/io/delta/tables/execution/DeltaTableOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/StatisticsCollection.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/DeleteCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/MergeCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/UpdateCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/DropColumnMappingFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingSuiteUtils.scala

Fix a number of code paths where we want to pass catalog table to the commit coordinator client via DeltaLog API
Unit tests
No.

[Spark] Pass catalog table to DeltaLog API call sites, part 3

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala

Previously, missing <key, value> pair in the partitionValues map was not handled correctly, resulting in a Delta -> Iceberg conversion failure. To fix this, this PR use default value correctly for missing entries in the partitionValues map.
Existing tests
No

Use default partition value during uniform conversion when partition value is missing

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala

Expose Delta Uniform write commit size in logs

Expose Delta Uniform write commit size in logs

---

examples/scala/build.sbt

In preparation for the 4.0 preview release which uses java 17 for Delta Spark we added `java17settings` to the scala examples build. This breaks when running with Java 8.
Ran tests locally.
No.

[3.3] Fix scala examples to run with Java 8 for the 3.3 release

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java

Resolves #3948 
Fixed incorrect load protocol and metadata time log
Unit tests
No

[Kernel] Fix incorrect load protocol and metadata time log

---

docs/source/delta-row-tracking.md

- Cherry-pick https://github.com/delta-io/delta/pull/3968 into Delta 3.3.
N/A
N/A

[Docs][3.3] Update documentation for Row Tracking to include Row Tracking Backfill introduced in Delta 3.3

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/optimize/OptimizeConflictSuite.scala

Bug: There was an existing long standing bug where the custom conflict detection logic in Optimize does not catch concurrent transactions that add DVs. e.g. AddFile(path='a') -> AddFile(path='a', dv='dv1').
Fix: Updated the conflict resolution to consider a composite key of (path, dvId) instead of just depending on path.
- unit tests
no

[Spark] Fix auto-conflict handling logic in Optimize to handle DVs

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/optimize/OptimizeConflictSuite.scala

Bug: There was an existing long standing bug where the custom conflict detection logic in Optimize does not catch concurrent transactions that add DVs. e.g. AddFile(path='a') -> AddFile(path='a', dv='dv1').
Fix: Updated the conflict resolution to consider a composite key of (path, dvId) instead of just depending on path.
- unit tests
no

[Spark][3.3] Fix auto-conflict handling logic in Optimize to handle DVs

---

python/delta/tables.py
python/delta/tests/test_deltatable.py
spark/src/main/scala/io/delta/tables/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/test/scala/io/delta/tables/DeltaTableSuite.scala

This PR adds drop feature support in the DeltaTable API  for both scala and python APIs.
Added UTs.
Yes. See description.

[Spark] Drop feature support in DeltaTable Scala/Python APIs

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaTestImplicits.scala

+ Avoid calling `DeltaLog.update()` in `getFilesFromDeltaLog`, which is already taking in a `snapshot`.
+ Add a new `DeltaTableV2ObjectTestHelper::apply` implicit method to simplify some tests
unit tests
No

[Spark] Avoid unnecessarily calling update and some minor clean up in tests

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/lang/ListUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/DefaultEngineErrors.java

We are re-thinking the design of the Coordinated Commits table feature and much of this snapshot code will be refactored. Remove it for now as it greatly complicates our snapshot construction, and hopefully we can be more intentional in our code design/organization when re-implementing it.
https://github.com/delta-io/delta/commit/fc81d1247d66cc32e454e985f0cfc81447f897b6 already removed the public interfaces and made it such that `SnapshotImpl::getTableCommitCoordinatorClientHandlerOpt` never returned a handler.
Existing tests should suffice.
No.

[Kernel] Remove CC code from SnapshotManager

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableConfigSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala

There are a couple of pieces missing from fully supporting these features
- Data path PR is not yet merged (delta-io/delta#3475), waiting on the expression fixup which is going to affect how column mapping is done.
- Auto enabling of the protocol version based on the current table version and column mapping/iceberg compat v2 enabled.
Disable these in 3.3 to avoid writing a partial column mapping data.

[3.3][Kernel] Disable setting columnMapping/icebergCompatV2 for 3.3.0

---

kernel/kernel-api/src/test/scala/io/delta/kernel/metrics/MetricsUtilsSuite.scala

Fixes a flaky test.
Unit test fix.
No.

[Kernel] Fix flaky test for the Timer class for metrics

---

docs/source/delta-batch.md
docs/source/delta-clustering.md
docs/source/delta-drop-feature.md
docs/source/delta-sharing.md
docs/source/delta-storage.md
docs/source/delta-type-widening.md
docs/source/delta-utility.md
docs/source/quick-start.md
docs/source/releases.md

Updates versions in docs.
Minor fixes / clarifications in docs.
Adds to list of supported features for dropping.
Local build
No

[3.3][Docs] Update docs for 3.3 release

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaEncoders.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala

When performing time travel operations that trigger parallel search in DeltaHistoryManager (when searching through >2000 commits), a NoSuchElementException can occur if some partitions return empty commit lists. This happens because the code attempts to call .head on potentially empty collections without proper checks.
UTs
No

[Spark] Fix NoSuchElementException in DeltaHistoryManager parallel search with empty commits

---

iceberg/src/test/scala/org/apache/spark/sql/delta/uniform/TypeWideningUniformSuite.scala
spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/IcebergCompat.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/ResolveDeltaMergeInto.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWidening.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWideningMode.scala
spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/ImplicitMetadataOperation.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaMergingUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSink.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoTest.scala
spark/src/test/scala/org/apache/spark/sql/delta/UniversalFormatSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningInsertSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningUniformTests.scala

Iceberg only supports a subset of the type changes that Delta's type widening feature covers.
See https://iceberg.apache.org/spec/#schema-evolution.
Unsupported type changes areL
- integers -> decimal
- integers -> double
- decimal scale increase
- date -> timestamp_ntz
This change makes using Uniform with Iceberg compatibility mutually exclusive with using one of these unsupported type changes, e.p.:
- Fail when trying to apply an unsupported type change if Uniform with Iceberg compatibility enabled.
- Fail when trying to enable Uniform with Iceberg compatibility if an unsupported type change was applied in the past.
- Don't automatically widen type during schema evolution if Uniform with Iceberg compatibility is enabled and the type promotion isn't supported by Iceberg.
- Added suite …

[Spark] Reject unsupported type changes with Uniform

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/RemoveFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/RowBackedAction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/DelegateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/StructType.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/DataFileStatistics.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/actions/AddFileSuite.scala

This PR implements the `AddFile` action class, with the help of `DelegateRow` and `RowBackedAction`, which are also newly introduced in this PR. The core changes include:
`RowBackedAction`
- A new abstract base class for Delta Log actions that are backed by a `Row`. It can be extended by actions like `AddFile`, where we want to avoid materializing of all fields from action rows when creating action instances within Kernel. 
`DelegateRow`:
- A new `Row` implementation that wraps an existing `Row` and allows overriding values for some particular ordinals.
- Currently this is used to update certain fields of an action by creating a modified view of its underlying row without mutating the original row.
- The implementation ensures we only keep one layer of delegation.
`AddFile`
- This PR …

[Kernel] Implement AddFile class using DelegateRow

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/DelayedCommitProtocol.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/PartitionUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoTableSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/uniform/UniFormE2ESuite.scala

- [X ] Spark (Uniform)
- [] Other 
This change fixes support for timestamp partition values in Uniform specifically when timestamp partition values which are not UTC instants are stored in the Delta log (Delta protocol supports both TS partition values where there is no timezone and  ISO-8601 instant timestamps).
In the fix these partition values will be interpreted in the system time of the system doing the metadata conversion and then UTC adjusted for the Iceberg metadata translation. Previously the fix assumed UTC instants but for compatibility reasons, we do want to be able to support the older form of the metadata for Iceberg conversion. 
Example:
Prior to this fix, the code would fail with a parsing exception for the non-instant case since a string like "2021-01-01 10:00:00.123" …

[UNIFORM] Fix converting non-ISO timestamp partition values to Iceberg

---

kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Predicate.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/ExpressionVisitor.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/StartsWithExpressionEvaluator.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/ExpressionSuiteBase.scala

Initial implementation of STARTS_WITH expression at this moment, we only support b as literal expression.
This is 1/n for addressing https://github.com/delta-io/delta/issues/2539, the logic of data skipping will be done in the following PRs
Added test cases in DefaultExpressionEvaluatorSuite.scala
No

[Kernel] Add `STARTS_WITH` expression and default impl 

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaLogActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/DeltaLogActionUtilsSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala

Kernel had two very similar `verifyDeltaVersions` functions which verify that the input versions are contiguous.
This PR removes one of them, cleaning up the extra & unneeded tests and making minor code improvements along the way.
Existing UTs.
No.

[Kernel] Remove duplicate `verifyDeltaVersions` function

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingUtils.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/TestClientForDeltaFormatSharing.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala-spark-master/org/apache/spark/sql/delta/DeltaVariantSuite.scala

creates the variant GA table feature. 
New variant tables are still created with the preview table feature. However, a future PR will switch this so new tables then are created with the GA table feature. At this point, we will keep the ability to read the `preview` table feature because there were no changes to the spec between preview and GA.
added UTs
no

[SPARK][SHARING][VARIANT] Create GA variant table feature

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/InternalScanFileUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/RowBackedAction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/SingleAction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/RowTracking.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/RowTrackingMetadataDomain.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala

This PR implements the row tracking _support_ requirements in Delta Kernel, according to the [Delta Protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#row-tracking). Specifically, it includes:
- assigning `baseRowId` and `defaultRowCommitVersion` to `AddFile` actions prior to committing them
- maintaining the `rowIdHighWaterMark` of the `delta.rowTracking` metadata domain during the base row ID assignment, which is the highest assigned fresh row id for the table
Added tests in `RowTrackingSuite.scala`. This includes unit tests and integration tests with Delta-Spark.
No.

[Kernel] Assign base row ID and default row commit version to AddFile

---

spark/src/main/scala/org/apache/spark/sql/delta/storage/ClosableIterator.scala
spark/src/test/scala/org/apache/spark/sql/delta/storage/LineClosableIteratorSuite.scala

Iterators cannot expect to be closed after instantiation, they can only expect that the caller will call close() after some next() or hasNext() call. For example, in `DeltaSource.getStartingOffsetFromSpecificDeltaVersion`, we do not wrap the iterator in a `finally` block directly after [instantiation](https://github.com/delta-io/delta/blob/7381d5a8b27b6c721b8b8da9e095c695cfd727b2/spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala#L411) but rather only once we have [started iterating](https://github.com/delta-io/delta/blob/7381d5a8b27b6c721b8b8da9e095c695cfd727b2/spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala#L1458).
However, the current `ClosableIterator` implementation from `flatMapWithClose` opens an inner iterator on instantiation, …

[Spark] Fix ClosableIterator to only open inner iterators when hasNext() is called

---

build.sbt
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/MetricsReportSerializers.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotMetrics.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotReportImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/DeltaOperationReport.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/SnapshotMetricsResult.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/SnapshotReport.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultEngine.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/LoggingMetricsReporter.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/MetricsReportSuite.scala

This PR is based off of https://github.com/delta-io/delta/pull/3903
See the diff for just this PR [here](https://github.com/delta-io/delta/pull/3904/files/aec95cf3dc0086c37f4c45e2b3e192b7b881768c..678ac473f4de65a8f7fd770696aad2d31a15aef7)
Adds a JSON serializer for metrics reports with serialization logic for SnapshotReport. Also adds a `LoggingMetricsReporter` to the default implementation which simply logs the JSON serialized reports using Log4J.
Adds a test suite.
No.

[Kernel][Metrics][PR#3] Metrics report JSON serializer and LoggingMetricsReporter for the default engine

---

connectors/flink/src/main/java/io/delta/flink/source/internal/SchemaConverter.java
connectors/flink/src/test/java/io/delta/flink/source/internal/SchemaConverterTest.java
connectors/flink/src/test/java/io/delta/flink/table/it/suite/DeltaEndToEndTableTestSuite.java

Resolves #3977
This PR fixes a bug where the Delta-Flink connector would incorrectly map Delta's `BinaryType` (which is variable length) type to Flink's `BinaryType` (which is fixed length). Instead, this PR fixes it so that Delta's `BinaryType` is mapped to Flink's `VarBinaryType(MAX_LENGTH)`. As a comparison, Iceberg does the same [here](https://github.com/apache/iceberg/blob/8e2ffb35da2d4c5059e96cb78a30fd8c54cfbedf/flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/TypeToFlinkType.java#L125).
This incorrect logic caused the behaviour seen in #3977 because:
- First, we had a source (datagen) table with Flink's BYTES (which is a synonym for VarBinaryType of MAX_LENGTH)
- Second, we had a target (delta) table. Flink created it with schema BYTES and the Delta schema had delta type …

[Flink] Fix mapping between Delta's BinaryType and Flink's VarBinaryType

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala

Delta metadata should have the same retention as Iceberg, otherwise weird behavior happens:
if iceberg retention is longer, then when reading as Delta it cannot go that far back when doing time travel.
if delta retention is longer, then time travel on the delta will break as the data files may already be deleted from iceberg side.

Delta metadata should have the same retention as Iceberg

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala

Currently, Kernel doesn't support the `invariants` feature and could not write to tables on writer version 7 if their `writerFeatures` contains `invariants`.
With this change, Kernel will allow `invariants` to be present in the `writerFeatures` for tables on writer version 7, provided the schema does not define any invariants. This unblocks Kernel from writing to such tables.
Tests are added in `TableFeaturesSuite.scala`. It also added a missing integration test in `RowTrackingSuite.scala` that was previously blocked by `invariants`.
No.

[Kernel] Enable writing to tables at version 7 when no invariants are defined in the schema

---

spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeletionVectorsTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala

This PR adds support for dropping deletion vectors.
Added tests in `DeltaProtocolVersionSuite`.
Yes. See description.

[Spark] Add support for dropping Deletion Vectors

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/FallbackToV1Relations.scala
spark/src/main/scala/org/apache/spark/sql/delta/ResolveDeltaTableWithPartitionFilters.scala

Refactored out the following read path functionality:
- V2 -> V1 relation conversions.
- Table with partition filters resolution.
This is a refactor-only change to support the single-pass Analyzer project in Spark: https://issues.apache.org/jira/browse/SPARK-49834.
It will be used in single-pass resolver extensions: https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/resolver/ResolverExtension.scala.
No.

[Spark] Refactor out Delta read path

---

spark/src/main/scala/org/apache/spark/sql/delta/SupportedGenerationExpressions.scala
spark/src/test/scala/org/apache/spark/sql/delta/GeneratedColumnSuite.scala

It allow-lists `timestampdiff` & `timestampadd` as generated column expressions as they are deterministic.
New test case.
Previously users cannot use `timestampdiff` or `timestampadd` in generation expression. The PR allows this.

[SPARK] Allow list `timestampdiff` & `timestampadd` as generated column expressions

---

spark/src/main/scala/org/apache/spark/sql/delta/IdentityColumn.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TransactionalWrite.scala

Avoid using attributes with outdated expression IDs in internal Delta DataFrame operations.
In this example:
```
val resolvedPlan = Dataset.ofRows(spark, LocalRelation(statsDataSchema)).select(to_json(statsCollection.statsCollector)).queryExecution.analyzed
```
the Analyzer might regenerate expression IDs (this is an implementation-specific behavior), and `statsDataSchema` may not be used along with `resolvedPlan.expressions.head`, because they will have different expression IDs associated with those expression trees. It would be correct to use `resolvedPlan.children.head.output` from that `LocalRelation`.
The issue might happen later when these attributes are passed to `DeltaJobStatisticsTracker` -> `DeltaTaskStatisticsTracker` -> `JoinedProjection.bind` along with the resolved …

[Spark] Avoid using attributes with outdated expression IDs in internal Delta DataFrame operations

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaFastDropFeatureSuite.scala

This PR adds comprehensive testing for fast drop feature.
Test only PR.
No.

[Spark] Add testing for Fast Drop Feature

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaFastDropFeatureSuite.scala

Testing only PR to ensure protocol validation in time travelling works as expected.
Testing only PR.
No.

[Spark] Protocol validation testing in time travelling

---

spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnIngestionSuite.scala

Test only PR. Adds some basic additional tests for inserting data into tables when the Identity Column high water mark isn't already defined. Split from the PR making identity column high water mark updates more consistent: https://github.com/delta-io/delta/pull/3989
New tests pass.
No.

[Spark][TEST-ONLY] Test identity high water mark inserts when target table has no high water mark

---

spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeletionVectorsTestUtils.scala

Just some minor reorganisation of tests to ensure CLONE codepaths are tested with and without DVs as expected.
Test-only PR.
No

[Spark] Reorganise where deletion vectors are added to the test suites for CLONE

---

kernel/kernel-api/src/main/java/io/delta/kernel/TransactionBuilder.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala

This PR allows setting the maximum number of times that kernel should retry a transaction. It does so by adding a `withMaxRetries` option to the `TransactionBuilder`.
It also refactors the commit loop code to make it a bit more clear.
New Unit test
Yes: Introduces a new public api

[Kernel] Add maxRetries to txnbuilder

---

spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaUDF.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/DeletionVectorDescriptor.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/TableFeatureSupport.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaFastDropFeatureSuite.scala

Drop feature with checkpoint protection allows dropped features to live in the table history. This has consequences in the vacuum command. This is because vacuum only reads the latest snapshot, and uses that to decide what can be deleted or not. This could lead clients that do not support past feature(s) to incorrectly vacuum auxiliary files, unless the latest snapshot can prevent this from happening using only features from the reduced protocol. The way that the table snapshot prevents deletion of files is by referencing files that were recently removed from the table (in the last 7 days) in RemoveFile actions or "tombstones".
This is problematic when a newer feature extends the functionality of these tombstones. For instance, the Deletion Vectors feature has `RemoveFile` actions that …

[Spark] Create DV tombstones when dropping Deletion Vectors #117451

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

If spark context is null when exception is thrown, then we don't need to generate documentation link. That's because it requires non-null context and it will throw another exception otherwise. But it's almost impossible case because a lot of code verifies that context is not null.
Added new test.
No overlapping exception during generation of documentation link.

Verify spark context during documentation link generation

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala-spark-master/org/apache/spark/sql/delta/DeltaVariantSuite.scala

upgrades the variant type preview feature to GA by adding a new table feature VariantType
Note there were no changes to the spec between preview and GA, so we will continue allow reading -preview features.
New tables going forward with variants are created with the `variantType` stable table feature.
A new config `"variant.forceUsePreviewTableFeature"` is also added to revert to the old behavior (create variant tables with `variantType-preview`) if need be
added UTs.

[VARIANT] Upgrade variantType-preview to variantType

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaLogActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/FileNames.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/DeltaLogActionUtilsSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaLogActionUtilsE2ESuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala

We used to have several duplicated log directory listing utilities. This PR cleans that up so there's just one utility method.
I also got rid of the listing utility that returns an `Optional<List<FileStatus>>`. If we cannot find the `_delta_log` folder, we throw an exception. If the `_delta_log` folder is empty, we should return an empty list.
Just a refactor. Existing UTs.
No.

[Kernel] Consolidate listing utilities code and simplify SnapshotManager log segment error case

---

build/sbt-config/repositories
build/sbt-launch-lib.bash
icebergShaded/generate_iceberg_jars.py

* Google maven repo URL is changed from `https://maven-central.storage-download.googleapis.com/repos/central/data/` to `https://maven-central.storage-download.googleapis.com/maven2/`. This caused more load on the central maven repo as the google maven repo is wrong.
* Currently we hard coded the URL to central maven repo for downloading the `sbt-launch-x.x.x.jar` as part of the build start. Change it to google maven repo which seems have better rate limits than the central maven repo. Also add the central maven repo as a backup so that we have two options. Example retrying:
```
(base) delta2 % ./build/sbt clean package test:package
Attempting to fetch sbt from https://eemaven-central.storage-download.googleapis.com/maven2/org/scala-sbt/sbt-launch/1.9.9/sbt-launch-1.9.9.jar
Download from …
```

[Build] Changes to avoid making too many requests to central maven repo

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala

Followup to #4035.
Our SnapshotManager LogSegment construction logic is ... a bit messy, to say the least. This PR makes `getLogSegmentForVersion` _not_ return an Optional LogSegment.
I also start documenting some of the key steps in constructing a LogSegment. More steps, refactors, and comments will come in future PRs.
Mainly just a refactor. Existing UTs.
No.

[Kernel] Minor SnapshotManager refactor followup

---

spark/src/main/scala/org/apache/spark/sql/delta/constraints/DeltaInvariantCheckerExec.scala

This adds an assertion after we attempt resolution to log additional information. The assertion will fail in testing mode but only emit an event outside of testing. This can later be turned into an actual exception if the data collected shows it's the right thing to do.
N/A, logging only

[Spark] Add assertion after resolving CHECK constraint child expressions

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/TransactionMetrics.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/TransactionMetricsResult.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/TransactionReportSuite.scala

This PR collects the metric for added file size. Together with the added file count, they will be used further for generating CRC files 
See https://github.com/delta-io/delta/pull/4091 for e2e poc
Unit test
No

[Kernel]Collect sum of added file size in Transaction metric

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/PrepareDeltaScan.scala

Currently, PrepareDeltaScan does not exclude non-deterministic filters (e.g. rand() < 0.25). So, it ends up creating a file index with these non-deterministic filters applied.
The same filters are reapplied downstream which causes them to be applied twice and the final result being unexpected.
In general, PrepareDeltaScan should not skip entire files/partitions because of non-deterministic filters.
Build
No

[Spark] Skip non-deterministic filters to prevent incorrect file pruning in Delta queries

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockFileSystemClientUtils.scala

This PR further refactors and cleans up SnapshotManager. We consolidate all of our `getLogSegment` methods to just one. It has a deep implementation. This PR adds nice, clean header blocks to describe the steps during log segment construction.
Refactor. Update existing UTs.
No.

[Kernel] Further refactor and cleanup SnapshotManager

---

connectors/flink/src/main/scala/io/delta/flink/internal/KernelDeltaLogDelegator.scala
connectors/flink/src/main/scala/io/delta/flink/internal/KernelSnapshotWrapper.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/MultiThreadedTableReader.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/SingleThreadedTableReader.java
kernel/kernel-api/src/main/java/io/delta/kernel/Snapshot.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ConflictChecker.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/InCommitTimestampUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/PartitionUtils.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/benchmarks/BenchmarkParallelCheckpointReading.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ActiveAddFilesLogReplayMetricsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CheckpointV2ReadSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DomainMetadataSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplayEngineMetricsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplaySuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ScanSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/SnapshotSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

Remove superfluous engine param from Snapshot APIs
Refactor only.
Removes param from public API.

[Kernel] [Refactor] Remove superfluous engine param from Snapshot APIs

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaLogActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/CloseableIterator.java
kernel/kernel-api/src/test/scala/io/delta/kernel/CloseableIteratorSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/DeltaLogActionUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaLogActionUtilsE2ESuite.scala

This PR does the following:
- changes our DeltaLogActionUtils `listDeltaLogFiles` method to return an iterator. This will eventually let it be used in a followup PR to further consolidate and clean up code in DeltaHistoryManager (which lists the delta log and expects an iterator)
- adds CloseabelIterator::takeWhile, breakableFilter, and toInMemoryList
- New UTs
No.

[Kernel] Minor refactor to DeltaLogActionUtils; add CloseableIterator takeWhile and other helpful methods

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/PartitionLikeDataSkippingSuite.scala

Currently, partition-like skipping is limited to a set of whitelisted expressions referencing only Liquid clustering columns. This PR adds configs that can be used to expand these restrictions (allow an arbitrary expression referencing any column).
See test changes.
No.

[Spark] Add configurable expansions to partition-like skipping coverage

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TransactionalWrite.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/AutoCompact.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/AutoCompactUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/ChecksumHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/GenerateSymlinkManifest.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/HudiConverterHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/IcebergConverterHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/PostCommitHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/UpdateCatalog.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

The `OptimisticTransactionImpl` trait is bloating as more features are added, making it difficult to extend from. This PR introduces `DeltaTransaction`, which is conceptually more general to support other implementations of the transaction, containing minimal number of fields that are essential for a transaction and necessary for the post-commit hooks.
unit test
no

[Spark] Introduce the DeltaTransaction trait 

---

docs/source/delta-kernel-java.md
docs/source/delta-kernel.md
kernel/USER_GUIDE.md
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/MultiThreadedTableReader.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/SingleThreadedTableReader.java
kernel/kernel-api/src/main/java/io/delta/kernel/ScanBuilder.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/PartitionUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ScanSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

Remove superfluous engine param from ScanBuilder APIs
Refactor only.
Removes param from public API.

[Kernel] [Refactor] Remove superfluous engine param from ScanBuilder APIs

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/LogSegment.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/snapshot/LogSegmentSuite.scala

Add better validations to LogSegment
New UTs.
No.

[Kernel] Add better param validations to LogSegment constructor

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableConfigSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TablePropertiesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TablePropertiesSutie.scala

Currently, Kernel doesn't allow setting arbitrary table properties other than the `delta.*` properties that Kernel understands. We have valid use cases where we need to allow storing properties with arbitrary key names.
As part of this, we also don't want to set any `delta.*` properties that Kernel doesn't understand or supports yet.
UTs
Now the connectors can property with any name.
Resolves #3149

[Kernel] Allow setting arbitrary properties when creating/updating the table

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/LogSegment.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/FileStatus.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/snapshot/LogSegmentSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CheckpointV2ReadSuite.scala

This PR does some misc improvements:
- turn public member values in LogSegment to be private; add proper getters
- add better validation
- add isComplete and toString methods
- add toString method in FileStatus
New UTs
No.

[Kernel] More LogSegment cleanup and refactor

---

docs/source/delta-utility.md

Remove the section about "easily converting Delta to parquet" from the docs. This section is very misleading as this doesn't work with anything but the most trivial of Delta tables with no parquet-incompatible features enabled. For the majority of modern Delta tables, the only real option to achieve this is via CTAS or equivalent that rewrites the contents as parquet, rather than an in-place conversion.
n/a
Yes, the docs look different^^

[Docs] Remove section about converting Delta back to parquet

---

sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceCMSuite.scala
spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWidening.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWideningMetadata.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWideningMode.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceMetadataEvolutionSupport.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/sources/DeltaSourceMetadataEvolutionSupportSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningStreamingSourceSuite.scala

Streaming reads from a Delta source currently don't allow any form of type change to be propagated: the stream fails with a non-retryable error. Type widening introduced the ability to change the type of an existing column or field in a Delta table.
This change allows widening type changes to be propagated during streaming reads from a Delta source. The same mechanism as non-additive schema changes from column mapping (Drop/Rename) is applied.
To allow widening type changes to propagate, the user must:
- Provide a schema tracking location via `.option("schemaTrackingLocation", ..)`
- Review and accept the type change by setting one of the available SQL confs (detailed in the error message)
Note that the current check for column mapping had a loophole: as long as a schema tracking location …

[Spark] Handle type widening in Delta streaming source

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaDataSource.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuite.scala

User-specified schema may come from the catalog if the Delta table is stored in an external catalog that syncs the table schema with the Delta log. We should allow it if it's the same as the real Delta table schema.
This is already the case for batch read, see https://github.com/apache/spark/pull/15046
This PR changes the Delta streaming read to allow it as well.
Note: since Delta uses DS v2 (`TableProvider`) and explicitly claims that user-specified schema is not supported (`TableProvider#supportsExternalMetadata` returns false by default), end users still can't specify schema in `spark.read/readStream.schema`. This change is only for advanced Spark plugins that can construct logical plans to triggers Delta v1 source stream scan.
a new test
No

allow user-specified schema in read if it's consistent

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/DeletionVectorDescriptor.scala

In this PR, we extract helpers for building the file name and for extracting DV prefix and UUID in DeletionVectorDescriptor to clean up the code a little and make testing easier in the future.
Simple refactors. Existing tests pass.
No.

[Spark][Refactor] Create helpers for DeletionVectorDescriptor

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaDataSource.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuite.scala

backport https://github.com/delta-io/delta/pull/3929/ to 3.3
User-specified schema may come from the catalog if the Delta table is stored in an external catalog that syncs the table schema with the Delta log. We should allow it if it's the same as the real Delta table schema.
This is already the case for batch read, see https://github.com/apache/spark/pull/15046
This PR changes the Delta streaming read to allow it as well.
Note: since Delta uses DS v2 (`TableProvider`) and explicitly claims that user-specified schema is not supported (`TableProvider#supportsExternalMetadata` returns false by default), end users still can't specify schema in `spark.read/readStream.schema`. This change is only for advanced Spark plugins that can construct logical plans to triggers Delta v1 source stream …

[3.3] allow user-specified schema in read if it's consistent (#3929)

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

Currently, in DataFrame's `option` API, if users specified a value that causes `NullPointerException` for the `delta.columnMapping.mode`, then a `NullPointerException` exception is thrown.
This exception is rather unclear for users, so for this case, we are throwing the user-facing `DeltaIllegalArgumentException` instead.
I checked all the `DeltaConfigs`, it seems that only Column Mapping mode faces this problems, all other DeltaConfigs are
1. Accepts `null` as a valid value.
2. Throws `IllegalArgumentException`.
3. Throws an user-facing exception for null cases.
Added UT.
Specifying `option("delta.columnMapping.mode", null)` will now throw a `DeltaIllegalArgumentException` instead of `NullPointerException`.

[Spark] Throw user-facing exception when the value specified for delta.columnMapping.mode in DF's option causes NullPointerException

---

spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCStreamSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceLargeLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

+ Unify the `modifyCommitTimestamp` helper functions to avoid code duplication.
+ Extend existing streaming tests to run with coordinated commits
Run the new tests
No

[Spark] Extend streaming tests with coordinated commits (1/2)

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaSinkImplicitCastSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSinkSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceTableAPISuite.scala

Extend existing streaming tests to run with coordinated commits
Run the new tests
No

[Spark] Extend streaming tests with coordinated commits (2/2)

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/PrepareDeltaScan.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/DataSkippingDeltaTests.scala

This is a follow-up to the previous attempt to handle double-filtering of non-deterministic conditions (e.g. rand() < 0.25) in https://github.com/delta-io/delta/pull/4095.
It prevented non-deterministic filters from appearing in `unusedFilters` in the `ScanReport` unless we added special pipelining for them from `PrepareDeltaScan` to `filesForScan`.
This is also inconsistent with how we skip `subqueryFilters`. We now treat `filesForScan` as the narrow waist to skip any filters.
UTs
No

[Spark] Skip non-deterministic filters in Data Skipping to prevent incorrect file pruning in Delta queries

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActionsIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActiveAddFilesIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java

Implemented a minor performance improvement to not read any RemoveFiles when we read checkpoint Parquet files during active-add-file-log-replay. Fixes #4102
Existing unit test, manual test using
delta/kernel/examples/run-kernel-examples.py --use-local
and
./run-tests.py --group kernel
No

[Kernel] During Active-AddFile-Log-Replay do not pass the RemoveFile to checkpoint reader

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checkpoints/Checkpointer.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala

This PR moves `SnapshotManager::checkpoint` to `Checkpointer` class. This reduces coupling and increases cohesion.
I also tidy up some code and logger statements along the way.
Just a refactor. Existing UTs.
No.

[Kernel] [Cleanup] Move `SnapshotManager::checkpoint` to `Checkpointer` class

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checkpoints/Checkpointer.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableFeaturesSuite.scala

Currently, we pass optional `Metadata` to `validateReadSupportedTable`, which is just used for checking whether it has supported column mapping mode. We don't need to check that as if an unknown mode is passed, it will anyway fail later on. Also if a new mode is added, it will be part of a new table feature
Also for `validateWriteSupportedTable`, we pass the `schema` and `metadata` separately. Instead just passing the `metadata` (which has the `schema`) should be sufficient.
The implementation of these APIs going to change in the subsequent PRs.

[Kernel] Minor cleanup of APIs used for checking read/write supported protocol

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala

Once bucket partition to nonpartition is enabled for a table, the clone from iceberg table will always convert bucket partition to non-partition for that table, regardless of if the flag is turned off or not in the future. This is to make those tables forward compatible with future Deltas where "truly" bucket conversion is supported so they will keep the old behavior and won't make regressions
Existing UTs

Preserve enablement for converting Iceberg table with bucket partition to unpartitioned delta table in table property

---

spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

This PR modifies the nested filed name normalization code. This code is used when we write to a Delta table. It makes sure that the names of all the columns in the source data (meaning, the data that we are writing to the table) match the target table column names in terms of case. For example, if the source contains column `address.CITY`, while the table contains column `address.city`, the source column is renamed to match the table.
If the schema of the source data and the table data differs enough to interfere with the name normalization, we log `delta.assertions.schemaNormalization.nonNestedTypeMismatch`. However, this check is too restrictive, and as a result, we log this assertion too often. This PR relaxes the check. We now assume that any two atomic columns can be matched to each …

[Spark] Relax type check in `SchemaUtils.normalizeColumnNamesInDataType`

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala

This utility method can be used to filter for columns with invariants or a certain data type (timestamp_ntz, variant, etc.) to implicitly identify the table features that should be enabled.
Unit tests.

[Kernel] Add utility to filter for columns in a schema

---

spark/src/main/scala/org/apache/spark/sql/delta/UpdateExpressionsSupport.scala

This PR changes the logic of data type casting in DML operations, so that when the expression has the desired output type no cast will be performed. This is to avoid a performance issue when the expression is slow to evaluate, such as for array functions on an array of structs, i.e., `array_*(array<struct<...>>, ...)`.
For example, given `array_distinct(physical_ids)` inside a WHEN UPDATE clause:
```
CASE WHEN (size(physical_ids#270, false) = 0) THEN array_except(physical_ids#1611, []) ELSE [] END
```
It will be first transformed into 
```
array_distinct(transform(physical_ids, (_, idx) -> physical_ids[idx]))
```
and then to 
```
transform(
when(size(to_add) != 0, array_distinct(physical_ids), to_remove),
(_, idx) ->
when(size(to_add) != 0, array_distinct(physical_ids), to_remove)[idx] …
```

[Spark] Do not cast data type when not needed in DML commands

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/FeatureAutoEnabledByMetadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeature.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/CaseInsensitiveMap.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala

Add APIs to define a table features and various properties/behaviors of the Table features
Check the `TableFeature.java` for the API details. Most of the APIs follow the Delta-Spark model, except Kernel adds two new additional APIs (`hasKernelReadSupport` and `hasKernelWriteSupport`) to make sure the Kernel has the support. This is because Kernel is in the middle of development and not both read and write are implemented for every feature.
UTs

[Kernel] Unify table feature logic into structred APIs

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingFileIndex.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeFileIndex.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaTestImplicits.scala

`TahoeLogFileIndex` contains `DeltaLog::update` calls but it does not pass in the catalog table yet. This causes the check for catalog table existence unreliable in `DeltaLog::update`. This PR fixes that by adding the catalog table argument to `TahoeLogFileIndex` and pass the catalog table from `DeltaLog::createRelation`
Run existing unit tests
No

[Spark] Pass catalog table through TahoeLogFileIndex

---

.github/workflows/connectors_test.yaml

actions/cache@v2 is being deprecated
- https://github.com/actions/cache/discussions/1510
- https://github.com/actions/toolkit/discussions/1890
This PR job caught the brownout https://github.com/delta-io/delta/actions/runs/13396661811/job/37417276819?pr=4127
Upgrades connectors workflow which is still on v2.
CI test suffices.
No

[Infra] Update actions/cache version for connectors

---

spark/src/main/scala-spark-3.5/shims/DecimalPrecisionTypeCoercionShims.scala
spark/src/main/scala-spark-master/shims/DecimalPrecisionTypeCoercionShims.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/TypeWideningMode.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaMergingUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

All code paths implementing type widening so far had a clear 'before' and 'after' schema and checked that 'before' could be widened to 'after'.
An additional use case is, given two schemas from two separate flows, to compute wider schema from the two.
To support this, 'bidirectional' widening modes are added to `SchemaMergingUtils.mergeSchemas()`.
These allow picking the wider of the two input types, or, for decimals, picking a decimal type that is wider than each input.
Added unit tests for `SchemaMergingUtils.mergeSchemas()`.

[Spark] Add order-agnostic type widening modes

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/InMemoryLogReplay.scala

Refactor remove file hashset in InMemoryLogReplay into activeRemoveFiles and cancelledRemoveFiles, because they are semantically different that the later had cancelled an AddFile, while the former did not. 
existing UT.

Refactor remove file handling in InMemoryLogReplay

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingStatsTracker.scala

This PR uses MutableProjection.create instead of directly generating the MutableProjection via GeneratMutableProjection.generate. As the latter forces codegen, it can fail if the generated code is too large, which, e.g., can happen for very wide schemas. The new code uses the correct Spark API to automatically fall back to an InterpretedMutableProjection if codegen fails for any reason.
This PR just uses the correct, higher-level API call to create a MutableProjection so existing tests are sufficient.
No

[Spark] Honor codegen configs in DataSkippingStatsTracker

---

spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CommitCoordinatorClientImplSuiteBase.scala

The helpers for commit coordinator tests currently write plain strings for commits. This PR switches these helpers to use actual commit json instead so that the log generated by these helpers are correctly formatted.
No

[Spark] Use correctly formatted commit in CommitCoordinatorClientImplSuiteBase

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/uniform/UniFormE2ESuite.scala

When converting timestamp partition values from Delta to Iceberg, currently we're doing the microsecond conversion incorectly. This leads to every conversion just returning the Unix epoch timestamp.
In the current approach we're using some utilities from Iceberg, such as DateTimeUtil.microsFromInstant which already have implemented this logic correctly.
There were unit tests that should've caught this earlier by testing the Iceberg spark session as a reader, but they were passing just because the wrong read method was used. This PR fixes that as well.
I fixed existing unit tests since they should've caught this.

Uniform: Fix microsecond conversion for timestamp/ntz partition value

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/IcebergCompatV2Utils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/TransactionStateRow.java

Just itty bitty clean up -- reduces changes in add/remove action API prototype.
No

[Kernel] Itty bitty refactor

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala

Currently, the `ColumnMapping.verifyColumnMappingChange` takes just the new properties as the argument for the new configuration. This is incorrect, as the method looks for the CM mode based on the new complete config.
Also missing the test coverage for this. Add a new test.

[Kernel] Fix config passed to the column mapping mode change validation method

---

spark/src/main/scala/org/apache/spark/sql/delta/storage/dv/DeletionVectorStore.scala

Right now, we are only logging for delta.deletionVector.write.offsetMismatch. In this PR, we trigger an exception at the time of writing the DV, so before we make a commit to the table. It'll fail the specific query, but won't put the table in a broken and unreadable state. We also change the log from delta.deletionVector.write.offsetMismatch into a delta assertion. 
Existing tests pass.
Yes. If we detect an issue related to the file size while writing Deletion Vector files, we will now throw an exception at the time of writing the DV, before we make a commit to the table. This will fail the specific query, but will prevent the table from being in an unreadable state.

[Spark] Throw an exception on write for DV size mismatch

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLogFileIndex.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaUDF.scala
spark/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/TableFeatureSupport.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckpointProtectionTestUtilsMixin.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala

`CheckpointProtectionTableFeature` requires clients to only cleanup metadata if they can clean up to `requireCheckpointProtectionBeforeVersion`. When this this not possible the metadata cleanup operation aborts. `requireCheckpointProtectionBeforeVersion` is updated with the version of the latest protocol downgrade every time a feature is dropped. Because of that, in certain scenarios, metadata cleanup could halt for extended periods of time.
This PR improves this behavior by allowing the client to proceed with metadata cleanup when the invariant above does not hold, as long as, a checkpoint already exists at the cleanup cut off version. If none of the invariants hold, it verifies it supports the protocols of all commits planning to remove (including any new checkpoint creation version). …

[Spark] Add protocol validation in Metadata cleanup based on CRCs

---

spark/src/main/scala/org/apache/spark/sql/delta/constraints/CheckDeltaInvariant.scala
spark/src/main/scala/org/apache/spark/sql/delta/constraints/DeltaInvariantCheckerExec.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TransactionalWrite.scala

This PR simplifies the binding of attribute references in `DeltaInvariantCheckerExec`. Before this PR we had some code to manually bind these references. This PR changes this to make Spark do the binding for us.

[Spark] Simplify reference binding in DeltaInvariantChecker

---

spark/src/main/scala/org/apache/spark/sql/delta/redirect/TableRedirect.scala

This PR removes comments from TableRedirect.scala.
N.A

[Spark] Fix Table Redirect Comment

---

examples/python/using_with_pip.py
python/run-tests.py

Add Google maven repo as an option for dependency lookup. Currently it defaults to maven central which has lower rate limits.
Locally tested, by setting `0.0.0.0		https://repo1.maven.org/maven2/` in `/etc/hosts` (request to maven central fails and should try to use other repos)

[Build] Add google maven repo as an option in `spark-submit` tests

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala

The `DeltaCatalog::alterTable` accepts a list of table changes. However, we are currently committing the column changes in separate transactions. This PR does the following refactoring:
+ introduces `DeltaChangeColumnSpec` as arguments to `AlterTableChangeColumnDeltaCommand` so that we can pass multiple changes and commit them in one transaction.
+ updates `DeltaCatalog::alterTable` to collect the column changes into `DeltaChangeColumnSpec`
+ for SYNC IDENITY, `DeltaCatalog::alterTable` previously has a single syncIdentity variable for all table changes to denote whether to run sync identity or not. This PR fixes that and record the sync identity parameter separately for each column.
No

[Spark] Support committing multiple column changes in one txn

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala

This PR adds extra metrics for fast drop feature.
N/A.
No.

[Spark] Add extra metrics for Fast Drop Feature

---

build.sbt
python/delta/integration_tests/unity-catalog-commit-coordinator-integration-tests.py
run-integration-tests.py
spark/src/main/java/io/delta/dynamodbcommitcoordinator/integration_tests/dynamodb_commitcoordinator_integration_test.py
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CommitCoordinatorClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/UCCommitCoordinatorBuilder.scala
spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CommitCoordinatorClientImplSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/InMemoryUCClient.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/InMemoryUCCommitCoordinator.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/UCCommitCoordinatorBuilderSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/UCCommitCoordinatorClientSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/UCCommitCoordinatorClientSuiteBase.scala
storage-s3-dynamodb/integration_tests/dynamodb_logstore.py
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/CommitLimitReachedException.java
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/InvalidTargetTableException.java
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UCClient.java
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UCCommitCoordinatorClient.java
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UCCommitCoordinatorException.java
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UCCoordinatedCommitsUsageLogs.java
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UCRestClientPayload.java
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UCTokenBasedRestClient.java
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UpgradeNotAllowedException.java

This PR follows up on https://github.com/delta-io/delta/pull/3837 adding support for Delta tables in delta-spark with Unity Catalog (UC) as the Commit Coordinator. 
See [Delta Coordinated Commits RFC](https://github.com/delta-io/delta/blob/master/protocol_rfcs/managed-commits.md) or [PROTOCOL.md](https://github.com/delta-io/delta/blob/master/PROTOCOL.md) for more information on the coordinated commits and its benefits.
Feature Request: https://github.com/delta-io/delta/issues/3836
[Design Doc](https://docs.google.com/document/d/1l2iql3e6rW06sQ8VQLdyjAtNW3NnWkOx1oyJC9B7tdM/edit?usp=sharing)
<!--
Unit Tests added in PR.
No.

[Spark] Unity Catalog (UC) as Commit Coordinator for Delta tables

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingLogFileSystem.scala

Improve logging in DeltaSharingLogFileSystem for delta sharing queries 
Unit Tests
No

Improve logging in DeltaSharingLogFileSystem for delta sharing queries 

---

spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala

This allows dropping RedirectWriterOnlyFeature and RedirectReaderWriterFeature
`DeltaProtocolVersionSuite.scala`
No

Make Redirect Table Features Droppable

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala

This PR contains a tiny fix of the redirect path reconstruction. The original getPath method would erase cloud vendor prefix: s3, abfs, etc.
Existing test case
No.

[Spark] Fix redirect path reconstruction

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Protocol.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/actions/ProtocolSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala

Adds new unit tests for timestampNtz writes. Note that most of the write functionality (creation, inserts, insert with partition columns) are already exercised by  DeltaTableWritesSuite. This PR adds a few more tests.
Fixes #4103
New unit tests
No

[Kernel] New tests for Timestamp_NTZ writes

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala

When converting timestamp partition values from Delta to Iceberg,
currently we're doing the microsecond conversion incorectly. This leads
to every conversion just returning the Unix epoch timestamp.
In the current approach we're using some utilities from Iceberg, such as
DateTimeUtil.microsFromInstant which already have implemented this logic
correctly.
There were unit tests that should've caught this earlier by testing the
Iceberg spark session as a reader, but they were passing just because
the wrong read method was used. This PR fixes that as well.

[updated][Uniform] Fix microsecond conversion for timestamp/ntz partition value

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/deletionvectors/DeletionVectorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/storage/dv/DeletionVectorFileSizeSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/util/BinPackingIteratorSuite.scala

Currently, it is possible for BinPackingIterator to create Deletion Vector files that are much bigger than the target size specified (default 2MB) because DeletionVectorData.size() only returns the size of the intermediate results and not the combined size with the persisted deletion vector.
In this PR,
* We add the size of the existing persistent DV to the size calculation in DeletionVectorData.
* We add some additional safeguards around the DV target size -- we bound it to [0, 1.5GB].
* If we detect overflow in DeletionVectorData, we will bump the size to Int.Max so that the erroneous item goes into its own bin. If the size is overflowing, it will likely fail later when we try to write the DV since it's oversized.
* We add the fixed cost of adding checksums to every DV to the size of …

[Spark] Take existing DV size into account in DeletionVectorData size

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergSparkWrappers.scala

- [] Other (fill in here)
Fix NPE in IcebergFileManifest when partitions is null
UT

[UniForm] Fix NPE in IcebergFileManifest when partitions is null

---

spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteringColumn.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteringColumnSuite.scala

Previously, we'd try casting the data type of the previously-found column into a StructType blindly, even if it was not of a StructType. This was problematic if the cluster by clause contained a column reference that did not exist; we'd return a ClassCastException instead of a column not found exception. This change addresses that.
Unit tests
No

[Spark] Fix exception type for missing nested clustering column

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/test/scala/org/apache/spark/sql/delta/GeneratedColumnSuite.scala

This PR fixes a `PLAN_VALIDATION_FAILED_RULE_EXECUTOR` error that occurs when reading the CDF of a commit range that contains no file actions and when reading a generated column. In this case `DeltaCDFRelation.buildScan` will add a `Project` or `Filter` containing `AttributeReference`s with empty `metadata` on top of a plan where the `metadata`. This will cause `hasUniqueExprIdsForOutput` to trip, but only if the plan does not contain a `Union`, which is only the case when reading the CDF of a commit range without any file actions.
The fix is to substitute the attribute references in the projections and filters entirely, instead of just patching up the expression ids. (I am not sure why I didn't simply do this in the first place.)
Modified an existing test to reproduce the error.
No

[Spark] Fix error when reading empty CDF of generated column

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala

The method `listFromOrNone` only has one call site so removing it and inline its implementation at that call site.
Existing UTs
No

[Spark] Remove listFromOrNone in SnapshotManagement

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Metadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergCompatMetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/InCommitTimestampUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaIcebergCompatV2Suite.scala

Reorganizes the order of metadata updates and validation in `TransactionBuilder`. When building the transaction the metadata may be updated many different ways including new user provided properties, new user provided schema, transitive property changes based on enabled confs (e.g. enabling `IcebergCompatV2` enables column mapping). We should be sure to perform any validation AFTER any metadata changes have been made, less we miss something. This PR reorganizes the transformations to do transformations first and then validation.
Examples of how this could go wrong
- Right now we only block changing cmMode none -> id (which not allowed for existing tables) when newProperties are set by the user. However, cmMode confs may change after during the `IcebergCompat` checks. We should perform …

[Kernel] Reorganize metadata updates in TransactionBuilder to clearly delineate what happens when for updates + validation

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultFileSystemClient.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/fileio/FileIO.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/hadoopio/HadoopFileIO.java

Removes the need for one another API.

[Kernel][Defaults] Remove redundant `FileIO.readFiles`; instead use `FileIO.newInputFile` for reads

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala

This PR adds a method to get the version at the base of a transaction. This is useful information to know about a transaction

[Kernel] Add `getReadTableVersion` method to `Transaction`

---

sharing/src/main/scala/io/delta/sharing/spark/PrepareDeltaSharingScan.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/PrepareDeltaScan.scala

Plumb the CatalogTable through PreparedDeltaFileIndex. This is a continuing effort to support coordinated commits.
Existing UTs
No

[Spark] Plumb CatalogTable through PreparedDeltaFileIndex

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala

This PR fixes an issue where REPLACE in uniform mode is not setting field IDs correctly.
The uniform conversion was not successful in the following situation:
1. Create a table with uniform mode and a schema with two fields
2. Replace the table with a new schema with one field
This is because currently we don't assign field IDs based on the previous last_column_id on replace table operations, which is not compatible with Iceberg's approach to field ID assignment.
For context, iceberg field id assignment will always starts from previous last_column_id, with reusing only the name matches.
https://github.com/apache/iceberg/blob/c7f3919f847ae8c4f661299fd0a64db4dde1a583/core/src/main/java/org/apache/iceberg/TableMetadata.java#L727C55-L727C67 …

[Uniform] Make field id assignment for uniform table same as Iceberg's behavior

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdater.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdaterSuite.scala

Blocks "typeWidening-preview" feauture with icebergCompatV2.
Updates unit tests.

[Kernel] Block typeWidening-preview feature with icebergCompatV2

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala

This PR adds a new test case for restoring table with column mapping enabled.
For src code, it make small refactor with no functional change
Added test
No

[Uniform]Add test for restore with name column mapping enabled

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaCommand.scala

In the case when `DeltaCommand.parsePredicates` throws a NullPointerException due to null predicate, throw a more user friendly error.
Not necessary.
Yes, user will get an `DELTA_FAILED_RECOGNIZE_PREDICATE` error instead of `NullPointerException`.

[Spark] Add user facing error for null predicate

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaChanges.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala

- [X ] Kernel
This change adds an internal SchemaChanges class which will be used to keep track of differences between Schema evolutions, and also adds a computeDiffByID package private method which will be used in future validation. 
This is breaking away some of the changes from https://github.com/delta-io/delta/pull/4196
Added unit tests
No

Kernel: Add package private SchemaChanges and SchemaUtils#computeDiffById

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultFileSystemClient.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultJsonHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultParquetHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/fileio/FileIO.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/fileio/InputFile.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/hadoopio/HadoopFileIO.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/hadoopio/HadoopInputFile.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFileReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFileWriter.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetStatsReader.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/benchmarks/BenchmarkParallelCheckpointReading.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CheckpointV2ReadSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetReaderPredicatePushdownSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetSuiteBase.scala

Length can be useful when readers want to optimize (for example, in Parquet reader to find the location of metadata and seek there directly rather than making a call to the filesystem to get the size). In Kernel's case we already have the information from Delta Log. Pass the length as new argument to `FileIO.newInputFile`.

[Kernel][Defaults] Add `fileSize` as argument to `FileIO.newInputFile` when reading

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java

Loading domainMetadatas from snapshot is expensive as it involves reading checkpoints and commit files.
Pending tests

[Kernel] In txn with no domainMetadata updates, skip loading domainMetadatas from snapshot

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdater.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

Parent issue https://github.com/delta-io/delta/issues/4289
Integrates the `IcebergWriterCompatV1MetadataValidatorAndUpdater` added in https://github.com/delta-io/delta/pull/4291 to the transaction write path. This means after this PR when writing to a table with `IcebergWriterCompatV1` enabled, or when enabling `IcebergWriterCompatV1` we will perform the necessary metadata validations and updates.
We currently limit this feature to only be enabled on new tables.
`IcebergWriterCompatV1MetadataValidatorAndUpdater` is already thoroughly tested in `IcebergWriterCompatV1MetadataValidatorAndUpdaterSuite` but we also add an E2E test suite that tests all the validation  & use cases (& covers the protocol upgrades for this feature).
Yes, after all tasks in …

[Kernel][icebergWriterCompatV1 - PR#3] E2E integration of IcebergWriterCompatV1 metadata validator + updater into transaction

---

spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaSQLTestUtils.scala

https://github.com/delta-io/delta/pull/4131 Added some utility methods in  `DeltaSQLTestUtils` class, however one of the method still had the check that it was being called for string columns, even though now we can call it on arbitrary column types; so I am just removing this simple assertion.
No testing required.
No.

[SPARK] Remove left over assertion from util method in DeltaSQLTestUtils

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java

Removes duplicate additions to the HashMap for TableConfig
Resolves #4315
N/A
No
Signed-off-by: Micah Kornfield <micah.kornfield@databricks.com>

[Kernel] Remove duplicate addConfig entries in TableConfig.java

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/io/delta/tables/DeltaMergeBuilder.scala
spark/src/main/scala/org/apache/spark/sql/delta/ResolveDeltaMergeInto.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoNotMatchedBySourceSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoScalaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala

Update MERGE tests to use `checkError` instead of inspecting error messages.
Also cleans up error `_LEGACY_ERROR_TEMP_DELTA_0011`, a catch all that serves no purpose and hides information, failures to resolve the MERGE plan will anyway result in a proper error message.
Updated tests.

[Spark] Check error classes in MERGE tests

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/AutoCompact.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/ChecksumHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/GenerateSymlinkManifest.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/HudiConverterHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/IcebergConverterHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/PostCommitHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/UpdateCatalog.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaGenerateSymlinkManifestSuite.scala

Currently, the `PostCommitHook::run` method is taking in a `Seq[Action]`. This means the actions must be materialized in memory before passing to this method, which may cause OOM for commit with a large number of actions. This PR changes the type to be an `Iterator[Action]` instead to allow future optimizations where the Actions are read from file on demand.
This change also prompts a change in `GenerateSymlinkManifest` to make sure that the iterator is only used once. Some test refactoring for `DeltaGenerateSymlinkManifestSuite` is also included
No

[Spark] Improve the API of the run method of PostCommitHook

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala

This change is broken away from #4196 as part of schema evolution support. This change adds validation that the updated schema is compatible with the previous schema. Compatibility includes:
1. making sure no new non-nullable fields are added
2. no existing fields are tightened in nullability and no invalid type changes have occurred. 
Note: For now, "invalid type changes" includes any type change but we can later extend this to support whatever type promotion is desired.
This change also cleans up the following:
1. Removing some duplication in the SchemaUtils validateUpdatedSchema suite
2. Removing usage of Longs for field IDs, they will always be 32 bit integers.
Added unit tests
No

[Kernel] Validate updated schema compatibility

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Metadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/actions/MetadataSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableFeaturesSuite.scala

This allows features to be enabled by adding a key value pair of "delta.feature.$feature_name"->"supported" in the table properties when creating a transaction, and have those features enabled for the table.
Disablement is not done in this PR because it is a less common use-case.
Resolves #4331
Unit tests:
1.  Detailed test for new method added on TableFeature
2. Added a more e2e test in DeltaTableFeaturesSuite
3. Introduced a new MetadataSuite for Metadata action method changes.
Yes.  Features can now be turned on in DeltaLake by using `"delta.feature.<feature_name>": "true"` in table properties.  These keys are removed from the configuration so they don't show up in the Metadata action.

[Kernel] Add ability to set table features via configuration properties.

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/DeltaToIcebergConvert.scala
spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala

This PR propagate the user-defined table properties to iceberg metadata, user-defined properties refer to the ones not starting with "delta.".
To avoid breaking change(some user might have started using "delta.universalformat.config.iceberg.abc" to set properties "abc"), we still keep propagating the ones with prefix "delta.universalformat.config.iceberg" by stripping the prefix instead of ignoring them.
However, we will do a duplication check to avoid both "delta.universalformat.config.iceberg.abc" and "abc" are set
Tested with running set tblProperties on spark
No

[Uniform]Propagate the user-defined table properties to Iceberg metadata

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala

Currently when we reconstruct the snapshot, we incorrectly record the old snapshot as the new one. This PR fixes it.
Existing tests to catch regressions.
No

Fix the logging bug where we use the incorrect snapshot

---

spark/src/main/scala/org/apache/spark/sql/delta/redirect/TableRedirect.scala
spark/src/test/scala/org/apache/spark/sql/delta/TableRedirectSuite.scala

When both redirect-rw and redirect-w configuration exist, we want redirect-rw take precedence over redirect-w. 
`TableRedirectSuite.scala`
No

Fix Redirect so that redirect-rw take precedence over redirect-w

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergFileManifest.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergStatsUtils.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/commands/convert/IcebergStatsUtilsSuite.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

This PR proposes to
* Avoid slow stats conversion fallback for iceberg clone by default
* Allow partial stats conversion for iceberg clone by default
More specifically,
* When stats conversion from iceberg off, fallback to slow stats conversion enabled
* When stats conversion from iceberg on, fallback to slow stats conversion will not happen if partial stats conversion enabled. It will only happen if partial stats conversion disabled and iceberg source has partial stats - either minValues or maxValues is missing
UTs
**Current**: delta tables cloned from iceberg source with only partial stats will collect stats from parquet footers. Here, partial stats means any of (maxValues, minValues, nullCounts) is missing
**Future**: delta tables cloned from iceberg source with only partial stats will …

 Avoid slow stats conversion fallback for iceberg clone

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala

A previous refactoring https://github.com/delta-io/delta/pull/4314/ introduced a bug that may cause an iterator to be used more than once. This PR fix this issue.
Existing tests
No

[Spark] Fix double-use iterator bug

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/DeltaToIcebergConvert.scala
spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala

Revert "[Uniform]Propagate the user-defined table properties to Iceberg metadata (#4357)"
This reverts commit 39af931dda3a2a0f66870e7f75f9e5d164939298.
We need more discussion of behavior and error code

Revert "[Uniform]Propagate the user-defined table properties to Iceberg metadata (#4357)"

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergFileManifest.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergPartitionConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala

Small refactor in IcebergTable util for CONVERT TO DELTA avoid having to rely on the entire IcebergTable implementation. This scopes the available methods more closely to target what's actually needed for conversion.
Existing tests should suffice - refactor only.
No

[Spark] Minor refactor to IcebergTable util

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaColumnMappingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

Part of https://github.com/delta-io/delta/issues/4289
Per-the-RFC when icebergWriterCompatV1 is enabled we want column mapping physicalName to be equal to `col-[fieldId]`. This PR enforces that as part of our icebergWriterCompatV1 metadata validations, and also updates our column mapping code to follow that behavior when icebergWriterCompatV1 is enabled.
Adds new tests and modifies existing tests to check the new changes.

[Kernel][IcebergWriterCompatV1] Update column mapping so physicalName='col-{columnId}' and enforce this as part of our checks

---

spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala

The unique id for a file action should be file path + dv id (if existing). The PR fixes `uniqueFileActionGroupBy` in `CloneTableSuiteBase.scala` by taking dv id into account when constructing group by id of a file action to make the method work when dv is enabled.
Test only change.
No.

[SPARK] Fix uniqueFileActionGroupBy in CloneTableSuiteBase.scala

---

spark/src/main/scala/org/apache/spark/sql/delta/DefaultRowCommitVersion.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/GenerateRowIDs.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaParquetFileFormatSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdSuite.scala

This PR:
- Renames `nullableRowTrackingFields` in `DeltaParquetFileFormat` to `nullableRowTrackingGeneratedFields`.
- Adds another field called `nullableRowTrackingConstantFields` in `DeltaParquetFileFormat`, which allows reading row ids and row commit versions when the `baseRowId` and `defaultRowCommitVersion`s are missing (returning a NULL in this case).
- It adds a helper function `transformFileFormat` to `DeltaTableUtils` to make it easier to set the new field.
Added a test to `RowIdSuite`.
No

[Spark] Add option to DeltaParquetFileFormat to allow missing Row Tracking metadata fields

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

Part of https://github.com/delta-io/delta/issues/4289
Per the RFC https://github.com/delta-io/delta/pull/4285 we should allow the legacy table features to be present in the table protocol if they are inactive for icebergWriterCompatV1.
Adds/updates tests.

[Kernel][icebergWriterCompatV1] Allow legacy features to be in the table protocol if they are inactive

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergUniversalFormatMetadataValidatorAndUpdater.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableConfigSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergUniversalFormatMetadataValidatorAndUpdaterSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableFeaturesSuite.scala

This added Uniform TableConfig properties and a validator/updater for metadata that ensures uniform values for iceberg are not set unless table compat v2 is not set.  The existing delta code is [here](https://github.com/delta-io/delta/blob/ae4a83fb879259b10807ce02166c188c04214aab/spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala#L169) for reference)
Resolves #4374
Added tests for:
* TableConfig property
* The updater/validator
* An additional e2e test in DeltaTableFeaturesSuite
Yes, it allows users to set Universal format table properties.

[Kernel] Add Universal format TableConfig.

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrorsInternal.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/GenerateIcebergCompatActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/TransactionMetrics.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/TransactionMetricsResult.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/TransactionReportSuite.scala

Follow-up to https://github.com/delta-io/delta/commit/bdd3c520ca20c03733d07bfff4261c2ebfc8db90.
Adds and updates unit tests.
No

[Kernel] Add `removeFileSizeInBytes` to transaction metrics and increment when removes are committed

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaFileProviderUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala

The current error message of `DeltaVersionsNotContiguousException` needs to be improved in order to provide detailed context regarding the table state when throwing the exception.
Specifically, we add `startVersion`, `endVersion`, and `versionToLoad` to the error message, which could be useful to identify the table state and potentially help investigate the root cause of `DeltaVersionsNotContiguousException`.
In addition, we add detailed logging (`usage_log`) to provide more specific context when throwing `DeltaVersionsNotContiguousException`, which includes the entire calling stack and could help improve future visibility.
Through UTs in `SnapshotManagementSuite`.
Improve the error message of the user-facing `DeltaVersionsNotContiguousException`.

[Spark] Improve `DeltaVersionsNotContiguousException` error message & add extra logging

---

spark/src/main/java/io/delta/dynamodbcommitcoordinator/integration_tests/dynamodb_commitcoordinator_integration_test.py
spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/AbstractBatchBackfillingCommitCoordinatorClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaCommitFileProvider.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/FileNames.scala
spark/src/test/scala/org/apache/spark/sql/delta/FileNamesSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
storage/src/main/java/io/delta/storage/commit/CoordinatedCommitsUtils.java
storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/InvalidTargetTableException.java
storage/src/test/scala/io/delta/storage/commit/InMemoryCommitCoordinator.scala

Per [Catalog-Owned RFC](https://github.com/delta-io/delta/pull/4382), we decided to use `_delta_log/_staged_commits/` folder to store all staged/unbackfilled commit files, which is different from [Manged Commits RFC](https://github.com/delta-io/delta/blob/master/protocol_rfcs/managed-commits.md)'s `_delta_log/_commits/` folder.
This PR changes the `COMMIT_SUBDIR` in both `CoordinatedCommitsUtils.java` and `FilesNames.scala`, plus update all the relevant comments/UTs.
Through existing UTs.
No, the change for commit subdirectory should **_not_** be a user-facing change.

[Spark] [Catalog-Owned] Use `_staged_commits/` folder for staged/unbackfilled commit files

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CommitCoordinatorClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/InMemoryCommitCoordinator.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/UCCommitCoordinatorBuilder.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CatalogOwnedEnablementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowtracking/RowTrackingConflictResolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaTestImplicits.scala

This PR implements the RFC "CatalogOwned" table feature to Delta-IO. https://github.com/delta-io/delta/pull/4382
Existing & New unit tests. More tests will be added.
No.

[Spark] Implement CatalogOwnedTableFeature

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checksum/CRCInfo.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/TransactionMetrics.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/stats/FileSizeHistogram.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/FileSizeHistogramResult.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/TransactionMetricsResult.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/checksum/ChecksumWriterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumSimpleComparisonSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/TransactionReportSuite.scala

Reads the fileSizeHistogram from CRC and add it as part of transaction metrics. Updates it as the transaction is executed.
Note, this is a little weird since it only adds read support and no write support, so we only actually have histograms available for new tables in E2E tests. But https://github.com/delta-io/delta/pull/4328 will add write support and fill out the full feature afterward. Documented throughout the changes needed when adding write support.
Updates tests.
No

[Kernel] Read the fileSizeHistogram from CRCInfo and propagate it through transaction metrics

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala

Currently, the physical name assignment is case-sensitive when assigning physical names to converted Iceberg tables. This physical name assignment should be case-insensitive (field names aren't case sensitive in Delta).
See test change.
No.

[Spark] Make physical name assignment case-insensitive on the logical field names

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningStreamingSourceSuite.scala

Add an internal config to disable tracking schema used to block widening type changes when streaming from a Delta table.
The default will remain to have schema tracking enabled, this only provides flexibility in case we need to disable this feature.
Added a test to cover the new config.
No

[Spark ]Add config to disable schema tracking for type widening

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/io/delta/tables/execution/VacuumTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala

This PR blocks running vacuum command on catalog owned managed tables. This is a safe guard since with catalog owned tables the clients running vacuum doesn't have complete ownership of the table and instead should go through their catalog to run the vacuum command.
UTs. Added a test to ensure that vacuum is block on catalog owned tables while all the other vacuum test suite still ensures existing behavior is unaffected.
No

[SPARK] Block vacuum on catalog owned managed tables

---

kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/CreateTableAndInsertData.java
kernel/kernel-api/src/main/java/io/delta/kernel/TransactionBuilder.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala

Previously we only threw tableAlreadyExists operation when partition columns or schema was provided on txnBuilder but the table already existed. Now, with schema evolution, we no longer throw that error when withSchema is used, and instead may throw a confusing exception if the intention is to "create table if does not exist".
Instead, we should use the `operation` provided to fail early in the create new table case when it already exists.
Updates tests.

[Backport][Kernel] Throw TableAlreadyExistsException when the table already exists and operation = CREATE_TABLE

---

kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/CreateTableAndInsertData.java
kernel/kernel-api/src/main/java/io/delta/kernel/TransactionBuilder.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala

Previously we only threw tableAlreadyExists operation when partition columns or schema was provided on txnBuilder but the table already existed. Now, with schema evolution, we no longer throw that error when withSchema is used, and instead may throw a confusing exception if the intention is to "create table if does not exist".
Instead, we should use the `operation` provided to fail early in the create new table case when it already exists.
Updates tests.

[Kernel] Throw TableAlreadyExistsException when the table already exists and operation = CREATE_TABLE

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaSharedExceptions.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaThrowableHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/InvariantViolationException.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaConfigSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DomainMetadataSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoNotMatchedBySourceSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/DropColumnMappingFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingSuite.scala

This change refactor Delta errors testing to use `checkError()` instead of `checkErrorMessage()`. This has multiple benefits:
- we can edit the error messages for style without having to alter the test code every time
- we can make sure that the error message template parameters are correctly filled, the number of parameters matches what is expected by the template, and the parameters with the same name are filled with the same value
- we are more consistently testing if the SQL states are set and propagated correctly
To that end, it was necessary to edit some of the exception classes to make sure they expose `getMessageParamters()` method correctly.
Some of the error message were edited to avoid unnamed parameters, and to correct obvious problems with formatting.
I also discovered and …

[SPARK] Refactor error test suites to use `checkError()`

---

protocol_rfcs/README.md
protocol_rfcs/checkpoint-protection.md

This is an RFC for the `checkpointProtection` table feature. The related issue is https://github.com/delta-io/delta/issues/4152.
N/A.
No.

[SPARK][PROTOCOL RFC] Checkpoint Protection

---

kernel/kernel-api/src/main/java/io/delta/kernel/TransactionBuilder.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Metadata.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TablePropertiesSuite.scala

Adds to the txn builder `withUnsetTableProperties` to support removing table properties from the table configuration. For now this only supports user-properties (those that do not start with 'delta.') since there is additional complexity and validation when removing delta properties.
Also fixes a bug where we were writing all user properties to the log with lower-case keys. Looking at delta-spark's behavior user properties should be case-sensitive.
(I can separate this fix into a separate PR but it's a 1 line change + 1 test added so left it together for now)
Adds tests.

[Kernel] Support unsetting user table properties + fix a bug where we write all user properties in lower case

---

spark/src/main/scala/org/apache/spark/sql/delta/GeneratedColumn.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableMerge.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableUpdate.scala
spark/src/test/scala/org/apache/spark/sql/delta/GeneratedColumnSuite.scala

Currently, GeneratedColumn is very strict in MERGE and UPDATE, not accepting anything else than a pure LogicalRelation as the target plan.
This is because, as generated column is defined as a piece of SQL text, it would have issues resolving against a view that does anything more tricky, which we (unfortunately and originally by accident) support, like e.g. if the view was select a as b, b as a from deltaTable, it would confuse the generated column which input columns to use.
Unfortunately, when CHAR columns are present on the table, ApplyCharTypePadding adds a projection with padding, which then Generated Columns does not accept. Refine the check, so that the char padding is allowed. Similar handling has been added in https://github.com/delta-io/delta/pull/1852/files#diff-e68090b34015f52f …

[Spark] Issue with MERGE/UPDATE on target with CHAR column, generated column and readSideCharPadding

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala

This PR passes catalogTable while constructing deltaLog in DeltaTableV2, this allows spark to interact with catalog owned tables as an external client.
E2E integration testing using Delta, Spark and Unity-Catalog
No

[DELTA] Pass catalogTable while constructing deltaLog for DeltaTableV2

---

python/delta/integration_tests/unity-catalog-commit-coordinator-integration-tests.py
python/mypy.ini

This PR expands on the existing python test script to add more e2e tests to cover more use cases using catalog owned tables.
E2E tests using OSS delta, spark and uc.

[DELTA] Add e2e tests for catalog owned managed tables

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala

This PR includes validation for clustering columns. Namely, that clustering columns cannot be dropped.
It allows for schema evolutions where clustering columns are renamed.
Updated/added new unit tests
The `withSchema` API will allow certain operations like renames to be performed on clustering columns

[Kernel] Schema validation for clustering columns

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CatalogOwnedEnablementSuite.scala

This PR explicitly/intentionally blocks `ALTER TABLE` command from modifying dependent properties (e.g., ICT) for Catalog-Owned enabled table.
In addition, update/refactor `CatalogOwnedEnablementSuite`.
Through newly added UTs in `CatalogOwnedEnablementSuite`.
N/A

[Spark] [Catalog-Owned] Block ALTER TABLE from modifying Catalog-Owned dependent table feature/properties

---

spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala

This PR fixes a case where CommitCoordinator will stop listing after filesystem listing if previous snapshot did not list any unbackfilled files.
Existing unit tests. More tests will be added as a separate PR.
No

[Spark] Fix CommitCoordinator iterator for CatalogOwned table feature

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala

Moves some generic methods that are not specific to OptimisticTransaction to DeltaTransaction
The methods have been moved as is, existing UTs should cover this change.
No

[Spark] Move some common methods from OptimisticTransaction to DeltaTransaction

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala

This PR includes CatalogOwned-specific logic for `CREATE/REPLACE/CLONE`.
N/A
N/A

[Spark] [CatalogOwned] CatalogOwned specific `CREATE/REPLACE/CLONE` logic

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java

Currently we avoid loading the existing domain metadata whenever no DM is added or removed in the txn. We only need to load existing DM when DM is removed -- further improve this optimization.
Existing tests should suffice that this does not break any functionality. Testing whether we actually load/don't load the DM map is out of scope for now.
No.

[Kernel] Load existing DM metadata in even narrower case -- only when DM are removed (optimization)

---

spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtilsSuite.scala

With the new RFC proposal for the table feature "CatalogOwned" and reject to the existing table feature "CoordinatedCommits", this PR provides a basic conversion to the suite. Note that we still need to keep CoordinatedCommit tests due to all other existing old tests, and we can remove them eventually once we remove/convert all old table feature tests.
This PR is a test.
No

[Spark] Convert CoordinatedCommits table feature test to CatalogOwned

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala

This PR blocks creating delta tables with catalogOwned property set when a non UC catalog is used.
UT
No

[DELTA] Block creating tables from delta with catalog owned property set

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/GenerateIcebergCompatActionUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CommitIcebergActionSuite.scala

When the client call generateIcebergCompatWriterV1AddAction, now they can pass the tags so that it would be persist in the AddFile
Unit tests

[Kernel] Support passing tags for generateIcebergCompatWriterV1AddAction

---

spark-connect/client/src/main/scala-spark-master/io/delta/connect/tables/DeltaTable.scala

The `SparkResult` needs to be closed after it's consumed.
detected by `DeltaTableSuite` with https://github.com/apache/spark/commit/510edd763b912a21883e8a0dbaa3f661fedec234 
no

Close SparkResult to avoid memory leak

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ConflictChecker.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala

Currently we assume every transaction in Kernel is a blind append operation. But we don't actually have any clear mechanism to indicate or require that this is true. For now, we set isBlindAppend=false to ensure safety (as this is always safe to do) and we will revisit how to more accurately set this field in the future (especially if addressing intent-based APIs).
Updated existing unit tests.

[Kernel] Quickfix isBlindAppend field in CommitInfo for writes

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaLogActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/compaction/LogCompactionWriter.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActionsIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/DeltaLogFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/LogSegment.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/FileNames.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/DeltaLogActionUtilsSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/snapshot/LogSegmentSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockFileSystemClientUtils.scala

Splitting up #4443 as requested. This part just lists relevant compaction files and stores them in the `LogSegment`. A follow-on PR will do the work to actually use them during log reply.
This PR includes a boolean to turn on/off listing, but it's just hard-coded to true. I'm happy to just remove that all together, but I suspect we'll want to configure it in the future so figured I'd leave that in.
Unit tests. 
No

[Delta Kernel] List compacted log files in SnapshotManager

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/ClassicMergeExecutor.scala

There were cases when the merge operation could report incorrect `numSourceRows` operation metric if the source side got pruned. Although couldn't reproduce this exact issue, with this PR the metric should be more reliable.
Added a new metric `operationNumSourceRows` which uses `numSourceRowsInSecondScan` if it was a full scan, or `numSourceRows` otherwise. This new metric is reported as `numSourceRows` in the operation metrics.
Didn't add new tests because couldn't reproduce the original issue, but made sure that the added code is covered by the existing test cases, specifically by the `DescribeDeltaHistorySuite` and its metrics tests.
No

[Spark] Make merge operationMetric numSourceRows more accurate

---

project/SparkMimaExcludes.scala
python/delta/tables.py
python/delta/tests/test_deltatable.py
spark/src/main/scala/io/delta/tables/DeltaMergeBuilder.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/AnalysisHelper.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoMetricsBase.scala

- Ensure that all public MERGE APIs return a DataFrame with the affected rows like the SQL API does, so they are all consistent.
- Added some minimal testing to the connector and Python tests.
- Added full coverage to the Scala suite to ensure the results returned always match what goes into the table history (operation metrics).
Yes, the Scala `DeltaMergeBuilder.execute()` now returns a `DataFrame` instead of `Unit`, and so does the Python equivalent (instead of a `None` value).
This is a **breaking** API change, as it can lead the Scala compiler to infer different surrounding types that expect in some places.

[Spark] Make all MERGE APIs return a DataFrame instead of Unit

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaReplaceTableSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/TransactionReportSuite.scala

Supports writing data as part of a REPLACE TABLE transaction. In https://github.com/delta-io/delta/pull/4481 we explicitly blocked this, this PR unblocks it and adds tests for it. Also blocks rowTracking tables for now as we need to spend a little bit more time investigating how to treat rowTracking for `REPLACE` and what the fields in the new adds should look like.
Updates our unit tests.

[Kernel] Support writing data in REPLACE TABLE transactions (RTAS)

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CatalogOwnedEnablementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala

This PR refactors the current `CatalogOwnedEnablementSuite` and adds UTs for `CatalogOwned` dependent features.
Specifically, dropping any `CatalogOwned` dependent features (e.g., `InCommitTimestampTableFeature`, `VacuumProtocolCheckTableFeature`) should be blocked.
Through existing and newly added UTs in `CatalogOwnedEnablementSuite`.
N/A

[Spark] Refactor `CatalogOwnedEnablementSuite` & Add UTs for CatalogOwned dependent features

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CatalogOwnedEnablementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala

Upgraded TemporallyUnstableInputException to user-facing error with proper error class. Reused the existing error class `DELTA_TIMESTAMP_GREATER_THAN_COMMIT`, which is currently being used by streaming reads. Make `DeltaErrors.timestampGreaterThanLatestCommit` also return `TemporallyUnstableInputException`.
Updated existing UTs
No.

[Delta] Upgrade to User-Facing Error with Proper Error Class in Time Travel

---

spark/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuiteBase.scala

Fixes Metadata Cleanup so that checksum files are also considered for removal. Resolves https://github.com/delta-io/delta/issues/4475
Updated DeltaRetentionSuite

[Spark][Version Checksum] Clean up stale checksum files during cleanup

---

python/delta/connect/proto/commands_pb2.py
python/delta/connect/proto/commands_pb2.pyi
spark-connect/client/src/main/scala-spark-master/io/delta/connect/tables/DeltaTable.scala
spark-connect/client/src/test/scala-spark-master/io/delta/connect/tables/DeltaTableSuite.scala
spark-connect/common/src/main/protobuf/delta/connect/commands.proto
spark-connect/common/src/main/scala-spark-master/io/delta/connect/ImplicitProtoConversions.scala
spark-connect/server/src/main/scala-spark-master/io/delta/connect/DeltaCommandPlugin.scala
spark-connect/server/src/main/scala-spark-master/io/delta/connect/DeltaPlannerBase.scala
spark-connect/server/src/main/scala-spark-master/io/delta/connect/DeltaRelationPlugin.scala
spark-connect/server/src/test/scala-spark-master/io/delta/connect/DeltaConnectPlannerSuite.scala

- [] Other
- Adds the following new API to the Scala Delta Connect client : `clone`, `vacuum`, `generate` and `upgradeTableProtocol`.
- Adds the proto definitions for the aforementioned APIs.
- Adds the server-side implementation of the aforementioned APIs.
New tests in `DeltaConnectPlannerSuite` (server-side changes) and in `DeltaTableSuite` (Note: these tests are set to `ignore` until https://github.com/delta-io/delta/pull/4468 is merged)
Yes. 
Adds the `clone`, `vacuum`, `generate` and `upgradeTableProtocol` APIs to the Scala Delta Connect client.

[Spark] Add `vacuum`, `upgrade`, `generate`, `clone` command APIs to Delta Connect (Scala client + server)

---

.github/workflows/spark_master_python_test.yaml
dev/pyproject.toml
dev/requirements.txt
examples/python/table_exists.py
project/Mima.scala
python/delta/pip_utils.py
python/delta/tests/test_deltatable.py
python/delta/tests/test_sql.py
python/run-tests.py
setup.py
spark/src/main/scala/org/apache/spark/sql/delta/DeltaSharedExceptions.scala

Currently we don't run our python tests for our Spark master build since there is no nightly pyspark snapshot, this PR runs those python tests using the latest RC for the Spark 4.0 release. When future RCs are released (or the release published) we will use those instead.
This unblocks the Delta Connect python client development in master, which previously was only merged to the `branch-4.0-preview1` branch since we could not run the python tests in master.
https://github.com/delta-io/delta/pull/4514 is based off of this one and adds the python delta connect client.
CI tests.

[Build] Run the Spark master PYTHON tests using the Spark 4.0 RC4

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala

Update SchemaUtils and ColumnMapping with unit tests in order to support REPLACE TABLE with column mapping + fieldId re-use in PR #2. Specifically this involves the following changes (not necessarily related, but combined in this PR)
1) When a connector provides its own column mapping info in the schema pre-populated we require that it's complete (i.e. fieldId AND physicalName must be present)
2) We add an argument to our schema validation checks `allowNewNonNullableFields`. This is useful in cases where we can be sure the table state has been completely cleared, and thus new non-null fields are valid (like REPLACE).
3) We don't allow adding a new column with a fieldId less than the maxColId. For now, do this proactively for safety. In the future in the case of something like RESTORE in …

[Kernel] Update column mapping and schema evolution code to support usage with replace table

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaIcebergCompatV2Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

Currently having this flag return 'false' prevents kernel from writing any table where this is feature is present.  this is the first change for #4491 .
N/A flag flip
Yes, kernel will now be able to write the table with this table feature set.

[Kernel] Allow kernel to write Type Widening enable

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

This PR fixes two subtle but critical parts for CatalogOwned enable table.
- For `CREATE LIKE`, enable CatalogOwned w/ default spark configuration.
- This is different from the normal behavior/semantic of `CREATE LIKE`, where the source table protocol will take precedence and override any default (table feature) enablement.
- For `REPLACE`, only filter out `CatalogOwnedTableFeature` if the existing table does **_not_** have CatalogOwned enabled - otherwise there would be protocol downgrade issue if we are adding new table feature (e.g., `ClusteringTableFeature`) at the same time.
- We also filter out any **_unintended_** `InCommitTimestampTableFeature` if the original table does not have ICT enabled, and users are not enabling ICT via explicit overrides or default ICT spark configuration. …

[Spark] Fix `REPLACE` and `CREATE LIKE` for CatalogOwned

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/FieldMetadata.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuiteBase.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/types/FieldMetadataSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala

This PR fixes how nested field IDs are populated on metadata.  Before this change metadata was added directly to the parent StructField no matter how deeply maps/arrays where nested.  With this change we populate metadata correctly on the near parent StructField (ignoring intermediate StructFields  in Maps/Array which are just a nicety for the schema object model).  This also has the impact of not incrementing max field ID for pre-populated fields.
Resolve #4535
Added unit tests/existing tests.
It fixes a bug.

[Kernel] Fix schema id population for iceberg compat v2

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableFeaturesSuite.scala

Example preview and graduated features are:
* (typeWidening-preview -> typeWidening)
* (variantType-preview -> variant)
Currently we enable both the preview and non-preview feature names if the feature enable criteria is true.
For example if the delta.enableTypeWidening is set to true, the table will have both typeWidening-preview and typeWidening
Expected behavior:
* if the table has no typeWidening or typeWidening-preview
* enable only the typeWidening feature
* if the table has typeWidening-preview
* keep it as is and don't add typeWidening
* If the table has typeWidening feature
* keep it as is
Resolves #4532
Unit and integration tests. Integration tests only for typeWiderning as Kernel doesn't yet support writes with variant.

[Kernel] Handle the preview and graduated table features when updating protocol through metadata

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableClusteringSuite.scala

When the existing table is already a partitioned table, we cannot update it to a clustered table anymore. 
Unit tests.

[kernel] Block updating partitioned table with clustering columns

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala

This PR fixes a place in CreateDeltaTableCommand that checks existence of an Option before calling get on it.
Existing UT
No

[Delta] Check existence before calling Option.get

---

connectors/flink/src/main/java/io/delta/flink/source/internal/SchemaConverter.java
connectors/flink/src/test/java/io/delta/flink/source/internal/SchemaConverterTest.java
connectors/flink/src/test/java/io/delta/flink/table/it/suite/DeltaEndToEndTableTestSuite.java

Resolves #3977
This PR fixes a bug where the Delta-Flink connector would incorrectly map Delta's `BinaryType` (which is variable length) type to Flink's `BinaryType` (which is fixed length). Instead, this PR fixes it so that Delta's `BinaryType` is mapped to Flink's `VarBinaryType(MAX_LENGTH)`. As a comparison, Iceberg does the same
[here](https://github.com/apache/iceberg/blob/8e2ffb35da2d4c5059e96cb78a30fd8c54cfbedf/flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/TypeToFlinkType.java#L125).
This incorrect logic caused the behaviour seen in #3977 because:
- First, we had a source (datagen) table with Flink's BYTES (which is a synonym for VarBinaryType of MAX_LENGTH)
- Second, we had a target (delta) table. Flink created it with schema BYTES and the Delta schema had delta type …

[Backport][Flink] Fix mapping between Delta's BinaryType and Flink's VarBinaryType

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/NumRecordsStats.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeleteCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DeltaCommandInvariants.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/UpdateCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/commands/DeltaCommandInvariantsSuite.scala

This PR adds invariant checks to DELETE, UPDATE, and MERGE to detect bugs in Spark and Delta, and to prevent these DML statements from committing if they suffered from the bug.
These invariants come in two flavors:
- Unreliable checks using the commit stats (i.e. number of rows in the files added and removed) and the SQL metrics. These checks are disabled by default, as Spark can overcount metrics when there are retries.
- Reliable checks based purely on the commit stats. These checks are enabled by default, but cannot detect every occurrence of a bug.
- Manually ran existing DML tests with all invariant checks enabled by default to confirm that the checks do not cause any issues.
- Manually ran existing DML tests with all invariant checks enabled by default with a bug introduced to …

[Spark] Add invariant checks to DML commands

---

spark/src/main/scala/org/apache/spark/sql/delta/CommittedTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala

An `OptimisticTransaction` is currently used to keep track of in-progress transaction and also as a container for post-commit information about the transaction. This makes the semantics messy when it comes to post-commit usage. For example, it is possible for a post-commit hook to takes in an in-progress transaction, intentionally or not. A post-commit hook has access to mutable fields and may need to check whether a field is ready to be consumed or not. 
Previously, we introduced `DeltaTransaction` to limit what can be accessed in a post-commit hook. However, that does not solve the in-progress vs. committed semantics problem and requires that if a new transaction implementation is introduced, it has to inherit all the var fields from the trait, so that it can be passed to the …

[Spark] Introduce CommittedTransaction to store post-commit txn info

---

python/delta/connect/tables.py
python/delta/connect/tests/test_deltatable.py
python/delta/tests/test_deltatable.py

Adds additional DeltaTable Python `clusterBy` tests, on top of https://github.com/delta-io/delta/pull/2880.
Added UTs.
No.

[Spark] Add additional clustering columns test in Delta Table Python APIs

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaReplaceTableSuite.scala

When the `clustering` table feature is in a tables writerFeatures it is required that a clustering domain metadata is present. During replace we never downgrade the protocol, so when transitioning from a clustered table to a non-clustered table we need to retain a clustering domain metadata, but with `clusteringColumns=[]`.
Currently we just remove the existing clustering domain metadata which is incorrect.
Updates existing tests.

[Kernel] Fix REPLACE to correctly retain the clustering domain metadata when replacing a clustered table with a non-clustered table

---

spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsSuite.scala

This PR re-enables UTs for `CatalogOwnedSuite` after the relevant changes.
In addition, moved some CoordinatedCommits-only UTs to `CoordinatedCommitsSuite`.
Through existing (and re-enabled) UTs in `CatalogOwnedSuite` and `CoordinatedCommitsSuite`.
N/A

[Spark] Re-enable UTs in `CatalogOwnedSuite`

---

PROTOCOL.md

Clarifies that the default value should be `null` for variant data type
n/a
No

Clarify that variant defaults should be null

---

spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableScalaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableTestMixin.scala

Non functional refactor of CLONE test helpers to put them in a dedicated trait `CloneTableTestMixin` that can be reused across test suites
N/A - existing tests are not modified
No

[Spark ] Move CLONE test helpers into CloneTableTestMixin

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedCheckpointData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedLogCompactionData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedLogData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedMultiPartCheckpointData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/FileNames.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/files/ParsedLogDataSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockFileSystemClientUtils.scala

Add classes: `ParsedLogData`, `ParsedLogCompactionData`, `ParsedCheckpointData`, and `ParsedMultiPartCheckpointData`
These classes aren't used anywhere, yet. That will come in future PRs.
`ParsedLogDataSuite`
No.

[Kernel][Catalog-Managed] ParsedLogData

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaHistorySuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

This PR migrates `DeltaTimeTravelSuite` and `DescribeDeltaHistorySuite` from Coordinated-Commits to Catalog-Owned.
Through existing UTs in both suites.
N/A

[Spark] Migrate `DeltaTimeTravelSuite` and `DescribeDeltaHistorySuite` to CatalogOwned

---

spark/src/main/scala/io/delta/tables/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/CatalogResolver.scala
spark/src/test/scala/io/delta/tables/DeltaTableForNameSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CustomCatalogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/CustomCatalogs.scala

Allow users to pass a fully qualified name (`catalog.schema.table`) to forName so they're able to use different catalogs than the default sessionCatalog. 
There are no changes in the behavior of input that's not fully qualified.
UTs

[DELTA] Handle fully qualified table names in DeltaTable.forName

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingPredicateBuilder.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/StatsProvider.scala

Change the name of `StatsProvider.getPredicateWithStatType` to be more clearer, to make it clear that when the column does not have stats, the return value is None.
Existing UTs, just a naming change.
No.

[Spark] Rename StatsProvider.getPredicateWithStatType to StatsProvider.getPredicateWithStatTypeIfExists

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaIcebergCompatV2Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

This reverts commit df114f1e597e8532f9d231d12ca232e580fbcb9b.
This reverts a commit that should not be shipped without follow-up feature work.
Not from a previous release.

Revert "[Kernel] Allow kernel to write Type Widening enable (#4517)"

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/checkpoints/CheckpointInstance.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedCheckpointData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedLogData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedMultiPartCheckpointData.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/files/ParsedLogDataSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/4597/files) to review incremental changes.
- [**stack/kernel_parsed_checkpoint_ordering**](https://github.com/delta-io/delta/pull/4597) [[Files changed](https://github.com/delta-io/delta/pull/4597/files)]
- [stack/kernel_parsed_complete_checkpoint_group](https://github.com/delta-io/delta/pull/4634) [[Files changed](https://github.com/delta-io/delta/pull/4634/files/52a6f8c8a5c618e1d16999d366b3f075065d1193..adfa8162be992222ad45cbc9ea3491e2538c21bf)]
---------
Update `ParsedCheckpointData` to supporting comparable, for ordering. This will be used to be able to group checkpoints together and identify the max (preferred), similar to CheckpointInstance today.
New UT
No.

[Kernel][Catalog-Managed] ParsedCheckpointData ordering

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/AutoCompact.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/AutoCompactUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/ChecksumHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/GenerateSymlinkManifest.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/HudiConverterHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/IcebergConverterHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/PostCommitHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/UpdateCatalog.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

Continuation of https://github.com/delta-io/delta/pull/4557
An `OptimisticTransaction` is currently used to keep track of in-progress transaction and also as a container for post-commit information about the transaction. This makes the semantics messy when it comes to post-commit usage. For example, it is possible for a post-commit hook to takes in an in-progress transaction, intentionally or not. A post-commit hook has access to mutable fields and may need to check whether a field is ready to be consumed or not.
Previously, we introduced `DeltaTransaction` to limit what can be accessed in a post-commit hook. However, that does not solve the in-progress vs. committed semantics problem and requires that if a new transaction implementation is introduced, it has to inherit all the var fields …

[Spark] Use CommittedTransaction in all post-commit hooks

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala

During analysis of CLONE command, we attempt to create a table, using a deprecated `createTable()` method.
This leads to a confusing assertion when running against unitycatalog: https://github.com/unitycatalog/unitycatalog/blob/f626a9efba14821808498e5af6d1344854951294/connectors/spark/src/main/scala/io/unitycatalog/spark/UCSingleCatalog.scala#L127
Updating the call to transform the argument and call into the preferred `createTable()` method
Existing clone tests
No

[Spark][4.0] Stop using deprecated createTable() in CLONE analysis

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala-spark-master/org/apache/spark/sql/delta/DeltaVariantShreddingSuite.scala
spark/src/test/scala-spark-master/org/apache/spark/sql/delta/DeltaVariantSuite.scala

Add the preview table feature for Variant Shredding (see https://github.com/delta-io/delta/pull/4033) enabled by the new enableVariantShredding table property. Spark will check if the `enableVariantShredding` table property is enabled before writing shredded data to Delta tables, when support for shredded writes is implemented in Spark.
Unit test
No

[VARIANT] Add enableVariantShredding Table Property and VariantShredding-preview table feature in Delta-Spark

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java

Use this [link](https://github.com/delta-io/delta/pull/4641/files) to review incremental changes.
- [**stack/kernel_log_replay_refactor**](https://github.com/delta-io/delta/pull/4641) [[Files changed](https://github.com/delta-io/delta/pull/4641/files)]
---------
As part of the `catalogManaged` table support feature (#4573), we want our incoming `ResolvedTableBuilder` (#4614) to be able to receive from the Engine/Catalog the latest Protocol and Metadata for that pinned `ResolvedTable`.
Consequently, we won't always want replay the log to get the latest P & M -- we might just want to use what was given to us!
Thus, this PR makes `LogReplay` load the P & M lazily -- that is, not in the constructor.
This has no impact on existing call sites today:
- `SnapshotManager` -- will immediately then …

[Kernel][CatalogManaged] Refactor LogReplay to lazy-load P&M [Note: Snapshot still constructed with P&M eagerly]

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/MaterializedRowTrackingColumn.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/RowTracking.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala

This PR addresses the missing [writer requirements](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#writer-requirements-for-row-tracking) to enable row tracking in Kernel. Specifically, on top of the existing implementation, it adds the assignment of materialized row tracking column names at table creation.
With this change, users will be able to create a new table with row tracking enabled. Note that enabling/disabling row tracking on existing tables is still blocked, since enabling requires backfilling row IDs/commit versions, which is not supported, and disabling is irreversible.
Existing and new tests in `RowTrackingSuite`.
No.

[Kernel] Support enabling row tracking in Kernel

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotQueryContext.java

Use this [link](https://github.com/delta-io/delta/pull/4654/files) to review incremental changes.
- [**stack/kernel_refactor_snapshot_error_reporting**](https://github.com/delta-io/delta/pull/4654) [[Files changed](https://github.com/delta-io/delta/pull/4654/files)]
---------
This PR moves the SnapshotQueryContext error reporting to an instance method. I want to be able to invoke the error reporting _on_ a SnnapshotQueryContext. This makes the error reporting logic re-usable, e.g. for our ResolvedTableBuilder that will want to do something similar.
Just a refactor. Existing UTs.
No.

[Kernel] [Refactor] Move SnapshotQueryContext error reporting to instance method

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

This change will block schema evolution support in 4.0. There's more work to be done to make sure this API is really safe to prevent invalid field reorderings. We aim to get this out and ready for the next release but for now to prevent users from potentially breaking their table due to lack of this validation we'll block the operation.
It's blocking a feature so I'm just disabling the tests which used to test this feature

[Kernel][4.0] Block schema evolution via withSchema for 4.0

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaChanges.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaIterable.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/4567/files) to review incremental changes.
- [**stack/tw_proper_addressing**](https://github.com/delta-io/delta/pull/4567) [[Files changed](https://github.com/delta-io/delta/pull/4567/files)]
- [stack/tw_type_changes](https://github.com/delta-io/delta/pull/4568) [[Files changed](https://github.com/delta-io/delta/pull/4568/files/7a07781a45a757873a5dbf519f84c3e25f3af4e3..2c2f71a4a6b775abb4da3b141058ed20196cd099)]
- [stack/tw_type_changes_to_field_metadata](https://github.com/delta-io/delta/pull/4588) [[Files changed](https://github.com/delta-io/delta/pull/4588/files/2c2f71a4a6b775abb4da3b141058ed20196cd099..d8f0abb884b33b12333f1b53b6d1aed124d3277a)]
- [stack/tw_type_changes_to_field_metadata_impl](https://github.com/delta-io/delta/pull/4 …

[Kernel][Type Widening] 4/ rework compute field ID to avoid recursion

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/TransactionStateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/test/scala/io/delta/kernel/TransactionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaColumnMappingSuite.scala

Currently the support is just for the metadata updates to column mapping enabled tables. Data path is not yet implemented. Block it so that the connectors won't write invalid data files.

[Kernel] Block writing data into column mapping enable table as it is not yet implemented

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala

Make sure RewriteHelper to always use the correct snapshot ID when validating the snapshot
Existing UT
NO

[Delta] Use the correct snapshotId for RewriteHelper

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaChanges.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/TypeChange.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/4568/files) to review incremental changes.
- [**stack/tw_type_changes**](https://github.com/delta-io/delta/pull/4568) [[Files changed](https://github.com/delta-io/delta/pull/4568/files)]
- [stack/tw_type_changes_to_field_metadata](https://github.com/delta-io/delta/pull/4588) [[Files changed](https://github.com/delta-io/delta/pull/4588/files/3cc7f9fce24cf8d1c3cd13fff9cb9ac8b2aa3f61..cd9d0a002af5ae669ff0f5951053fc9f0f696509)]
- [stack/tw_type_changes_to_field_metadata_impl](https://github.com/delta-io/delta/pull/4589) [[Files changed](https://github.com/delta-io/delta/pull/4589/files/cd9d0a002af5ae669ff0f5951053fc9f0f696509..61dd9cf9cc4620c2f2123acae907eb3df1b56326)]
- [stack/tw_serde_refactor](https://github.com/delta-io/delta/pull/4592 …

[Kernel][Type Widening] 5/ Add type changes rules for type widening

---

docs/source/delta-type-widening.md

Update the existing type widening documentation page to cover changes in Delta 4.0:
- Feature transition from `typeWidening-preview` to `typeWidening`
- Additional changes supported.
+ some minor improvements and clarifications
Locally deployed documentation page and reviewed formatting

[Doc] Update Type widening documentation for Delta 4.0 release

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingLogFileSystem.scala
sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingUtils.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingUtilsSuite.scala

[During cache registration](https://sourcegraph.prod.databricks-corp.com/databricks-eng/runtime/-/blob/sql/core/src/main/scala/io/delta/sharing/spark/DeltaSharingLogFileSystem.scala?L676-679), we store more fileId-URL entries than what the refresh logic stores. The additional entries come from files associated with deletion vectors. However, [the refresh logic does not include these deletion vector entries](https://sourcegraph.prod.databricks-corp.com/databricks-eng/runtime/-/blob/sql/core/src/main/scala/io/delta/sharing/spark/DeltaSharingUtils.scala?L142-155). As a result, if we query a Delta table in Delta format and the table contains deletion vectors, the refresh operation will drop the corresponding fileId-URL entries for those files.
This causes long running queries seeing file id …

Ensure deletion vector fileId-URL entries are preserved during cache refresh

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdater.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/types/TypeWideningCheckerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaIcebergCompatV2Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

Use this [link](https://github.com/delta-io/delta/pull/4603/files) to review incremental changes.
- [**stack/tw_upgrade_downgrade**](https://github.com/delta-io/delta/pull/4603) [[Files changed](https://github.com/delta-io/delta/pull/4603/files)]
---------
This PR adds a validator to ensure only iceberg compatible type changes are present before enabling IcebergCompatV2.
Resolves #4491
Added direct unit tests, and integration tests to check that the feature can be turned on with valid type changes, and throws an exception when invalid type changes are present.
This adds validation for type-widening so if there are tables that do not follow the protocol, it could start rejecting some writes.

[Kernel][Type Widening] 10/ Add iceberg compat check for type changes

---

spark/src/main/scala-spark-3.5/shims/DeltaTimeTravelSpecShims.scala
spark/src/main/scala-spark-master/shims/DeltaTimeTravelSpecShims.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaTimeTravelSpec.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala

This PR fixes a bug that occurs when trying to time travel on a Delta table using Spark's dataframe API and timestamps, e.g. through spark.read.option("timestampAsOf", "some-timestamp").table("some-table"). For some input timestamps, this can lead to the time travel specification being defined twice (once through the DeltaTableV2 and once through the options), which is not allowed. To work around this problem, there is a check for allowing two time travel specifications in case they are equal.
However, in cases where the timestamp in the options is specified with microsecond precision or without any milliseconds, the equality check fails because the time travel specification in the DeltaTableV2 adds `.0` milliseconds by default but drops the microseconds and so the timestamp in the time …

[Spark] Fixes options-based time travel with timestamps

---

python/delta/integration_tests/unity-catalog-commit-coordinator-integration-tests.py
run-integration-tests.py

This extends coverage for Unity Catalog integration tests:
- Split tests across multiple suites
- Add coverage for DMLs using SQL, time-travel, streaming, ALTER TABLE, utility functions, ...
Ran tests locally. These tests aren't executed automatically as part of PR validation as they require provisioning external resources.
No

[Spark] Add more Unity Catalog integration tests

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergCompatMetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergCompatV2MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdater.java

This PR is refactoring only, move all the IcebergCompatChecks from `IcebergCompatV2MetadataValidatorAndUpdater.java` to its base class `IcebergCompatMetadataValidatorAndUpdater.java` so that later newly added `IcebergCompatV3MetadataValidatorAndUpdater.java` can use them.
Existing unit tests since it is only doing refactoring.

[Kernel][#2] IcebergCompatV3 - move IcebergCompatCheck to base class

---

spark/src/test/scala/org/apache/spark/sql/delta/DeleteSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoTest.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/UpdateSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningTestMixin.scala

This PR is one of a series of PRs aiming to refactor the DML suites such that we can extend the existing suites to test with name-based table access.
Currently, all DML suites are centered around the `DeltaDMLTestUtils` trait that creates a test table stored in `tempPath`. In this PR, all path-related elements in this trait will be abstracted out and put into a new specialized trait called `DeltaDMLByPathTestUtils`.
Existing UTs 
No

[Spark] Make DeltaDMLTestUtils agnostic to name/path-based access

---

icebergShaded/generate_iceberg_jars.py

This change adds an exclusion to building javadoc when building iceberg jars.  On my machine javadoc build fails and it is not critical to building and it appears not critical to building the jars.
Tested locally, and should be fine as long as CI passes.
No

[BUILD] Don't build javadoc for iceberg jars.

---

spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

This PR refactors and migrates DeltaLog-related suites to CatalogOwned.
Through existing suites.
N/A

[Delta] Refactor & Migrate DeltaLog related suites to CatalogOwned

---

connectors/examples/run_examples.py
kernel/examples/run-kernel-examples.py
python/run-tests.py
run-integration-tests.py
storage/src/test/scala/io/delta/storage/integration/S3LogStoreUtilIntegrationTest.scala

Cherry-pick https://github.com/delta-io/delta/pull/3258 to the 4.0 branch

[4.0][INFRA] Update integration tests to clear all possible ivy caches + minor update to S3LogStoreUtilIntegrationTest 

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/ClassicMergeExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeIntoMaterializeSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaSparkPlanUtils.scala

Fixes a source of non-determinism in MERGE due to query caching. Query caching doesn't pin the version of Delta tables, a source cached using `df.cache()` can then return different results between the two internal MERGE jobs if it is updated in the meantime.
Guarded by flag `spark.databricks.delta.merge.materializeCachedSource`.
This is tough to cover with a test since it requires precise timing to update the source while the MERGE operation is running.
I did validate that the fix works manually, running with a debugger.
No

[Spark] Materialize cached Delta sources in MERGE

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/InCommitTimestampUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala

This PR fixes ICT so that we don't end up accidentally dropping enablement info (ICT enablement timestamp and version) when REPLACE is run on an ICT table.
Note that this PR does not change the behaviour of when ICT remains enabled/disabled after a REPLACE. It just makes sure that if ICT remains enabled, we don't drop the enablement info.
New tests in InCommitTimestampSuite.
No

[Spark][ICT] Bug Fix: Avoid accidentally dropping enablement info during REPLACE on ICT tables

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaIterable.java

Use this [link](https://github.com/delta-io/delta/pull/4742/files) to review incremental changes.
- [**stack/schemaIdToSchemaIterable**](https://github.com/delta-io/delta/pull/4742) [[Files changed](https://github.com/delta-io/delta/pull/4742/files)]
- [stack/update_table_features](https://github.com/delta-io/delta/pull/4752) [[Files changed](https://github.com/delta-io/delta/pull/4752/files/4631f204cf59016d876a0c3bd408e7c67112b22b..19c2fe51f33bba7e4e584874238884d04bef514e)]
- [stack/update_validators](https://github.com/delta-io/delta/pull/4753) [[Files changed](https://github.com/delta-io/delta/pull/4753/files/19c2fe51f33bba7e4e584874238884d04bef514e..378a8eda53800bcbfffc648459f5b0af69fdfffc)]
- [stack/remove_recurse_from_schema_utils](https://github.com/delta-io/delta/pull/4754) …

[Kernel] Update max id to use SchemaIterable

---

kernel/kernel-api/src/main/java/io/delta/kernel/TransactionCommitResult.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/MetricsReportSerializers.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/TransactionReportImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/TransactionReport.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaReplaceTableSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableClusteringSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/TransactionReportSuite.scala

Helps connectors decide on what further operations to trigger after the commit is done.
UTs and Integration tests

[Kernel] Expose the clustering columns in txn report returned by the txn commit status

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaIterable.java

Use this [link](https://github.com/delta-io/delta/pull/4752/files/4631f204cf59016d876a0c3bd408e7c67112b22b..19c2fe51f33bba7e4e584874238884d04bef514e) to review incremental changes.
- [stack/schemaIdToSchemaIterable](https://github.com/delta-io/delta/pull/4742) [[Files changed](https://github.com/delta-io/delta/pull/4742/files)]
- [**stack/update_table_features**](https://github.com/delta-io/delta/pull/4752) [[Files changed](https://github.com/delta-io/delta/pull/4752/files/4631f204cf59016d876a0c3bd408e7c67112b22b..19c2fe51f33bba7e4e584874238884d04bef514e)]
- [stack/update_validators](https://github.com/delta-io/delta/pull/4753) [[Files changed](https://github.com/delta-io/delta/pull/4753/files/19c2fe51f33bba7e4e584874238884d04bef514e..378a8eda53800bcbfffc648459f5b0af69fdfffc)]
- …

[Kernel] Use schema iterable for table feature checks

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala

Delete eligible delta log files only if there's a checkpoint newer than them before the cutoff window.
Resolves #606
Unit tests based on https://github.com/delta-io/delta/pull/2673
Unit Tests
Yes, tables with low rate of commit/checkpoints will have increased log retention beyond the cutoff window

[Spark] Fix metadata cleanup by retaining files required for log reconstruction

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/ResolvedTableFactory.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/ResolvedTableInternal.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/ResolvedTableInternalImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/test/AbstractTableManagerAdapter.scala

Use this [link](https://github.com/delta-io/delta/pull/4663/files) to review incremental changes.
- [**stack/kernel_catalog_managed_4**](https://github.com/delta-io/delta/pull/4663) [[Files changed](https://github.com/delta-io/delta/pull/4663/files)]
---------
This PR adds the minimal code to `ResolvedTable` to support creating `ScanBuilder`s
This PR also refactors `AbstractDeltaTableReadsSuite` to fully support, for all applicable tests, the `TableManagerAdapter` test APIs (that let us test with both (a) `TableManager` and `ResolvedTable` and (b) `Table` and `Snapshot` APIs
New child class implementation of `AbstractDeltaTableReadsSuite` for the new `TableManager` APIs.
No.

[Kernel] [CatalogManaged] Create ScanBuilder from ResolvedTable; Run E2E read tests using new TableManager APIs

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala

Change the type of `readPredicates` in `OptimisticTransaction` class from generic `Seq` to `Vector`.
No behaviour change. Existing tests are suficient.
No

[Spark] Change readPredicates from Seq to Vector

---

spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala-spark-master/org/apache/spark/sql/delta/DeltaVariantSuite.scala

`variantType` and `variantType-preview` features did not have the `automaticallyUpdateProtocolOfExistingTables` flag enabled which disallowed adding Variant columns to an existing Delta table unless the feature was explicitly added. This PR enables this flag for these features.
Unit tests.
Yes, it allows users to add Variant columns to tables easily.

[VARIANT] Add automaticallyUpdateProtocolOfExistingTables to variantType features

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala

(Cherrypick #4146)
Delete eligible delta log files only if there's a checkpoint newer than them before the cutoff window.
Unit Tests
Yes, tables with low rate of commit/checkpoints will have increased log retention beyond the cutoff window

[4.0][Spark] Fix metadata cleanup by retaining files required for log reconstruction

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFileReader.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/FakeFileSystem.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetFileReaderSuite.scala

When we fixed the IllegalAccessError we missed this parameter when creating the ParquetReader, we are only using it to read the footer.
Maybe also need fix to master and 4.0, I didn't have a chance to experiment the new version yet.
Manual tests.
No

[3.3][Kernel] Bug fix: Missing Hadoop configuration parameter when creating parquet reader

---

iceberg/src/test/scala/org/apache/spark/sql/delta/CloneIcebergSuite.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/NonSparkIcebergTestUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/convert/ConvertUtils.scala

This PR enables CloneSources to use absolutePath in data files
UT

[Delta] Allow Clone Source to use absolutePath

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdCloneSuite.scala

Improve exception message when customer attempt to clone a table without `numRecords` statistics and at the same time enable Row Tracking.
Updated existing test.
No

[Spark] Better exception for clones without stats that enable row tracking

---

spark/src/main/scala/org/apache/spark/sql/delta/RowCommitVersion.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala
spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/ClassicMergeExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeOutputGeneration.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

For uniform tables, to make the materialized row id column and row commit version column is understandable by Iceberg, we need to assign the corresponding parquet field id to these two columns.

[spark] assign reserved row tracking field id for uniform tables

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotMetrics.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/SnapshotMetricsResult.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/SnapshotReportSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/4800/files) to review incremental changes.
- [**stack/kernel_snapshot_construction_better_observability_1**](https://github.com/delta-io/delta/pull/4800) [[Files changed](https://github.com/delta-io/delta/pull/4800/files)]
---------
Add a new Snapshot metric `getLoadSnapshotTotalDurationNs` that records the total duration to load a Snapshot.
Includes minor refactors along the way.
Added new, minimal changes to existing UTs.
New Kernel Snapshot metric.

[Kernel] Add new metric for total snapshot construction duration

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/AutoCompactPartitionStats.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/TransactionHelper.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala

Factors out CommitStats computation out of commitLarge and doCommit into a common method.
Fixes one test. Other changes should be covered by existing UTs.
No

[Spark] Unify CommitStats computation

---

kernel/kernel-api/src/main/java/io/delta/kernel/ResolvedTable.java
kernel/kernel-api/src/main/java/io/delta/kernel/ResolvedTableBuilder.java
kernel/kernel-api/src/main/java/io/delta/kernel/TableManager.java

Use this [link](https://github.com/delta-io/delta/pull/4822/files) to review incremental changes.
- [**stack/kernel_catalog_managed_better_docs**](https://github.com/delta-io/delta/pull/4822) [[Files changed](https://github.com/delta-io/delta/pull/4822/files)]
---------
Better class/method docs for TableManager, ResolvedTableBuilder, ResolvedTable
Comments only. Existing CI.
No.

[Kernel] [CatalogManaged] Better class/method docs for TableManager, ResolvedTableBuilder, ResolvedTable

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala

This PR keeps table protocol intact before and after REPLACE commands.
Under the current implementation, we have the following scenario that may automatically/silently upgrade a normal delta table's Protocol when using REPLACE commands. It would be upgraded from `(x, x)` (i.e., any combinations of protocol versions) to `(3, 7)`, plus an additional (unintended) `VacuumProtocolCheckTableFeature`.
```sql
-- w/ protocol version (1, 2) if DV is turned off.
1. CREATE TABLE t (id LONG) USING delta;
-- Enable CO by default in the current SparkSession.
2. spark.conf.set("default CO conf", "supported")
-- The protocol would be automatically upgraded to (3, 7) w/ an extra VacuumProtocolCheckTableFeature.
3. REPLACE TABLE t (id LONG) USING delta;
```
N/A
N/A

[Delta] Keep table protocol intact before and after REPLACE regardless of default CC enablement

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaDataFrameWriterV2Suite.scala

CannotReplaceMissingTableException extends AnalysisException.
Spark has rewrites that sometimes change AnalysisException into ExtendedAnalysisException to add more context.
For some reason, it started happening here. Rewriting it into ExtendedAnalysisException makes it lose the CannotReplaceMissingTableException, but it retains the correct error class and SQL state. Make the test check the error class and SQL state instead.
Test runs.
No.

[Spark] Fix DeltaDataFrameWriterV2Suite.Replace: fail if table does not exist

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumLogReplayMetricsTestBase.scala

Add a crc test for loading a version missing crc while the version later and before have, we want to make sure versions after are not used
No

[Kernel][Test]Add a crc test for loading a version missing crc while the version later and before have

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/GenerateIcebergCompatActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatMetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV3MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV3MetadataValidatorAndUpdaterSuite.scala

- Implement IcebergWriterCompatV3. We skipped v2 to align with IcebergCompatV3 which maps to iceberg format v3.
Unit tests.
Yes. Introduces IcebergWriterCompatV3.

[Kernel][#4] Introduce IcebergWriterCompatV3

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/DeltaScan.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/ScanReportHelper.scala

When logging DeltaScans, we currently naively convert the rewritten partition-like data filters (which may be unresolved) to SQL. This is unsafe, as unresolved expressions might throw an error when converted to SQL (if the conversion to SQL accesses a child expression's data type). Wrap the SQL conversion to catch any potential errors to prevent this issue.
N/A.
No.

[Spark] Safely log unresolved data skipping filters from DeltaScan

---

spark/src/test/scala/org/apache/spark/sql/delta/schema/InvariantEnforcementSuite.scala

The values in error message could be printed in different order. `checkConstraintException` already handles that, just that the different substrings expected in the error messages need to be passed to it separately.
Deflaking existing test.
No

[Spark] Deflake InvariantEnforcementSuite

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaHistoryManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/CommitInfo.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/InCommitTimestampUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/DeltaHistoryManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableImplSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockEngineUtils.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockFileSystemClientUtils.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockSnapshotUtils.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/SnapshotReportSuite.scala

Cherry pick of https://github.com/delta-io/delta/pull/4581
Adds initial support for performing ICT-based time travel. More specifically, this PR:
Updates all code paths that rely on timestamp-based time travel such that they all create a snapshot of the latest table version first. This allows us to determine whether ICT is enabled.
Adds an initial binary-search-based greatest lower bound implementation for time traveling based on ICT. A follow PR will make this more efficient by intelligently utilizing file modification timestamps for narrowing the search window.
Added test cases to DeltaHistoryManagerSuite

[Kernel][4.0] Add support for ICT-based time travel (part 1)

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala

The PR adds two new methods `fromMetaDataOption` and `fromMapOption` to return `None` if the delta config is not set in the metadata. It also adds `CheckpointProtectionTableFeature.getCheckpointProtectionVersionOption` to use `fromMetaDataOption` and let `CheckpointProtectionTableFeature.getCheckpointProtectionVersion` use `CheckpointProtectionTableFeature.getCheckpointProtectionVersionOption`.
No.

[SPARK] Refactor `DeltaConfig.fromMetadata`

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

This PR migrates `DeltaSuite` and `DeltaSuiteEdge` to `CatalogOwned`.
Existing UTs.
No

[Delta] Migrate `DeltaSuite` and `DeltaSuiteEdge` to `CatalogOwned`

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillCommandStats.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillBackfillConflictsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillConflictsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowIdTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingBackfillSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowtracking/RowTrackingConflictResolutionSuite.scala

This PR removes the parallelism from the row tracking backfill. This parallelism is currently unused, and it makes it more difficult to add performance optimizations.
As part of this change an new backfill observer was added, as we can no longer rely on injecting a thread factory to inject transaction observers.
Existing tests to ensure that nothing breaks.
No

[Spark] Remove parallelism in Row Tracking Backfill

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/DefaultRowCommitVersion.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningFeatureCompatibilitySuite.scala

The preview of Type Widening used to store the table version in the type change metadata whenever a type change was applied.
This was removed in the stable version of the feature, but we kept assigning default row commit version when type widening is enabled even though we're not using this anymore.
This causes mismatches where rows present in the table before Row tracking is enabled have a row commit version that is older than the version where Row Tracking is enabled, as is usually the case.
This isn't a big issue in itself afaict, but it can be confusing and should be cleaned up.
Adding test covering the case where Row tracking is enabled on a table after type widening.

Clean up assigning default row commit version when type widening is enabled

---

spark/src/main/scala/org/apache/spark/sql/delta/constraints/DeltaInvariantCheckerExec.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/CheckConstraintsSuite.scala

In DeltaInvariantCheckerExec, if the check constraint expressions are unresolvable, we used to create an assertion log and not throw an exception. So in some cases an internal error is thrown in the subsequent steps.
The PR proposes to throw a proper user-facing error (AnalysisException) in DeltaInvariantCheckerExec to expose the problem to the user for better clarity, and avoid the issues in the downstream. It invokes checkAnalysis to throw a user-facing exception when the check constraint expression is unresolved.
New UT.
Yes.
Previous behavior:
If the check constraint expressions are unresolvable, we used to create an assertion log and not throw an exception. So in some cases an internal error is thrown in the subsequent steps.
Proposed change: 
We throw a proper user-facing error …

[SPARK] Throw exceptions when check constraint expression is unresolved in DeltaInvariantCheckerExec

---

spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaMergingUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

Currently, `SchemaMergingUtils.mergeDataTypes` will always use the existing metadata when merging a new `StructField` with the same name as an existing field. This change provides a new flag `overrideMetadata` that allows the update schema to override the metadata in the current schema.
New unit test in `SchemaUtilsSuite`.scala
No

[Spark] Allow overriding StructField metadata in mergeDataTypes

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoDVsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoNotMatchedBySourceSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoScalaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala

This PR is a continuation of https://github.com/delta-io/delta/pull/4808. Here, we continue pushing the `DeltaDMLByPathTestUtils` trait down closer to the MergeInto suites. In the process, we need to change all explicit path-based accesses to more generic constructs such as `tableSQLIdentifier` and `readDeltaTableByIdentifier`, which can be overrode with either `DeltaDMLByPathTestUtils` or `DeltaDMLByNameTestUtils` (to be added later) traits.
Existing UTs
No

[Spark] Make MergeIntoSuiteBase agnostic to name/path-based access

---

.github/workflows/connectors_test.yaml
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ChecksumReader.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/CloseableIterator.java
kernel/kernel-api/src/test/scala/io/delta/kernel/CloseableIteratorSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplayEngineMetricsSuite.scala

Adds a test (mirrors the other tests in the suite just ensures a later CRC does exist). Confirmed that the test fails without the fix.
Also cherry-picked https://github.com/delta-io/delta/commit/ab1fa99f78631ff4e6592445d9d5d8b3e650674c as it's needed for the CI.

[Kernel] Fix CRC listing to correctly terminate at the readVersion

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala

This PR avoids Avoid referencing DataSkippingReader in DetlaConfig. It might cause the cyclic import through SQLConf -> SparkSession -> DetlaConfig
Manually
No

[Spark] Avoid referencing DataSkippingReader in DetlaConfig

---

spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/ModularSuiteGenerator.scala
spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/SuiteGeneratorConfig.scala
spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/SuitesWriter.scala
spark/src/test/scala/org/apache/spark/sql/delta/generatedsuites/DeleteSuites.scala
spark/src/test/scala/org/apache/spark/sql/delta/generatedsuites/MergeSuites.scala
spark/src/test/scala/org/apache/spark/sql/delta/generatedsuites/UpdateSuites.scala

This PR makes some improvements to the suite generator and its configuration. Namely:
- Instead of global imports, each test group now has its own import list
- Added a new utility method to easily create `DimensionMixin` from a `DimensionWithMultipleValues`
NA
No

[Spark] Improve Suite Generator

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergStatsConverter.scala

Currently, when converting Delta stats to Iceberg, if MIN/MAX stats are missing, but are in the stats schema (meaning that all columns in the stats schema are entirely null for a file), we throw an error. This error is caught, but stats are not collected for that file. 
N/A.

[Spark] Fix Delta -> Iceberg stats translation when all min/max stats are null

---

spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CatalogOwnedEnablementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

This PR refactors the current `CatalogOwnedCommitCoordinatorProvider.registerBuilder` by utilizing the `DEFAULT_CATALOG_NAME_FOR_TESTING` to improve general readability.
Through existing UTs.
No.

[Spark] Use `DEFAULT_CATALOG_NAME_FOR_TESTING` in `registerBuilder`

---

spark/src/test/scala/org/apache/spark/sql/delta/CheckpointsSuite.scala

This PR migrates `CheckpointsSuite` to `CatalogOwned`.
Existing UTs.
No

[Delta] Migrate `CheckpointsSuite` to `CatalogOwned`

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/UpdateSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/UpdateScalaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/UpdateSuiteBase.scala

This PR refactor the existing UPDATE tests to use abstract methods in DeltaDMLTestUtils, so that the tests can later be run with name-based or path-based access, depending on whether the DeltaDMLTestUtilsPathBased or DeltaDMLTestUtilsNameBased is mixed in.
Existing UTs
No

[Spark] Make UpdateSuiteBase agnostic to name/path-based access

---

spark/src/test/scala/org/apache/spark/sql/delta/DeleteSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeleteScalaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeleteSuiteBase.scala

This PR refactor the existing DELETE tests to use abstract methods in `DeltaDMLTestUtils`, so that the tests can later be run with name-based or path-based access, depending on whether the `DeltaDMLTestUtilsPathBased` or `DeltaDMLTestUtilsNameBased` is mixed in.
UTs
No

[Spark] Make DeleteSuiteBase agnostic to name/path-based access

---

spark/src/test/scala/org/apache/spark/sql/delta/DeletionVectorsTestUtils.scala

This PR adds helper to enable persistent Deletion Vectors with table name.
Existing UTs.
No

[Delta] Add helper to enable persistent Deletion Vectors with table name

---

PROTOCOL.md

The protocol spec has a typo in the row tracking metadata domain. [Kernel implements the high water mark as `rowIdHighWaterMark`](https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/RowTrackingMetadataDomain.java#L60) but the spec defines it to be `highWaterMark`. Since the current implementation is already used in production (i.e., delta-spark has been using that name for years), I suggest to adapt that specification instead of opting for a breaking change in the code base.
Since this PR touches the spec anyways, I also fixed some non-critical typos along the way.
No since no code was changed.
This PR introduces user-facing changes to anyone who wants to implement the row tracking feature as part of a Delta connector.

[Protocol] Fix typo in name of a row tracking domain metadata field in protocol spec

---

spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableScalaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableTestMixin.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

This PR migrates `CloneTableSQLSuite` to CC.
Through existing and newly migrated suites.
No.

[Spark] Migrate `CloneTableSQLSuite` to CC

---

spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/SuiteGeneratorConfig.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoNotMatchedBySourceSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/generatedsuites/MergeSuites.scala

This PR splits existing long-running unit test suites for better parallelization, utilizing the test generator script for the same coverage.
Existing tests
No

[Spark] Split Large Test Suites

---

spark/src/test/scala/org/apache/spark/sql/delta/stats/DataSkippingDeltaTests.scala

This PR migrates `DataSkippingDeltaV1Suite` to `CatalogOwned`.
Existing UTs.
No

[Delta] Migrate `DataSkippingDeltaV1Suite` to `CatalogOwned`

---

spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/StatisticsCollection.scala

Refactor table configuration column rename function.
Through existing unit tests.

[Spark] Refactor table configuration column rename function.

---

build.sbt
kernel/kernel-api/src/main/java/io/delta/kernel/internal/fs/Path.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/fs/PathSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/fs/benchmarks/PathNormalizationBenchmarks.java

This PR attempts to optimize path normalization, assuming that most paths are already normalized (don't contain more then. 1 front-slash in a row).  It first does a check to see if this condition holds, and if it doesn't it applies the regex replace.
Regex.replace is fairly heavy weight and by making this change we see a 40-50% reduction in Path construction time when the path is already normalized.  The additional overhead for when normalization is needed is within measurement noise on the computer I'm running in (best estimate is someplace between 1-5%).
Also remove an outdated TODO for removing path.
- Add unit tests (mostly AI generated)
- Added a JMH benchmark for cases when normalization is needed and not needed.
No.

[Kernel] Optimize path construction 

---

spark/src/main/scala/org/apache/spark/sql/delta/stats/StatisticsCollection.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/StatsCollectionSuite.scala

Previously, we didn't handle the case when the physical name doesn't exist in the metadata, causing non-informative  NoSuchElementException. 
Fix with a physical name check before getting it. Throw a ColumnMappingException when missing physical name.
Added unit test.
No.

[Spark] Fix NoSuchElementException with missing physical name

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala
spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/DefaultRowCommitVersion.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/TableFeatureSupport.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillBatch.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillBatch.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingUnBackfillBatch.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingUnBackfillCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingUnBackfillExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingBackfillSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingRemovalSuite.scala

This PR adds support for row tracking removal. The main complexity is that row tracking cannot be disabled. The feature property, `delta.enableRowTracking`, only controls whether clients should expect all rows to contain row IDs. This means that concurrent transactions may continue generating row IDs while we clean up metadata.
Furthermore, the feature can be dropped and then re-enabled multiple times. Once the feature is dropped, there are no guarantees writers will preserve past metadata (either by copying action metadata or preserving them in the checkpoints). Therefore, we need to ensure that re-enablement is safe and it does not mix up (potentially incomplete) metadata from past enablements.
This can be aided with the introduction of an optional new configuration, …

[Spark] Add support for Row Tracking removal

---

spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaDetailSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

This PR migrates `DescribeDeltaDetailSuite` to `CatalogOwned`.
Existing UTs.
No

[Delta] Migrate `DescribeDeltaDetailSuite` to `CatalogOwned`

---

kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/MaterializedRowTrackingColumn.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/RowTracking.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/StructField.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

This PR adds initial support for reading row tracking metadata columns to kernel. Right now, this feature is limited to reading the materialized row ID and row commit version (i.e., values will be null if they were not materialized). Adding support for computing missing values on the fly will be added in a later PR.
The PR partially builds upon #4897 and #4924 and should be merged afterwards.
The PR adds several tests to the `RowTrackingSuite`, both based on a newly generated Delta table and a golden table (see #4924) that was generated with delta-spark.
This PR introduces (incomplete) new features to kernel. It does not modify any existing features.

[Kernel] Support reading materialized row tracking metadata columns

---

kernel/kernel-api/src/main/java/io/delta/kernel/ResolvedTableBuilder.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrorsInternal.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/commit/DefaultFileSystemManagedTableOnlyCommitter.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/ResolvedTableBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/ResolvedTableFactory.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/ResolvedTableInternalImpl.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/catalogManaged/ResolvedTableBuilderSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/commit/DefaultCommitterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/ActionUtils.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/VectorTestUtils.scala

Use this [link](https://github.com/delta-io/delta/pull/4936/files) to review incremental changes.
- [**stack/kernel_catalog_managed_writes_get_committer**](https://github.com/delta-io/delta/pull/4936) [[Files changed](https://github.com/delta-io/delta/pull/4936/files)]
---------
https://github.com/delta-io/delta/pull/4814 introduced new TransactionV2, Committer, CommitContext, etc APIs.
This PR now adds the abilities for Engines to inject into Kernel the actual Committer.
This PR also includes a no-op Default committer implementation that validates that it is not interacting with catalog-managed tables. We do this because: ResolvedTable does not return an Optional committer, but rather just a committer. So we need to give it _something_ in the case that no committer was provided to the …

[Kernel] [CatalogManaged] Add new builder .withCommitter API; Create DefaultCommitter skeleton

---

spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/SuiteGeneratorConfig.scala
spark/src/test/scala/org/apache/spark/sql/delta/UpdateSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/UpdateSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/UpdateCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/generatedsuites/UpdateSuites.scala

This PR makes UpdateSQLSuite an abstract suite and extends it to run with both path-based and name-based access
The updated UTs
No

[Spark] Run UpdateSQLSuite with both path-based and name-based access

---

kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/ScanStateRow.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeletionVectorSuite.scala

See https://github.com/delta-io/delta/issues/4989
```
test("end-to-end usage: reading a table with dv with space in the root path") {
withTempDir { tempDir =>
val target = tempDir.getCanonicalPath + "spark test"
spark.sql(s"""CREATE TABLE tbl (
id int
) USING delta LOCATION '$target'
TBLPROPERTIES ('delta.enableDeletionVectors' = true) """)
spark.sql("INSERT INTO tbl VALUES (1),(2),(3),(4),(5)")
spark.sql("DELETE FROM tbl WHERE id = 1")
checkTable(
path = target,
expectedAnswer = Seq(TestRow(2), TestRow(3), TestRow(4), TestRow(5)))
}
}
IOException reading from file file:/private/var/folders/9k/rzsv_9697k53xcx101546y280000gp/T/109f478a-4f50-4e5a-80d2-216ba12669e81886802785450513247spark%20test/deletion_vector_bf2b7f39-cdc0-4289-945b-79f9829a4e97.bin at offset 1 size 42 …
```

[Kernel]Fixing kernel resolving dv for a table with path containing space.

---

.github/workflows/spark_master_test.yaml
spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/SuiteGeneratorConfig.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoNotMatchedBySourceSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/generatedsuites/MergeSuites.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaSQLTestUtils.scala

Currently impression is splitting of test suite change how tests are sharding, and some test setup/turn down pollutes each other(deleting other tests path during cleanup
We increase test shard which seems to be working
workflow

Roll forward  [Spark] Split Large Test Suites (#4957), with increasing test shard

---

kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/InternalScanFileUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/ScanStateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/MaterializedRowTrackingColumn.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/StructField.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala

This PR builds upon #4943 and #4953 to enable fully functioning reads of row tracking metadata columns. Concretely, it adds functionality to compute non-materialized row IDs and row commit versions on the fly.
I modified the tests that I added in #4943 to now expect the fully correct result (instead of `null` for non-materialized values).
This PR turns the work started in #4943 into a usable new feature. Users/engines can now request row tracking metadata columns from Delta tables. At the moment, this PR still uses a preliminary API for requesting metadata columns until we agree on a stable metadata column API going forward.

[Kernel] Enable fresh & materialized reads of row tracking metadata columns

---

sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingTestSparkUtils.scala
spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/RestoreTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/io/delta/tables/DeltaTableSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableScalaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/RestoreTableScalaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/RestoreTableSuiteBase.scala

This change blocks time travel beyond deletedFileRetentionDuration. The affected commands are SELECT, RESTORE, CLONE and CDC which use the syntax AS OF.
Added new tests
Fixed existing tests to be compatible with the changes proposed.
Yes. Previously, user could time travel to any delta version beyond deletedFileRetentionDuration. With this change, time travel is restricted to be within the deletedFileRetentionDuration.

[SPARK] Block Time Travel beyond DeletedFileRetentionDuration

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/test/scala/org/apache/spark/sql/delta/ActionSerializerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/CommitInfoSerializerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogMinorCompactionSuite.scala

This PR completely fixes `CommitInfo`.operationParameters deserialization. A new method `getLegacyPostDeserializationOperationParameters` has been added to retain the legacy behaviour for old callsites. This PR, by itself, should be a no-op in terms of behaviour changes as the legacy callsites will use `getLegacyPostDeserializationOperationParameters` for now.
The newly introduced `JsonMapDeserializer` effectively performs an inverse of `JsonMapSerializer`. The original problem is explained in detail below:
The in-memory representation of operation params of any Delta Operation can be a combination of json encoded strings, simple strings, or primitives single-encoded as strings. The values can be any of:
- `"123"`
- `"true"`
- `"1.0"`
- `"\"true\""`
- `"\"1.0\""`
- or more complex json …

[Spark] Fix CommitInfo Deserialization and retain legacy deserialization for legacy callsites

---

spark-kernel-dsv2/src/test/java/io/delta/spark/dsv2/Dsv2BasicTest.java
spark-kernel-dsv2/src/test/java/io/delta/spark/dsv2/catalog/TestCatalog.java

This PR setup test catalog and add a e2e test for `DESCRIBE TABLE` using new kernel table implementation. Currently we just use path based legacy kernel api to write and create table for unblocking current or future e2e testing.
When CCv2's commiter lands, we will migrate to the new api
No

[Kernel][Dsv2]Setup test catalog to create spark table using the kernel backed table

---

kernel/kernel-api/src/main/java/io/delta/kernel/commit/CommitMetadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/commit/CommitContextImpl.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/commit/CommitMetadataSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/commit/DefaultCommitterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/ActionUtils.scala

Use this [link](https://github.com/delta-io/delta/pull/5060/files) to review incremental changes.
- [**stack/kernel_commit_metadata_types**](https://github.com/delta-io/delta/pull/5060) [[Files changed](https://github.com/delta-io/delta/pull/5060/files)]
---------
This PR adds some helpful APIs to CommitMetadata, which will be used by https://github.com/delta-io/delta/pull/5052 (see their usage there; I will rebase that 5052 PR after this PR is merged).
New UTs.
No.

[Kernel] [CatalogManaged] Add helpful APIs to CommitMetadata, useful for Committers

---

kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/MultiThreadedTableReader.java
kernel/examples/kernel-examples/src/main/java/io/delta/kernel/examples/SingleThreadedTableReader.java
kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrorsInternal.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/ScanStateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/MaterializedRowTrackingColumn.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/PartitionUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

This PR refactors the way kernel internally keeps track of logical and physical (read) schemas as well as intermediate versions thereof. The reason for this change is that the existing implementation is rather unintuitive and hard to maintain (especially for new developers).
In the context of this refactoring, I also modified the public API of `ScanStateRow`. Concretely, we do not serialize/expose the physical schema with partition columns anymore (formerly called `physicalSchema` although it is not the actual physical schema). Instead, we only expose the `logicalSchema` (sometimes also called `readSchema`) and the `physicalDataReadSchema` (which is the actual physical schema).
Internally, `physicalSchema` now refers to the actual physical schema (formerly `physicalDataReadSchema`). …

[Kernel] Refactor `ScanStateRow` and clean up schema representations

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/CreateTableTransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/transaction/CreateTableTransactionBuilder.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesTransactionBuilderV2Suite.scala

See title.
Adds tests.
Yes, a custom committer can now be provided when creating new tables.

[Kernel] Add `withCommitter` API to CreateTableTransactionBuilder

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/DataSkippingDeltaTests.scala

Previously, we did not push down IsNull through AND/OR or other Null intolerant expressions when evaluating expressions for data skipping. This disabled more expressions for data skipping than we would otherwise desire.
Unit tests
No

[Spark] Push down IsNull through nullIntolerant exprs

---

spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/ModularSuiteGenerator.scala
spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/SuiteGeneratorConfig.scala
spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/SuitesWriter.scala
spark/src/test/scala/org/apache/spark/sql/delta/generatedsuites/DeleteSuites.scala
spark/src/test/scala/org/apache/spark/sql/delta/generatedsuites/MergeSuites.scala
spark/src/test/scala/org/apache/spark/sql/delta/generatedsuites/UpdateSuites.scala

We used to limit the generated suite names so that the class definitions fit in 100 characters. However, this created problems because the suite names were not self-explanatory, and it was difficult to use wildcards to execute a set of tests.
This PR increases the limit and introduces aliases for test dimensions. These aliases are used for the suite names instead of the actual dimension trait name, shortening the total suite name length.
This PR only defines the aliases for a small set of dimensions to decrease the length of the longest suite names and prevent the truncation of any current suites. More aliases can be added as needed.
No

[Spark] Shorten generated suite names with dimension aliases

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeIntoMaterializeSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala

Convert `log.warn` to `logWarning` to add support for logging `MessageWithContext` objects.
The operation `log"..." + s"..."` currently produces an object of type `String`, which is compatible with `log.warn` but which is not consistent with the goals of Spark Structured Logging.  This converts the message fully to `MessageWithContext` and logs via `logWarning` to log in the Structured Logging format.
Confirmed it compiles
Changes the format of this warning.

Fix misuse of structured logging in MergeIntoMaterializeSource

---

kernel/kernel-api/src/main/java/io/delta/kernel/commit/CommitMetadata.java
unity/src/main/java/io/delta/unity/UCCatalogManagedClient.java
unity/src/main/java/io/delta/unity/UCCatalogManagedCommitter.java
unity/src/main/java/io/delta/unity/utils/OperationTimer.java
unity/src/test/scala/io/delta/unity/InMemoryUCClient.scala
unity/src/test/scala/io/delta/unity/InMemoryUCClientSuite.scala
unity/src/test/scala/io/delta/unity/UCCatalogManagedClientSuite.scala
unity/src/test/scala/io/delta/unity/UCCatalogManagedCommitterSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/5074/files) to review incremental changes.
- [**stack/kernel_uc_catalog_managed_committer_2b**](https://github.com/delta-io/delta/pull/5074) [[Files changed](https://github.com/delta-io/delta/pull/5074/files)]
---------
This PR fleshes out the remaining WRITE (not CREATE) UCCatalogManagedCommitter implementation. e.g. write the staged commit file, and then send that info to UC.
Simple unit tests. E2E mock write tests will come later.
No.

[Kernel] UCCatalogManagedCommitter: finish the lightweight WRITE (not CREATE) implementation

---

kernel/kernel-api/src/main/java/io/delta/kernel/engine/JsonHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
unity/src/main/java/io/delta/unity/UCCatalogManagedCommitter.java
unity/src/test/scala/io/delta/unity/UCCatalogManagedCommitterSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/5121/files) to review incremental changes.
- [**stack/kernel_uc_catalog_managed_committer_create**](https://github.com/delta-io/delta/pull/5121) [[Files changed](https://github.com/delta-io/delta/pull/5121/files)]
---------
Enable the UCCatalogManagedCommiter to be invoked for v0 at to thus CREATE the delta table. Note that UC still needs to be contacted about 00.json in a post-commit RPC hook. This is outside the purview of Kernel.
Simple UTs. More complex integration tests will come soon.
No.

[Kernel] [UC] UCatalogManagedCommitter CREATE support

---

build.sbt
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala

Added support for TRUNCATE operations in Delta tables by:
- Implementing the `SupportsTruncate` interface in `DeltaV1WriteBuilder`
- Adding TRUNCATE and OVERWRITE_BY_FILTER capabilities to the table's supported capabilities
- Importing required `SupportsTruncate` class from Spark SQL connector API
This change enables proper handling of TRUNCATE TABLE operations on Delta tables.
Spark’s change https://github.com/apache/spark/pull/50739 in 3.5.6 version
Spark 3.5.6 introduced stricter validation in the V2Writes rule (PR #50739) that requires tables to properly implement overwrite interfaces, not just declare capabilities.
1. Added stricter capability checks for TRUNCATE TABLE operations
The issue came from Delta tables not declaring TRUNCATE capability, leading to compatibility problems …

Fix Spark 3.5.6 compatibility: Add truncate with overwrite support to StagedDeltaTableV2

---

scalastyle-config.xml
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/ClassicMergeExecutor.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/merge/MergeOutputGeneration.scala

Spark
Consider a MERGE INTO query as follows:
```
MERGE INTO target_table t
USING change_events c
on c.id = t.id
WHEN MATCHED and c.operation = 'Update' THEN UPDATE SET *
```
Originally, this would create projections like this which would reference the target table's columns, causing a full table scan:
```
If(update_condition) c.data else t.data
```
This PR changes the projection to be like this:
```
If(update_condition) c.data else RaiseError("unexpected row: this row should have been filtered out
```
The key question is: why can we do this? The basic answer is because we will never hit the else condition because in a previous step, we filtered to rows that will be modified and need to be rewritten. At this point, I will mention that we can optimize the projection by directly setting …

[Spark] Avoid full table scan when MATCHED, NOT MATCHED predicates have conditionals 

---

kernel/kernel-api/src/main/java/io/delta/kernel/SnapshotBuilder.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotQueryContext.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotReportImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/SnapshotBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/SnapshotFactory.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/catalogManaged/SnapshotBuilderSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockSnapshotUtils.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/MetricsReportTestUtils.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/SnapshotReportSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/test/AbstractTableManagerAdapter.scala

Use this [link](https://github.com/delta-io/delta/pull/5145/files) to review incremental changes.
- [**stack/kernel_snapshot_builder_at_timestamp**](https://github.com/delta-io/delta/pull/5145) [[Files changed](https://github.com/delta-io/delta/pull/5145/files)]
---------
Implement `SnapshotBuilder::atTimestamp` API for the new SnapshotBuilder Kernel interface.
For now, this only supports tables where you are NOT passing in any ratifiedCommits (we need to still build the timestamp->version parsing logic to handle ratified commits)
New UTs for the builder.
Un-ignore other test cases so now we e2e test time-travel-by-timestamp with the new SnapshotBuilder API too 👍 
New SnapshotBuilder::atTimestamp API

[Kernel] Implement SnapshotBuilder::atTimestamp (doesn't support ratified commits)

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/LogSegment.java

Use this [link](https://github.com/delta-io/delta/pull/5148/files) to review incremental changes.
- [**stack/kernel_log_segment_refactor_cleanup**](https://github.com/delta-io/delta/pull/5148) [[Files changed](https://github.com/delta-io/delta/pull/5148/files)]
- [stack/kernel_snapshot_get_commit_info_from_ratified_commit_b](https://github.com/delta-io/delta/pull/5149) [[Files changed](https://github.com/delta-io/delta/pull/5149/files/b62d0c36bcd0dea0de02f5c88b6b9d8a4766cd2b..571011dc474d0a6144db43b1199314b5b7bd3537)]
---------
Use tiny input validationmethods to make the constructor of LogSegment more readable.
Just a refactor. No logic change. Existing UTs.
No.

[Kernel] LogSegment input validation refactor / simplification

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/test/scala/org/apache/spark/sql/delta/FeatureEnablementConcurrencySuite.scala

This PR allow the conflict free enablement of column mapping. This is based on the fact that when a table is first created without column mapping and then enabled later, we do not write any metadata to the file footers. Therefore, if a transaction conflicted with a column mapping enablement transaction, it does not need to write any metadata changes to adapt.
Added new suite.
No.

[Spark] Column mapping conflict free Enablement

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSink.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoColumnOrderSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaInsertIntoImplicitCastSuite.scala

An implicit cast is currently added during streaming writes whenever there is any schema mismatch between the data and the table schema.
While this is generally ok, it is too broad as just having extra, missing or differently ordered fields in the data to write is acceptable: the data written to Parquet files can be read back correctly in these cases.
Casting suffers from a long-standing issue, where `null` structs get incorrectly expanded to struct of null fields. To reduce the impact of that issue, we limit the cases where we add an implicit cast to the strict minimum: when there's actually a type mismatch in the data.
Added test cases covering the null expansion issue with casting in stream and other insert types:
For differently ordered fields: streaming doesn't add a cast anymore and …

[Spark] Don't add implicit cast in streaming write for extra/missing/reordered fields

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaColumnMappingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaIcebergCompatBaseSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaIcebergCompatV2Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaIcebergCompatV3Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableClusteringSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

Runs additional test suites with both the V1 and V2 transaction builders to increase test coverage. Previously these suites were run using only the V1 builders.
Test only change.
No.

[Kernel][Test-only] Run more write test suites with both the V1 and V2 transaction builders

---

spark/src/main/scala/io/delta/sql/DeltaSparkSessionExtension.scala
spark/src/main/scala/org/apache/spark/sql/delta/metric/IncrementMetric.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/metric/IncrementMetricSuite.scala

Resubmit https://github.com/delta-io/delta/pull/5172 which needed to be reverted because of failure.
Add `ConditionalIncrementMetric` expression that allows to increment a metric only if an additional conditions is passed.
In some cases, `IncrementMetric` is used inside a more complex expression, like `if (updated) IncrementMetric("numUpdatedRows", true) else IncrementMetric("numCopiedRows", false)`. But in some cases, Spark can optimize some of these out. `ConditionalIncrementMetric` will let us express this better.
Tests added.
No

[Spark] ConditionalIncrementMetric

---

spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/SuiteGeneratorConfig.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/DeleteCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/MergeCDCSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/UpdateCDCSuite.scala

This PR modularizes how CDC tests are run by introducing a Mixin to run `CDCReader.changesToBatchDF` to be compatible with the new suite generator framework.
This PR doesn't change any functionality and only refactors tests.
No

[SPARK][TEST-ONLY] Modularize CDC tests

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/JsonUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/DataFileStatisticsSuite.scala

This change adds support for reading and writing variant stats in the Delta Log JSON.  
Details for the structure are in this protocol RFC: https://github.com/delta-io/delta/blob/master/protocol_rfcs/variant-shredding.md#statistics-for-variant-columns
These stats are themselves variants (metadata + values concatenated) and then z85 encoded into a String. 
-->
Added unit tests
No because the ability to even create tables with variant is not supported yet, these are the underlying primitives....

[Kernel] Support reading/writing variant stats in JSON

---

connectors/golden-tables/src/main/scala/io/delta/golden/GoldenTableUtils.scala
kernel-spark/src/main/java/io/delta/kernel/spark/catalog/SparkTable.java
kernel-spark/src/test/java/io/delta/kernel/spark/read/GoldTableTest.java

Follow-up to https://github.com/delta-io/delta/pull/5201.  
Before that PR, the table schema column order was correct. After it, the schema aligned with Spark’s Parquet tables but diverged from Delta tables.  
This PR reverts the affected changes and adds tests to validate consistency between the delta-spark and kernel-spark connectors in both schema and table data.
Added new tests to compare schema and table data between delta-spark and kernel-spark connectors.
No, the kernel-spark connector is not released yet.

[kernel-spark] Fix table schema column order; add golden table comparison test

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingUtils.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceDeltaSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/TestClientForDeltaFormatSharing.scala

title. this change allows delta sharing delta-spark client to read shredded variants ("variantShredding-preview") table feature through delta sharing
added UT

[VARIANT][SPARK][SHARING] Allow delta-spark delta shraing reader to read shredded variants

---

spark/src/main/scala/org/apache/spark/sql/delta/ConflictChecker.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingRemovalConcurrencySuite.scala

This PR fixes a bug where conflict resolution between a business transaction and an unbackfill transaction would produce a conflict. Furthermore, it adds concurrency tests for Row Tracking removal.
Added new suite.
No.

[Spark] Unbackfill conflict resolution fix

---

spark/src/main/scala/org/apache/spark/sql/delta/RowCommitVersion.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowId.scala
spark/src/main/scala/org/apache/spark/sql/delta/RowTracking.scala

Not use field id when trying to access the two row tracking materialized columns
Existing tests
No

[Spark] not using field id when read row tracking columns

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/SnapshotBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/SnapshotFactory.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/catalogManaged/SnapshotBuilderSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/catalogManaged/CatalogManagedE2EReadSuite.scala

Support time-travel-by-timestamp using the new SnapshotBuilder APIs with parsedLogData.
Adds an E2E test. The actual underlying timestamp-to-version resolution used for time-travel is already thoroughly unit tested in https://github.com/delta-io/delta/pull/5235.
SnapshotBuilder.atTimestamp will work with parsedLogData.

[Kernel][CCV2] Support time-travel-by-timestamp with CCV2 commits in SnapshotBuilder

---

spark/src/main/scala/org/apache/spark/sql/delta/files/TransactionalWrite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaAlterTableTests.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableCreationTests.scala

Add implementation for DeltaConfigs.RANDOM_PREFIX_LENGTH.
Added a unit test in DeltaTableCreationTest.

[Spark][CherryPick][3.3] Support RANDOMIZE_FILE_PREFIXES 

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceCDCSupport.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaFastDropFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/CDCReaderSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingMergeSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaTestImplicits.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningFeatureCompatibilitySuite.scala

This PR is to plumb catalog tables to `CDCReader` API `changesToDF` call sites.
Existing UTs.
No

[Spark] Plumb catalog tables to `DeltaLog` API call sites in `changesToDF`

---

kernel/kernel-api/src/main/java/io/delta/kernel/commit/CommitResponse.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaHistoryManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/commit/DefaultFileSystemManagedTableOnlyCommitter.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedCatalogCommitData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedCheckpointData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedChecksumData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedClassicCheckpointData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedDeltaData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedLogCompactionData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedLogData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedMultiPartCheckpointData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedPublishedDeltaData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/files/ParsedV2CheckpointData.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/SnapshotBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/SnapshotFactory.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/DeltaHistoryManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/catalogManaged/SnapshotBuilderSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/files/ParsedLogDataSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/snapshot/LogSegmentSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/catalogManaged/CatalogManagedE2EReadSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestCommitterUtils.scala
unity/src/main/java/io/delta/unity/UCCatalogManagedClient.java
unity/src/main/java/io/delta/unity/UCCatalogManagedCommitter.java

Use this [link](https://github.com/delta-io/delta/pull/5279/files) to review incremental changes.
- [**stack/kernel_parsed_delta_data_refactor**](https://github.com/delta-io/delta/pull/5279) [[Files changed](https://github.com/delta-io/delta/pull/5279/files)]
---------
Create ParsedCatalogCommitData -- an explicit type of the now-abstarct-parent-class ParsedLogData.
The reason for this change is:
- catalog commits are different file types than published deltas. they have a different name (when as a file) and take priority over published deltas
- Note then that there is the type (catalog commit, published delta, crc, checkpoint, etc.) and then there is "where are the bytes?" --> which is either in a file or inline.
Refactor existing codes.
Mainly just a refactor. Updated a few tests. Added …

[Kernel] Create ParsedCatalogCommitData class

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/SnapshotImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checksum/ChecksumReader.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checksum/ChecksumUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ConflictChecker.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ProtocolMetadataLogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/SnapshotFactory.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumSimpleComparisonSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumStatsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

Use this [link](https://github.com/delta-io/delta/pull/5292/files) to review incremental changes.
- [**stack/kernel_protocol_metadata_log_replay_refactor_b**](https://github.com/delta-io/delta/pull/5292) [[Files changed](https://github.com/delta-io/delta/pull/5292/files)]
---------
Today, LogReplay <> P&M is a bit odd. LogReplay can load the P & M for you (def getProtocol, def getMetadata), but then when we create a snapshot we are injecting (a) the LogReplay object, but (b) the pre-loaded P & M, too.
This PR splits up that functionality. There is now an individual ProtocolMetadataLogReplay static loader that loads the P & M and returns any CRC file that was read along the way.
Just a refactor. Existing UTs.
No.

[Kernel] Refactor P&M replay to static utility

---

kernel/kernel-api/src/main/java/io/delta/kernel/commit/CatalogCommitterUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeature.java
unity/src/main/java/io/delta/unity/UCCatalogManagedClient.java

This PR adds #5245. 
- `TablePropertyEnablementKey` should exist for every `TableFeature`.
- We are alllowed to access `SET_TABLE_FEATURE_SUPPORTED_PREFIX` from `TableFeature` since it is also accessed from other places.
Since this does not add new functionality, I just ran the test suite, which passed.
No

[Kernel] refactored table_property_enablement_key (#5245)
