.github/workflows/test.yaml
build/sbt-launch-lib.bash
contribs/src/main/scala/io/delta/storage/GCSLogStore.scala
contribs/src/test/scala/io/delta/storage/GCSLogStoreSuite.scala
core/src/main/scala/io/delta/tables/DeltaColumnBuilder.scala
core/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
core/src/main/scala/org/apache/spark/sql/delta/commands/DeltaCommand.scala
core/src/main/scala/org/apache/spark/sql/delta/util/DeltaFileOperations.scala
core/src/test/scala/io/delta/tables/DeltaTableBuilderSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/CheckpointsSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
core/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
examples/scala/build/sbt-launch-lib.bash
python/delta/tables.py
python/delta/tests/test_deltatable.py
run-tests.py

Backport a variety of minor bug fixes and improvements to branch-1.0.
- https://github.com/delta-io/delta/commit/59aa330c403f8a71b3eef0e90bd61cd54aab108c
- https://github.com/delta-io/delta/commit/104e2a472b5a0a5c718c42ac14ac8b851a1a7fe8
- https://github.com/delta-io/delta/commit/7a3f1e8ec626e80880d524c2b897a969c8b4d63a
- https://github.com/delta-io/delta/commit/43d14226cc802d721d1683495cdc8511acf460a1
- https://github.com/delta-io/delta/commit/c586f9a7374923867c36f61df4ed133725c8df2c
- https://github.com/delta-io/delta/commit/95e90763fd9f54df8880911b28b97b023a485d5f
- https://github.com/delta-io/delta/pull/856/commits/ee5d31f52fadc03d46d7ffe5010e7b3ffe73baf1 // enable github actions to run tests
- https://github.com/delta-io/delta/commit/4359484368b4a06c32b663826ac60bf12d9e8025
- …

Branch 1.0.1 candidate

---

build.sbt
storage-dynamodb/integration_tests/dynamodb_logstore.py
storage-dynamodb/src/main/java/io/delta/storage/DynamoDBLogStore.java
storage-dynamodb/src/test/java/io/delta/storage/FailingDynamoDBLogStore.java

- misc code cleanup
- update DDB api config prefix to contain `.ddb` in response to TDs delta.io docs PR review
- add better prints to integration test

Improvements to DynamoDBLogStore.java feature #2

---

README.md

- Added a separate section for Delta Stand-alone.
- Added the connectors information about Apache Hive, Apache Flink, PrestoDB, Trino, Rust and Kafka-delta-ingest
- Added Delta Lake LinkedIn and youtube channels.

Adding the latest integrations and community channels

---

examples/scala/build.sbt

Update the version in integration test suite to upcoming release 1.2.1

Update Delta version to 1.2.1 in integration tests

---

kernel/USER_GUIDE.md

This PR adds `USER_GUIDE.md` which explains how to use the Delta Kernel APIs to build Delta Lake connectors.

[Kernel] API user guide

---

build.sbt

upgrade iceberg dependency to 1.4.0 in Delta 3.0 branch
UT

[Spark] upgrade iceberg dependency to 1.4.0 in Delta 3.0 branch

---

build.sbt

Use iceberg 1.4.0 final release
UT

[Spark] Use iceberg 1.4.0 final release

---

kernel/USER_GUIDE.md

There have been a few changes to APIs since the last update to `USER_GUIDE.md`. Update it to reflect the latest API changes.

[Kernel] Update Kernel USER_GUIDE based on the latest API updates

---

kernel/USER_GUIDE.md
kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java
kernel/kernel-api/src/main/java/io/delta/kernel/client/ParquetHandler.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/StructField.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/RowConverter.java
kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/internal/parquet/TestParquetBatchReader.java

Renames `ROW_INDEX_COLUMN_NAME` to `METADATA_ROW_INDEX_COLUMN_NAME` and `ROW_INDEX_COLUMN` to `METADATA_ROW_INDEX_COLUMN`. Also fixes a few typos in the user guide.
NA

[Kernel] Rename row index column variable names to mention "metadata"

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/client/package-info.java

Quality the class reference with full namespace in `package-info`.

[Kernel] Fix doc build error

---

kernel/README.md

The `kernel/README.md` got bit stale. Fix the links, add more links and update content.

[Kernel] Update `README.md`

---

kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala

Moves some helper methods under the "getLogSegementForVersion" heading to `object SnapshotManagerSuite` since they may be useful for other tests.
RE https://github.com/delta-io/delta/pull/2223#discussion_r1393345913
NA (refactor)

[Kernel] Refactor SnapshotManagerSuite helper methods

---

examples/scala/build.sbt

Previously, the <delta>/examples/scala sbt project was using (hardcoded) an older version of delta, which had no delta-iceberg artifact. Updated the delta version to be the latest.
cd <delta>/examples/scala && build/sbt compile
No

[Examples] Fix compilation - 3.0

---

kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Predicate.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultPredicateEvaluator.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/ExpressionUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/ExpressionVisitor.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/ExpressionSuiteBase.scala

Adds the `NOT` and `IS NOT NULL` expressions.
- Adds them to the list of supported expressions in `Predicate`
- Adds support to the `DefaultExpressionEvaluator`

[Kernel][Expressions] Adds the NOT and IS_NOT_NULL expressions

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/DataSkippingUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ExpressionUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ScanSuite.scala

Generate data skipping filters for NOT expressions for already supported skipping expressions (=, >, >=, <, <=, and).
Adds tests

[Kernel][Data skipping] Generate data skipping filters when possible for NOT expressions

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/DataSkippingUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/StatsSchemaHelper.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ScanSuite.scala

[3.1][DO_NOT_MERGE] Cherry-pick some Kernel expression commits to 3.1

---

docs/source/optimizations-oss.md

Adding docs for auto-compact. Rendered:
Generated the docs

[Docs] Add auto-compact docs

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TransactionalWrite.scala

(Cherry-pick of 04096f624e8bf1cc0c8ca8126000c176d79af4e7 to branch-3.1)
This change fixes two problems found in REORG APPLY UNIFORM
INSERT into a table enabling IcebergCompatV2 triggers NullPointerException.
REORG APPLY UNIFORM does not rewrite files
unit tests and manual tests
No

[UniForm][3.1] Fix REORG APPLY UNIFORM

---

examples/scala/src/main/scala/example/IcebergCompatV2.scala

This PR add an example explaining how to use REORG APPLY UniForm command to enable IcebergCompatV2 and UniForm
Manual run
No

[UniForm] [3.1] Add example for IcebergCompatV2 and REORG

---

docs/source/delta-batch.md

https://github.com/delta-io/delta/pull/2409 added table metadata sync (to HMS) to Delta Lake. This PR adds some documentation about this feature.

[Doc] Add doc describing table schema/properties sync to HMS

---

docs/source/delta-clustering.md
docs/source/index.md
docs/source/versioning.md

This PR adds documentation about liquid clustering preview in Delta Lake 3.1.0.

[Doc] Add liquid clustering preview documentation

---

docs/source/conf.py
docs/source/delta-storage.md
docs/source/quick-start.md
docs/source/releases.md

Few updates to to get the docs ready for 3.1.0 release.

[Docs] Update the docs to refer to the 3.1.0 version

---

examples/scala/src/main/scala/example/Clustering.scala

Add Clustering example
Cherry picked from https://github.com/delta-io/delta/pull/2520
manually run the example
```
python3 run-integration-tests.py --use-local
```
No

[Spark][3.1] Add Clustering example

---

docs/source/delta-clustering.md
docs/source/index.md
docs/source/versioning.md

This PR adds documentation about liquid clustering preview in Delta Lake 3.1.0.
Cherry picked from https://github.com/delta-io/delta/pull/2513

[Doc][3.1] Add liquid clustering preview documentation

---

kernel/examples/table-reader/src/main/java/io/delta/kernel/integration/IntegrationTestSuite.java

Adds additional integration tests.
Ran the integration tests.

[Kernel] Add additional integration tests for data skipping, partition pruning, and column mapping mode ID

---

docs/source/delta-deletion-vectors.md

Update Deletion Vectors doc to include deletion support for UPDATE and MERGE.
Docs-only changes.
No.

Update Deletion Vectors doc to include UPDATE and MERGE.

---

docs/source/delta-uniform.md

The doc update captures several major upgrades for Delta Uniform in Delta 3.1

Update Delta Uniform documentation for Delta 3.1

---

docs/source/delta-uniform.md

Cherry-pick #2543 to branch-3.1
The doc update captures several major upgrades for Delta Uniform in Delta 3.1

[3.1] Update Delta Uniform documentation for Delta 3.1

---

docs/source/delta-deletion-vectors.md

Update Deletion Vectors doc to include deletion support for UPDATE and MERGE.
This is a cherry pick of https://github.com/delta-io/delta/pull/2511.
Docs-only changes.
No.

[3.1] Update Deletion Vectors doc to include UPDATE and MERGE

---

docs/source/delta-deletion-vectors.md
docs/source/delta-drop-feature.md
docs/source/index.md

Update documentation to cover `ALTER TABLE <table-name> DROP FEATURE <feature-name>` command.
N/A
No.

[Docs] Add docs for dropping table feature

---

docs/source/delta-batch.md
docs/source/delta-sharing.md
docs/source/delta-streaming.md
docs/source/index.md

Add doc for delta sharing with examples of commands.
N/A
No

[Spark][Sharing] Add doc for delta sharing

---

docs/source/delta-drop-feature.md

Backport of https://github.com/delta-io/delta/pull/2572. Support for dropping V2 Checkpoints was added in Delta 3.1. This PR makes sure that the V2 Checkpoint spec is linked in the doc about DROP Table Feature.

[Doc][3.1] Add a link to the V2 Checkpoint specification in the DROP TABLE Feature doc

---

docs/source/delta-drop-feature.md

Support for dropping V2 Checkpoints was added in Delta 3.1. This PR makes sure that the V2 Checkpoint spec is linked in the doc about DROP Table Feature.

[Doc] Add a link to the V2 Checkpoint specification in the DROP TABLE Feature doc

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableForUpgradeUniformHelper.scala

Cherrypick https://github.com/delta-io/delta/pull/2485 to branch-3.1
manual test

[Spark] auto upgrade protocol for REORG UPGRADE UNIFORM

---

docs/source/delta-uniform.md

update Uniform documentation for explicitly enable column mapping during REORG

update Uniform documentation for explicitly enable column mapping during REORG

---

docs/source/delta-uniform.md

Minor update to Delta Uniform doc specifying delta version that requires column mapping for REORG

Minor update to Delta Uniform doc specifying delta version that requires column mapping for REORG

---

kernel/kernel-api/src/main/java/io/delta/kernel/Table.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala

Follow-up to https://github.com/delta-io/delta/pull/2607#discussion_r1480314605
Refactor PR existing tests suffice

[Kernel] Refactor SnapshotManager to take logPath and dataPath as part of the constructor

---

.github/ISSUE_TEMPLATE/protocol-rfc.md
protocol_rfcs/managed-commits.md

Adds the proposal for spec change for Managed-Commits (see https://github.com/delta-io/delta/issues/2598) to the RFC folder.
NA
NA

[Protocol Change] SPEC change proposal for managed-commits

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultFileSystemClientSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

Resolves #2640
Adds unit test
No

[Kernel][Java to Scala test conversion] Convert TestDefaultFileSystemClient written in Java to Scala

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/client/DefaultJsonHandlerSuite.scala

Resolves #2639
Unit tests added.
No.

[Kernel][Java to Scala test conversion] Convert TestDefaultJsonHandler written in Java to Scala

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/DataSkippingUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ScanSuite.scala

Resolves #2530
Unit tests added.
No.

[Kernel][Data skipping] Add support data skipping for IS_NULL and NOT(IS_NULL)

---

kernel/kernel-api/src/test/scala/io/delta/kernel/MockFileSystemClientUtils.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala

- Moves the utilities for mocking the file system handler to a separate trait and make the modificationTime=version*10 for delta file status generations
- Moves tests in DeltaTableReadsSuite to under the correct header
Just refactors tests

[Kernel] Test refactoring for #2662 (separate utilities for mocking file system handler)

---

protocol_rfcs/README.md
protocol_rfcs/vacuum-protocol-check.md

Adds the VacuumProtocolCheck PROTOCOL change proposal. Design Doc: https://docs.google.com/document/d/15o8WO2T0vN21S5JG-FT_ZNhXFCWyh0i9tqhr9kBmZpE/edit#heading=h.4cz970y1mk93
Protocol RFC issue: https://github.com/delta-io/delta/issues/2630
The Delta Lake Community encourages protocol innovations. Would you or another member of your organization be willing to contribute this feature to the Delta Lake code base?

[Protocol Change Request] Add VacuumProtocolCheck PROTOCOL change request

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableStrategy.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/optimize/AddFileWithNumRecords.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/optimize/OptimizeStats.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/optimize/ZCubeFileStatsCollector.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/optimize/ZOrderMetrics.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteringStats.scala
spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ZCube.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/zorder/ZCubeInfo.scala
spark/src/test/scala/org/apache/spark/sql/delta/optimize/OptimizeMetricsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/IncrementalZCubeClusteringSuite.scala

Implement incremental Liquid clustering according to the deisgn [doc](https://docs.google.com/document/d/1FWR3odjOw4v4-hjFy_hVaNdxHVs4WuK1asfB6M6XEMw/edit?usp=sharing).
This implementation uses ZCube based approach to achieve incremental clustering. When a Zcube size is big enough, the zcube is sealed and the next clustering won't re-cluster those files and so less write amplification.
Key changes
Each clustered file is tagged with ZCUBE_ID to track which ZCUBE it belongs to and the id is generated using UUID. Also anther tag ZCUBE_ZORDER_BY is used to track the clustering columns. Each clustered file has the clsuteringProvider populated with liquid.
new unit tests.
No

[Spark] Implement incremental clustering using ZCUBE approach

---

connectors/flink/src/test/java/io/delta/flink/sink/DeltaSinkStreamingExecutionITCase.java

We have two flaky tests that sometimes block other jobs.
See [here](https://github.com/delta-io/delta/actions/runs/8191593850/job/22401155588?pr=2727) and [here](https://github.com/delta-io/delta/pull/1934) for example.
This disables these tests while we investigate and fix them.
No

[Flink] disable two flaky flink tests

---

spark/src/test/scala/org/apache/spark/sql/delta/rowtracking/MaterializedColumnSuite.scala

Add Materialized Row Tracking columns CLONE tests, making sure we have enough Row Tracking test coverage necessary to gear us towards [enabling Row Tracking outside of testing](https://github.com/delta-io/delta/pull/2059).
Existing + added UTs.
No.

[Spark][Test-Only] Add Materialized Row Tracking columns CLONE tests

---

kernel/examples/run-kernel-examples.py
kernel/examples/table-reader/pom.xml

[Build] Add `storage` module dependency to Kernel examples

---

build.sbt

Build changes from PR: https://github.com/delta-io/delta/pull/2770

[Build] Add `storage` module dependency to `kernel-defaults`

---

spark/src/main/scala/io/delta/tables/DeltaMergeBuilder.scala

Currently, `DeltaMergeBuilder` performs a custom relation deduplication logic reminiscent to the DeduplicateRelations analyzer rule. This duplicates logic and might cause issues from unforeseen interaction with the rule during the analysis of the MERGE plan. This PR refactors the deduplication in DeltaMergeBuilder to utilise the `DeduplicateRelations` rule. The new flow is as follows:
1. Un-resolve the ambiguous pre-resolved references.
2. Invoke DeduplicateRelations to do the deduplication work with FakeLogicalPlan.
3. Use the deduplicated source and target plan in the final MERGE command.
Existing tests. `MergeIntoScalaSuite` covers self merges with the Scala API.
No.

[Spark] Refactor deduplication in DeltaMergeBuilder to utilize DeduplicateRelations Rule.

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala

minor refactor to delta shallow clone to reorder and simplify logics. 
UT

Refactor to Delta shallow clone

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTimeTravelSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

Minor refactor to ManagedCommitBaseSuite utility - add comments.
Existing UTs
No

[Spark] Minor refactor to ManagedCommitBaseSuite utility - add comments

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaHistoryManagerSuite.scala

Allow invalid ranges in DeltaHistoryManager::getHistory and return the valid subset of the commits.
UTs
No

[Spark] Make DeltaHistoryManager::getHistory more lenient towards incorrect ranges

---

connectors/flink/README.md

[docs] Update README.md

---

spark/src/test/scala/org/apache/spark/sql/delta/deletionvectors/DeletionVectorsSuite.scala

Delete commit json then write the new json as env may cannot overwrite file. 
UT

[DeletionVectorsSuite] Delete commit json then write the new json

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala

Add CommitStore support in more snapshot create codeflow
Existing UTs

[Spark] Add CommitStore support in more snapshot create codeflow

---

PROTOCOL.md

Minor fix: add IcebergCompatV2 to appendix supported list of table features

Minor fix: add IcebergCompatV2 to appendix supported list of table features

---

spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala

fix Delta UniversalFormat bug so it supports overwrite table. It should use a full metadata for later detection logic.
manual test with dataframe overwrite.

fix Delta UniversalFormat bug so it supports overwrite table

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/CheckpointHook.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

Add Managed Commit support in deltaLog.getSnapshotAt() API.
UTs
No

[Spark] Add Managed Commit support in getSnapshotAt API

---

PROTOCOL.md

[PROTOCOL] Clarify checkpoint names

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckpointsSuite.scala

V2 Checkpoint Manifest writes currently have a bug: logStore.write(overwrite=true) is invoked for all logstores. This is unsafe for clouds like Azure where partial writes are visible to readers (i.e. a failed result can create a corrupted manifest). This PR updates this so that logStore.isPartialWriteVisible is used to determine where overwrite should be true.
Added a new test suite V2CheckpointManifestOverwriteSuite which makes sure that the correct API is invoked depending on what logStore.isPartialWriteVisible returns.
No

[Spark] V2Checkpoint Manifest Writes: Use overwrite=false for logstores when partial write is visible

---

spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoMaterializeSourceSuite.scala

Reverts delta-io/delta#2896
It was merged too soon before the tests were completed. Unfortunately, the tests have a failure.

Revert "[Spark][TEST-ONLY] Merge source materialization non-determinism determination in subqueries tests"

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala

Minor refactor to consolidate code path.  Replace `new Path(tableWithLocation.location)` with `getDeltaTablePath(tableWithLocation)`, which better express the purpose here.
Exist unit tests.
No

Refactor Create and Clone command

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingLogFileSystem.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

This PR makes changes to `DeltaLog.getChanges/getChangeLogFiles` API in order to support managed-commits.
UTs
No

[Spark] Managed Commit support for DeltaLog's getChanges/getChangeLogFiles API

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/columnmapping/RemoveColumnMappingCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/columnmapping/RemoveColumnMappingCDCSuite.scala

Extend CDC support around column mapping removal.
Most notably, ensure CDC data is not generated for the column mapping removal commit and prohibit reading CDC data across column mapping removal boundary.
New unit tests

Column mapping removal: support CDC enabled tables

---

build.sbt
sharing/src/main/scala/io/delta/sharing/spark/DeltaFormatSharingSource.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaFormatSharingSourceSuite.scala

Upgrade delta-sharing-client to 1.0.5
Unit Tests
No

Upgrade delta-sharing-client to 1.0.5

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwner.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/TableCommitOwnerClient.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogMinorCompactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/InCommitTimestampSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/OptimisticTransactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/CommitOwnerClientSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/InMemoryCommitOwnerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitTestUtils.scala

Rename Commit Store to Commit Owner
Existing UTs
No

[Spark] Rename Commit Store to Commit Owner

---

.github/workflows/spark_master_test.yaml
.github/workflows/spark_test.yaml

Set test parallelism to 2 for delta-spark against Spark Master tests
CI tests on this PR
No

[INFRA] Set Spark Master test parallelism to 2

---

docs/source/delta-clustering.md

Update documentation about liquid clustering for Delta 3.2
No

[Docs] Update liquid clustering documentation for Delta 3.2

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala

Handle incomplete backfills after MC -> FS conversion.
UTs
No

[Spark] Handle incomplete backfills after MC -> FS conversion 

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/PartitionUtilsSuite.scala

(Split from larger PR #2944)
Utility method to construct the partition data directory.
UTs

[Kernel][Writes] Utility method to construct partition data directory

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaFileProviderUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala

Use DeltaLog.getChanges API in DeltaFileProviderUtils's getDeltaFilesInVersionRange API.
UT
No

[Spark] Use DeltaLog.getChanges API in DeltaFileProviderUtils's getDeltaFilesInVersionRange API

---

docs/source/delta-uniform.md
docs/source/versioning.md

Add documentation for Uniform Hudi

Add documentation for Uniform Hudi

---

spark/src/main/scala/org/apache/spark/sql/delta/PreDowngradeTableFeatureCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala

This PR adds validations around dropping of dependent table features.
UTs
No

[Spark] Disallow dropping of dependent table features

---

docs/source/versioning.md

Add documentation link for Vacuum Protocol Check spec

Add documentation link for Vacuum Protocol Check

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala

Fix the exception name for REORG TABLE table_name APPLY (UPGRADE UNIFORM (ICEBERG_COMPAT_VERSION = version)
Current unit tests
No

[Spark]fix the exception name for REORG TABLE ... APPLY (UPGRADE UNIFORM ...)

---

docs/source/delta-drop-feature.md
docs/source/delta-type-widening.md
docs/source/index.md
docs/source/versioning.md

Add a documentation page for the type widening table feature, in preview in Delta. 3.2
N/A

[Doc] Type Widening documentation

---

docs/source/snowflake-integration.md

Updates the Snowflake integration page to mark the manifest file method as outdated and include the Snowflake Delta Lake connector as main content.
Current page: https://docs.delta.io/latest/snowflake-integration.html
Updated page:
Built locally.

[Docs] Update the Snowflake integration page

---

kernel/kernel-api/src/main/java/io/delta/kernel/ScanBuilder.java

addresses https://github.com/delta-io/delta/issues/2703
No. API docs updates only.
No

[Kernel] [API-Docs] API doc update for ScanBuilder.withFilter

---

version.sbt

Set the version to 3.2.1-SNAPSHOT

[BUILD] Set the version to 3.2.1-SNAPSHOT

---

spark/src/test/scala/org/apache/spark/sql/delta/AutoCompactSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/deletionvectors/DeletionVectorsSuite.scala

adds testing for auto compaction and deletion vectors
test only change

[SPARK] Add more testing for variant + delta features

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/AbstractBatchBackfillingCommitOwnerClient.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala

Resolves TODOs around ICT <-> MC integration.
Updated existing tests.
No

[Spark] Integrate ICT into Managed Commits

---

docs/source/bigquery-integration.md
docs/source/integrations.md

Adds a page on BigQuery Delta Lake integration to the "integrations" page.
Page is like this:
And it is indexed as part of the integrations page here:
Local build.
No.

[DOCS] Add page on BigQuery Delta Lake integration

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala

Make WRITE commands call `OptimisticTransaction.withActive` to set as active the transaction the transaction that is created by `startTxnForTableCreation()`.
No

[Spark] Set active txn during write and ctas commands

---

docs/source/delta-type-widening.md

Update the type widening documentation to list additional type changes supported in Delta 4.0

Delta 4.0 - Type Widening documentation

---

docs/source/delta-apidoc.md

[DOCS] Fix typo suggestions on Delta APIs page

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableFeaturesSuite.scala

[Kernel] Add the InCommitTimestamp table feature

[Kernel] Add the InCommitTimestamp table feature

---

examples/scala/src/main/scala/example/Variant.scala

adds an integration test for variant to create and insert variant values using sql and scala API
test only change.
Haven't been able to run this in the integration testing framework yet. However, manually tested this in spark shell using instructions [here](https://docs.google.com/document/d/1gpxcKZitSGf0K217kJa8eOaq5y-BDnDKpcuQ3JCjNCE/edit#heading=h.ybzt6s7hn9ff)
no

[VARIANT] Add variant integration tests

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala

This PR adds logging the main DeltaSource operations to allow us to measure the duration of these operations.
Existing tests to make sure nothing breaks.
No

[Spark] Log duration of DeltaSource operations

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitUsageLogs.scala
spark/src/main/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/SnapshotManagementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/managedcommit/ManagedCommitSuite.scala

Add logging around managed commits.
UTs
No

[DELTA] Add logs around managed commits

---

spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableWithDVs.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/constraints/DeltaInvariantCheckerExec.scala
spark/src/main/scala/org/apache/spark/sql/delta/deletionvectors/RowIndexMarkingFilters.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaParquetFileFormatSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/deletionvectors/DeletionVectorsSuite.scala

Improves the running time of DeletionVectorsSuite. It also includes some minor import cleanup.
Resolves #3257 
Test only PR.

[Tests] Improve the running time of DeletionVectorsSuite

---

PROTOCOL.md
docs/source/versioning.md

adds variant type to the docs in "feature by protocol version" and "what delta features require client upgrades" section.
I didn't think that this feature requires a dedicated section (similar to TimestampNTZ).
manually tested links using localhost

[VARIANT][DOCS] Add Variant type (Preview) to docs 

---

docs/source/delta-spark-connect.md
docs/source/index.md

Add a documentation page for the [Delta Connect](https://github.com/delta-io/delta/issues/1570), in Delta 4.0 preview.
N/A

[Doc] Delta 4.0 - Delta Connect documentation

---

docs/source/delta-row-tracking.md
docs/source/index.md
docs/source/versioning.md

This PR adds documentation for the new Row Tracking table feature that is releasing in Delta 3.2.0. This is a cherry-pick of https://github.com/delta-io/delta/pull/2939 to branch-3.2
N/A
N/A

[Docs][3.2] Add documentation for Row Tracking

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala

Instead of calling `SchemaUtils.findNestedFieldIgnoreCase` for each column, we prepare a map with `SchemaUtils.explode` before, and perform map lookups during iteration. 
This speeds up this function on wide tables. It may still be slow for tables with deeply nested schemas because the path needs to be built every time, but there should be no regression.
Manual profiling for an alter table add columns query:
Before: (~13s)
After: (~3s)

[Spark] use map lookup in createPhysicalSchema

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/ThreadStorageExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/TransactionExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/AbstractBatchBackfillingCommitCoordinatorClient.scala

Add generic trait for thread local execution observers to extend and implement.
Unit tests
No

[Spark] Add trait for generic executor observer thread local storage

---

spark/src/test/scala/org/apache/spark/sql/delta/ImplicitDMLCastingSuite.scala

- Break down ImplicitDMLCastingSuite into command-specific sub-suites to improve organisation of tests.
Testing-only PR.
No.

[Spark] Break down ImplicitDMLCastingSuite

---

spark/src/main/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteringColumn.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteringColumnSuite.scala

Improves error message on internal clustering column API. 
N/A.

[Spark] Improve internal error message for clustering column validation

---

build.sbt
hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConversionTransaction.scala
hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConverter.scala
hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiTransactionUtils.scala
hudi/src/test/scala/org/apache/spark/sql/delta/hudi/ConvertToHudiSuite.scala

This version upgrades the Hudi version from 0.14.0 to 0.15.0. This upgrade is needed because 0.14.0 does not support Apache Spark 3.5.
Unit tests
No

[Hudi] Upgrade Hudi version

---

spark/src/test/scala/org/apache/spark/sql/delta/ConvertToDeltaSuiteBase.scala

Use trigger.AvailableNow in ConvertToDelta suites.
This PR itself is test-only
No

Use trigger.AvailableNow in ConvertToDelta suites

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConversionTransaction.scala

This PR adds a clause to catch a few specific HoodieExceptions from the Hudi metadata conversion that are not data-corrupting and only cause the conversion to abort. This is acceptable because the conversion of this commit will just happen in a future Delta commit instead.
These exceptions can occur due to IO failures or multiple writers trying to write to the metadata table at the same time. If multiple writers are writing to the metadata table at the same time, the issue that occurs is that both writers see a failed commit in the Hudi metadata timeline and try to roll it back. The faster writer is able to roll it back with no problem and no exception, but the slower writer will try to roll it back and find that the commit no longer exists (since it was already rolled back by the faster …

[Hudi] Catch harmless HoodieExceptions when metadata conversion aborts

---

docs/source/quick-start.md

modified very to every
This PR corrects the typographical error in quick-start.md by modifying `very` to `every`.
Not needed.
No.

[Documentation] typo correction - very to every in quick-start docs

---

spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala

This PR fixes an inaccurate error message when IcebergCompat discovers incompatible data type in the schema. Before the fix, if a struct has a field containing nested incompatible data type, the checks in IcebergCompat reports the field type. For example, "STRUCT<v0: STRING, v1: STRUCT<v11: VOID>>" contains an incompatible type "VOID", our message will report "struct is not supported". As struct is supported, this causes a confusion. This fix makes it report the actual incompatible data type. In the example above, we will report "void is not supported".
UT
No

[UniForm] Report accurate type when checking Iceberg compatible types

---

spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaMergingUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

As title, this adds an useful utils to prune out empty structs from a schema, in preparation for some future work.
New UT.
No

[SPARK] Add schema utils to prune empty structs from a schema

---

spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaSQLTestUtils.scala

`withTempDir` is widely used across Delta tests to create temporary directories. The spark version in `SQLTestUtil` waits for all running spark tasks to finish with a 10s timeout, but seems to be prone to under or over counting the number of running tasks, sometime causing it to timeout and fail the test.
Change:
- Use Delta's version of `withTempDir`/`withTempPath`/withTempPaths`, which immediately deletes the temp directory when the code returns. This version is already in many Delta tests.

[Spark] Remove timeout source from withTempDir in Delta tests

---

spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoMaterializeSourceSuite.scala

This PR adds an integration test in `MergeIntoMaterializeSourceSuite` to improve code coverage for `MergeIntoMaterializeSource.scala`.
An integration test was added to `MergeIntoMaterializeSourceSuite`
No.

[SPARK] Add Integration Test in `MergeIntoMaterializeSourceSuite`

---

build.sbt
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/DefaultCommitCoordinatorClientHandler.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/coordinatedcommits/StorageKernelAPIAdapter.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/coordinatedcommits/InMemoryCommitCoordinatorBuilder.scala
storage/src/main/java/io/delta/storage/commit/CommitCoordinatorClient.java
storage/src/test/scala/io/delta/storage/commit/CoordinatedCommitsUtils.java
storage/src/test/scala/io/delta/storage/commit/InMemoryCommitCoordinator.scala

An InMemoryCommitCoordinator to kernel to track per-table commits, backfills and validates various edge cases and unexpected scenarios.
Unit tests
No.

[Storage][Kernel] Add InMemoryCommitCoordinator

---

hudi/src/test/scala/org/apache/spark/sql/delta/hudi/ConvertToHudiSuite.scala

This PR refactors a unit test for UniForm Hudi
It is a test-only change
No.

[Hudi] Refactor tests

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala
spark/src/main/scala/org/apache/spark/sql/delta/metering/DeltaLogging.scala
spark/src/test/scala/org/apache/spark/sql/delta/logging/LogThrottlingSuite.scala

- Add a token bucket based throttler implementation that can be used to throttle log messages that are suspected of potential log flooding issues.
New test suite: `LogThrottlingSuite`
No

[Spark] Add Delta log throttling class

---

docs/generate_docs.py
docs/source/delta-apidoc.md
docs/source/delta-coordinated-commits.md
docs/source/delta-drop-feature.md
docs/source/delta-spark-connect.md
docs/source/index.md
docs/source/quick-start.md
docs/source/releases.md
docs/source/versioning.md

- Update the versions in quickstart to use the preview release version
- Cherry-pick some docs from master
- Exclude the API docs for now
Local build

[DO_NOT_MERGE][4.0 Preview] Docs changes

---

kernel/kernel-api/src/main/java/io/delta/kernel/types/ArrayType.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/MapType.java

Rather than just tracking the underlying `DataType` this tracks the underlying field and thus allows to track nullability and metadata through that field

[Kernel] Track nested fields in ArrayType / MapType

---

.github/workflows/spark_master_test.yaml
build.sbt
project/Unidoc.scala
project/plugins.sbt
spark-connect/client/src/main/scala-spark-master/io/delta/connect/tables/DeltaTable.scala
spark-connect/client/src/test/scala-spark-master/io/delta/connect/tables/DeltaQueryTest.scala
spark-connect/client/src/test/scala-spark-master/io/delta/connect/tables/DeltaTableSuite.scala
spark-connect/client/src/test/scala-spark-master/io/delta/connect/tables/RemoteSparkSession.scala
spark-connect/server/src/main/scala-spark-master/io/delta/connect/SimpleDeltaConnectService.scala

This PR adds the skeleton for the Delta Connect Scala Client. It adds some basic methods (`forPath`, `forName`, and `as`) to confirm that Delta Connect relations work. More methods will be added in future PRs.
Added `DeltaTableSuite`.
No.

[Spark] Add Delta Connect Scala Client

---

spark/src/main/scala/org/apache/spark/sql/delta/FileMetadataMaterializationTracker.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillBatchIterator.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillBatch.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingBackfillIteratorSuite.scala

In this PR, we add `BackfillBatchIterator` which contains the core logic for selecting files for the WIP Row Tracking Backfill operation, creating iterators which batches files together. The Row Tracking Backfill operation will have multiple commits, each commit adds `baseRowId` to a batch of files. More details can be found in the [Design Doc](https://docs.google.com/document/d/1ji3zIWURSz_qugpRHjIV_2BUZPVKxYMiEFaDORt_ULA/edit#heading=h.8al9qhd83yov).
Added new Test Suite.
No.

[Spark] Add BackfillBatchIterator for Row Tracking Backfill

---

examples/scala/build.sbt
examples/scala/src/main/scala/example/Variant.scala

Variant type support was added for the Delta 4.0 preview release on Spark 4.0 Preview. An integration test was added to the release branch in https://github.com/delta-io/delta/pull/3220, this PR adds the integration test to master with some updated infra.
- Doesn't run the test when Spark version is too low
- Updates `examples/scala/build.sbt` to work for 4.0.0+
Ran the scala integration tests using both `3.2.0` and `4.0.0rc1`
No.

[Spark] Add variant integration test to master

---

kernel/EXCEPTION_PRINCIPLES.md

[Kernel] Add exception principles for Kernel to solidify the rules for our exception framework

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/ArrayType.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/MapType.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala

This handles nested schema and resolves https://github.com/delta-io/delta/issues/3427. This currently depends on https://github.com/delta-io/delta/pull/3435

[Kernel] Add support for nested schema fields

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/LikeExpressionEvaluator.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluatorSuite.scala

Resolves https://github.com/delta-io/delta/issues/3129
Existing tests validated. This is a performance optimization for LIKE expression evaluation.
No

[Kernel][Expression] - Performance Optimization for LIKE expression evaluation

---

.github/workflows/spark_test.yaml

(cherry-pick #3302)
... enforced by the `pip` from `24.1`
Recent `delta-spark` [CI
jobs](https://github.com/delta-io/delta/actions/runs/9628486756/job/26556785657) are failing with the following error.
```
ERROR: Invalid requirement: 'delta-spark==3.3.0-SNAPSHOT': Expected end or semicolon (after version specifier)
delta-spark==3.3.0-SNAPSHOT
~~~~~~~^
```
Earlier
[runs](https://github.com/delta-io/delta/actions/runs/9526169441/job/26261227425) had the following warning
```
DEPRECATION: delta-spark 3.3.0-SNAPSHOT has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of delta-spark or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at …
```

[Spark] Pin the `pip` version to `24.0` to get around the version format requirement

---

.github/workflows/spark_test.yaml

Cherry-pick  #3302
... enforced by the `pip` from `24.1`
Recent `delta-spark` [CI
jobs](https://github.com/delta-io/delta/actions/runs/9628486756/job/26556785657) are failing with the following error.
```
ERROR: Invalid requirement: 'delta-spark==3.3.0-SNAPSHOT': Expected end or semicolon (after version specifier)
delta-spark==3.3.0-SNAPSHOT
~~~~~~~^
```
Earlier
[runs](https://github.com/delta-io/delta/actions/runs/9526169441/job/26261227425) had the following warning
```
DEPRECATION: delta-spark 3.3.0-SNAPSHOT has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of delta-spark or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at …
```

[3.2][Spark] Pin the `pip` version to `24.0` to get around the version format requirement

---

build.sbt
dev/kernel-checkstyle.xml
kernel/README.md
project/plugins.sbt

This configures a code formatter using *google-java-format* for the Java code in the Kernel (similarly to how it was done in https://github.com/unitycatalog/unitycatalog/commit/54b76d88255dd2baa3f11e515159cfd34cb295e2).
Code can be checked by running `build/sbt javafmtCheckAll`. Code can automatically be formatted `build/sbt javafmtAll`.
Once this PR is in, we should open follow-up PRs where the code in the Kernel is properly formatted. 
After that we can enforce the new code style during compilation

[Kernel] Configure code formatter for Java Code

---

build.sbt

Upgrade delta-sharing-client to 1.1.1
Unit tests.

[Sharing] Upgrade delta-sharing-client to 1.1.1

---

build.sbt
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingCDFUtilsSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingFileIndexSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/TestClientForDeltaFormatSharing.scala

Upgrade delta-sharing-client to v1.1.1
Unit tests.

[3.2][Sharing] Upgrade delta-sharing-client to version 1.1.1

---

iceberg/src/test/scala/org/apache/spark/sql/delta/uniform/IcebergCompatV2EnableUniformByAlterTableSuite.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/uniform/UniversalFormatSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/IcebergCompatUtilsBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/UniversalFormatSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/uniform/IcebergCompatV2EnableUniformByAlterTableSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/uniform/UniFormE2ETest.scala

this PR adds unit tests in `UniversalFormatSuiteBase` and the corresponding testing utilities, especially for `IcebergCompatV1/V2` table features and `REORG UPGRADE UNIFORM` command.
- `UniversalFormatSuiteBase` contains all common unit tests.
- `UniversalFormatSuite` contains the actual classes to run the corresponding suites, it also contains helper traits for testing.
through unit tests in `UniversalFormatSuite`.
no.

[Spark][UniForm] Add `UniversalFormatSuite` and utils for `IcebergCompatV1/V2` & `REORG UPGRADE UNIFORM`

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/DefaultKernelUtils.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetSchemaUtils.java

Minor cleanup in delta-kernel
N/A
N/A

[Kernel] Minor cleanup in delta-kernel

---

docs/README.md

An additional step are needed to build the docs locally.

[Docs] Minor update to docs build instructions

---

build.sbt

Remove print statements from Iceberg assembly output.
CI tests.
No

[INFRA] Cleanup build.sbt build output

---

PROTOCOL.md

Fix style in PROTOCOL

---

spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionTestMixin.scala

2 PRs both added `unblockCommit` at similar time, which causes Compile Error to the repro.
Removing one of it to fix the problem.
Existing UTs.
No.

[Spark] Remove duplicate unblockCommit to fix GitHub tests

---

.github/workflows/spark_master_test.yaml
.github/workflows/spark_test.yaml
project/TestParallelization.scala

Increase test JVM parallelization to 4.
CI tests.
No.

[Infra] Increase test parallelism

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/MergeIntoCommandBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSQLSuite.scala

It makes `MergeIntoCommandBase` extend a trait `SupportsNonDeterministicExpression` in Spark that logical plans can extend to check whether it can allow non-deterministic expressions and pass the CheckAnalysis rule.
`MergeIntoCommandBase` extends `SupportsNonDeterministicExpression` to check whether all the conditions in the Merge command are deterministic.
This is harmless and allows more flexible usage of merge. For example, we use a non-deterministic UDF to generate identity values for identity columns, so it is required to allow non-deterministic expressions in updated/inserted column values of merge statements in order to support merge on target tables with identity columns. So this PR is part of https://github.com/delta-io/delta/issues/1959.
New test cases.
Yes.
We are changing the …

[SPARK] Allow non-deterministic expressions in actions of merge

---

spark/src/test/scala/org/apache/spark/sql/delta/FileMetadataMaterializationTrackerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingCompactionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingDeleteSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingMergeSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingUpdateSuite.scala

- Add tests that check row tracking preservation works on DMLs for backfilled enabled tables, as opposed to having row tracking enabled from the start.
- `FileMetadataMaterializationTrackerSuite` has a test that sets a different number of permits than the default in the `FileMetadataMaterializationTracker` but forgot to set it back, which causes unwanted failure in other test. We address that by using the default number of permits in that test instead of a different one.
Added UTs.
No.

[Spark] Add tests that check row tracking preservation works on DMLs for backfilled enabled tables

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala

Fix Vacuum test code to make use of artificial clock everywhere
Existing tests
No

[TEST-ONLY + Refactor] Fix Vacuum test code to make use of artificial clock everywhere

---

python/delta/connect/proto/relations_pb2.py
python/delta/connect/proto/relations_pb2.pyi
spark-connect/client/src/main/scala-spark-master/io/delta/connect/tables/DeltaTable.scala
spark-connect/client/src/test/scala-spark-master/io/delta/connect/tables/DeltaMergeBuilderSuite.scala
spark-connect/common/src/main/protobuf/delta/connect/relations.proto
spark-connect/server/src/main/scala-spark-master/io/delta/connect/DeltaRelationPlugin.scala
spark-connect/server/src/test/scala-spark-master/io/delta/connect/DeltaConnectPlannerSuite.scala
spark/src/main/scala/io/delta/tables/DeltaTable.scala

Add support for `merge` for Delta Connect Server and Scala Client.
Added UTs.
No.

[Spark] Add Delta Connect Merge Server and Scala Client

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/convert/ParquetFileManifest.scala
spark/src/test/scala/org/apache/spark/sql/delta/ConvertToDeltaSuiteBase.scala

As title, handle URI properly to cover special characters in partition path for ConvertToDelta
Unit test
no

Handle URI properly in CatalogFileManifest for special characters

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/TableFeature.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaConfigSuite.scala

Provide an API for apps or developers to have a view of all configs and features available in Delta.
A new unit test on the new API + existing tests.
No

Open up APIs to access all Delta configs and features

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala

Refactor iceberg & hudi constants
Existing UTs

[Delta Uniform] Refactor iceberg & hudi constants

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaParquetWriteSupport.scala

Adds null pointer check in DeltaParquetWriteSupport to handle null field ids
always good and safe to have. no test.

Adds null pointer check in DeltaParquetWriteSupport

---

docs/source/delta-coordinated-commits.md
docs/source/delta-drop-feature.md
docs/source/delta-spark-connect.md
docs/source/delta-type-widening.md
docs/source/index.md
docs/source/quick-start.md
docs/source/versioning.md

Cherry-picks commits for the 4.0 preview features to this branch so we can include them in the latest docs. Also updates versions in the quickstart guide which are out of date.
Local build.

[3.2 branch] Add docs for the 4.0 preview features + fix the versions in the quickstart guide

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionUtils.java

Changed string comparator to fallback to binary comparator.
No.

[KERNEL] Changed string comparator to fallback to binary comparator

---

spark/src/test/scala/org/apache/spark/sql/delta/CustomCatalogSuite.scala

A followup of https://github.com/delta-io/delta/pull/3536 to fix import ordering
No

[MINOR] fix import ordering

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaLogActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java

Adds some logging to the getChanges implementation.
N/A

[Kernel] Add some logging to the getChanges implementation

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala

The PR extracts the logic to block conversion to Delta table into a separate method `checkConversionIsAllowed` in `ConvertToDeltaCommand` in order not to bloat the main `performConvert` method when more blocking conditions are added.
Just refactoring. Existent tests should cover the change.
No.

[Spark] Refactor CONVERT TO DELTA blocking conversion logic

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala

This is intended to handle special characters in the table path. For context, DV team recently made a change to include special characters in all paths used by tests.
As of today, the paths we get from listing are not url encoded -- they get url-encoded later in the logic. However, paths contained in delta log files are already url encoded. To keep these two things compatible, this change makes the file names from listing to be url encoded and changes the later logic to not url encode again.
Existing tests
NO

Refactor Vacuum code to properly handle path url encoding 

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/TransactionExecutionObserver.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/OptimisticTransactionPhases.scala
spark/src/main/scala/org/apache/spark/sql/delta/fuzzer/PhaseLockingTransactionExecutionObserver.scala
spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnConflictSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/commands/backfill/RowTrackingBackfillConflictsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionObserverSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/concurrency/TransactionExecutionTestMixin.scala

Adds additional phase to capture in Fuzz test. PostCommit is intended to capture the phase after the commit to run some post commit hooks.
Uni tests
No

[Spark] Extend FuzzSuite to have PostCommit phase

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala

Revert "Make CTAS with replace honor column mapping when writing first set of parquet files"

---

spark/src/main/scala/org/apache/spark/sql/delta/GeneratedColumn.scala
spark/src/main/scala/org/apache/spark/sql/delta/PreprocessTableUpdate.scala
spark/src/main/scala/org/apache/spark/sql/delta/files/TahoeFileIndex.scala

This reverts commit d10e62a2da74d31b619eeffce925b1725224ee74.
https://github.com/delta-io/delta/pull/3722

Revert "Remove snapshotAnalysis from TahoeLogFileIndex"

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CreateDeltaTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

Refactor Coordinated Commits utility methods names and calling orders.
Existing UTs.
No.

[Delta] Refactor Coordinated Commits Util Names and Calling Orders

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingSuite.scala

After https://github.com/apache/spark/pull/48211 this test needs to use a separate Dataframe object for the failing / succeeding test case, because LazyTry will cache the error of the failing case.
Running the test on Spark master.
No.

[Spark] Fix DeltaColumnMappingSuite."column mapping batch scan should detect physical name changes" test

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/TableFeatureSupport.scala
spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala
spark/src/test/scala/org/apache/spark/sql/delta/ActionSerializerSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaColumnMappingTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceColumnMappingSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaTableFeatureSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaHistorySuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/rowid/RowTrackingBackfillSuite.scala

We revert of https://github.com/delta-io/delta/commit/920f185a04382ff466e47e75240dfda48efe40d3 due to creating a backward/forward compatibility issue.
In the original PR we fixed an issue where when column mapping was the only reader feature, it would not appear in the reader features set. This is primarily a memory representation issue, but it turns out the invalid protocol could also be serialized with a specific sequence of events.
The protocol action, has a requirement at initialization time to ensure that only protocols with version 3 have the reader features set. When we fixed the column mapping bug, the requirement was expanded to also include reader features with version 2. This can be problematic if a table was created with an old Delta version which allowed to serialize the …

[Spark] Revert column mapping protocol fix

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala

Makes some no-op changes to make the formatting consistent after https://github.com/delta-io/delta/pull/3754.
No logical changes.
No

[Spark] Make formatting consistent

---

spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaMergingUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/schema/SchemaUtilsSuite.scala

Expanding existing Delta utils to add schema merging of non-struct root functions
New IT.
No.

Allow schema to be merged on non struct root type

---

spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUsageLogs.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala

1. Renames the full error message with 
- `"exceptionString" -> exceptionString(e)` to record the full error message;
- `"exceptionClass" -> e.getClass.getName` to retain the error class information.
2. Adds field `registeredCommitCoordinators`.
3. Removes nested JSONizing. 
Existed UTs.
No.

[Delta] Update Coordinated Commits Usage Logs

---

spark/src/main/java/io/delta/dynamodbcommitcoordinator/DynamoDBCommitCoordinatorClient.java
storage/src/main/java/io/delta/storage/commit/CommitFailedException.java

Refactor `CommitFailedException` to allow for passing in a root cause exception so that we don't lose its stack trace
Simulate exceptions in unit tests and observe the output exception
No

[Spark] Refactor CommitFailedException to allow passing in an inner exception

---

hudi/src/main/scala/org/apache/spark/sql/delta/hudi/HudiConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/FileMetadataMaterializationTracker.scala
spark/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/ProvidesUniFormConverters.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/convert/ConvertUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/logging/DeltaLogKeys.scala
spark/src/main/scala/org/apache/spark/sql/delta/perf/DeltaOptimizedWriterExec.scala
spark/src/main/scala/org/apache/spark/sql/delta/perf/OptimizeMetadataOnlyDeltaQuery.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/PrepareDeltaScan.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/StatsCollectionUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/threads/DeltaThreadPool.scala

[Spark] Update more logs to use structured logging

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergFileManifest.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

use snapshot time as the Delta AddFile modificationTime
UT
No

Skip getFileStatus call during iceberg to delta clone

---

spark/src/main/scala/org/apache/spark/sql/delta/TypeWideningMetadata.scala

Spark master introduced collated `StringType`. In `TypeWideningMetadata.collectTypeChanges`, we used to only match StringType instance, therefore if the type change is from/to `StringType(collationId)`, which is expected and unrelated to type widening, we will throw an error `typeWidening.unexpectedTypeChange`. This PR fixes this by matching both collated and uncollated `StringType` when capturing string type changes. 
Existent tests.
Tests related to collations cannot be added as delta does not support collations yet.
No.

[SPARK] Match collated StringType in TypeWideningMetadata

---

sharing/src/test/scala/io/delta/sharing/spark/DeltaFormatSharingSourceSuite.scala

No actual code change, format only change.
Test only change.

[Sharing][TEST ONLY] Reformat DeltaFormatSharingSourceSuite

---

hudi/src/test/scala/org/apache/spark/sql/delta/hudi/ConvertToHudiSuite.scala

Disable a flaky UniForm Hudi Unit test
Change to UT
No

[Hudi] Disable a flaky UniForm Hudi unit test

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala

Not include baseConvertedDeltaVersion in iceberg table property when flag is off
manual test

Not include baseConvertedDeltaVersion in iceberg table property when flag is off

---

spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsStreamingSuite.scala

Add tests for the streaming use case of coordinated commits.
Unit tests
No

[SPARK] Tests for streaming use case of coordinated commits

---

spark/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala
spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableForUpgradeUniformHelper.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/backfill/BackfillBatch.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/GenerateSymlinkManifest.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSink.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/DeltaFileOperations.scala

Ensures that the types of logged values for each logkey are consistent.
Code compiles and existing tests pass.
No

Make type of logged values consistent for each logkey

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaSinkImplicitCastSuite.scala

Test `write wider type - long -> int` in suite `DeltaSinkImplicitCastSuiteBase`  is randomly timing out. Specifically, the first write in the test suite times out, due to the initial streaming setup taking a long time.
The timeout on that first write is increased to address the test flakiness
Test-only change
No

Increase timeout on first test in DeltaSinkImplicitCastSuite

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/PartitionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/utils/PartitionUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/PartitionUtilsSuite.scala

Add a public utility function to determine if a given partition exists (i.e. actually has data)
Simple UTs.
Yes.

[Kernel] Add a public utility function to determine if a given partition exists (i.e. actually has data)

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/Counter.java
kernel/kernel-api/src/test/scala/io/delta/kernel/metrics/MetricsUtilsSuite.scala

Adds a `Counter` that will be used by following PRs to count metrics.
Adds a unit test.
No.

[Kernel][Metrics][PR#4] Adds Counter class

---

PROTOCOL.md

Adds the concept of a Version Checksum to the protocol. This version checksum can be emitted on every commit and stores important bits of information about the snapshot which can later be used to validate the integrity of the delta log.
N/A
N/A

[Protocol] Add a version checksum to the specification

---

docs/source/delta-utility.md

Adds Documentation for Vacuum LITE
N/A
NO

Add Documentation for Vacuum LITE

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergFileManifest.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/convert/ParquetTable.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/convert/interfaces.scala

Add sizeInBytes API for Delta clone
existing UT

Add sizeInBytes API for Delta clone

---

docs/source/delta-uniform.md

Update Delta uniform documentation to include ALTER enabling

Update Delta uniform documentation to include ALTER enabling

---

spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnSuite.scala

Quick follow up for https://github.com/delta-io/delta/pull/3937
Expand test to cover partitioned tables too.
Test only change. New tests and existing tests pass.
No.

[Spark][TEST-ONLY] Identity Column replace tests for partitioned tables

---

docs/source/delta-clustering.md

Add docs for OPTIMIZE FULL, in-place migration, and create table from external location.
No

Update liquid clustering docs

---

PROTOCOL.md

Fixes a Version Checksum spec changes introduced in https://github.com/delta-io/delta/pull/3777. The last two bin bounds for Deleted File Count Histogram right now are defined in terms of Java's Int.MaxValue and Long.MaxValue. This PR makes the spec language independent by inlining the actual values of these bounds. 
N/A
No

[PROTOCOL][Version Checksum] Remove references to Java-specific Int.MaxValue and Long.MaxValue

---

spark/src/test/scala/org/apache/spark/sql/delta/IdentityColumnConflictSuite.scala

It adds a test for identity column to verify merge will be aborted if high water mark is changed after analysis and before execution.
Test-only.
No.

[SPARK] Add test for Identity Column merge metadata conflict

---

docs/source/delta-clustering.md

This is a manual backport of https://github.com/delta-io/delta/pull/3958 to branch 3.3
Add docs for OPTIMIZE FULL, in-place migration, and create table from external location.
No

[Backport 3.3] Update liquid clustering docs

---

spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/Checksum.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaUDF.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotState.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/DeletedRecordCountsHistogram.scala
spark/src/main/scala/org/apache/spark/sql/delta/stats/DeletedRecordCountsHistogramUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/ChecksumDVMetricsSuite.scala
version.sbt

1. Adds Deletion Vector-related metrics to Version Checksum. 
2. Adds full and incremental computation of these metrics
3. Updates checksum verification so that it takes these new metrics into account 
ChecksumDVMetricsSuite
No

[Spark][Version Checksum][3.3] Add DV-related metrics

---

PROTOCOL.md

Fixes a Version Checksum spec changes introduced in https://github.com/delta-io/delta/pull/3777. The last two bin bounds for Deleted File Count Histogram right now are defined in terms of Java's Int.MaxValue and Long.MaxValue. This PR makes the spec language independent by inlining the actual values of these bounds. 
N/A
No

[PROTOCOL][Version Checksum][3.3] Remove references to Java-specific Int.MaxValue and Long.MaxValue

---

docs/source/delta-row-tracking.md

- Update the [Row Tracking blog](https://docs.delta.io/latest/delta-row-tracking.html#-limitations). Before, we mention in the limitation that we cannot enable Row Tracking on non-empty tables. Now, with [Row Tracking Backfill release](https://github.com/delta-io/delta/releases/) in Delta 3.3, we are now enable Row Tracking on non-empty tables.
- Explicitly mention that you can enable Row Tracking on existing tables from Delta 3.3.
N/A
N/A

[Docs] Update documentation for Row Tracking to include Row Tracking Backfill introduced in Delta 3.3

---

docs/source/delta-utility.md

Adds Documentation for Vacuum LITE
N/A
NO

[3.3] Add Documentation for Vacuum LITE

---

docs/source/delta-uniform.md

Update Delta uniform documentation to include ALTER enabling

Update Delta uniform documentation to include ALTER enabling - 3.3

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableBase.scala

Fix indentation in CloneTableBase

Fix indentation in CloneTableBase

---

docs/source/delta-row-tracking.md

- Cherry-pick https://github.com/delta-io/delta/pull/3968 into Delta 3.3.
N/A
N/A

[Docs][3.3] Update documentation for Row Tracking to include Row Tracking Backfill introduced in Delta 3.3

---

docs/source/delta-batch.md
docs/source/delta-clustering.md
docs/source/delta-drop-feature.md
docs/source/delta-sharing.md
docs/source/delta-storage.md
docs/source/delta-type-widening.md
docs/source/delta-utility.md
docs/source/quick-start.md
docs/source/releases.md

Cherrypick https://github.com/delta-io/delta/commit/2e186b46749a592c8ea71d1b771daa21ba5f39a5 to master.

[Docs] Update docs for 3.3 release (#3992)

---

version.sbt

Update version in master after 3.3 release https://github.com/delta-io/delta/releases/tag/v3.3.0

Update version to 3.4.0-SNAPSHOT after the 3.3 release

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/DeltaOperationReportImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotReportImpl.java

Minor refactor. Factors out `DeltaOperationReportImpl` from `SnapshotReportImpl` which allows it to be reused by any future subclasses.
N/A 
No

[Kernel][Metrics][PR#5] Minor refactor to SnapshotReportImpl

---

spark/src/main/scala/org/apache/spark/sql/delta/FallbackToV1Relations.scala
spark/src/main/scala/org/apache/spark/sql/delta/ResolveDeltaTableWithPartitionFilters.scala

Update imports in FallbackToV1Relations and ResolveDeltaTableWithPartitionFilters to match other files.
Successful compilation.
No.

[Spark] Update imports in FallbackToV1Relations and ResolveDeltaTableWithPartitionFilters to match other files

---

protocol_rfcs/collated-string-type.md

Fixed example for storing collation information in metadata in `collated-string-type.md`. JSON representation had incorrect column name and path to StringType.
No.

Fixed 'collated-string-type.md' JSON example.

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ConflictChecker.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/RowTracking.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala

This PR implements transaction conflict resolution for the row tracking feature. Key changes include:
1. Add logic for resolving conflicts for the row tracking metadata domain
2. Reassign `baseRowId` and `defaultRowCommitVersion` for `AddFile` actions during conflict resolution
3. Update the row tracking domain metadata action during conflict resolution
Tests were added in `RowTrackingSuite.scala`.
No.

[Kernel] Implement row tracking conflict resolution

---

docs/source/delta-storage.md

Just a docs update to clarify the setup.

[DynamoDBLogStore] Update setup requirements in docs

---

iceberg/src/main/scala/org/apache/iceberg/transforms/IcebergPartitionUtil.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergPartitionConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/CloneIcebergSuite.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

Do not convert iceberg bucket partition to delta partition; This will result in a unpartitioned delta table. 
UT

skip iceberg bucket partition during delta conversion

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/FileNames.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/FileNamesSuite.scala

Clean up `FileNames.java` and add more tests
New UTs.
No.

[Kernel] Clean up `FileNames.java` and add more tests

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergSchemaUtils.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/TypeToSparkTypeWithCustomCast.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/CloneIcebergSuite.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/NonSparkIcebergTestUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/convert/ConvertUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

This PR introduces the feature that allows UniForm to cast Iceberg TIME type to Spark Long data type. The result will be represented as the microseconds since midnight.
UT
No

[UniForm] Cast Iceberg TIME to Spark Long

---

.github/workflows/iceberg_test.yaml
build.sbt
project/Unidoc.scala
run-tests.py

Separates out the iceberg tests to a separate github action. Also makes the unidoc settings dependent on an environmental variable `DISABLE_UNIDOC`. This is useful because due to unidoc, running tests compiles all the projects in the entire repo. If you disable unidoc, you can, for example, run `spark / test` without compiling the iceberg projects.
CI jobs look good.
No

[INFRA][Spark][Iceberg] Separate out the iceberg tests to a separate github action

---

spark/src/main/scala/org/apache/spark/sql/delta/redirect/TableRedirect.scala
spark/src/test/scala/org/apache/spark/sql/delta/TableRedirectSuite.scala

Fix TableRedirect to allow path-based access.
Unit tests.
No.

Fix path-based access for table redirect

---

kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala

Fix a minor typo in TableFeaturesSuite
$ build/sbt kernelGroup/test
No

[Kernel] Fix typo in TableFeaturesSuite

---

iceberg/src/main/scala/org/apache/iceberg/transforms/IcebergPartitionUtil.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergFileManifest.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergPartitionConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/ConvertIcebergToDeltaSuite.scala
spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala

We are supporting limited partition evolution for clone from iceberg: 
* When all data files only have bucket partitions or non-partitions, convert all of them to non-partitions
UTs

[UniForm] Support limited partition evolution in clone from iceberg

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala

[uniform]fix import order

---

.github/workflows/connectors_test.yaml
.github/workflows/iceberg_test.yaml
.github/workflows/kernel_test.yaml
.github/workflows/spark_examples_test.yaml
.github/workflows/spark_master_test.yaml
.github/workflows/spark_python_test.yaml
.github/workflows/spark_test.yaml
.github/workflows/unidoc.yaml

Current image LTS is being expired: https://github.com/actions/runner-images/issues/11101
Jobs started failing (warning before deprecation): https://github.com/delta-io/delta/actions/runs/13659779604/job/38188156870?pr=4221

[Build/CI/CD] Upgrade the ubuntu image version to ubuntu-24.04

---

spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/metering/DeltaLogging.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

Reorder the imports to follow style guide
N/A
No

[Spark] Fix import order

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/uniform/UniFormE2EIcebergSuiteBase.scala

revert the PR of https://github.com/delta-io/delta/pull/4195, would raise another PR later.

revert the timestamp fix 

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Metadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checksum/CRCInfo.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumSimpleComparisonSuite.scala

This PR implements equals/hashcode to Metadata and CrcInfo, so we could close one TODO in the test

[Kernel]Add equals/hashcode to Metadata and CrcInfo

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Format.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumSimpleComparisonSuite.scala

This PR fixes forward the test failure by https://github.com/delta-io/delta/pull/4224
Fixed test
No

[Kernel]Fix test failure by adding equals method to Format.java 

---

spark/src/main/scala/org/apache/spark/sql/delta/UniversalFormat.scala

This PR refactors IcebergCompat check, making it easier to add new Compat checks.
UT/HiFi
No

[UniForm] A small refactoring of IcebergCompat

---

spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala

This PR refactors listFromFileSystemInternal. The introduction of filesIter makes the steps of listing files and categorizing files clearer.
Existing test case
No

[SPARK] A small refactoring of listFromFileSystemInternal

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala

revert the PR of https://github.com/delta-io/delta/pull/4230, would
raise another PR later.

revert "Uniform: Fix microsecond conversion for timestamp/ntz partition value"

---

spark/src/test/scala/org/apache/spark/sql/delta/DescribeDeltaHistorySuite.scala

Upgrade `DescribeDeltaHistorySuite` to be compatible with scala `2.13`: we will validate properties for describing delta history separately to ignore order difference
This is because pairs inside map have different orders between scala `2.12` and `2.13`
Existing UTs

Upgrade DescribeDeltaHistorySuite to be compatible with scala 2.13 - ignore order in column properties

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergStatsUtils.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/CloneIcebergSuite.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/NonSparkIcebergTestUtils.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/commands/convert/IcebergStatsUtilsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/DataSkippingDeltaTests.scala

While converting iceberg table to delta table, convert stats for date type from int to string, which delta readers can understand
Add UTs

Convert stats for Date data type from int to date string in converting iceberg metadata to delta

---

spark/src/main/scala/org/apache/spark/sql/delta/IcebergCompat.scala

This PR refactors the IcebergCompat to allow easily adding new functions in the future.
UT
No

[UniForm] Refactor the IcebergCompat

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergSchemaUtils.scala

This PR enables IcebergSchemaUtils to support Delta schema without any mapping (e.g., NoMapping mode) using Iceberg default name mapping.
Unit tests
No

Support Iceberg default name mapping in Iceberg schema utils

---

spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/UCCommitCoordinatorBuilder.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/UCCommitCoordinatorBuilderSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/UCCommitCoordinatorClientSuite.scala

Fix package name for UCSingleCatalog to match https://github.com/unitycatalog/unitycatalog/blob/main/connectors/spark/src/main/scala/io/unitycatalog/spark/UCSingleCatalog.scala
E2E tests using unity catalog.

[Delta] Fix package name for UCSingleCatalog class

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/4290/files) to review incremental changes.
- [**stack/introduce-table-feature**](https://github.com/delta-io/delta/pull/4290) [[Files changed](https://github.com/delta-io/delta/pull/4290/files)]
---------
Parent issue https://github.com/delta-io/delta/issues/4289
Adds the writer table feature `IcebergWriterCompatV1` and it's corresponding table config `delta.enableIcebergWriterCompatV1`.
Updates unit tests. E2E tests writing to tables with this feature will come in follow-up PRs (see the parent issue).
Yes, after all tasks in https://github.com/delta-io/delta/issues/4289 are complete a new writer feature will be supported.

[Kernel][icebergWriterCompatV1 - PR#1] Introduce table feature IcebergWriterCompatV1

---

docs/source/delta-storage.md
docs/source/quick-start.md

[3.3][Docs] Update docs for 3.3.1 release

---

README.md

This PR adds some extra context to address common pitfalls when setting up intellij and the delta repository

docs: Update readme to mention JDK 1.8 and how to setup Intellij

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergFileManifest.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergStatsUtils.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/CloneIcebergSuite.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/commands/convert/IcebergStatsUtilsSuite.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala

While converting iceberg metadata to delta metadata, convert stats for decimal type in the fast path
UTs

Convert stats for Decimal data type in converting iceberg metadata to delta

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala

…ical name presence and physical name consistency
This PR breaks away some of the changes from https://github.com/delta-io/delta/pull/4196/files
Specifically, this PR includes:
1. validateUpdatedSchema to SchemaUtils which will be used on the schema evolution path
2. Add validation of ID/physical name presence and for physical name consistency
Subsequent PRs will include the other validations required for IcebergCompatV2 and schema compatibility (type changes/nullavbility) etc. 
Added some simple unit tests to SchemaUtils. We'll be adding API tests which will be more extensive.
No

[Kernel] Add SchemaUtils#validateUpdatedSchema with validation of id/physical name and physical name consistency check

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/IcebergCompat.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ReorgTableForUpgradeUniformHelper.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningUniformTests.scala

This PR add two properties to IcebergCompat
* Allow IcebergCompat to indicate the "format-version" of Iceberg. This will be written into Iceberg tables created from UniForm.
* Allow IcebergCompat to indicate a list of incompatible TableFeatures. Also add a utils method to check if any IcebergCompatVx that is incompatible with some table features are enabled. 
Existing tests
No

[UniForm] Refactor IcebergCompat to support format-version and Incompatible Table Feature

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala

Split the main PR https://github.com/delta-io/delta/pull/4265 for faster review
Adds the writer table feature clustering.
Updates unit tests. E2E testing would be added later once table creation with this table feature supported.

[Kernel][Clustering #1] introduce table feature Clustering

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

Change the retry mechanism used while testing the correctness of URLs in Delta error messages.
The original mechanism would retry the fetch whenever a valid response was received, and fail the test immediately whenever an invalid response was received. I believe that the intended behavior was the opposite. The new implementation only retries the fetch if the fetch was successful.
No.

[SPARK] Fix retry mechanism used to validate URLs in Delta error messages

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Metadata.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/checksum/ChecksumWriterSuite.scala

This PR address some leftover todos in the test by removing custom helper method for checking equality of P&M.
As a part of this effort, added fromRow() method for Metadata which may address several different use cases.
No functional changes
Existing tests
No

[Kernel][Clean up]Add fromRow() method for Metadata and directly compare P&M in test

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DomainMetadataSuite.scala

This PR makes no functional change, it makes DomainMetadataSuite work with post commit hook and do some clean up
Existing test
No

[Kernel][Test]Make DomainMetadataSuite work with post commit hook and do some clean up

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala

This PR makes no functional change, it mainly makes ExpireSnapshotHelper follow Iceberg's ExpireSnapshot's API and removes the custom logic outside of the method that creates ExpireSnapshotHelper. https://github.com/apache/iceberg/blob/main/api/src/main/java/org/apache/iceberg/ExpireSnapshots.java#L40
Existing tests
No

[Uniform]Refactor ExpireSnapshotHelper to follow Iceberg's ExpireSnapshot's API

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergStatsUtils.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/CloneIcebergSuite.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/commands/convert/IcebergStatsUtilsSuite.scala

While converting iceberg metadata to delta metadata, convert stats for timestamp type in the fast path
UTs

[UniForm] Convert stats for TIMESTAMP data type in converting iceberg metadata to delta

---

spark/src/main/scala/org/apache/spark/sql/delta/IcebergCompat.scala

This PR refactors the UniForm IcebergCompat
UT
No

[UniForm] Refactor IcebergCompat

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala

Split the main PR https://github.com/delta-io/delta/pull/4265 for faster review
Add a util func `convertToPhysicalColumnNames` in ColumnMapping to get the corresponding physical column name for a logical column
Add unit test cases in ColumnMappingSuite.scala

[Kernel][Clustering #2] add getPhysicalColumnNameAndDataType util in ColumnMapping 

---

.github/workflows/connectors_test.yaml

actions/cache@v2 is being deprecated
- https://github.com/actions/cache/discussions/1510
- https://github.com/actions/toolkit/discussions/1890
This PR job caught the brownout
https://github.com/delta-io/delta/actions/runs/13396661811/job/37417276819?pr=4127
Upgrades connectors workflow which is still on v2.
CI test suffices.
No
(cherry picked from commit d8148886297179f70eac9ce809d173b00ae5ba29)

[Branch 3.3][Infra] Update actions/cache version for connectors (#4173)

---

build.sbt
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingCDFUtilsSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingFileIndexSuite.scala
sharing/src/test/scala/io/delta/sharing/spark/TestClientForDeltaFormatSharing.scala

Upgrade delta-sharing-client to v1.2.4. See changes in https://github.com/delta-io/delta-sharing/releases/tag/v1.2.4.
Unit test.

[Sharing] Upgrade delta-sharing-client to version 1.2.4

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Metadata.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/TransactionStateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/test/scala/io/delta/kernel/TransactionSuite.scala

Rename some fields, improve docs, and move some code for better clarity / readability.
No

[Kernel] Minor refactor to column mapping related code for clarity

---

kernel/kernel-api/src/main/java/io/delta/kernel/TransactionCommitResult.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/TransactionMetricsResult.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/TransactionReportSuite.scala

Return txn metrics as part of TransactionCommitResult
Updates test suite to check these metrics as well

[Kernel] Return txn metrics as part of TransactionCommitResult

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java

Replaced string formatting with concise logging  syntax to improve readability and maintainability
No

[Kernel] Replace `String.format` with parameterized log in SnapshotManager

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/clustering/ClusteringMetadataDomain.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/clustering/ClusteringMetadataDomainSuite.scala

Split the main PR https://github.com/delta-io/delta/pull/4265 for faster review
add `ClusteringMetadataDomain` which could generate the clustering domain metadata like
```
{
"domainMetadata": {
"domain": "delta.clustering",
"configuration": "{\"clusteringColumns\":[\"col-daadafd7-7c20-4697-98f8-bff70199b1f9\", \"col-5abe0e80-cf57-47ac-9ffc-a861a3d1077e\"]}",
"removed": false
}
}
```
unit tests

[Kernel][Clustering #3] add ClusteringMetadataDomain

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaColumnMappingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala

[Kernel] Update maxFieldId when updating the schema

---

sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingDataSourceCMSuite.scala
spark/src/main/resources/error/delta-error-classes.json
spark/src/main/scala/org/apache/spark/sql/delta/DeltaColumnMapping.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSourceMetadataEvolutionSupport.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceSchemaEvolutionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/sources/DeltaSourceMetadataEvolutionSupportSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/typewidening/TypeWideningStreamingSourceSuite.scala

Previously the error message for tracking type widening changes and non-additive schema changes have diverged, we are going to unify them with consistency.
New / modified UT.
No.

Unify and Improve error message for Delta source schema tracking

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/DeltaToIcebergConvert.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala

This PR refactors IcebergConversionTransaction
UT
No

[UniForm] Refactoring IcebergTransaction

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergWriterCompatV1MetadataValidatorAndUpdater.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

For now don't allow disabling the icebergWriterCompatV1 table property. We can change this in the future if there is need.
Updates unit tests.

[Kernel][icebergWriterCompatV1] Block disabling the icebergWriterCompatV1 table property

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/GenerateIcebergCompatActionUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/RemoveFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/TransactionMetrics.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/actions/GenerateIcebergCompatActionUtilsSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/actions/RemoveFileSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CommitIcebergActionSuite.scala

Based off of https://github.com/delta-io/delta/pull/4368
View the changes in this PR here 
https://github.com/delta-io/delta/pull/4369/commits/2e54a730f9a511ccfa062b7b2f92832d5de0170f
Support creating raw RemoveFile action row that can be committed to the transaction for Iceberg metadata conversion. Also updates the check in txn.commit to not allow deletes from append-only table.
Adds unit tests to `kernelApi` and E2E tests.
No

[Kernel] Support creating remove actions for Iceberg metadata conversion

---

spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaDataSource.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSourceColumnMappingSuite.scala

Minor clean up and improvement, ensure table id must match during streaming.
No.

Minor improvements to Delta streaming source

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java

Add a comment as requested in a [previous PR](https://github.com/delta-io/delta/pull/4340#discussion_r2023673166)
N/A
No

[Kernel] Add comment

---

build.sbt
kernel/examples/kernel-examples/pom.xml
storage/src/main/java/io/delta/storage/internal/S3LogStoreUtil.java

See https://github.com/delta-io/delta/pull/4256
Delta-storage changes taken from https://github.com/delta-io/delta/commit/e02b65c26105b092909e8909b095987d274c9847 specifically https://github.com/delta-io/delta/commit/f29496b808a41f6be8f21b7bbb2371955c98b361

[Branch-4.0-kernel] Upgrade Hadoop to 3.4.0

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checksum/CRCInfo.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/checksum/ChecksumWriterSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumSimpleComparisonSuite.scala

This is 1/n for domain metadata in crc support, it adds domain metadata to crcInfo.java and implements the toRow() method. 
(see https://github.com/delta-io/delta/pull/4330/files for e2e poc)
Follow up will be: (1)e2e integration to populate domain metadata in crc in a txn (2)load domain metadata from crc and use it for building snapshot.
Unit test
No

[Kernel]Add domain metadata to CRC Info and implements the toRow() 

---

README.md

fix link to ActionSerializerSuite.scala

---

storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UCTokenBasedRestClient.java

This PR changes the Delta commit API endpoint from `/delta/commits` to `/delta/preview/commit`.
Through existing UTs.
N/A

[Spark] Update Delta commit API endpoint from `/delta/commits` to `/delta/preview/commit`

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/DataSkippingUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/StatsSchemaHelper.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/StatsUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
kernel/kernel-api/src/test/scala/io/delta/kernel/TransactionSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/DataFileStatisticsSuite.scala
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetFileWriter.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetFileWriterSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetSuiteBase.scala

- Fix the `nullCount` field name used when serializing stats. Previously, we were using `nullCounts`, which according to the [spec](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#checkpoints-1) should only be used in Checkpoints for `stats_parsed` fields. 
- Fixed existing tests and also addressed some minor nits that didn't get checked in the last [PR](https://github.com/delta-io/delta/pull/3342)
- Additional follow up tasks are listed [here](https://github.com/delta-io/delta/issues/4282) and I will add more Spark integration tests as part of those follow ups (which should further help surface any other inconsistencies).
Unit tests
No

[Kernel] Fix nullCount stats serialization field name

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ConflictChecker.java

This PR implements the refactor idea in https://github.com/delta-io/delta/pull/4410#discussion_r2047439689
No functional change but make dm to commit only accessible from getComputedDomainMetadatasToCommit().
Existing tests
No

[Kernel][Refactor]Introduce a internal class for grouping all domain metadata members of TransactionImpl class

---

storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UCTokenBasedRestClient.java

This PR renames the commit endpoint from `/delta/preview/commit` to `/delta/preview/commits` to follow RESTful convention.
Through existing UTs.
N/A

[Spark] [CatalogOwned] `/delta/preview/commit` -> `/delta/preview/commits`

---

spark/src/test/scala/org/apache/spark/sql/delta/UniversalFormatSuiteBase.scala

In a test validating the correctness of Delta table properties we mistakenly pass two invalid Delta properties, which can sometimes make the test flaky.
Self-testing.
No.

[SPARK] Fix a test in `UniversalFormatSuiteBase`

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableClusteringSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala

Support update clustering columns and generating a new clusteringDomainMetadata.
Unit tests

[Kernel]support update clustering columns

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java

Initial refactoring of `TransactionBuilderImpl` to enable future support for replace table. A full prototype can be seen here https://github.com/delta-io/delta/commit/168f295d5fa5d059554c2640a5cf596f8bf6cb54
Just a refactor, existing tests should suffice.

[Kernel] Initial refactor to TransactionBuilder to support replace table in the future

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergStatsUtils.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/commands/convert/IcebergStatsUtilsSuite.scala

Allow convert nullCount for List/Map/Decimal/Date/Timestamp types from iceberg to Delta
unit test

Allow convert nullCount for List/Map/Decimal/Date/Timestamp types  from iceberg to Delta

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CatalogOwnedEnablementSuite.scala

Previously for a `CatalogManaged` table, `coordinatedCommitsCoordinatorName` will be empty - so every commit is considered `CC_TO_FS_DOWNGRADE_COMMIT` when generating `CoordinatedCommitsStats` for `CommitStats`.
This PR generates appropriate `CoordinatedCommitsStats` for `CatalogManaged` tables when:
1) Creating a `CatalogManaged` table - which is considered as `FS_TO_CO_UPGRADE_COMMIT` since the 0th commit is through file-system.
2) Normal `CatalogManaged` table commit - which is considered as `CO_COMMIT`.
Through newly added UTs in `CatalogOwnedEnablementSuite`.
N/A

[Spark] [CatalogManaged] Generate appropriate `CoordinatedCommitsStats` for `CatalogManaged` tables

---

kernel/kernel-api/src/main/java/io/delta/kernel/hook/PostCommitHook.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/hook/ChecksumFullHook.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumSimpleComparisonSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumStatsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

This PR adds a fallback mechanism for checksum generation when the simple CRC information isn't available. Previously, in cases where we couldn't generate an incremental checksum, we would skip checksum generation entirely. With this change, we:
- Try to generate a simple checksum first (fast path)
- If not feasible, add a post commit hook to as a fall back, the fall back will do state construction.
Extends two write tests
No

[Kernel]Introduce checksum full post commit hook

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/alterDeltaTableCommands.scala
spark/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaAlterTableTests.scala

Previously, there was a bug where char/varchar to string conversion didn't work correctly due to how they are internally represented. 
For example: 
- An `array<varchar<10>>` is represented as `(dataType = array<string>, char_varchar_metadata = "array<varchar<10>>")`.
- If we convert `array<varchar<10>>` into `array<string>` by setting the `dataType` part with`array<string>`, nothing will change. 
This has been fixed in https://github.com/delta-io/delta/pull/3346. The idea is to first convert the representation into one without the metadata part. In the example above, `(dataType = array<string>, char_varchar_metadata = "array<varchar<10>>")` will first be converted into `(dataType = array<varchar<10>>, char_varchar_metadata = "")` before setting the `dataType` part to `string`. 
In the …

[Spark] Fix a bug that prevents altering array/map/struct<varchar> column

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala

pass the `startingSnapshotId` via `validateFromSnapshot` when creating the rewriteHelper
existing tests
No

[uniform]pass startSnapshotID when create rewriter

---

protocol_rfcs/iceberg-writer-compat-v1.md

Add a new requirement to the RFC. See changes in the PR.
N/A
No

Update IcebergWriterCompatV1 with map struct key requirements

---

build.sbt
spark/src/main/scala-spark-3.5/shims/DeltaSqlParserShims.scala
spark/src/main/scala-spark-master/shims/DeltaSqlParserShims.scala
spark/src/main/scala/io/delta/sql/parser/DeltaSqlParser.scala
spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
spark/src/test/scala/org/apache/spark/sql/delta/stats/PartitionLikeDataSkippingSuite.scala

This PR updates the version of Apache Spark  to 4.0.1-SNAPSHOT. This is effectively tracks the version of Spark that will be released as Spark 4 (at some point).
No

Use Apache Spark 4.0.1-SNAPSHOT

---

python/delta/connect/proto/relations_pb2.py
python/delta/connect/proto/relations_pb2.pyi
spark-connect/client/src/main/scala-spark-master/io/delta/connect/tables/DeltaOptimizeBuilder.scala
spark-connect/client/src/main/scala-spark-master/io/delta/connect/tables/DeltaTable.scala
spark-connect/client/src/test/scala-spark-master/io/delta/connect/tables/DeltaTableSuite.scala
spark-connect/common/src/main/protobuf/delta/connect/relations.proto
spark-connect/server/src/main/scala-spark-master/io/delta/connect/DeltaRelationPlugin.scala
spark-connect/server/src/test/scala-spark-master/io/delta/connect/DeltaConnectPlannerSuite.scala

Adds the `optimize` API to Delta Connect (Scala client implementation + server-side handling logic).
`DeltaOptimizeBuilder` is introduced on the client-side to aid in building the operation.
New server-side unit tests in `DeltaConnectPlannerSuite` and client-side tests in `DeltaTableSuite` (client-side tests are set to `ignore` until https://github.com/delta-io/delta/pull/4468 is merged)
Yes. Users of the Scala Delta Connect client may now utilise the `optimize` API.

[Spark] Add `optimize` API to Delta Connect (Scala Client + Server) 

---

python/delta/connect/_typing.py
python/delta/connect/plan.py
python/delta/connect/tables.py
python/delta/connect/tests/test_deltatable.py
python/delta/tables.py
python/run-tests.py

Add all Delta Connect Python Client Relation and Command APIs since 4.0 Preview, except create/replace, addFeatureSupport, dropFeatureSupport.
The list of supported APIs for Delta 4.0: https://docs.delta.io/3.2.1/delta-spark-connect.html
Added UTs.
Yes, brand new APIs for Delta Connect Python Client.

[Spark] Add all Delta Connect Python Client Relation and Command APIs since 4.0 Preview, except create/replace, addFeatureSupport, dropFeatureSupport

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/types/TypeWideningChecker.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/types/TypeWideningCheckerSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/4549/files) to review incremental changes.
- [**stack/tw_checker**](https://github.com/delta-io/delta/pull/4549) [[Files changed](https://github.com/delta-io/delta/pull/4549/files)]
- [stack/tw_iterable](https://github.com/delta-io/delta/pull/4560) [[Files changed](https://github.com/delta-io/delta/pull/4560/files/ceb5fde8d9c61a66a8ac6a614caf00e5b3006fa5..6141e7dbc3d0d5292bccb473e355cbca642a1fc8)]
- [stack/tw_cleanup_signature](https://github.com/delta-io/delta/pull/4561) [[Files changed](https://github.com/delta-io/delta/pull/4561/files/6141e7dbc3d0d5292bccb473e355cbca642a1fc8..4bc8ad4b277084069bf96436acd30c32be1e0b22)]
- [stack/tw_make_update_real](https://github.com/delta-io/delta/pull/4566) [[Files …

[Kernel] #4491 Add type widening rules

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala

Handle case where Iceberg summary doesn't exist during Iceberg to Delta conversion so that exceptions won't be thrown
Existing UTs

Handle case where Iceberg summary doesn't exist during Iceberg to Delta conversion

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala

Consolidate logInfo messages
log only change.

Refactor iceberg schema update log message

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java

Add logging to record domain metadata loading time.
Unit test
No

[Kernel][Logging][2/n]Add logging to record domain metadata/P&M loading time.

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java

This is 1/n PR for improving logging for debug purpos, no functional changes
No

[Kernel][Logging][1/n]Improve the logging for building a log segment.

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/stats/FileSizeHistogram.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/stats/FileSizeHistogramSuite.scala

Introduce plus/minus API for FileSizeHistorgram, this will allow up doing operation between two histogram.
One use case is https://github.com/delta-io/delta/pull/4587
Unit test
No

[Kernel]Introduce plus/minus API for FileSizeHistorgram

---

PROTOCOL.md

Add `inCommitTimestamp` feature name to Appendix
N/A
N/A

[DOCS] Add inCommitTimestamp to Appendix

---

python/delta/connect/tables.py
python/delta/tables.py
python/delta/tests/test_deltatable.py
spark/src/main/scala/io/delta/tables/DeltaTable.scala
spark/src/test/scala/org/apache/spark/sql/delta/CloneTableTestMixin.scala

Add Python APIs for cloning Delta tables: `clone`, `cloneAtVersion` and `cloneAtTimestamp`.
Cherry-pick https://github.com/delta-io/delta/pull/4598
Added UTs.
Yes, new Python APIs for cloning.

[Spark] Add Python Clone APIs clone, cloneAtVersion, and cloneAtTimestamp

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaIterable.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/ArrayType.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/MapType.java
kernel/kernel-api/src/main/java/io/delta/kernel/types/StructField.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaIterableSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/4560/files) to review incremental changes.
- [**stack/tw_iterable**](https://github.com/delta-io/delta/pull/4560) [[Files changed](https://github.com/delta-io/delta/pull/4560/files)]
- [stack/tw_cleanup_signature](https://github.com/delta-io/delta/pull/4561) [[Files changed](https://github.com/delta-io/delta/pull/4561/files/d85f1ee710f766b82228f81e0face2518ccaaa0c..96edf0378c81d9a156571fa1fd2f688d0d04ef27)]
- [stack/tw_make_update_real](https://github.com/delta-io/delta/pull/4566) [[Files changed](https://github.com/delta-io/delta/pull/4566/files/96edf0378c81d9a156571fa1fd2f688d0d04ef27..66fd80cd94099869489ef2fded10b04a2977da35)]
- [stack/tw_proper_addressing](https://github.com/delta-io/delta/pull/4567) [[Files …

[Kernel][Type Widening] 1/ Add utility class for iterating/modifying schemas

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaChanges.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/4566/files) to review incremental changes.
- [**stack/tw_make_update_real**](https://github.com/delta-io/delta/pull/4566) [[Files changed](https://github.com/delta-io/delta/pull/4566/files)]
- [stack/tw_proper_addressing](https://github.com/delta-io/delta/pull/4567) [[Files changed](https://github.com/delta-io/delta/pull/4567/files/10c63b52905094fab67fffdbed2c89689b56dc10..a6c5a4b29316b9fe7ac04bf15200ce5f647fafb8)]
- [stack/tw_type_changes](https://github.com/delta-io/delta/pull/4568) [[Files changed](https://github.com/delta-io/delta/pull/4568/files/a6c5a4b29316b9fe7ac04bf15200ce5f647fafb8..f7f67a943ab6e196a5ae70fa50959d0ab1b25654)]
- [stack/tw_type_changes_to_field_metadata](https://github.com/delta-io/delta/pull/4588) [[Files …

[Kernel][Type Widening] 3/ Make udpates a real first class type

---

spark-connect/common/src/main/protobuf/spark/connect/base.proto
spark-connect/common/src/main/protobuf/spark/connect/commands.proto
spark-connect/common/src/main/protobuf/spark/connect/common.proto
spark-connect/common/src/main/protobuf/spark/connect/expressions.proto
spark-connect/common/src/main/protobuf/spark/connect/ml.proto
spark-connect/common/src/main/protobuf/spark/connect/ml_common.proto
spark-connect/common/src/main/protobuf/spark/connect/pipelines.proto
spark-connect/common/src/main/protobuf/spark/connect/relations.proto
spark-connect/common/src/main/protobuf/spark/connect/types.proto

Update the Spark Connect protos that we introduced in https://github.com/delta-io/delta/pull/3168, for Delta Connect, to the latest version that the Spark repository is using (https://github.com/apache/spark/tree/master/sql/connect/common/src/main/protobuf/spark/connect).
N/A.
No.

[Spark] Update the Spark Connect protos in Delta Connect to the latest version

---

docs/source/delta-storage.md
docs/source/quick-start.md

[3.3][Docs] Update docs for 3.3.2 release 

---

build/sbt-config/repositories

[Infra] Add an additional back up repo to avoid hitting rate limits for maven deps

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotQueryContext.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotReportImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/SnapshotReport.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/SnapshotReportSuite.scala

Add the checkpoint version used for the snapshot construction
Unit tests

[Kernel] Add checkpointVersion to SnapshotReport

---

.github/workflows/connectors_test.yaml
.github/workflows/kernel_test.yaml
.github/workflows/spark_examples_test.yaml
.github/workflows/spark_master_test.yaml
.github/workflows/spark_python_test.yaml
.github/workflows/spark_test.yaml
.github/workflows/unidoc.yaml
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/Protocol.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActionsIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/InCommitTimestampUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TableChangesSuite.scala

Cherry pick https://github.com/delta-io/delta/pull/4478

Cherry pick 5c9130ead53d5df114d509e32b0c58be1d467acc

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checksum/ChecksumUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/checksum/ChecksumWriter.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumLogReplayMetricsTestBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplayBaseSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TestUtils.scala

This is 1st PR from https://github.com/delta-io/delta/pull/4587. It removed the unnecessary log replay in state construction. Code structure wise, it group into small helpers so the next PR could reuse
Added test
No

[Kernel]Improve table.checksum to remove unnecessary snapshot construction

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/MaterializedRowTrackingColumn.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/rowtracking/RowTracking.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala

This is a cherrypick of #4425.
This PR addresses the missing [writer requirements](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#writer-requirements-for-row-tracking) to enable row tracking in Kernel. Specifically, on top of the existing implementation, it adds the assignment of materialized row tracking column names at table creation.
With this change, users will be able to create a new table with row tracking enabled. Note that enabling/disabling row tracking on existing tables is still blocked, since enabling requires backfilling row IDs/commit versions, which is not supported, and disabling is irreversible.
Existing and new tests in `RowTrackingSuite`.
No.

[4.0][Kernel] Support enabling row tracking in Kernel

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaHistoryManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/CommitInfo.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/GenericColumnVector.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/InCommitTimestampUtils.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/VectorUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/DeltaHistoryManagerSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/TableImplSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockEngineUtils.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockFileSystemClientUtils.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/MockSnapshotUtils.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala

Cherry pick fce3d8424327bdfe2c96c805bc68d3aded9783e4

---

spark/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala

Consider both key 'notebook_id' ad 'notebookID'

Fix Notebook IDs in commitInfo

---

docs/source/delta-drop-feature.md
docs/source/delta-spark-connect.md
docs/source/delta-spark.md
docs/source/delta-storage.md
docs/source/delta-type-widening.md
docs/source/index.md
docs/source/quick-start.md
docs/source/releases.md
docs/source/versioning.md

Updates docs for the 4.0 release. This updates versions for Delta/Spark as well as cherry-picks docs changes for type widening and delta connect from the `branch-4.0-preview1` branch (with a few changes of my own to update statuses). Also incorporates changes in https://github.com/delta-io/delta/pull/4681 for variant table feature. 
Built locally.
No.
TODO: merge these to master later

[4.0 release] Docs changes in preparation for the 4.0 release

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/SnapshotMetrics.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/SnapshotManager.java
kernel/kernel-api/src/main/java/io/delta/kernel/metrics/SnapshotMetricsResult.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/SnapshotReportSuite.scala

Collect time to take to load log segments. 1/6 for https://github.com/delta-io/delta/issues/4701
Unit test
No

[Kernel][Snapshot Metric]Collect metrics timeToBuildLogSegmentForVersionNs

---

spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala

Small refactor on DeltaConfigs

Small refactor on DeltaConfigs

---

docs/source/delta-spark-connect.md

Update the Delta Connect documentation to reflect the latest status, for the Delta 4.0.0 release.
- Simplified CUJs
- All `DeltaTable` APIs are now supported.
- Removed details regarding 4.0.0 Preview.
Previous PR: https://github.com/delta-io/delta/pull/3232#event-13138474987
Manually tested the simplified CUJs.
N/A

[Doc] Update Delta Connect Documentation for Delta 4.0.0 release

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/types/DataTypeJsonSerDe.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/types/DataTypeJsonSerDeSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/4592/files) to review incremental changes.
- [**stack/tw_serde_refactor**](https://github.com/delta-io/delta/pull/4592) [[Files changed](https://github.com/delta-io/delta/pull/4592/files)]
- [stack/add_type_change_parsing](https://github.com/delta-io/delta/pull/4593) [[Files changed](https://github.com/delta-io/delta/pull/4593/files/6e5bbbeb27f0b6d0418c22e0e0b39907cbd2cc4e..48e303c7921df89414e75f9b45d78defcd17847a)]
- [stack/tw_upgrade_downgrade](https://github.com/delta-io/delta/pull/4603) [[Files changed](https://github.com/delta-io/delta/pull/4603/files/48e303c7921df89414e75f9b45d78defcd17847a..2d6fffbe062fb6aab01d4ce59d0736caf8c13a87)]
---------
This refactors the population of collation on StringTypes to be separate from parsing. …

[Kernel][Type Widening] 8/ refactor collation parsing/setting not be intertwined with type parsing

---

docs/source/delta-spark-connect.md
docs/source/delta-type-widening.md

[Docs] Mark Delta Connect as in preview in our docs

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/CatalogResolver.scala
spark/src/test/scala/io/delta/tables/DeltaTableForNameSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/CustomCatalogs.scala

Follow up PR for https://github.com/delta-io/delta/pull/4605, adding an extra test and refactoring some parts of the previous PR. This PR doesn't add any new functional changes.
UTs

[SPARK] Refactor deltaTable forName fix

---

sharing/src/main/scala/io/delta/sharing/spark/DeltaSharingUtils.scala
sharing/src/test/scala/io/delta/sharing/spark/DeltaSharingUtilsSuite.scala

Fixing import format
CI pipeline
No

Fix import format

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/data/TransactionStateRow.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergUniversalFormatMetadataValidatorAndUpdater.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergUniversalFormatMetadataValidatorAndUpdaterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala

Add the IcebergCompatV3 table feature, which requires the columnMapping and rowTracking to be enabled.
Unit tests

[Kernel][#1] IcebergCompatV3 - add icebergCompatV3 table feature

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/hooks/AutoCompactUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/util/TransactionHelper.scala

Continue from https://github.com/delta-io/delta/pull/4735. This PR renames `DeltaTransaction` to `TransactionHelper` and some additional clean-ups.
Existing UTs
No

[Spark] Rename DeltaTransaction to TransactionHelper

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/tablefeatures/TableFeatures.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/tablefeatures/TableFeaturesSuite.scala

Add IcebergWriterCompatV3 table feature and unit tests.
Unit tests.

[Kernel][#1] Implement table features and tests for iceberg writer compat v3

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConverter.scala

This PR refactors convertSnapshot to isolate snapshot expiry logic.
No behavior is changed. 
UT
No

[Spark] Refactor convertSnapshot to isolate snapshot expiry logic

---

build/sbt-config/repositories

Cherrypick of https://github.com/delta-io/delta/commit/68582cdc4269a944f99010fe85778434b383c29c for master

[Infra] Cherry-pick Add an additional back up repo to avoid hitting rate limits for maven deps (#4660) for master

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/table/ResolvedTableBuilderImpl.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/catalogManaged/CatalogManagedLogSegmentSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/catalogManaged/ResolvedTableBuilderSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/files/ParsedLogDataSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/test/VectorTestUtils.scala

Use this [link](https://github.com/delta-io/delta/pull/4664/files) to review incremental changes.
- [**stack/kernel_catalog_managed_5_builder_validation**](https://github.com/delta-io/delta/pull/4664) [[Files changed](https://github.com/delta-io/delta/pull/4664/files)]
---------
This PR adds some pretty straight forward builder validation and tests.
New UTs.
No.

[Kernel] [CatalogManaged] More Builder validation and tests

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala

This PR blocks running VACUUM command on CC tables for Delta-Spark clients.
The reason is that any CC table is expected to already be a UC Managed table, so we can simply check the table's protocol to verify this.
Through existing UT.
N/A

[Spark] Block VACUUM on CC tables regardless of table type

---

build.sbt
unity/src/test/scala/io/delta/unity/InMemoryUCClient.scala
unity/src/test/scala/io/delta/unity/InMemoryUCClientSuite.scala
unity/src/test/scala/io/delta/unity/UCCatalogManagedClientSuite.scala
unity/src/test/scala/io/delta/unity/UCCatalogManagedTestUtils.scala

Use this [link](https://github.com/delta-io/delta/pull/4835/files) to review incremental changes.
- [**stack/uc_kernel_catalog_managed_2_in_memory_test_client_b**](https://github.com/delta-io/delta/pull/4835) [[Files changed](https://github.com/delta-io/delta/pull/4835/files)]
- [stack/uc_kernel_catalog_managed_3](https://github.com/delta-io/delta/pull/4838) [[Files changed](https://github.com/delta-io/delta/pull/4838/files/e9eeef9043b562c6e7eac81f95da0b3e94f44a9c..c3662f9ddfb192244e89f9c7d15c56dbe063cb45)]
---------
Create an `InMemoryUCClient` and a simple test suite
New test suite
No

[Kernel] [CatalogManaged] [UC] InMemoryUCClient

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/test/scala/org/apache/spark/sql/delta/ChecksumSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaSQLTestUtils.scala

This PR extends `ChecksumSuite` w/ CatalogOwned & migrates existing UTs to name-based.
Through existing and newly added suites.
N/A

[Spark] Extends ChecksumSuite w/ CatalogOwned & Migrates to name-based testing

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala

This PR migrates `DeltaVacuumSuite` to `CatalogOwned`.
Existing UTs.
No

[Delta] Refactor `DeltaVacuumSuite`

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActionWrapper.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActionsIterator.java

Use this [link](https://github.com/delta-io/delta/pull/4852/files) to review incremental changes.
- [**stack/refactor-batch**](https://github.com/delta-io/delta/pull/4852) [[Files changed](https://github.com/delta-io/delta/pull/4852/files)]
- [stack/refactor-FB](https://github.com/delta-io/delta/pull/4853) [[Files changed](https://github.com/delta-io/delta/pull/4853/files/e335ce14517cecdec073fb2e535fa9a762801e2f..47d4e10a4e6bb9bf2f26e38f57740fd4b43278ed)]
---------
Refactor Action wrapper -> put file Path associated with the ColumnarBatch to the action wrapper.

[Kernel] [Refactor] Add File Path to Action Wrapper

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala

This PR does a minor refactoring to simplify the interface of `buildRowIndexSetsForFilesMatchingCondition` and `DeletionVectorSet`
Refactoring Only, no behavior change
No

Minor Refactoring of DMLWithDeletionVectorsHelper

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/DeltaToIcebergConvert.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergConversionTransaction.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergSchemaUtils.scala

This PR is a preparation of translating Delta Column Defaults to Iceberg
UT
No

[UniForm] Prepare for translating Column Defaults to Iceberg

---

spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala
spark/src/test/scala/org/apache/spark/sql/delta/cdc/CDCReaderSuite.scala

Add a new log event for cdf execution.
UT

[SPARK] Emit event for CDF calls.

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/PaginatedScanImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActionsIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/PaginatedScanFilesIteratorImpl.java

Use this [link](https://github.com/delta-io/delta/pull/4880/files) to review incremental changes.
- [**stack/scan**](https://github.com/delta-io/delta/pull/4880) [[Files changed](https://github.com/delta-io/delta/pull/4880/files)]
- [stack/page-one](https://github.com/delta-io/delta/pull/4887) [[Files changed](https://github.com/delta-io/delta/pull/4887/files/d6bddc4a51c305eccede0a1e9e27d40fe2b0b709..c5712d663f5fef0aaf8eaee016a129a4e950bbb4)]
- [stack/sidecar-1](https://github.com/delta-io/delta/pull/4888) [[Files changed](https://github.com/delta-io/delta/pull/4888/files/2a89abed437cc553d2dafe345f2499fde466ca0e..0c6965512c58876304a91090bafc66a55b28f8a3)]
---------

[Kernel] [Pagination] Add PaginationScanImpl Class

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/DeltaToIcebergConvert.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergSchemaUtils.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala

This PR allows Delta default values to be converted to Iceberg
UT
No

[UniForm] Support converting Delta default values to Iceberg

---

kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/DeletionVectorDescriptor.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/GenerateIcebergCompatActionUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/actions/AddFileSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/actions/RemoveFileSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CommitIcebergActionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/TransactionReportSuite.scala

Exposes deletion vector descriptor field as a parameter of AddFile for generating v3 add actions. 
Unit tests. 
No.

[Kernel] [#5] Introduce deletion vector support

---

examples/python/using_with_pip.py
setup.py

This Pr updates the the delta_spark python package to contain the exceptions module. Previously, the delta_spark package for delta 4.0 would not include the exceptions package. This adds it to the list.
Resolves: #4755 
An automated test is added that ensures the exceptions module can be imported by a user of the python library.
Yes. The exceptions module was previously private and is now public.

Export exceptions module in delta_spark python module

---

spark/delta-suite-generator/src/main/scala/io/delta/suitegenerator/ModularSuiteGenerator.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoSuiteBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/MergeIntoTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/TableRedirectSuite.scala

This PR does various small clean-ups, mainly in tests
Existing UTs
No

[Spark] Some miscellaneous clean-up

---

kernel/kernel-api/src/main/java/io/delta/kernel/PaginatedScanFilesIterator.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/PaginatedScanFilesIteratorImpl.java

Update PaginatedScanFilesIterator::getCurrentPageToken() to make it return an optional page token. If the page token isn't present, this means all files in current scan are consumed and no more pages to read. 
yes.

[Kernel] [Pagination] Update getCurrentPageToken to return an Optional Type

---

spark/src/test/scala/org/apache/spark/sql/delta/IcebergCompatUtilsBase.scala
spark/src/test/scala/org/apache/spark/sql/delta/uniform/UniFormE2EIcebergSuiteBase.scala

Refactor of UniForm tests
Test only changes
No

[UniForm] Refactoring UniForm tests

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/PaginatedScanImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanBuilderImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/PageToken.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/PaginatedScanFilesIteratorImpl.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/PaginationContext.java
kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/LogSegment.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/PageTokenSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/PaginationContextSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/PaginatedScanSuite.scala

Check if the log segment has changed between page reqeusts. 
PaginationContextSuite.scala.

[Kernel] [Pagination] Check Log Segment Changes between Page Requests

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaProtocolVersionSuite.scala

This PR migrates `DeltaProtocolVersionSuite` to CatalogOwned.
Through existing and newly migrated UTs.
No.

[Spark] Migrate `DeltaProtocolVersionSuite` to CC

---

examples/python/using_with_pip.py
setup.py

This PR exports the delta exceptions module in python. 
This change is applied to the master branch [here](https://github.com/delta-io/delta/pull/4801)
I ensure that the exception can be imported in the python tests.
Yes, this makes a module public when it was previously private.

Add Delta exceptions to delta-spark 4.0 branch

---

spark/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala

This PR fixes a bug of `findEarliestReliableCheckpoint`, which may return wrong result due to missing validate reliable checkpoint
existing UTs
No

Fix a bug of findEarliestReliableCheckpoint

---

spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala
spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaDataSource.scala
spark/src/test/scala/org/apache/spark/sql/delta/test/DeltaTestImplicits.scala

Revert PathInfo refactor in DeltaTableV2 to avoid performance regression in DataFrame writers.
Clean revert covered by existing unit tests.
No

[Delta] Revert DeltaTableV2 Refactoring

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSQLSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaCDCSuite.scala

This PR migrates `DeltaCDCScalaSuite` & `DeltaCDCSQLSuite` to `CatalogOwned` w/ name-based migration.
Existing UTs.
No

[Delta] Migrate `DeltaCDCScalaSuite` & `DeltaCDCSQLSuite` to `CatalogOwned` w/ name-based migration

---

iceberg/src/main/scala/org/apache/spark/sql/delta/icebergShaded/IcebergTransactionUtils.scala

Delta path uses URL-encoded string while Iceberg path uses plain string, this PR fixes a bug due to the format mismatch 
UTs
No

Handle URL-encoded path properly for Iceberg

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaVacuumSuite.scala

This change fixes a couple of Vacuum related tests to use the right clock throughout the test logic.
Existing UTs.
No

[Delta] Fix a couple of vacuum related tests to use the right clock

---

docs/source/delta-drop-feature.md

This PR adds a clarification in docs about Deletion Vectors Removal Support.
N/A.
No.

[Spark] Add clarification in docs about Deletion Vectors Removal Support

---

spark/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala
spark/src/test/scala/org/apache/spark/sql/delta/CheckpointsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaIncrementalSetTransactionsSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaLogSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaRetentionSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CatalogOwnedEnablementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/skipping/clustering/ClusteredTableDDLSuite.scala

This PR refactors CC relevant code.
1. Fix indentation.
2. Correctly override `catalogOwnedCoordinatorBackfillBatchSize` that extends `CatalogOwnedTestBaseSuite`.
3. Consolidate the two checkpoints helpers to `CatalogOwnedTestBaseSuite`.
4. Refactor `CatalogOwnedEnablementSuite`.
Through existing suites.
No.

[Spark] [CatalogManged] CC Refactor - Phase #1

---

kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ArrayColumnReader.java
kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ParquetSchemaUtils.java
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableReadsSuite.scala

Today, we only do projection of schema when reading parquet on struct type. However there is one more case that need to consider, which is array of struct. See https://github.com/delta-io/delta/issues/4983
This PR handle this case by pruning/projecting field of subtype of a list element.
3 level list is the pre-requisite as kernel only support this but not the legacy 2 level structure https://github.com/delta-io/delta/blob/994012fa71286a6e404f55da799723ab2356b26c/kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/parquet/ArrayColumnReader.java#L55
Add unit
No

[Kernel]Fix an issue of schema projection of array of struct

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumSimpleComparisonSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumStatsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CommitIcebergActionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CreateCheckpointSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaColumnMappingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaIcebergCompatBaseSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaReplaceTableSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableClusteringSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteWithCrcSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DomainMetadataSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogCompactionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogCompactionWriterSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/PaginatedScanSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ScanSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TableChangesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TablePropertiesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TimestampStatsAndDataSkippingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TransactionCommitLoopSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/WriteUtils.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/metrics/TransactionReportSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TransactionBuilderSupport.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/WriteUtils.scala

Refactor our write test utilities. This is in preparation for [https://github.com/delta-io/delta/pull/5044](https://github.com/delta-io/delta/pull/5058#top)
- Refactors DeltaWritesSuiteBase to a WriteUtils class that does not extend AnyFunSuite
- Separates it into a class hierarchy with abstract spec and concrete implementations so we can abstract specific write utilities to use different code paths (e.g. v1 vs v2 transaction builders, in the future commit methods, ccv2 code path, etc).
Test refactor.
No.

[KERNEL][REFACTOR] Refactor some test utils + suites in preparation for https://github.com/delta-io/delta/pull/5044

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableFeaturesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableSchemaEvolutionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWriteSuiteBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesTransactionBuilderV2Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DomainMetadataSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogCompactionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TableChangesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TimestampStatsAndDataSkippingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TransactionBuilderSupport.scala

Cleans up some test suites to use test fx `createTxn`
Test change
No

[Kernel][Refactor] Clean up some tests to use createTxn

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaReplaceTableSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/RowTrackingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/utils/TransactionBuilderSupport.scala

[Kernel][Refactor] Refactor ReplaceTableSuite to use utils in TransactionBuilderSupport

---

spark/src/main/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsUtils.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CatalogOwnedEnablementSuite.scala
spark/src/test/scala/org/apache/spark/sql/delta/coordinatedcommits/CoordinatedCommitsTestUtils.scala

Some minor cleanup to make the tests easier to read
Existing UTs
No

[Spark] Refactor some catalog-managed tests for better readability

---

.github/workflows/kernel_test.yaml
run-tests.py

Use this [link](https://github.com/delta-io/delta/pull/5120/files) to review incremental changes.
- [**stack/kernel_ci_more_improvements**](https://github.com/delta-io/delta/pull/5120) [[Files changed](https://github.com/delta-io/delta/pull/5120/files)]
---------
Disables unidoc for Kernel tests (the unidoc job tests that).
Adds a cache for Kernel tests.
https://github.com/delta-io/delta/actions/runs/17108208829
❌ Cache MISS - will download dependencies
https://github.com/delta-io/delta/actions/runs/17108706467/job/48524302868?pr=5120
✅ Cache HIT - using cached dependencies
CI tests.
No.

[CI] [Kernel] More Kernel CI improvements (disable unidoc; cache dependencies; print cache hit/miss & runner info)

---

spark-kernel-dsv2/src/main/java/io/delta/spark/dsv2/scan/KernelSparkScanContext.java
spark-kernel-dsv2/src/test/java/io/delta/spark/dsv2/catalog/TestCatalog.java

Run javafmtAll for fixing pipeline

[Build]Run javafmtAll for fixing pipeline

---

kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/CounterSuite.scala
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/TimerSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/5061/files) to review incremental changes.
- [**stack/refactor_tests**](https://github.com/delta-io/delta/pull/5061) [[Files changed](https://github.com/delta-io/delta/pull/5061/files)]
- [stack/incorporate_metrics](https://github.com/delta-io/delta/pull/5051) [[Files changed](https://github.com/delta-io/delta/pull/5051/files/706f0fe26262895c1cfb23088828720ceaa16b68..a6caa60b596e529fb54426f1a1ae26a0da154b75)]
---------
This PR removes MetricsutilsSuite and puts the separates the tests for `Counter` and `Timer` into there own suite in the package they are defined.  This makes the tests more discoverable.
N/A
No

[Kernel] Refactor MetricsUtilsSuite

---

kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/CounterSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/5051/files) to review incremental changes.
- [**stack/incorporate_metrics**](https://github.com/delta-io/delta/pull/5051) [[Files changed](https://github.com/delta-io/delta/pull/5051/files)]
---------
Add test for toString method on Counter.  
N/A
No

[Kernel] Add test for toString method on Counter.  

---

storage/src/main/java/io/delta/storage/commit/uccommitcoordinator/UCCommitCoordinatorClient.java

[UCCommitCoordinator] Improve documentation for `hasSameContent` method

---

spark/src/test/scala/org/apache/spark/sql/delta/DeltaErrorsSuite.scala

Fix curl call to follow redirects
Unit tests
No

[Spark] [Test] [3.3] Fix curl call to follow redirects

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergSchemaUtils.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/TypeToSparkTypeWithCustomCast.scala

Consolidate type conversion customized logics in Iceberg Metadata to Delta Metadata
Existing UTs

[UniForm] Consolidate type conversion customized logics in Iceberg Metadata to Delta Metadata

---

iceberg/src/main/scala/org/apache/iceberg/transforms/IcebergPartitionUtil.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergSchemaUtils.scala
iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala

Remove Iceberg metadata conversion dependency on Iceberg-Spark SparkSchemaUtil
Existing UTs

[UniForm] Remove Iceberg metadata conversion dependency on Iceberg-Spark SparkSchemaUtil

---

kernel/kernel-api/src/test/scala/io/delta/kernel/internal/CommitRangeBuilderSuite.scala

Refactors BoundaryDef in CommitRangeBuilderSuite to have child classes representing the valid cases for boundary definitions.
Test refactor.
No.

[Kernel][Test refactor] Refactor BoundaryDef in CommitRangeBuilderSuite

---

unity/src/main/java/io/delta/unity/UCCatalogManagedCommitter.java
unity/src/test/scala/io/delta/unity/InMemoryUCClient.scala
unity/src/test/scala/io/delta/unity/UCCatalogManagedCommitterSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/5185/files) to review incremental changes.
- [**stack/kernel_uc_committer_support_p_and_m**](https://github.com/delta-io/delta/pull/5185) [[Files changed](https://github.com/delta-io/delta/pull/5185/files)]
---------
In this PR, we now send the **changed** Protocol and Metadata actions to UC as part of the UC-CatalogManaged-Committer commit.
Tiny new tests.
No.

[Kernel] UCCatalogManagedCommitter: Send new protocol and metadata to UC as part of the commit

---

iceberg/src/main/scala/org/apache/spark/sql/delta/IcebergTable.scala
iceberg/src/test/scala/org/apache/spark/sql/delta/CloneIcebergSuite.scala
spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/CloneTableCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/ConvertToDeltaCommand.scala
spark/src/main/scala/org/apache/spark/sql/delta/commands/convert/ConvertUtils.scala

Remove dependency on SparkTable for Clone from Iceberg
Existing UTs

[UniForm] Remove dependency on SparkTable for Clone from Iceberg

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogCompactionSuite.scala

Refactors LogCompactionSuite to run with both the new and legacy APIs for loading snapshots.
Test change.
No.

[Kernel][Test-only] Refactor LogCompactionSuite run with the new and legacy APIs for reads

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/CommitIcebergActionSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/TransactionCommitLoopSuite.scala

See title. Increases test coverage.
Test change
no

[Kernel][Test-only] Refactor CommitIcebergActionSuite and TransactionCommitLoopSuite to run with both the v1 and v2 txn builders

---

build.sbt

Spark master jobs are currently failing as Spark has released 4.0.1 and thus the snapshot version has been bumped to 4.0.2-SNAPSHOT.
No.

[Spark] Upgrade Spark version for master build to 4.0.2-SNAPSHOT

---

kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ChecksumLogReplayMetricsTestBase.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DomainMetadataCheckSumReplayMetricsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplayBaseSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplayEngineMetricsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/PandMCheckSumLogReplayMetricsSuite.scala

Updates various engine metrics suites to run with the new and old snapshot APIs.
Test refactor.
No.

[Test-only][Kernel] Refactor LogReplayEngineMetric suites to run using new and old snapshot APIs

---

kernel-spark/src/test/java/io/delta/kernel/spark/read/SparkGoldenTableTest.java

Rename GoldTableTest to SparkGoldenTableTest
It's just test renaming
No

[kernel-spark]  Rename GoldTableTest to SparkGoldenTableTest

---

kernel-spark/src/main/java/io/delta/kernel/spark/utils/ExpressionUtils.java
kernel-spark/src/test/java/io/delta/kernel/spark/utils/ExpressionUtilsTest.java

Introduce utils to convert spark's `Filter` to kernel's `Predicate`
unit test
No

[Kernel connector]introduce expression convertion utils for dsv2 connector

---

spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala
spark/src/main/scala/org/apache/spark/sql/delta/SnapshotManagement.scala

refactors `getSnapshotForLogSegment` to push the equality check into a separate method 
existing tests

[SPARK] refactor get snapshot for log segment

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/icebergcompat/IcebergCompatMetadataValidatorAndUpdater.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/icebergcompat/IcebergCompatV3MetadataValidatorAndUpdateSuite.scala

This change adds variant as supported data type to Iceberg Compat V3
Updated existing unit tests

[Kernel] Add variant as supported v3 type in IcebergCompatV3

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/SchemaUtilsSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/IcebergWriterCompatV1Suite.scala

This change allows variant in SchemaUtils validateSchema/validateUpdatedSchema
Added unit tests to SchemaUtilsSuite

[Kernel] Update SchemaUtils validation to  allow for variant

---

kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/ColumnMapping.java
kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/ColumnMappingSuite.scala
kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableClusteringSuite.scala

Use this [link](https://github.com/delta-io/delta/pull/5258/files) to review incremental changes.
- [**stack/kernel_physical_to_logical_column_mapping_util**](https://github.com/delta-io/delta/pull/5258) [[Files changed](https://github.com/delta-io/delta/pull/5258/files)]
---------
Adds a utility to be able to convert from physical to logical name.
This is useful for getting the logical name of clustering columns.
New UTs + integration tests.
No.

[Kernel] Add utility to convert physical name to logical name

---

kernel-spark/src/main/java/io/delta/kernel/spark/exception/VersionNotFoundException.java
kernel-spark/src/main/java/io/delta/kernel/spark/utils/StreamingHelper.java
kernel-spark/src/test/java/io/delta/kernel/spark/utils/StreamingHelperTest.java

V1 DeltaSource rely on deltaLog, we want to introduce a helper to ensure kernel could provide the same semantic
Unit test with paring with delta log
NO

Introduce Streaming helper to facilitate Micro-batch stream impl
